In [1]:
import pandas as pd

#import matplotlib.pyplot as plt

df = pd.read_csv("uber_rapido_driver_dirty.csv")
df.head(5)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
0,DRV016649,Naresh Chauhan,70,Chennai,9255500096,naresh.chauhan@hotmail.com,Uber,Auto,Good,4+ yrs,...,4.3,5.8,7.7,5.3,Fail,Clear,On hold,Invalid_id,2025-02-10 22:07:31,False
1,DRV032785,Amit Gupta,45,Ahmedabad,9940345570,amit.gupta@rediffmail.com,Uber,Mini,Excellent,Fresher,...,9.3,7.5,9.0,8.1,Distinction,Clear,On hold,Invalid_id,2026-01-12 11:59:18,False
2,DRV011323,Yogesh Nair,53,Lucknow,9170487337,Yogesh Nair @gmail.com,Uber,Suv,Average,4+ yrs,...,6.3,9.0,5.5,6.9,Distinction,Clear,Selected,Invalid_id,2021-04-19 00:00:00,False
3,DRV022168,Manoj Patel,46,Hyderabad,9246425981,manoj.patel@hotmail.com,Rapido,Mini,Super,1-3 yrs,...,8.7,9.6,5.3,7.8,Average,Clear,Selected,Invalid_id,2021-05-27 00:00:00,False
4,DRV040782,Vikram Chaudhary,25,Kolkata,9282240,vikram.chaudhary@gmail.com,Uber,Suv,Good,Fresher,...,12.7,6.5,7.9,6.0,Fail,Clear,Rejected,Low rating history,2026-02-08 13:31:18,False

In [2]:
df.describe()

,phone,total_trips_completed,trip_completion_rate_%,cancellation_rate_%,total_complaints,total_compliments,communication_score_10,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10
count,5.000000e+04,45930.000000,45565.00000,45484.000000,45965.000000,46024.000000,45416.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,2.582512e+10,6802.510799,77.89254,22.416584,8809.843120,8942.686272,6.508777,7.078886,6.679730,6.762170,6.892432
std,3.364797e+10,17638.171153,20.80393,23.708155,28303.698509,28456.710282,2.789817,2.272019,2.470516,2.551966,1.951489
min,9.000153e+06,-7996.000000,-2.00000,-2.000000,0.000000,0.000000,-2.000000,0.100000,0.100000,0.000000,0.100000
25%,9.246444e+09,1704.000000,69.40000,8.100000,14.000000,27.000000,4.600000,5.500000,4.800000,4.800000,6.000000
50%,9.595512e+09,3909.000000,80.50000,18.100000,27.000000,55.000000,6.600000,7.400000,7.000000,7.000000,6.800000
75%,9.938337e+09,6086.750000,91.60000,27.900000,41.000000,82.000000,8.500000,8.600000,8.400000,8.500000,7.800000
max,9.199984e+10,99999.000000,103.00000,103.000000,99999.000000,99999.000000,13.000000,13.000000,13.000000,13.000000,13.000000

In [3]:
df.shape

(50000, 33)

In [4]:
df['email'].unique()

array(['naresh.chauhan@hotmail.com', 'amit.gupta@rediffmail.com',
       '  Yogesh Nair  @gmail.com', ..., 'deepak.srivastavahotmail.com',
       'deepak.singhgmail.com', 'deepak.dubeygmail.com'], dtype=object)

In [5]:
df['email'] = df['email'].astype("string")
print(df['email'].dtype)

string

In [6]:
##This code creates a gmail adrress for the drivers using their names, where they have no existing emails.

df['email'] = df['email'].fillna(
    df['driver_name'] + '@gmail.com'
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
45615,DRV015521,RAJESH SHUKLA,45,Pune,9865931972,rajesh.shukla@hotmail.com,Ola,Sedan,Super,3-5 yrs,...,5.5,11.4,8.7,10.6,Pass,Clear,Selected,Invalid_id,2025-06-02 22:51:08,True
32158,DRV044207,Yogesh Verma,38,Mumabi,9732150660,yogesh.verma@rediffmail.com,Rapido,Sedan,Good,3-5 yrs,...,7.5,5.8,9.1,0.5,Distinction,Clear,Selected,Invalid_id,2025-11-16 07:44:06,False
13610,DRV008116,Naresh Jha,37,Delhi,9895203102,Naresh Jha@gmail.com,Uber,Auto,Excellent,Fresher,...,7.4,7.3,8.5,8.8,Pass,Flagged,Selected,Invalid_id,2026-04-18 14:58:11,False
13675,DRV008714,Ganesh Patel,33,Jaipur,9976285826,ganesh.patel@hotmail.com,Uber,Bike,Average,Fresher,...,9.1,7.4,7.0,1.2,Fail,Pending,Selected,Invalid_id,2025-06-12 22:20:21,True
23150,DRV029678,Ravi Rao,54,Jaipur,9913478493,ravi.rao@@rediffmail.com,Uber,Suv,Excellent,4+ yrs,...,8.4,4.3,9.5,8.1,Fail,Clear,Selected,Invalid_id,2025-07-30 08:13:41,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13944,DRV041466,Lokesh Dubey,-26,Ahmedabad,9955872041,lokesh.dubey@rediffmail.com,Uber,Bike,Super,5+ yrs,...,5.4,7.5,8.5,0.3,Fail,Clear,Selected,Invalid_id,2025-11-11 23:56:21,False
10233,DRV023243,girish mishra,52,Mumbai,9875614383,girish.mishra@rediffmail.com,Rapido,Tricycle,Good,1-3 yrs,...,1.9,8.0,9.8,8.2,Distinction,Clear,On hold,Background check failed,2026-06-08 04:56:59,True
34424,DRV019476,Yogesh Nair,70,Hyderabad,9004813490,yogesh.nair@hotmail.com,Uber,Auto,Poor,5+ yrs,...,9.7,6.0,8.5,6.2,Fail,Flagged,Rejected,Invalid_id,2025-02-17 05:46:10,False
29474,DRV023998,Mukesh Verma,45,Lucknow,91919226260,mukesh.verma@rediffmail.com,Rapido,Suv,Super,5+ yrs,...,4.8,0.9,9.8,8.8,Pending,Clear,On hold,Invalid_id,2025-01-25 18:42:26,False
35002,DRV013485,Naveen Srivastava,unknown,Mumbai,9924822027,naveen.srivastava@yahoo.com,Uber,Suv,Poor,1-3 yrs,...,8.2,7.3,9.0,7.2,Distinction,Clear,On hold,Invalid_id,2025-03-24 17:20:57,False

In [7]:
df.sample(10)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
40558,DRV004666,Lokesh Pandey,49,Bangalore,91778657270,lokesh.pandey@gmail.com,Rapido,Auto,Super,1-3 yrs,...,9.8,7.5,8.5,6.0,Pending,Flagged,Rejected,Selected,2025-05-26 15:08:56,False
20022,DRV031178,Deepak Chauhan,40,Jaipur,91746086878,deepak.chauhan@hotmail.com,Rapido,Bike,Good,4+ yrs,...,9.5,1.5,8.0,7.5,Fail,Clear,Selected,Invalid_id,2025-07-14 18:10:57,True
40512,DRV044885,Vikram Chauhan,36,Kolkata,9138869268,vikram.chauhan@gmail.com,Ola,Sedan,Excellent,5+ yrs,...,5.4,7.0,4.3,5.0,Pass,Pending,Selected,Invalid_id,2025-02-01 02:21:57,False
41018,DRV047819,Hitesh Nair,22,Hyderabad,91260310245,hitesh.nair@yahoo.com,Uber,Mini,Poor,4+ yrs,...,7.7,9.1,3.1,8.8,Pass,Clear,On hold,Invalid_id,2025-05-08 15:22:23,True
20259,NaN,Mukesh Tiwari,35,Pune,9413517549,Mukesh Tiwari @gmail.com,Uber,Suv,Good,Fresher,...,9.2,11.0,4.4,6.5,Pass,Clear,Rejected,Invalid_id,2025-02-09 10:50:12,False
40137,DRV033661,PANKAJ RAO,39,Hyderabad,9374588970,pankaj.rao@yahoo.com,Uber,Auto,Average,5+ yrs,...,5.7,7.7,4.6,8.8,Pass,Clear,Selected,Invalid_id,2025-12-24 01:18:22,False
17529,DRV039454,RAJESH RAO,51,Ahmedabad,9981055197,rajesh.rao@hotmail.com,Rapido,Bike,Good,5+ yrs,...,8.8,6.2,4.6,7.0,Pending,Clear,Selected,Invalid_id,2026-07-17 13:32:54,False
34417,DRV044664,Rakesh Tripathi,32,Lucknow,9299242686,rakesh.tripathihotmail.com,Bolt,Tricycle,Average,4+ yrs,...,7.5,9.4,7.7,7.4,Fail,Flagged,Selected,Invalid_id,2026-03-08 20:42:19,False
37400,DRV049873,Santosh Shukla,51,Kolkata,91658824911,santosh.shukla@gmail,Uber & rapido,Suv,Average,1-3 yrs,...,6.5,10.9,5.7,6.6,Fail,Clear,Selected,Invalid_id,2025-11-20 23:37:51,False
19760,DRV048118,Mahesh Tripathi,43,Mumbai,9519997412,mahesh.tripathi@rediffmail.com,Uber,Auto,Average,3-5 yrs,...,4.8,4.9,4.7,5.5,Distinction,Clear,On hold,Invalid_id,2025-03-25 05:46:03,True

In [8]:
df['phone'] = pd.to_numeric(df['phone'], errors='coerce') 
## This is to convert the phone collumn from object to numeric

In [9]:
df['phone'] = df['phone'].astype("string")
print(df['phone'].dtype)

string

In [10]:
df['driving_test_score_10'].unique()

array([ 4.3,  9.3,  6.3,  8.7, 12.7,  8.8,  8.1,  1.1, 11.6,  7.5,  7.4,
        0.6,  7.7,  6.2,  4.8,  7.1, 12.5, 11.2,  0.9,  5.5,  8.9,  6.4,
        5.1,  7. , 11. ,  7.6,  5.7, 12.2,  9.1,  8.3,  4.6,  4. ,  7.2,
        8. ,  9.7, 10.9,  4.2,  9.5,  4.9,  5.8,  5. ,  6.9,  4.1,  6.5,
        4.5,  9.8,  5.4,  4.4,  1.3,  9.2,  4.7,  7.3,  1.5, 12.4,  8.6,
        8.4,  1.7,  5.3,  6.1,  6. ,  9.6,  7.9,  6.8,  5.2,  5.6, 10.2,
        0.7,  9.4,  9.9,  7.8,  8.2,  6.6,  6.7, 10.5,  9. , 10.8,  5.9,
       12. , 12.1, 11.5,  8.5, 10. ,  1. ,  0.8, 11.4, 10.3,  0.4,  0.5,
       10.7, 11.7, 11.8,  0.3, 10.4, 12.8,  1.8,  1.2,  0.2, 11.9,  1.4,
       10.1, 11.3, 12.3,  1.6, 12.6,  1.9, 10.6, 12.9, 11.1, 13. ,  0.1,
        2. ])

In [11]:
## This code removes the decimals from the values and make them strings rather than floats. 
df['phone'] = df['phone'].str.replace(r'\.0$', '', regex=True)

In [12]:
## This creates random phone numbers for NaN values in the phone column

import numpy as np

mask = df['phone'].isna()

df.loc[mask, 'phone'] = [
    '+91' + ''.join(np.random.choice(list('0123456789'), 9))
    for _ in range(mask.sum())
]
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
43556,DRV012989,Ramesh Jha,-51,Delhi,9758749965,ramesh.jha@hotmail.com,Ola,Suv,Super,3-5 yrs,...,7.5,9.9,8.8,9.1,Fail,Flagged,On hold,Invalid_id,2025-08-13 04:56:20,False
29798,DRV028447,SANJAY PATEL,30,Chennai,9951608,sanjay.patel@hotmail.com,Uber,Sedan,Good,1-3 yrs,...,8.4,8.6,7.5,8.2,Pending,Flagged,On hold,Invalid_id,2025-06-27 09:01:55,False
3242,DRV007519,Vijay Shukla,21,Lucknow,9674654794,vijay.shukla@gmail.com,Na,Truck,Good,4+ yrs,...,7.8,9.0,3.7,6.8,Pending,Flagged,Rejected,Vehicle age too old,2025-10-22 10:02:42,False
1505,DRV029179,Umesh Reddy,31,Ahmedabad,9778770918,umesh.reddy@gmail.com,Rapido,Suv,Super,3-5 yrs,...,4.3,7.3,5.2,5.8,Distinction,Clear,Selected,Invalid_id,2025-08-14 22:04:40,True
12126,NaN,PRADEEP YADAV,49,Hyderabad,9699044238,pradeep.yadav@hotmail.com,Uber,Auto,Average,3-5 yrs,...,7.5,7.5,8.5,7.0,Pending,Pending,Selected,Invalid_id,2025-10-09 03:42:29,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21352,DRV007268,Umesh Kumar,33,Delhi,9363064,umesh.kumar@yahoo.com,Uber,Auto,Average,4+ yrs,...,7.5,7.5,8.5,8.8,Pass,Clear,Selected,Invalid_id,2026-05-30 03:17:25,True
12989,DRV016045,Pradeep Rao,999,Hyderabad,91404213507,pradeep.raogmail.com,Ola,Bike,Good,Fresher,...,5.9,7.2,6.9,6.8,Pass,Flagged,Selected,Invalid_id,2025-09-22 16:19:30,True
12562,DRV046784,Vijay Verma,28,Lucknow,9695977281,vijay.verma@@rediffmail.com,Uber,Mini,Super,5+ yrs,...,6.4,4.6,3.9,5.8,Pass,Pending,Selected,Invalid_id,2026-02-14 14:00:02,False
21119,DRV016719,Pradeep Yadav,49,Bangalore,9301241450,pradeep.yadav@hotmail.com,Rapido,Sedan,Good,1-3 yrs,...,8.4,9.4,8.0,7.5,Fail,Pending,Selected,Invalid_id,2025-08-20 15:12:40,True
3810,DRV043264,naresh srivastava,50,Ahmedabad,9593177539,naresh.srivastavahotmail.com,Ola,Motorbike,Good,3-5 yrs,...,6.6,3.7,7.4,5.4,Distinction,Pending,Selected,Invalid_id,2026-05-07 01:48:06,False

In [13]:
df['age'] = df['age'].astype("string")
print(df['age'].dtype)

string

In [14]:
df['age'] = df['age'].fillna('70')

In [15]:
## This code fills the age column where NaN values exist with random values between 1 and 100

import numpy as np

mask = df['age'].isna()

df.loc[mask, 'age'] = np.random.randint(
    1, 101, size=mask.sum()
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
30475,DRV005845,manoj verma,54,Kolkata,9950612,manoj.verma@rediffmail.com,Uber & rapido,Sedan,Average,5+ yrs,...,6.4,6.8,8.2,6.1,Pass,Flagged,Selected,Invalid_id,2026-03-30 07:43:50,True
14360,DRV000722,Anil Reddy,53,Hyderabad,9534017200,anil.reddy@gmail.com,NaN,Suv,Average,3-5 yrs,...,4.3,3.7,7.3,5.4,Distinction,Flagged,Rejected,Incomplete documents,2025-08-25 12:44:59,False
39731,DRV033165,Pankaj Dubey,52,Lucknow,9721382963,pankaj.dubey@hotmail.com,Uber,Suv,Super,3-5 yrs,...,7.2,5.1,5.6,6.8,Distinction,Flagged,On hold,Invalid_id,2025-11-01 08:40:51,False
27821,DRV001438,Pradeep Gupta,26,Mumbai,9790970933,pradeep.guptagmail.com,Uber & rapido,Bike,Poor,Fresher,...,7.9,7.5,7.2,7.1,Distinction,Flagged,Selected,Invalid_id,2025-07-02 19:22:52,True
44801,DRV018491,Bharat Patel,31,Hyderabad,91026325046,bharat.patel@yahoo.com,Uber,Mini,Poor,Fresher,...,12.6,8.2,3.1,6.1,Fail,Clear,Selected,Invalid_id,2025-03-02 10:51:28,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21683,DRV033539,Manoj Singh,45,Kolkata,9898229095,Manoj Singh@gmail.com,Uber,Auto,Super,Fresher,...,7.5,7.5,4.0,5.7,Pending,Clear,Selected,Not applicable,2025-09-05 02:38:41,False
44059,DRV016735,Dinesh Reddy,29,Lucknow,9472859977,dinesh.reddy@yahoo.com,Rapido,Bike,Average,Fresher,...,8.4,7.6,5.1,6.3,Fail,Clear,Rejected,Poor communication,2026-03-30 20:15:01,True
19162,DRV025397,SANTOSH CHAUHAN,39,Ahmedabad,9578803915,SANTOSH CHAUHAN@gmail.com,Rapido,Bike,Average,Fresher,...,5.5,5.6,8.9,6.2,Distinction,Clear,Selected,Invalid_id,2026-06-22 08:38:15,True
11010,DRV041351,Mahesh Jha,46,Mumbai,91098283489,mahesh.jha@@gmail.com,Rapido,Bike,Excellent,5+ yrs,...,10.0,5.8,7.8,1.3,Fail,Clear,Selected,Invalid_id,2026-07-29 12:40:24,True
45226,DRV022744,Ravi Mishra,40,Chennai,9749013363,ravi.mishra@rediffmail.com,Rapido,Bike,Good,1-3 yrs,...,7.5,12.9,5.7,8.8,Fail,Clear,Rejected,Invalid_id,2026-05-01 01:22:05,False

In [16]:
## This is to remove the negative values and also the yrs in the age column.
df['driving_test_score_10'] = df['driving_test_score_10'].astype("string")
df['driving_test_score_10'] = df['driving_test_score_10'].str.lstrip('-')
#df['age'] = df['age'].str.rstrip('yrs')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
16826,DRV018144,RAMESH TRIPATHI,48,Jaipur,9233906515,ramesh.tripathi@@hotmail.com,Rapido,Bike,Poor,1-3 yrs,...,7.7,8.8,3.1,7.4,Distinction,Pending,Selected,Invalid_id,2026-01-21 03:29:05,False
22797,DRV030282,Yogesh Patel,29,Kolkata,91068011479,yogesh.patel@yahoo.com,Rapido,Sedan,Average,4+ yrs,...,4.4,9.3,8.5,6.8,Pass,Clear,On hold,Invalid_id,2025-06-28 22:53:16,False
48094,DRV031284,Ajay Tiwari,21,Hyderabad,9647748,ajay.tiwari@rediffmail.com,Rapido,Auto,Super,3-5 yrs,...,12.5,5.7,7.2,8.8,Pending,Flagged,Rejected,Invalid_id,2026-02-20 22:20:28,True
36152,DRV009979,Rajesh Tripathi,29,Mumbai,9343819822,rajesh.tripathi@yahoo.com,Rapido,Suv,Poor,Fresher,...,6.1,5.2,9.9,7.0,Distinction,Clear,Selected,Invalid_id,2025-02-10 11:13:56,False
18499,DRV011005,Dinesh Nair,27,Hyderabad,9236454291,dinesh.nair@yahoo.com,Rapido,Mini,Poor,5+ yrs,...,8.0,7.5,3.6,6.9,Distinction,Pending,Selected,Invalid_id,2026-03-20 08:07:24,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12688,DRV001997,Amit Jha,41,Ahmedabad,9852846396,amit.jha@@gmail.com,Uber & rapido,Auto,Good,3-5 yrs,...,8.0,9.1,6.6,8.8,Distinction,Clear,On hold,Invalid_id,2025-02-01 23:00:22,True
25149,DRV047616,Naresh Chaudhary,30,Ahmedabad,91075457545,naresh.chaudhary@hotmail.com,Ola,Bike,Fair,4+ yrs,...,5.4,3.6,0.8,8.8,Distinction,Clear,Rejected,Poor communication,2026-04-28 11:29:45,False
303,DRV000079,Harish Tiwari,48,Mumbai,9330242571,harish.tiwari@hotmail.com,Rapido,Suv,Average,1-3 yrs,...,8.5,8.7,6.1,7.7,Distinction,Clear,On hold,Invalid_id,2025-10-01 03:39:17,False
16392,DRV033242,Dinesh Mishra,32,Delhi,91354072522,dinesh.mishra@gmail.com,Rapido,Auto,Super,Fresher,...,9.9,5.2,3.7,10.9,Pass,Flagged,Selected,Invalid_id,2025-06-29 02:09:23,False
5214,DRV032061,Ramesh Chaudhary,42,Hyderabad,9682086079,ramesh.chaudhary@rediffmail.com,Ola,Auto,Excellent,5+ yrs,...,6.7,8.6,7.1,7.4,Distinction,Clear,Selected,Invalid_id,2025-03-16 19:44:24,False

In [17]:
## This is to capitalise the platform column to give it a uniform format and also convert the data type from object to string.

df['platform'] = df['platform'].str.capitalize()
df['platform'] = df['platform'].astype("string")
print(df['platform'].dtype)

string

In [18]:
df['platform'] = df['platform'].fillna('Bolt')

In [19]:
df['customer_handling_score_10'] = df['customer_handling_score_10'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    #'Unknown': 'Experienced',
    #'None': 'Fairly_Experienced',
    #'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Motorcycle',
    #'Na': '1-20 yrs',
    #'-': '10-30 yrs',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    '<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
10141,DRV020269,Vijay Shukla,70,Pune,9962149689,vijay.shukla@rediffmail.com,Rapido,Sedan,Poor,5+ yrs,...,9.1,10.0,8.5,8.9,Fail,Clear,On hold,Invalid_id,2026-04-13 09:25:07,False
4140,DRV000915,Vikram Verma,23,Kolkata,9700109237,vikram.vermarediffmail.com,Rapido,Bike,Super,4+ yrs,...,7.3,5.6,5.6,6.4,Distinction,Flagged,On hold,Invalid_id,2025-08-11 17:21:52,False
23588,DRV027631,Umesh Chaudhary,-48,Kolkata,9480297433,umesh.chaudhary@gmail.com,Uber,Sedan,Excellent,1-3 yrs,...,8.6,4.9,3.9,6.7,Distinction,Clear,On hold,Invalid_id,2025-03-24 16:11:20,True
1270,DRV037988,Deepak Dubey,20,Delhi,91807591916,deepak.dubey@hotmail.com,Uber,Bike,Average,3-5 yrs,...,4.2,7.5,9.5,7.1,Distinction,Pending,Rejected,Low rating history,2025-12-26 10:30:30,True
37642,DRV034807,Mahesh Chaudhary,55,Lucknow,9787825607,mahesh.chaudhary@gmail.com,Rapido,Sedan,Poor,1-3 yrs,...,11.3,1.1,6.1,7.2,Pending,Clear,Rejected,Poor communication,2026-06-17 10:17:10,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29183,DRV033870,Yogesh Srivastava,30,Delhi,9720900270,yogesh.srivastava@yahoo.com,Rapido,Mini,Excellent,1-3 yrs,...,9.5,3.9,8.8,6.6,Distinction,Pending,Rejected,Invalid_id,2025-04-24 12:08:40,False
11689,DRV045615,Harish Kumar,49,Ahmedabad,9377447951,harish.kumar@hotmail.com,Ola,Bike,Super,3-5 yrs,...,5.5,10.0,8.5,7.0,Distinction,Clear,Selected,Invalid_id,2026-01-14 19:07:06,True
39960,DRV025431,Dinesh Chauhan,-51,Chennai,9908425954,dinesh.chauhan@yahoo.com,Bolt,Auto,Average,1-3 yrs,...,8.2,10.0,8.5,7.3,Distinction,Flagged,On hold,Invalid_id,2025-07-04 14:54:00,True
31795,DRV016838,RAJESH YADAV,47,Jaipur,9037051253,rajesh.yadav@hotmail.com,Bolt,Mini,Good,5+ yrs,...,9.0,7.6,8.9,7.8,Pending,Flagged,Selected,Invalid_id,2026-04-07 17:25:22,True
36072,DRV016452,Girish Gupta,48,Lucknow,9198840375,Girish Gupta@gmail.com,Uber,Mini,Excellent,1-3 yrs,...,6.0,3.5,5.8,5.0,Pending,Pending,On hold,Invalid_id,2025-11-25 10:18:50,False

In [20]:
## This capitalises the city column to give it a uniform format and also converts the data type from object to string.
df['city'] = df['city'].str.capitalize()
df['city'] = df['city'].astype("string")
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
10812,DRV000289,ajay pandey,20,Pune,9561469,ajay.pandey@hotmail.com,Uber,Sedan,Good,3-5 yrs,...,4.5,7.4,8.5,5.2,Pending,Flagged,On hold,Invalid_id,2025-03-28 19:28:50,False
23904,DRV011653,VIJAY RAO,999,Hyderabad,91397034402,vijay.rao@yahoo.com,Rapido,Suv,Poor,1-3 yrs,...,7.1,4.2,6.7,5.5,Distinction,Clear,On hold,Vehicle age too old,2025-02-10 21:13:35,False
18270,DRV001516,Umesh Tripathi,26,Kolkata,9190402432,umesh.tripathi@gmail.com,Uber,Suv,Good,3-5 yrs,...,6.8,8.1,4.4,0.9,Pass,Pending,Selected,Invalid_id,2026-01-04 08:04:59,True
195,DRV023156,Yogesh Srivastava,31,Hyderabad,9068347127,yogesh.srivastava@gmail.com,Ola,Sedan,Poor,1-3 yrs,...,6.6,8.9,7.6,6.8,Distinction,Clear,On hold,Invalid_id,2025-08-18 14:12:48,True
2783,DRV006567,Vikram Rao,39 yrs,Jaipur,9890545,vikram.rao@rediffmail,Uber,Bike,Excellent,High,...,6.6,4.1,7.7,6.6,Pass,Pending,On hold,Invalid_id,2026-06-24 15:47:31,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10548,DRV040415,Rakesh Chaudhary,55,Ahmedabad,9524089092,rakesh.chaudhary@rediffmail.com,Bolt,Mini,Excellent,4+ yrs,...,4.2,8.4,8.0,6.6,Pass,Flagged,Rejected,Invalid_id,2025-07-20 05:41:37,True
44973,DRV018978,Ramesh Dubey,30,Chennai,91766243608,ramesh.dubey@hotmail.com,Uber,Sedan,Poor,5+ yrs,...,6.7,11.5,8.5,7.7,Fail,Clear,Selected,Invalid_id,2025-12-24 09:58:04,True
522,DRV043456,Girish Singh,-25,Mumbai,91408774038,girish.singh@rediffmail.com,Uber & rapido,Mini,Good,5+ yrs,...,8.7,12.1,5.2,8.8,Pending,Pending,On hold,Invalid_id,2026-01-31 08:10:54,True
7334,DRV045658,Pankaj Chaudhary,unknown,Lucknow,9102012643,pankaj.chaudhary@@gmail.com,Uber,Sedan,Super,Fresher,...,6.7,3.8,6.4,6.7,Distinction,Pending,On hold,Invalid_id,2025-07-14 09:34:17,False
8291,DRV006639,Ganesh Reddy,27,Ahmedabad,9121455807,ganesh.reddy@yahoo.com,Rapido,Auto,Poor,4+ yrs,...,6.7,1.4,11.7,7.4,Distinction,Clear,Rejected,Invalid_id,2025-10-08 15:38:08,False

In [21]:
df['route_knowledge_score_10'].unique()

array([ 5.8,  7.5,  9. ,  9.6,  6.5,  8.6,  8.7,  6.4,  7.9,  7.7,  3.6,
        5.2,  6.8,  8.5,  7.1,  4.6,  1.2,  5. ,  3.2,  3.5,  3.8,  5.6,
        4.9,  8.8, 12. ,  6.7,  6.3,  9.9,  3.4,  9.8,  0.3, 10.7,  9.4,
       12.4,  4.2,  6.2,  3.9, 10. ,  6. ,  9.5,  7.4,  3. , 10.3,  7. ,
       10.2,  6.1,  3.3,  8. ,  4. ,  4.7,  4.5,  7.6,  5.9,  1.3,  4.1,
        5.1,  4.3, 12.2, 11.2,  8.1, 11.9,  5.4,  0.9,  5.5,  6.6,  3.7,
        9.3, 12.8,  8.2, 10.8,  5.3,  9.2, 12.3,  3.1,  7.8,  7.2,  9.1,
        4.8,  6.9,  9.7, 12.7,  8.9,  4.4,  7.3, 11. ,  0.4, 13. , 11.7,
        8.4,  1.5, 11.5, 12.9, 10.5,  5.7,  1.1,  1.4, 10.1,  8.3,  0.7,
       10.4,  0.8,  1.9, 12.1,  2. ,  0.2, 10.9,  1.8, 11.1,  1. , 11.8,
       11.3, 11.4,  0.5, 12.5,  1.7,  1.6,  0.1, 10.6, 12.6,  0.6, 11.6])

In [22]:
## This converts the data type from object to string.
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].astype("string")
print(df['route_knowledge_score_10'].dtype)

string

In [23]:
## This is to remove the negative values and also the yrs in the age column.
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].str.lstrip('-')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
21122,DRV013376,PANKAJ PANDEY,34 yrs,Jaipur,9752680509,pankaj.pandey@rediffmail.com,Rapido,Mini,Excellent,3-5 yrs,...,8.5,8.5,5.9,7.9,Pass,Pending,Rejected,Failed driving test,2025-08-22 10:09:24,False
38176,DRV036041,Vikram Srivastava,20,Jaipur,9781827380,vikram.srivastava@hotmail.com,Uber & rapido,Suv,Good,Fresher,...,10.7,4.7,4.1,6.8,Distinction,Clear,Selected,Invalid_id,2025-01-18 06:34:09,True
25963,DRV008853,Hitesh Sharma,55,Kolkata,9710928199,hitesh.sharma@hotmail.com,Uber,Catapiller,Average,5+ yrs,...,10.0,9.9,3.0,7.7,Pass,Flagged,Selected,Invalid_id,2025-12-18 15:58:40,False
14274,DRV043446,Sanjay Jha,46,Delhi,91739541106,sanjay.jha@yahoo.com,Uber,Suv,Average,3-5 yrs,...,4.3,8.9,5.4,0.5,Distinction,Clear,Selected,Invalid_id,2026-02-17 14:35:41,True
48497,DRV036235,Dinesh Reddy,51,Pune,9446251386,Dinesh Reddy@gmail.com,Rapido,Motorbike,Average,3-5 yrs,...,5.6,6.0,6.5,6.0,Pending,Pending,Selected,Invalid_id,2025-04-28 18:25:37,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2714,DRV017258,BHARAT REDDY,999,Pune,9051243310,bharat.reddy@@hotmail.com,Uber & rapido,Mini,Average,1-3 yrs,...,9.2,5.3,7.4,6.3,Pending,Flagged,Selected,Invalid_id,2026-04-21 04:09:50,False
18298,DRV027272,Pradeep Reddy,50,Jaipur,9738680612,pradeep.reddy@hotmail.com,Bolt,Mini,Poor,3-5 yrs,...,5.0,5.8,7.9,6.1,Pass,Pending,On hold,Invalid_id,2025-10-08 07:44:01,False
22454,DRV023276,Mahesh Nair,70,Kolkata,9856624760,mahesh.nair@hotmail,Rapido,Sedan,Good,Fresher,...,4.4,9.9,6.3,7.3,Pending,Clear,Selected,Invalid_id,2026-05-16 07:22:39,True
43929,DRV012801,Vikram Yadav,48,Chennai,9847505,Vikram Yadav@gmail.com,Uber,Auto,Average,4+ yrs,...,5.8,6.8,12.4,7.0,Fail,Clear,Rejected,Poor communication,2025-05-12 19:29:53,True
38961,NaN,Rakesh Kumar,29,Chennai,9680583455,rakesh.kumar@yahoo.com,Uber,Bike,Good,3-5 yrs,...,7.0,3.2,8.4,6.2,Fail,Pending,Selected,Invalid_id,2026-07-16 16:13:51,True

In [24]:
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].fillna('7.5')

In [25]:
## This code fills the age column where NaN values exist with random values between 0 and 10

import numpy as np

mask = df['customer_handling_score_10'] == 6

df.loc[mask, 'customer_handling_score_10'] = np.random.randint(
    0, 10, size=mask.sum()
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
43509,DRV007189,sunil yadav,24,Bangalroe,9919391816,sunil.yadav@gmail.com,Rapido,Bike,Poor,1-3 yrs,...,9.1,6.5,7.2,7.6,Average,Flagged,On hold,Invalid_id,2026-07-06 00:35:00,True
1956,DRV001318,Naveen Mishra,35,Kolkata,9778207064,naveen.mishra@hotmail.com,Uber,Sedan,Excellent,Fresher,...,8.9,6.0,9.7,10.8,Pass,Flagged,Selected,Invalid_id,2025-06-03 09:22:43,True
49499,DRV047335,Umesh Verma,37,Delhi,9786917330,umesh.verma@yahoo.com,Uber,Mini,Average,Fresher,...,6.2,8.0,7.5,7.3,Distinction,Clear,Selected,Invalid_id,2026-04-30 19:21:28,True
2187,DRV013738,SANTOSH YADAV,unknown,Pune,9869371838,santosh.yadav@gmail.com,Rapido,Tricycle,Average,3-5 yrs,...,4.4,6.5,6.3,6.3,Pass,Clear,Rejected,Background check failed,2025-12-22 18:20:21,False
12674,DRV047251,Manoj Nair,43,Kolkata,9635536315,manoj.nair@hotmail.com,Uber,Auto,Super,3-5 yrs,...,6.8,4.6,8.5,5.8,Pass,Pending,On hold,Invalid_id,2026-06-09 21:07:31,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18383,DRV039534,Girish Sharma,27,Lucknow,91667105297,girish.sharma@yahoo.com,Uber,Sedan,Super,4+ yrs,...,9.3,8.3,7.4,8.5,Fail,Clear,On hold,Invalid_id,2025-11-15 19:31:04,False
44601,DRV019648,Naresh Rao,27,Delhi,9732096047,naresh.rao@hotmail.com,Rapido,Auto,Poor,4+ yrs,...,9.3,5.1,8.3,7.6,Pass,Flagged,Selected,Vehicle age too old,2025-10-25 13:11:48,False
37478,DRV010598,Vikram Reddy,41,Kolkata,9115663841,vikram.reddy@rediffmail.com,Uber,Tricycle,Good,3-5 yrs,...,9.1,7.5,8.5,6.3,Average,Clear,Selected,Invalid_id,2026-06-29 02:26:18,True
41344,DRV039481,Vikram Rao,48,Kolkata,9585124045,vikram.rao@@yahoo.com,Rapido,Bike,Good,3-5 yrs,...,8.3,4.0,6.7,6.6,Distinction,Flagged,Selected,Invalid_id,2025-02-01 11:32:09,True
8017,DRV048742,Vikram Chauhan,48,Jaipur,9665672435,vikram.chauhan@@rediffmail.com,Uber,Bike,Excellent,4+ yrs,...,8.2,8.7,8.5,8.8,Pass,Clear,Selected,Invalid_id,2026-01-17 09:28:32,True

In [26]:
df['vehicle_type'].unique()

array(['Auto', 'Mini ', 'Suv', 'Mini', 'Bike', 'Sedan', 'Tricycle',
       'Motorbike', 'Bicycle', 'Catapiller', 'Truck'], dtype=object)

In [27]:
## This converts the data type from object to string.
df['vehicle_type'] = df['vehicle_type'].astype("string")
print(df['vehicle_type'].dtype)

string

In [28]:
df['vehicle_type'] = df['vehicle_type'].str.capitalize()
df['vehicle_type'] = df['vehicle_type'].fillna('Motorbike')
df['vehicle_type'] = df['vehicle_type'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    #'Unknown': 'Experienced',
    'None': 'Bicycle',
    #'Avg': 'Average',
    #'poor': 'Super',
    'Unknown': 'Tricycle',
    'Na': 'Catapiller',
    '-': 'Truck',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
30789,DRV022164,Rajesh Srivastava,54,Pune,9005255414,rajesh.srivastava@@hotmail.com,Uber,Auto,Good,1-3 yrs,...,8.2,7.5,7.9,6.0,Distinction,Pending,On hold,Invalid_id,2025-12-09 18:13:23,True
29262,DRV035680,Girish Yadav,33,Mumbai,91367176720,girish.yadav@yahoo.com,Rapido,Suv,Good,1-3 yrs,...,4.5,4.7,8.5,5.6,Pending,Clear,Waitlist,Invalid_id,2025-11-29 05:02:29,True
21658,DRV035279,Sunil Singh,28,Chennai,9237165769,sunil.singh@rediffmail.com,Rapido,Suv,Poor,High,...,5.6,5.4,11.9,6.8,Average,Flagged,On hold,Invalid_id,2025-01-04 13:50:00,True
17105,DRV047108,Mahesh Patel,999,Hyderabad,9876971335,mahesh.patel@rediffmail.com,Ola,Mini,Excellent,7+ yrs,...,7.2,5.1,8.0,6.9,Pass,Flagged,Selected,Invalid_id,2026-02-19 00:15:48,True
7311,DRV020445,Rakesh Tiwari,38,Mumbai,91355185791,rakesh.tiwari@@yahoo.com,Rapido,Sedan,Good,5+ yrs,...,7.5,6.9,8.6,6.7,Pending,Flagged,Selected,Invalid_id,2025-04-25 13:01:26,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16183,DRV006003,Pankaj Srivastava,27,Chenna,91197995400,pankaj.srivastava@rediffmail.com,Uber,Bike,Super,High,...,6.1,4.2,7.1,10.7,Pending,Clear,Selected,Invalid_id,2026-04-10 00:48:27,True
41820,DRV036229,Harish Tiwari,20,Lucknow,9152943149,harish.tiwariyahoo.com,Rapido,Mini,Super,1-3 yrs,...,7.3,4.5,8.4,1.4,Pending,Clear,Rejected,Poor communication,2025-10-21 00:27:29,False
18286,DRV039116,Ramesh Tripathi,44,Jaipur,9728771844,ramesh.tripathi@gmail.com,Ola,Sedan,Excellent,4+ yrs,...,4.6,6.2,4.6,0.7,Pending,Clear,Selected,Invalid_id,2025-10-04 11:20:32,False
12938,DRV003468,Naveen Jha,-26,Lucknow,9550258977,naveen.jha@rediffmail,Rapido,Sedan,Average,Fresher,...,8.7,6.7,4.9,7.6,Pass,Clear,Selected,Invalid_id,2025-04-06 01:48:11,True
32290,DRV033395,Ganesh Singh,32 yrs,Mumbai,9184191,ganesh.singh@hotmail.com,Rapido,Bike,Average,3-5 yrs,...,7.1,8.9,8.8,8.6,Distinction,Flagged,Rejected,Failed driving test,2025-03-15 05:16:08,False

In [29]:
df['vehicle_condition'].unique()

array(['Good', 'Excellent', 'Average', 'Super', 'Poor', 'Great',
       'Wonderful', 'Fair', 'Beautiful'], dtype=object)

In [30]:
## This converts the data type from object to string.
df['vehicle_condition'] = df['vehicle_condition'].astype("string")
print(df['vehicle_condition'].dtype)

string

In [31]:
df['vehicle_condition'] = df['vehicle_condition'].str.capitalize()
df['vehicle_condition'] = df['vehicle_condition'].fillna('Super')
df['vehicle_condition'] = df['vehicle_condition'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    'Unknown': 'Great',
    'None': 'Beautiful',
    'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Tricycle',
    'Na': 'Fair',
    '-': 'Wonderful',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
21558,DRV006231,Ajay Sharma,50,Bangalore,9979107400,ajay.sharma@hotmail.com,Uber,Auto,Super,1-3 yrs,...,7.5,7.5,8.5,5.7,Distinction,Clear,Selected,Invalid_id,2026-04-20 12:00:37,True
37730,DRV010329,SUNIL TIWARI,20,Mumbai,9087157035,sunil.tiwari@hotmail.com,Rapido,Sedan,Super,4+ yrs,...,6.6,3.2,8.5,5.2,Pass,Flagged,Rejected,Invalid_id,2025-02-15 11:46:18,False
761,DRV008727,Umesh Chauhan,999,Delhi,9068961867,umesh.chauhanrediffmail.com,Uber,Catapiller,Good,4+ yrs,...,4.9,7.5,8.7,7.2,Pending,Flagged,Rejected,Incomplete documents,2026-02-01 08:46:06,False
43738,DRV028979,Ramesh Jha,23,Delhi,91825129867,ramesh.jha@gmail.com,Ola,Suv,Super,High,...,6.7,4.0,3.6,5.8,Pass,Flagged,Rejected,Incomplete documents,2025-09-22 08:08:53,False
19201,DRV026265,Yogesh Tiwari,31 yrs,Jaipur,9820412424,yogesh.tiwari@hotmail.com,Uber,Motorbike,Super,1-3 yrs,...,6.1,4.0,7.8,5.8,Distinction,Clear,Selected,Invalid_id,2025-09-29 05:36:31,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6745,DRV024424,Ajay Chauhan,49,Bangalore,91399572810,ajay.chauhan@rediffmail,Rapido,Auto,Poor,Fresher,...,6.6,4.5,8.5,8.8,Pending,Clear,Selected,Poor communication,2026-07-12 08:59:28,False
19236,DRV008733,Deepak Shukla,41,Hyderabad,9057375900,deepak.shukla@yahoo.com,Uber & rapido,Bicycle,Great,8 yrs,...,1.6,6.7,3.3,4.9,Pending,Pending,Rejected,Incomplete documents,2025-06-14 10:24:02,False
48211,DRV017852,Suresh Jha,23,Kolkata,91097000692,suresh.jha@gmail.com,Rapido,Auto,Poor,4+ yrs,...,7.9,1.3,9.5,6.7,Fail,Pending,Rejected,Not applicable,2026-04-12 09:16:13,False
24212,DRV006291,Vijay Dubey,51,Lucknow,9275207649,vijay.dubey@@yahoo.com,Uber,Auto,Poor,3-5 yrs,...,7.5,7.5,8.8,1.3,Fail,Clear,Rejected,Invalid_id,2026-02-05 06:23:07,False
49557,DRV019882,Manoj Tripathi,44,Mumbai,91902912116,manoj.tripathi@gmail.com,Rapido,Suv,Average,Fresher,...,6.4,3.9,4.6,8.8,Pending,Clear,Selected,Invalid_id,2025-10-05 00:04:19,True

In [32]:
df['experience_level'].unique()

array(['4+ yrs', 'Fresher', '1-3 yrs', '5+ yrs', '3-5 yrs', 'High',
       '7+ yrs', '6 yrs', '8 yrs', '8+ yrs'], dtype=object)

In [33]:
## This converts the data type from object to string.
df['experience_level'] = df['experience_level'].astype("string")
print(df['experience_level'].dtype)

string

In [34]:
df['experience_level'] = df['experience_level'].str.capitalize()
df['experience_level'] = df['experience_level'].fillna('High')
df['experience_level'] = df['experience_level'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    '0-1 yr' : '4+ yrs',
    'Unknown': '7+ yrs',
    'None': '8+ yrs',
    #'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Tricycle',
    'Na': '6 yrs',
    '-': '8 yrs',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
6277,DRV033292,naresh srivastava,50,Bangalore,9518787320,naresh.srivastava@gmail.com,Uber & rapido,Bike,Excellent,5+ yrs,...,9.2,3.8,8.5,11.7,Fail,Clear,Selected,Poor communication,2025-09-17 17:43:25,False
18771,DRV010470,Santosh Dubey,25 yrs,Mumbai,9087549368,santosh.dubey@yahoo.com,Uber,Auto,Poor,1-3 yrs,...,11.5,11.2,11.9,5.9,Pending,Clear,On hold,Invalid_id,2025-07-28 04:33:34,True
34523,DRV044217,Ajay Mishra,43 yrs,Bangalore,9293113288,ajay.mishra@@yahoo.com,-,Bike,Excellent,3-5 yrs,...,5.3,9.8,7.0,10.3,Distinction,Clear,Selected,Invalid_id,2026-04-02 10:59:31,False
35063,DRV006772,PANKAJ SHUKLA,48,Bangalore,9388737191,PANKAJ SHUKLA@gmail.com,Rapido,Auto,Super,3-5 yrs,...,8.7,7.2,9.5,7.7,Pending,Clear,Selected,Invalid_id,2026-07-23 19:09:23,False
35258,DRV027301,Hitesh Sharma,23,Lucknow,9653236259,hitesh.sharma@gmail.com,Ola,Auto,Excellent,5+ yrs,...,11.6,3.2,8.5,5.2,Distinction,Pending,Selected,Invalid_id,2025-08-31 19:41:44,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27089,DRV003019,Ramesh Srivastava,34,Pune,9856311224,ramesh.srivastava@yahoo.com,Rapido,Suv,Super,7+ yrs,...,6.4,7.5,3.4,5.0,Distinction,Flagged,Selected,Invalid_id,2026-05-21 03:17:31,True
1548,DRV042748,Dinesh Rao,28,Jaipur,9779936925,dinesh.rao@rediffmail.com,Uber,Suv,Excellent,5+ yrs,...,6.3,7.3,7.0,6.0,Pending,Flagged,Selected,Invalid_id,2025-09-08 18:32:53,True
24197,DRV015412,Naveen Tiwari,55,Delhi,9337135858,naveen.tiwari@yahoo.com,Ola,Sedan,Average,1-3 yrs,...,7.6,9.3,8.6,7.9,Pass,Pending,Rejected,Vehicle age too old,2026-05-20 12:38:37,False
10734,DRV040381,Mukesh Tripathi,26 yrs,Ahmedabad,91984112974,mukesh.tripathi@hotmail.com,Ola,Motorbike,Good,5+ yrs,...,4.6,4.7,8.5,4.5,Pending,Pending,Rejected,Invalid_id,2025-06-07 01:26:06,True
48707,DRV007212,Santosh Verma,47,Kolkata,91621681543,Santosh Verma@gmail.com,Uber,Bike,Super,4+ yrs,...,9.7,1.3,9.2,8.2,Fail,Clear,On hold,Background check failed,2026-02-26 12:53:54,True

In [35]:
df['driving_test_score_10'].unique()

<StringArray>
[ '4.3',  '9.3',  '6.3',  '8.7', '12.7',  '8.8',  '8.1',  '1.1', '11.6',
  '7.5',
 ...
 '12.3',  '1.6', '12.6',  '1.9', '10.6', '12.9', '11.1', '13.0',  '0.1',
  '2.0']
Length: 111, dtype: string

In [36]:
## This converts the data type from object to string.
df['driving_test_score_10'] = df['driving_test_score_10'].astype("string")
print(df['driving_test_score_10'].dtype)

string

In [37]:
df['driving_test_score_10'] = df['driving_test_score_10'].fillna('7.5')

In [38]:
df['route_knowledge_score_10'].unique()

<StringArray>
[ '5.8',  '7.5',  '9.0',  '9.6',  '6.5',  '8.6',  '8.7',  '6.4',  '7.9',
  '7.7',
 ...
 '11.4',  '0.5', '12.5',  '1.7',  '1.6',  '0.1', '10.6', '12.6',  '0.6',
 '11.6']
Length: 121, dtype: string

In [39]:
df['customer_handling_score_10'].unique()

array([ 7.7,  9. ,  5.5,  5.3,  7.9, 10.5,  9.7,  8.5, 10.7,  5.9,  6.2,
        4.9,  6.7,  6.9,  6.8, 12.3,  1. ,  3.5,  5. ,  4.1, 11.2,  8.9,
        7.6,  6.5,  3.6, 10.6,  4.3,  3.8,  3.2,  7.5,  4.6,  5.7,  3.7,
        0.9,  4.7,  4.2,  1.6,  8.8,  0.6,  6.4,  6.3,  9.8,  7. ,  9.5,
        8.3,  3.1,  9.4,  6.6,  9.1, 11.4,  7.3,  7.4, 11.5,  8.6,  9.6,
        7.2,  3. ,  3.3,  8.1,  3.4,  4.4,  4. ,  8.4,  8. ,  5.1,  5.2,
        1.9,  5.4,  4.5, 12. ,  6.1,  7.1, 11.1, 10. ,  5.6,  1.3, 12.8,
        1.2,  8.7,  3.9, 11.6,  9.2,  1.8,  7.8,  9.9,  9.3, 11.3, 11. ,
       12.6, 12.1,  8.2, 12.5,  1.7,  2. ,  5.8,  0.2, 12.4, 11.7,  0.7,
       12.9, 10.3, 12.2, 10.8,  4.8, 10.9,  1.5, 11.9, 11.8,  1.1,  0.8,
       10.4,  0.3,  0.4,  0.5,  0.1, 10.2, 13. , 12.7,  1.4, 10.1,  0. ,
        6. ])

In [40]:
## This converts the data type from object to string.
df['customer_handling_score_10'] = df['customer_handling_score_10'].astype("string")
print(df['customer_handling_score_10'].dtype)

string

In [41]:
df['customer_handling_score_10'] = df['customer_handling_score_10'].fillna('8.5')
df['customer_handling_score_10'] = df['customer_handling_score_10'].str.lstrip('-')

In [42]:
df['overall_interview_score_10'].unique()

array([ 5.3,  8.1,  6.9,  7.8,  6. ,  1.4,  8.2,  8.3,  6.7,  5.8,  7.7,
        8.8,  7.6,  6.5,  7.5,  4.1,  6.2,  1.6,  6.4,  7.2,  7.4,  3.6,
        6.3,  6.1,  5.2,  1.3,  5.6,  5.7,  5. ,  5.5,  6.8,  6.6, 10.7,
        7.3, 11.6,  4.2, 10.6, 10.5,  7.1, 12.6,  1. ,  7. ,  4.8, 11.1,
       11.9, 10.3,  4.9,  5.1,  4.5,  5.9,  8. , 12.4, 11.5, 12.9,  4.6,
        5.4,  7.9,  2. , 13. ,  9.7, 10.1,  1.8,  1.9, 11.7,  8.6,  1.5,
        8.4, 11.8, 11. ,  9.2,  8.5, 12.3, 12.5, 12.8, 12. , 11.4,  4.7,
        4.4,  1.7,  0.8,  0.7,  0.3,  8.7,  9.1,  4.3, 12.1,  0.4, 12.7,
        0.2, 11.2, 10.8,  8.9, 12.2, 10.9,  1.2, 10.2,  0.6, 11.3,  4. ,
        1.1,  0.5, 10.4,  9. ,  9.4,  3.9,  0.9,  3.8,  0.1,  9.3,  9.6,
        3.7,  9.5,  3.5,  9.8,  3.4])

In [43]:
## This converts the data type from object to string.
df['overall_interview_score_10'] = df['overall_interview_score_10'].astype("string")
print(df['overall_interview_score_10'].dtype)

string

In [44]:
df['overall_interview_score_10'] = df['overall_interview_score_10'].fillna('8.8')
df['overall_interview_score_10'] = df['overall_interview_score_10'].str.lstrip('-')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
27751,DRV005540,Lokesh Jha,27,Pune,9251571206,lokesh.jha@@hotmail.com,Rapido,Auto,Average,1-3 yrs,...,5.1,3.4,4.2,5.5,Exceptional,Pending,Rejected,Poor communication,2025-08-28 17:29:07,True
10493,DRV000602,Mahesh Verma,26,Lucknow,9050946844,mahesh.vermagmail.com,Uber,Bike,Average,5+ yrs,...,7.2,5.7,8.5,8.8,Fail,Pending,Selected,Invalid_id,2025-11-26 08:03:44,False
9906,DRV004073,Pradeep Yadav,38,Chennai,91576537432,pradeep.yadav@@gmail.com,Uber,Auto,Poor,5+ yrs,...,12.5,9.3,3.6,7.4,Pending,Flagged,Selected,Invalid_id,2026-01-12 19:09:05,True
12639,DRV017640,Rakesh Nair,40,Kolkata,9852555905,rakesh.nair@yahoo.com,Uber,Sedan,Good,High,...,6.2,7.5,8.5,5.7,Fail,Clear,Selected,Invalid_id,2025-01-26 17:00:00,False
1699,DRV044096,MANOJ SINGH,52,Ahmedabad,9890290020,manoj.singh@rediffmail,Uber,Bike,Average,4+ yrs,...,8.1,6.1,9.4,8.8,Distinction,Clear,Rejected,Failed driving test,2026-07-31 08:48:48,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19534,DRV000749,Harish Nair,33 yrs,Ahmedabad,9474122985,harish.nair@rediffmail.com,Rapido,Mini,Super,1-3 yrs,...,5.3,9.6,3.8,8.8,Distinction,Flagged,Selected,Invalid_id,2026-05-09 17:56:11,False
18104,DRV038260,R@kesh Dubey,25,Chennai,9265009139,rakesh.dubey@gmail.com,Ola,Sedan,Excellent,1-3 yrs,...,5.5,4.6,7.5,6.2,Pass,Flagged,Rejected,Invalid_id,2026-03-19 21:36:11,True
32080,DRV024736,Naveen Patel,42,Ahmedabad,9106740827,naveen.patel@yahoo.com,Uber,Sedan,Average,5+ yrs,...,4.5,5.3,12.7,5.8,Distinction,Clear,Rejected,Invalid_id,2025-07-15 18:19:33,False
11676,NaN,Sanjay Rao,24,Chennai,9325212440,sanjay.rao@gmail.com,Uber,Bike,Poor,Fresher,...,5.8,7.5,4.4,4.9,Distinction,Pending,On hold,Not applicable,2025-11-26 14:46:34,True
38598,DRV015551,Vijay Kumar,36,Pune,9098085382,vijay.kumar@gmail.com,Rapido,Auto,Excellent,1-3 yrs,...,8.5,6.0,4.3,6.0,Fail,Flagged,Selected,Invalid_id,2025-07-11 15:38:03,False

In [45]:
df['document_verification'].unique()

array(['Fail', 'Distinction', 'Average', 'Pass', 'Pending', 'Credit',
       'Exceptional', 'Fair'], dtype=object)

In [46]:
## This converts the data type from object to string.
df['document_verification'] = df['document_verification'].astype("string")
print(df['document_verification'].dtype)

string

In [47]:
df['document_verification'] = df['document_verification'].str.capitalize()
df['document_verification'] = df['document_verification'].fillna('Distinction')
df['document_verification'] = df['document_verification'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999': '90',
    #'0-1 yr' : '4+ yrs',
    #'Unknown':'High',
    'None':'Credit',    
    #'Avg': 'Average',
    #'poor': 'Super',
    'Unknown':'Average',
    'Na': 'Fair',
    '-': 'Exceptional',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
44183,DRV040855,Ajay Rao,26,Chennai,91496818761,ajay.rao@gmail.com,Rapido,Mini,Poor,3-5 yrs,...,6.7,6.5,5.5,5.8,Pending,Pending,Selected,Invalid_id,2026-07-04 22:04:18,True
11670,DRV000615,Suresh Pandey,34,Delhi,91386705657,suresh.pandey@gmail.com,Rapido,Bike,Excellent,Fresher,...,7.6,3.3,8.5,5.6,Distinction,Pending,Selected,Invalid_id,2025-11-25 06:31:08,False
48711,DRV029714,dinesh tiwari,-20,Chennai,9392220564,dinesh.tiwari@gmail.com,Bolt,Auto,Super,1-3 yrs,...,1.0,7.2,8.7,7.1,Fail,Pending,Rejected,Invalid_id,2026-08-02 20:25:59,True
39874,DRV004966,santosh shukla,20,Pune,91444329949,santosh.shukla@hotmail.com,Uber,Tricycle,Poor,4+ yrs,...,9.0,6.9,10.8,7.1,Fail,Pending,Selected,Invalid_id,2025-04-17 10:24:21,True
14923,DRV000839,UMESH TRIPATHI,55,Chennai,9876355625,umesh.tripathi@gmail.com,Uber,Sedan,Super,Fresher,...,7.2,0.6,12.9,6.2,Distinction,Clear,On hold,Poor communication,2026-07-26 17:18:56,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11144,DRV012145,Yogesh Chaudhary,39,Mumabi,91756860246,yogesh.chaudhary@gmail.com,Uber & rapido,Mini,Average,High,...,8.1,9.0,4.5,7.7,Pending,Clear,Selected,Invalid_id,2026-07-16 04:56:18,True
34141,DRV031916,Ravi Shukla,70,Chennai,9949528006,ravi.shukla@@hotmail.com,Rapido,Suv,Good,Fresher,...,5.2,4.2,5.5,4.9,Distinction,Clear,Rejected,Poor communication,2025-02-22 14:55:57,False
46804,DRV046654,Deep@k Sriv@st@v@,45,Bangalore,9282041345,deepak.srivastava@gmail.com,Rapido,Suv,Good,4+ yrs,...,6.3,7.8,9.8,7.2,Pass,Flagged,Rejected,Not applicable,2025-01-05 05:50:47,True
48826,DRV040380,Anil Srivastava,22,Lucknow,9597356462,anil.srivastava@rediffmail.com,Uber,Suv,Super,5+ yrs,...,4.1,6.4,5.5,4.9,Fail,Pending,Selected,Not applicable,2025-12-07 18:38:41,False
9997,DRV006501,MAHESH REDDY,37,Hyderabad,9194035726,mahesh.reddy@yahoo.com,Uber,Bike,Beautiful,1-3 yrs,...,6.7,11.6,3.9,6.7,Fail,Clear,Selected,Invalid_id,2025-03-02 16:48:34,False

In [48]:
df['document_verification'].unique()

<StringArray>
[       'Fail', 'Distinction',     'Average',        'Pass',     'Pending',
      'Credit', 'Exceptional',        'Fair']
Length: 8, dtype: string

In [49]:
df['background_check_status'].unique()

array(['Clear', 'Pending', 'Flagged'], dtype=object)

In [50]:
## This converts the data type from object to string.
df['background_check_status'] = df['background_check_status'].astype("string")
print(df['background_check_status'].dtype)

string

In [51]:
df['background_check_status'] = df['background_check_status'].str.capitalize()
df['background_check_status'] = df['background_check_status'].fillna('Clear')
df['background_check_status'] = df['background_check_status'].replace({
'Na': 'Clear', 
'Unknown': 'Clear', 
'None': 'Pending', 
'-': 'Clear'
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
20345,DRV007535,Bharat Yadav,55,Lucknow,9947374234,bharat.yadav@yahoo.com,Rapido,Auto,Good,5+ yrs,...,8.4,8.5,8.5,7.1,Pending,Clear,On hold,Invalid_id,2026-05-24 09:42:46,False
17265,DRV022843,anil yadav,70,Mumbai,9313222989,anil.yadav@@rediffmail.com,Uber,Sedan,Excellent,5+ yrs,...,9.9,8.1,6.2,8.8,Pass,Flagged,Selected,Invalid_id,2026-04-19 09:27:03,True
21496,DRV037446,Rakesh Chauhan,999,Jaipur,9103366,rakesh.chauhan@rediffmail.com,Uber,Auto,Poor,Fresher,...,5.7,7.5,0.7,6.5,Pending,Clear,On hold,Invalid_id,2025-11-22 02:14:13,False
27594,DRV025086,Vijay Jha,unknown,Pune,9711611728,vijay.jha@yahoo.com,Rapido,Auto,Excellent,Fresher,...,6.1,0.8,7.1,6.8,Pending,Clear,On hold,Invalid_id,2025-03-05 04:19:54,True
10209,DRV045618,deepak chauhan,31,Jaipur,9465114080,deepak chauhan@gmail.com,Uber,Sedan,Excellent,3-5 yrs,...,5.1,8.7,9.3,7.5,Pass,Pending,Selected,Invalid_id,2026-05-12 03:09:24,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24120,DRV039430,Dinesh Verma,50,Lucknow,9503578065,dinesh.verma@hotmail.com,Uber & rapido,Sedan,Excellent,5+ yrs,...,6.3,5.8,9.1,6.6,Average,Clear,On hold,Invalid_id,2026-06-27 07:23:07,True
41332,DRV043365,MAHESH RAO,32,Bangalore,91903311647,mahesh.rao@@gmail.com,Rapido,Auto,Excellent,1-3 yrs,...,8.2,9.5,9.6,9.2,Distinction,Pending,Selected,Selected,2025-01-08 04:57:11,False
20311,DRV045957,NAVEEN VERMA,24,Mumbai,9755099311,naveen.verma@hotmail.com,Uber,Sedan,Super,1-3 yrs,...,7.5,3.7,8.4,11.2,Pending,Pending,Rejected,Failed driving test,2026-04-02 11:20:27,True
21957,DRV030455,Bharat Sharma,70,Dlhi,91382592904,bharat.sharma@gmail.com,Uber,Sedan,Excellent,3-5 yrs,...,4.9,7.5,5.2,6.2,Distinction,Flagged,On hold,Background check failed,2025-02-23 10:51:24,True
5779,DRV033298,Naveen Tiwari,36,Lucknow,9957376938,naveen.tiwari@hotmail.com,Rapido,Suv,Super,4+ yrs,...,8.4,5.6,3.0,8.8,Distinction,Pending,Rejected,Invalid_id,2025-06-15 16:11:49,True

In [52]:
df['background_check_status'].unique()

<StringArray>
['Clear', 'Pending', 'Flagged']
Length: 3, dtype: string

In [53]:
df['interview_result'].unique()

array(['On hold', 'Selected', 'Rejected', 'Waitlist', 'Pending'],
      dtype=object)

In [54]:
## This converts the data type from object to string.
df['interview_result'] = df['interview_result'].astype("string")
print(df['interview_result'].dtype)

string

In [55]:
df['interview_result'] = df['interview_result'].str.capitalize()
df['interview_result'] = df['interview_result'].fillna('Selected')
df['interview_result'] = df['interview_result'].replace({
'Na': 'Selected', 
'Unknown': 'Selected', 
'None': 'Pending', 
'-': 'Pending'
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
44126,DRV030719,YOGESH JHA,34,Delhi,91641781735,yogesh.jha@gmail.com,Rapido,Sedan,Super,Fresher,...,5.3,8.1,5.3,6.4,Distinction,Flagged,Selected,Invalid_id,2026-02-28 19:58:16,True
8334,DRV038878,Dinesh Chauhan,43,Jaipur,9808925645,dinesh.chauhan@yahoo.com,Rapido,Auto,Good,5+ yrs,...,5.9,12.9,8.0,6.2,Pass,Clear,On hold,Invalid_id,2025-01-26 17:03:05,True
11462,DRV008492,Umesh Tiwari,48,Hyderabad,9943820029,umesh.tiwari@rediffmail.com,Uber,Bike,Good,5+ yrs,...,8.5,8.7,9.6,9.0,Pass,Clear,Selected,Invalid_id,2025-06-25 07:01:26,True
3323,DRV049616,Suresh Kumar,46,Kolkata,9191308,suresh.kumar@yahoo.com,Uber,Bike,Excellent,8+ yrs,...,9.5,9.5,8.3,9.2,Fail,Clear,Selected,Invalid_id,2026-04-08 14:50:05,True
42662,DRV032962,Anil Verma,51,Ahmedabad,9279930184,Anil Verma@gmail.com,Uber & rapido,Motorbike,Good,5+ yrs,...,5.9,2.0,8.2,8.8,Pass,Clear,On hold,Invalid_id,2025-05-01 00:19:29,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30429,DRV016952,NARESH SINGH,37,Pune,9259436131,naresh.singh@rediffmail.com,Uber,Mini,Average,5+ yrs,...,7.1,9.2,4.8,7.2,Distinction,Clear,On hold,Invalid_id,2026-01-30 10:00:23,False
8231,DRV031497,N@resh N@ir,47,Pune,91973328195,naresh.nair@yahoo.com,Rapido,Suv,Super,3-5 yrs,...,4.6,9.6,1.0,6.8,Distinction,Pending,Rejected,Failed driving test,2026-02-26 09:15:27,False
49952,DRV015197,Naresh Nair,20,Pune,9588008080,Naresh Nair@gmail.com,Rapido,Mini,Good,3-5 yrs,...,8.6,7.5,8.5,8.8,Pass,Flagged,Selected,Poor communication,2026-01-23 16:51:18,True
3729,DRV024803,santosh shukla,50,Bangalore,9654642263,santosh shukla@gmail.com,Rapido,Tricycle,Excellent,4+ yrs,...,4.4,4.1,1.4,6.8,Pending,Pending,Selected,Invalid_id,2025-10-31 03:30:31,False
26974,DRV002132,RAJESH PANDEY,22,Pune,9406930961,rajesh.pandey@rediffmail.com,Uber,Bike,Super,5+ yrs,...,1.3,9.7,4.7,7.1,Pass,Clear,Selected,Invalid_id,2025-08-25 16:46:15,False

In [56]:
df['interview_result'].unique()

<StringArray>
['On hold', 'Selected', 'Rejected', 'Waitlist', 'Pending']
Length: 5, dtype: string

In [57]:
df['rejection_reason'].unique()

array(['Invalid_id', 'Low rating history', 'Not applicable',
       'Poor communication', 'Incomplete documents',
       'Vehicle age too old', 'Background check failed',
       'Failed driving test', 'Selected'], dtype=object)

In [58]:
## This converts the data type from object to string.
df['rejection_reason'] = df['rejection_reason'].astype("string")
print(df['rejection_reason'].dtype)

string

In [59]:
df['rejection_reason'] = df['rejection_reason'].str.capitalize()
df['rejection_reason'] = df['rejection_reason'].fillna('Invalid_id')
df['rejection_reason'] = df['rejection_reason'].replace({
'Na': 'Invalid_id', 
'Unknown': 'Selected', 
'None': 'Poor communication', 
'-': 'Background check failed'
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
7104,DRV029549,Sunil Reddy,999,Kolkata,9602707886,Sunil Reddy@gmail.com,Uber,Bike,Excellent,5+ yrs,...,7.2,7.8,7.4,8.0,Fail,Clear,Selected,Invalid_id,2026-03-02 14:37:53,True
26725,DRV011692,Rakesh Kumar,-37,Ahmedabad,9485500436,rakesh.kumar@yahoo.com,Ola,Bike,Good,Fresher,...,7.5,8.9,3.6,7.4,Pass,Flagged,Selected,Invalid_id,2026-07-04 11:50:55,True
42400,DRV029174,Anil Chauhan,-42,Mumbai,9314944760,anil.chauhan@rediffmail.com,Rapido,Sedan,Super,3-5 yrs,...,9.2,9.2,5.7,7.8,Distinction,Clear,Selected,Invalid_id,2026-05-24 20:26:39,False
48593,DRV010947,Lokesh Singh,51,Lucknow,9993296190,lokesh.singh@gmail.com,Uber,Mini,Average,5+ yrs,...,8.2,6.3,3.7,7.0,Fail,Flagged,Selected,Invalid_id,2026-07-11 12:30:30,True
15023,DRV041007,Rakesh Patel,-43,Bangalore,9551492390,rakesh.patelhotmail.com,Rapido,Sedan,Super,Fresher,...,5.1,4.2,13.0,10.7,Pending,Clear,Selected,Invalid_id,2025-05-15 22:54:46,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46009,DRV011298,Anil Gupta,38 yrs,Jaipur,9481756912,anil.gupta@hotmail.com,Ola,Auto,Good,3-5 yrs,...,5.7,4.4,5.6,5.5,Pending,Flagged,Selected,Invalid_id,2025-05-11 02:55:14,True
30830,NaN,Vijay Reddy,33,Delhi,91279067922,Vijay Reddy@gmail.com,Rapido,Suv,Super,7+ yrs,...,5.4,7.5,7.4,1.2,Pass,Flagged,Selected,Invalid_id,2025-11-30 06:19:07,False
7751,DRV047830,Mahesh Singh,47,Ahmedabad,9915399391,mahesh.singh@gmail.com,Rapido,Suv,Good,5+ yrs,...,5.2,8.5,9.4,6.7,Pending,Clear,Rejected,Poor communication,2025-03-30 08:45:52,False
15049,DRV041379,Harish Jha,40,Ahmedabad,9831939671,harish.jha@yahoo.com,Rapido,Mini,Good,4+ yrs,...,4.2,8.5,3.5,4.8,Pass,Flagged,Rejected,Incomplete documents,2025-10-04 15:10:07,False
21844,DRV011249,pankaj tiwari,42,Ahmedabad,9189402185,pankaj.tiwari@gmail.com,Bolt,Bike,Super,1-3 yrs,...,9.3,7.9,4.8,7.9,Distinction,Pending,Selected,Invalid_id,2026-02-02 01:12:18,True

In [60]:
df['rejection_reason'].unique()

<StringArray>
[             'Invalid_id',      'Low rating history',
          'Not applicable',      'Poor communication',
    'Incomplete documents',     'Vehicle age too old',
 'Background check failed',     'Failed driving test',
                'Selected']
Length: 9, dtype: string

In [61]:
df['onboarding_date'].unique()

array(['2025-02-10 22:07:31', '2026-01-12 11:59:18',
       '2021-04-19 00:00:00', ..., '2025-09-26 06:05:30',
       '2026-04-12 21:14:46', '2025-05-06 04:10:59'], dtype=object)

In [62]:
## This code generates random date values for the onboarding column. 

import pandas as pd
import numpy as np

df['onboarding_date'] = pd.to_datetime(df['onboarding_date'], errors='coerce')

start = pd.Timestamp("2025-01-01")
end = pd.Timestamp("2026-08-11")

mask = df["onboarding_date"].isna()

df.loc[mask, "onboarding_date"] = pd.to_datetime(
    np.random.randint(
        start.value // 10**9,
        end.value // 10**9,
        size=mask.sum()
    ),
    unit="s"
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
40158,DRV008364,Naveen Rao,37,Bangalore,9090956087,naveen.rao@rediffmail.com,Rapido,Mini,Average,4+ yrs,...,5.2,1.3,8.5,6.8,Fail,Flagged,On hold,Invalid_id,2025-08-30 10:37:16,False
45288,DRV019259,Deepak Yadav,unknown,Kolkata,9198757851,deepak.yadav@gmail.com,Uber,Suv,Super,Fresher,...,7.3,3.8,3.6,5.9,Pass,Flagged,Rejected,Poor communication,2026-07-18 12:23:12,True
36261,DRV011529,Ravi Singh,22,Bangalore,9233567977,ravi.singh@gmail.com,Uber,Bike,Good,3-5 yrs,...,9.0,7.5,12.7,8.0,Pass,Flagged,On hold,Invalid_id,2026-05-06 14:32:26,True
21653,DRV030349,Rakesh Tiwari,42,Mumbai,9788260230,Rakesh Tiwari@gmail.com,Rapido,Sedan,Excellent,High,...,8.6,5.6,9.1,7.5,Distinction,Clear,On hold,Invalid_id,2025-07-29 15:48:50,True
28345,DRV009305,Hitesh Singh,37,Mumbai,9066763397,hitesh.singh@gmail.com,Uber,Mini,Super,5+ yrs,...,5.5,7.4,8.5,2.0,Fail,Clear,On hold,Invalid_id,2025-09-24 02:02:29,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47970,DRV006762,Vikram Jha,38,Mumbai,91812184396,vikram.jha@hotmail.com,Uber & rapido,Mini,Poor,8 yrs,...,7.0,4.7,3.5,4.8,Pass,Clear,Rejected,Background check failed,2025-07-19 23:18:36,False
7903,DRV016064,Anil Tiwari,21,Chennai,9144964761,anil.tiwari@hotmail.com,Uber,Mini,Excellent,4+ yrs,...,7.5,6.4,3.5,5.6,Pending,Flagged,Selected,Invalid_id,2025-06-30 00:09:40,False
1262,DRV007569,VIKRAM GUPTA,40,Kolkata,9986894085,vikram.guptahotmail.com,Rapido,Sedan,Good,6 yrs,...,8.5,4.2,3.3,5.8,Pending,Clear,On hold,Invalid_id,2026-06-23 00:47:56,False
28080,DRV043473,Ajay Chauhan,43,Pune,9534336446,ajay.chauhan@hotmail.com,Uber,Suv,Good,Fresher,...,9.6,6.2,6.9,8.2,Distinction,Clear,Selected,Invalid_id,2025-01-14 11:18:56,False
43415,DRV031878,Sunil Sriv@st@v@,-35,Lucknow,9725839617,Sunil Sriv@st@v@@gmail.com,Rapido,Sedan,Poor,Fresher,...,8.7,8.4,3.0,7.0,Pass,Pending,Selected,Invalid_id,2026-05-04 05:27:37,False

In [63]:
df['onboarding_date'].unique()

<DatetimeArray>
['2025-02-10 22:07:31', '2026-01-12 11:59:18', '2021-04-19 00:00:00',
 '2021-05-27 00:00:00', '2026-02-08 13:31:18', '2023-04-01 00:00:00',
 '2023-08-08 00:00:00', '2022-02-06 00:00:00', '2025-12-30 07:03:08',
 '2025-07-04 10:48:53',
 ...
 '2025-11-25 01:15:51', '2026-01-07 07:46:46', '2026-04-23 02:16:25',
 '2026-05-06 22:04:05', '2025-06-23 16:04:25', '2025-10-09 23:03:17',
 '2025-06-21 04:21:16', '2025-09-26 06:05:30', '2026-04-12 21:14:46',
 '2025-05-06 04:10:59']
Length: 49969, dtype: datetime64[ns]

In [64]:
df['is_currently_active'].unique()

array([False,  True])

In [65]:
## This converts the data type from object to string.
df['is_currently_active'] = df['is_currently_active'].astype("string")
print(df['is_currently_active'].dtype)

string

In [66]:
df['is_currently_active'] = df['is_currently_active'].str.capitalize()
df['is_currently_active'] = df['is_currently_active'].fillna('True')
df['is_currently_active'] = df['is_currently_active'].replace({
'No':'False', 
'0': 'False', 
'1': 'True', 
'N': 'False',
'Y': 'True',
'Yes': 'True',
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
43026,DRV004179,Rajesh Nair,53,Lucknow,9233922529,rajesh.nair@rediffmail.com,Ola,Auto,Good,1-3 yrs,...,6.8,8.9,4.4,6.7,Distinction,Clear,On hold,Selected,2026-05-16 17:37:25,True
37616,DRV047198,Bharat Tiwari,23 yrs,Pune,9609292922,bharat.tiwari@yahoo.com,Uber,Auto,Good,5+ yrs,...,8.7,8.4,7.3,7.0,Fail,Pending,Selected,Invalid_id,2026-06-29 04:53:23,True
17679,DRV006121,Anil Shukla,49,Dlhi,9863133009,anil.shukla@hotmail.com,-,Mini,Great,High,...,9.5,7.5,7.6,8.5,Pass,Clear,Selected,Invalid_id,2025-11-22 05:25:19,True
16263,DRV022410,Deepak Rao,30 yrs,Jaipur,9547232194,deepak.rao@rediffmail.com,Rapido,Sedan,Excellent,5+ yrs,...,4.5,4.9,8.5,5.7,Pass,Clear,Rejected,Incomplete documents,2025-05-03 17:55:56,True
25204,DRV043010,Anil Gupta,43,Bangalore,91193368196,anil.gupta@hotmail.com,Uber,Bike,Good,3-5 yrs,...,10.8,3.4,6.5,6.4,Pending,Pending,Selected,Invalid_id,2025-01-18 20:29:29,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29813,DRV025906,Bharat Tiwari,52,Hyderabad,91188917904,bharat.tiwari@rediffmail.com,Rapido,Bike,Super,Fresher,...,7.5,5.9,9.5,7.1,Pending,Flagged,Selected,Invalid_id,2026-05-23 03:27:08,False
34928,DRV012537,Anil Reddy,44,Pune,9990087,anil.reddy@yahoo.com,Rapido,Suv,Beautiful,3-5 yrs,...,8.8,3.6,4.4,8.8,Distinction,Pending,Rejected,Incomplete documents,2025-01-05 02:24:05,True
38492,DRV000363,Ganesh Yadav,55,Hyderabad,9262974944,ganesh.yadavrediffmail.com,Uber,Suv,Poor,5+ yrs,...,7.5,5.6,3.0,4.8,Distinction,Clear,Selected,Invalid_id,2026-02-02 09:54:38,False
25394,DRV038092,VIKRAM YADAV,40,Mumbai,9107839156,vikram.yadav@gmail.com,Uber,Mini,Good,5+ yrs,...,8.9,9.0,8.5,7.1,Credit,Clear,On hold,Invalid_id,2025-05-30 00:21:09,False
8510,DRV006380,Yogesh Tiwari,35,Hyderabad,9832520116,yogesh.tiwari@rediffmail.com,Rapido,Bike,Good,Fresher,...,7.5,4.4,7.7,6.2,Fail,Clear,Rejected,Poor communication,2025-01-27 09:19:45,True

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   driver_id                   49005 non-null  object
 1   driver_name                 50000 non-null  object
 2   age                         50000 non-null  string
 3   city                        50000 non-null  string
 4   phone                       50000 non-null  string
 5   email                       50000 non-null  string
 6   platform                    50000 non-null  string
 7   vehicle_type                50000 non-null  string
 8   vehicle_condition           50000 non-null  string
 9   experience_level            50000 non-null  string
 10  preferred_shift             38773 non-null  object
 11  reason_for_joining          38637 non-null  object
 12  languages_known             47847 non-null  object
 13  overall_driver_rating       46033 non-null  object
 14  total_trips_completed       45930 non-null  float64
 15  trip_completion_rate_%      45565 non-null  float64
 16  cancellation_rate_%         45484 non-null  float64
 17  avg_daily_earnings_INR      47489 non-null  object
 18  total_complaints            45965 non-null  float64
 19  total_compliments           46024 non-null  float64
 20  peak_hour_availability      50000 non-null  object
 21  interview_date              45067 non-null  object
 22  communication_score_10      45416 non-null  float64
 23  driving_test_score_10       50000 non-null  string
 24  route_knowledge_score_10    50000 non-null  string
 25  customer_handling_score_10  50000 non-null  string
 26  overall_interview_score_10  50000 non-null  string
 27  document_verification       50000 non-null  string
 28  background_check_status     50000 non-null  string
 29  interview_result            50000 non-null  string
 30  rejection_reason            50000 non-null  string
 31  onboarding_date             50000 non-null  datetime64[ns]
 32  is_currently_active         50000 non-null  string
dtypes: datetime64[ns](1), float64(6), object(9), string(17)
memory usage: 12.6+ MB

In [68]:
## This converts the data type from object to string.
df['preferred_shift'] = df['preferred_shift'].astype("string")
print(df['preferred_shift'].dtype)

string

In [69]:
df['preferred_shift'] = df['preferred_shift'].str.capitalize()
df['preferred_shift'] = df['preferred_shift'].fillna('Afternoon')
df['preferred_shift'] = df['preferred_shift'].replace({
'Na': 'Evening', 
'Unknown': 'Midweek', 
'None': 'Twice_Weekly', 
'-': 'Weekend',
'Night ': 'Morning',
})

In [70]:
df['preferred_shift'].unique()

<StringArray>
[       'Night',      'Weekend',    'Afternoon',          'Day',
         'Both',      'Morning',      'Midweek', 'Twice_Weekly',
      'Evening']
Length: 9, dtype: string

In [71]:
df['driver_id'].unique()

array(['DRV016649', 'DRV032785', 'DRV011323', ..., 'DRV026085',
       'DRV025771', 'DRV025843'], dtype=object)

In [72]:
## This converts the data type from object to string.
df['driver_id'] = df['driver_id'].astype("string")
print(df['driver_id'].dtype)

string

In [73]:
import numpy as np

conversion = df['driver_id']= np.nan
print(conversion)

nan

In [74]:
##This code creates a driver_id for the drivers using their names, where they have no existing emails.

#DRV037476 

import numpy as np

df["driver_id"] = [
    f"DRV{np.random.randint(0, 1000000):06d}"
    for _ in range(len(df))
]
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
4434,DRV738426,Suresh Gupta,49,Bangalore,9963551127,Suresh Gupta@gmail.com,Rapido,Mini,Good,5+ yrs,...,5.1,3.8,8.5,5.1,Pass,Flagged,On hold,Invalid_id,2025-08-28 04:20:32,False
15263,DRV414227,Pradeep Jha,999,Pune,9413144807,pradeep.jha@gmail.com,Ola,Sedan,Good,4+ yrs,...,5.2,8.1,4.5,6.5,Fail,Pending,Selected,Background check failed,2026-06-26 09:25:56,False
33071,DRV106367,Dinesh Pandey,25,Chennai,9322866045,dinesh.pandey@hotmail.com,Uber,Suv,Good,Fresher,...,9.5,8.4,9.8,9.0,Distinction,Clear,Selected,Invalid_id,2026-07-19 01:40:36,True
23612,DRV244393,Ramesh Shukla,28,Ahmedabad,9669801003,ramesh.shukla@rediffmail.com,Rapido,Auto,Super,4+ yrs,...,6.2,6.5,3.3,5.7,Fail,Clear,Selected,Invalid_id,2026-02-02 02:19:28,False
23867,DRV269301,Umesh Reddy,44,Lucknow,9575836,umesh.reddy@gmail.com,Rapido,Auto,Poor,4+ yrs,...,7.8,5.8,0.8,6.4,Pass,Pending,Selected,Invalid_id,2025-11-26 16:37:08,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42107,DRV621428,Vijay Jha,39,Delhi,9468151592,Vijay Jha@gmail.com,Uber,Sedan,Poor,Fresher,...,5.5,6.6,3.6,6.2,Distinction,Clear,Selected,Invalid_id,2025-09-16 07:38:01,False
9288,DRV889792,Manoj Chaudhary,48,Mumbai,9211705235,manoj.chaudhary@rediffmail.com,Uber,Sedan,Super,1-3 yrs,...,5.1,3.3,8.2,5.1,Pass,Clear,Selected,Invalid_id,2026-05-03 23:13:34,True
27888,DRV373310,Ramesh Sharma,70,Ahmedabad,9724230024,ramesh.sharma@yahoo.com,Rapido,Bike,Average,Fresher,...,7.5,8.5,3.5,6.5,Pending,Flagged,Selected,Invalid_id,2025-09-29 21:04:06,True
1882,DRV000418,Santosh Pandey,55,Delhi,9786687441,santosh.pandey@gmail.com,Uber,Sedan,Good,4+ yrs,...,7.5,4.4,4.1,4.2,Distinction,Flagged,Rejected,Low rating history,2025-07-10 17:24:37,False
37859,DRV152805,Amit Tiwari,49,Delhi,91724450887,Amit Tiwari@gmail.com,Uber,Sedan,Super,Fresher,...,7.5,7.5,9.5,5.8,Distinction,Flagged,Selected,Invalid_id,2025-12-01 22:54:08,True

In [75]:
df['driver_id'].unique()

array(['DRV546585', 'DRV254084', 'DRV782717', ..., 'DRV454212',
       'DRV052061', 'DRV314549'], dtype=object)

In [76]:
## This converts the data type from object to string.
df['reason_for_joining'] = df['reason_for_joining'].astype("string")
print(df['reason_for_joining'].dtype)

string

In [77]:
df['reason_for_joining'] = df['reason_for_joining'].str.capitalize()
df['reason_for_joining'] = df['reason_for_joining'].fillna('Part_Time')
df['reason_for_joining'] = df['reason_for_joining'].replace({
'Na': 'Internship', 
'Unknown': 'Trainer', 
'None': 'Passion', 
'-': 'Passive_Income',
})

In [78]:
df['reason_for_joining'].unique()

<StringArray>
[      'Side hustle',         'Part_Time',     'Not disclosed',
      'Extra income', 'Lost previous job',   'Family pressure',
           'Passion',     'Full time job',    'Flexible hours',
           'Trainer',        'Internship',    'Passive_Income']
Length: 12, dtype: string

In [79]:
## This converts the data type from object to string.
df['languages_known'] = df['languages_known'].astype("string")
print(df['languages_known'].dtype)

string

In [80]:
df['languages_known'] = df['languages_known'].str.capitalize()
df['languages_known'] = df['languages_known'].fillna('English, Igbo, Yoruba')

In [81]:
df['languages_known'].unique()

<StringArray>
[      'Hindi, tamil, telugu',    'Kannada, tamil, marathi',
      'Tamil, marathi, hindi', 'Gujarati, kannada, marathi',
              'Hindi, telugu',             'English, tamil',
    'English, tamil, marathi',                      'Hindi',
   'Tamil, gujarati, bengali',                    'Marathi',
 ...
      'English, hindi, tamil',    'Marathi, hindi, bengali',
   'Marathi, gujarati, tamil',   'English, gujarati, tamil',
    'Kannada, hindi, english',   'Gujarati, tamil, marathi',
   'Marathi, gujarati, hindi',  'Kannada, english, bengali',
  'Gujarati, bengali, telugu',   'Gujarati, kannada, hindi']
Length: 405, dtype: string

In [82]:
## This converts the data type from object to string.
df['overall_driver_rating'] = df['overall_driver_rating'].astype("string")
print(df['overall_driver_rating'].dtype)

string

In [83]:
df['overall_driver_rating'] = df['overall_driver_rating'].fillna('7.7')
df['overall_driver_rating'] = df['overall_driver_rating'].str.lstrip('-')
df['overall_driver_rating'] = df['overall_driver_rating'].replace({
#'Na': 'Internship', 
#'Unknown': 'Trainer', 
#'None': 'Passion', 
#'-': 'Passive_Income',
'unrated': '6.9',
})

In [84]:
df['overall_driver_rating'].unique()

<StringArray>
['7.7', '5.8', '4.8', '4.4', '3.1', '4.3', '3.9', '3.3', '4.9', '3.6', '4.6',
 '2.6', '3.2', '6.9', '3.4', '5.6', '3.8', '6.4', '2.9', '5.2', '4.1', '3.5',
 '5.5', '1.7', '4.5', '4.2', '4.0', '3.0', '1.0', '5.7', '4.7', '2.5', '3.7',
 '2.7', '2.8', '6.0', '1.2', '1.6', '1.3', '0.6', '5.3', '6.1', '6.2', '5.0',
 '0.8', '5.9', '0.2', '0.4', '6.5', '5.4', '1.9', '5.1', '1.1', '1.4', '1.5',
 '0.9', '6.3', '0.5', '0.7', '1.8', '0.3', '2.0', '0.1']
Length: 63, dtype: string

In [85]:
## This converts the data type from object to string.
df['total_trips_completed'] = df['total_trips_completed'].astype("string")
print(df['total_trips_completed'].dtype)

string

In [86]:
#df['total_trips_completed'] = df['total_trips_completed'].fillna('7450')
#df['total_trips_completed'] = df['total_trips_completed'].str.lstrip('-')

import numpy as np

df['total_trips_completed'] = np.random.randint(2000, 7001, size=len(df))

In [87]:
df['total_trips_completed'].unique()

array([4685, 6324, 3340, ..., 5040, 5956, 3093])

In [88]:
## This converts the data type from object to string.
df['trip_completion_rate_%'] = df['trip_completion_rate_%'].astype("string")
print(df['trip_completion_rate_%'].dtype)

string

In [89]:
df['trip_completion_rate_%'].unique()

<StringArray>
[ '68.4',  '99.8',  '75.8',  '64.4',  '97.6',  '72.8',  '84.6',  '94.8',
    <NA>,  '63.1',
 ...
  '96.0', '100.7',  '-1.2',  '90.0', '102.0',  '80.3',  '75.3',  '97.0',
 '103.0',  '89.3']
Length: 452, dtype: string

In [90]:
df['trip_completion_rate_%'] = df['trip_completion_rate_%'].fillna('74.5')
df['trip_completion_rate_%'] = df['trip_completion_rate_%'].str.lstrip('-')

In [91]:
#df.to_csv("cleaned_uber_rapido_driver.csv", index=False)

print(df.isna().sum())

driver_id                        0
driver_name                      0
age                              0
city                             0
phone                            0
email                            0
platform                         0
vehicle_type                     0
vehicle_condition                0
experience_level                 0
preferred_shift                  0
reason_for_joining               0
languages_known                  0
overall_driver_rating            0
total_trips_completed            0
trip_completion_rate_%           0
cancellation_rate_%           4516
avg_daily_earnings_INR        2511
total_complaints              4035
total_compliments             3976
peak_hour_availability           0
interview_date                4933
communication_score_10        4584
driving_test_score_10            0
route_knowledge_score_10         0
customer_handling_score_10       0
overall_interview_score_10       0
document_verification            0
background_check_status          0
interview_result                 0
rejection_reason                 0
onboarding_date                  0
is_currently_active              0
dtype: int64

In [92]:
## This converts the data type from object to string.
df['cancellation_rate_%'] = df['cancellation_rate_%'].astype("string")
print(df['cancellation_rate_%'].dtype)

string

In [93]:
df['cancellation_rate_%'] = df['cancellation_rate_%'].fillna('44.5')

In [94]:
df['cancellation_rate_%'].unique()

<StringArray>
[ '17.5',  '28.5',  '29.3',  '21.7',  '33.2',   '0.1',  '33.4',  '11.4',
   '2.3',   '3.4',
 ...
 '101.3',   '9.1',  '30.9',  '15.3',   '0.2', '100.2',  '27.8',  '16.2',
  '28.3', '103.0']
Length: 402, dtype: string

In [95]:
df['avg_daily_earnings_INR'].unique()

array(['2275', '1164', '2394', ..., '₹488', '642.00', '₹1690'],
      dtype=object)

In [96]:
## This converts the data type from object to string.
df['avg_daily_earnings_INR'] = df['avg_daily_earnings_INR'].astype("string")
print(df['avg_daily_earnings_INR'].dtype)

string

In [97]:
df['avg_daily_earnings_INR'] = df['avg_daily_earnings_INR'].fillna('4445')

In [98]:
df['total_complaints'].unique()

array([3.6000e+01, 1.8000e+01, 1.7000e+01, 2.4000e+01, 1.6000e+01,
       1.4000e+01, 4.4000e+01, 2.1000e+01, 9.9999e+04, 2.3000e+01,
       9.0000e+00, 3.5000e+01, 3.0000e+01, 4.8000e+01, 3.1000e+01,
              nan, 2.9000e+01, 1.5000e+01, 1.9000e+01, 4.5000e+01,
       2.6000e+01, 4.1000e+01, 4.9000e+01, 1.0000e+01, 2.2000e+01,
       2.8000e+01, 3.0000e+00, 4.0000e+01, 3.8000e+01, 1.3000e+01,
       2.7000e+01, 2.5000e+01, 1.2000e+01, 2.0000e+00, 6.0000e+00,
       8.0000e+00, 4.3000e+01, 3.4000e+01, 3.3000e+01, 5.0000e+00,
       1.0000e+00, 3.9000e+01, 7.0000e+00, 3.2000e+01, 5.0000e+01,
       3.7000e+01, 4.7000e+01, 4.6000e+01, 1.1000e+01, 4.2000e+01,
       0.0000e+00, 2.0000e+01, 4.0000e+00])

In [99]:
## This converts the data type from object to string.
df['total_complaints'] = df['total_complaints'].astype("string")
print(df['total_complaints'].dtype)

string

In [100]:
df['total_complaints'] = df['total_complaints'].fillna('50.5')

In [101]:
df['total_compliments'].unique()

array([7.7000e+01, 2.2000e+01, 5.9000e+01, 3.0000e+00,        nan,
       1.9000e+01, 6.8000e+01, 7.5000e+01, 2.3000e+01, 1.0000e+00,
       1.7000e+01, 9.0000e+01, 2.5000e+01, 6.1000e+01, 3.5000e+01,
       7.0000e+00, 9.9999e+04, 9.1000e+01, 5.4000e+01, 5.5000e+01,
       4.0000e+01, 8.9000e+01, 4.4000e+01, 9.8000e+01, 3.9000e+01,
       1.3000e+01, 9.0000e+00, 9.3000e+01, 6.0000e+01, 9.9000e+01,
       6.9000e+01, 4.2000e+01, 1.0000e+02, 7.9000e+01, 8.0000e+01,
       2.9000e+01, 4.9000e+01, 8.4000e+01, 4.8000e+01, 7.0000e+01,
       1.5000e+01, 6.2000e+01, 1.4000e+01, 9.6000e+01, 2.6000e+01,
       2.4000e+01, 5.2000e+01, 4.1000e+01, 8.3000e+01, 8.8000e+01,
       4.7000e+01, 3.1000e+01, 1.0000e+01, 3.0000e+01, 2.1000e+01,
       6.4000e+01, 5.0000e+01, 5.8000e+01, 3.6000e+01, 6.0000e+00,
       7.8000e+01, 1.1000e+01, 9.2000e+01, 7.4000e+01, 8.1000e+01,
       5.7000e+01, 7.6000e+01, 8.6000e+01, 3.2000e+01, 4.5000e+01,
       7.1000e+01, 2.0000e+00, 8.2000e+01, 5.3000e+01, 4.3000e+01,
       3.3000e+01, 2.8000e+01, 1.8000e+01, 6.5000e+01, 1.6000e+01,
       9.7000e+01, 6.6000e+01, 2.7000e+01, 4.0000e+00, 5.6000e+01,
       8.7000e+01, 8.0000e+00, 6.7000e+01, 5.0000e+00, 5.1000e+01,
       3.7000e+01, 7.3000e+01, 3.4000e+01, 8.5000e+01, 9.5000e+01,
       2.0000e+01, 6.3000e+01, 4.6000e+01, 0.0000e+00, 7.2000e+01,
       1.2000e+01, 3.8000e+01, 9.4000e+01])

In [102]:
## This converts the data type from object to string.
df['total_compliments'] = df['total_compliments'].astype("string")
print(df['total_compliments'].dtype)

string

In [103]:
df['total_compliments'] = df['total_compliments'].fillna('20.5')

In [104]:
df['interview_date'].unique()

array(['10 July 2023', 'June 2021', 'February 2021', ..., '2022/04/24',
       '11 April 2023', '03/27/22'], dtype=object)

In [105]:
## This converts the data type from object to string.
df['interview_date'] = df['interview_date'].astype("string")
print(df['interview_date'].dtype)

string

In [106]:
df['interview_date'] = df['interview_date'].fillna('20 May 25')

In [110]:
## This code generates random date values for the onboarding column. 

import pandas as pd
import numpy as np

df['interview_date'] = pd.to_datetime(df['interview_date'], errors='coerce')

start = pd.Timestamp("2021-01-01")
end = pd.Timestamp("2024-08-11")

mask = df["interview_date"].isna()

df.loc[mask, "interview_date"] = pd.to_datetime(
    np.random.randint(
        start.value // 10**9,
        end.value // 10**9,
        size=mask.sum()
    ),
    unit="s"
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
42805,DRV088857,Ravi Chaudhary,37,Delhi,9058997157,ravi.chaudhary@hotmail.com,Uber,Sedan,Fair,1-3 yrs,...,7.5,6.9,12.7,4.9,Distinction,Clear,Rejected,Invalid_id,2026-04-08 17:28:36,True
17966,DRV372546,Yogesh Yadav,33,Kolkata,9772450619,yogesh.yadavrediffmail.com,Uber & rapido,Sedan,Good,4+ yrs,...,7.5,7.5,5.8,6.1,Pass,Flagged,Rejected,Incomplete documents,2025-05-26 04:34:46,False
31329,DRV560713,Naveen Tiwari,44 yrs,Pune,9614168432,naveen.tiwari@gmail.com,Ola,Bike,Average,5+ yrs,...,6.2,6.8,8.4,6.3,Pending,Clear,Selected,Invalid_id,2025-12-25 14:38:49,False
21330,DRV489929,Sunil Reddy,35,Chennai,9436596160,sunil.reddy@gmail.com,Rapido,Auto,Great,3-5 yrs,...,12.9,7.5,6.7,8.8,Distinction,Flagged,Rejected,Invalid_id,2026-03-10 23:04:20,True
39665,DRV093763,Yogesh Chaudhary,22,Bangalore,91446340052,yogesh.chaudharyhotmail.com,Ola,Suv,Excellent,3-5 yrs,...,5.3,5.8,9.0,7.1,Pending,Clear,Selected,Invalid_id,2025-02-19 07:23:38,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18675,DRV306860,Rajesh Yadav,49,Jaipur,91810568996,rajesh.yadav@rediffmail.com,Rapido,Sedan,Good,Fresher,...,8.6,7.7,8.9,8.8,Pass,Flagged,Selected,Invalid_id,2026-07-21 01:03:27,False
12154,DRV972845,Sanjay Verma,25 yrs,Bangalore,9763546317,sanjay.verma@hotmail.com,Uber,Auto,Super,4+ yrs,...,7.5,6.9,7.4,7.2,Pass,Clear,Rejected,Background check failed,2025-02-19 02:39:20,True
3391,DRV623356,Anil Chauhan,43,Jaipur,9163132,anil.chauhan@rediffmail.com,Uber,Sedan,Average,5+ yrs,...,1.0,6.2,5.4,6.4,Fail,Clear,On hold,Invalid_id,2025-06-28 19:30:50,False
11996,DRV802452,dinesh shukla,30 yrs,Ahmedabad,9028949016,dinesh.shukla@yahoo.com,Uber,Suv,Super,3-5 yrs,...,4.7,3.2,4.6,4.8,Distinction,Flagged,Selected,Poor communication,2026-02-19 09:49:46,False
42119,DRV275787,Lokesh Ch@uh@n,54,Hyderabad,9132921958,lokesh.chauhan@yahoo.com,Rapido,Suv,Super,5+ yrs,...,8.9,7.3,8.7,8.7,Fail,Clear,Selected,Poor communication,2026-06-03 13:48:01,False

In [111]:
df['interview_date'].unique()

<DatetimeArray>
['2023-07-10 00:00:00', '2021-09-14 22:49:51', '2021-06-19 05:52:34',
 '2023-02-14 02:51:47', '2021-07-22 22:33:27', '2024-02-08 10:28:04',
 '2022-10-07 00:54:31', '2022-01-24 00:00:00', '2022-09-18 01:45:00',
 '2021-03-31 00:00:00',
 ...
 '2023-06-04 12:26:19', '2023-02-14 22:21:16', '2023-09-28 06:39:53',
 '2021-07-19 21:34:27', '2021-07-01 13:40:24', '2022-06-03 18:41:38',
 '2023-12-02 05:29:51', '2022-04-27 10:44:13', '2023-09-01 22:25:15',
 '2022-04-23 22:34:42']
Length: 44819, dtype: datetime64[ns]

In [118]:
#df.to_csv("cleaned_uber_rapido_driver.csv", index=False)

print(df.isna().sum())

driver_id                     0
driver_name                   0
age                           0
city                          0
phone                         0
email                         0
platform                      0
vehicle_type                  0
vehicle_condition             0
experience_level              0
preferred_shift               0
reason_for_joining            0
languages_known               0
overall_driver_rating         0
total_trips_completed         0
trip_completion_rate_%        0
cancellation_rate_%           0
avg_daily_earnings_INR        0
total_complaints              0
total_compliments             0
peak_hour_availability        0
interview_date                0
communication_score_10        0
driving_test_score_10         0
route_knowledge_score_10      0
customer_handling_score_10    0
overall_interview_score_10    0
document_verification         0
background_check_status       0
interview_result              0
rejection_reason              0
onboarding_date               0
is_currently_active           0
dtype: int64

In [113]:
df['communication_score_10'].unique()

<StringArray>
['10.4',  '7.0',  '4.5',  '7.4',  '4.0',  '8.1',  '4.1',  '7.3',  '7.6',
  '7.5',
 ...
 '12.9', '11.3', '12.3',  '0.3', '10.6',  '2.0',  '0.5', '11.2', '13.0',
 '12.0']
Length: 121, dtype: string

In [116]:
# This converts the data type from object to string.
df['communication_score_10'] = df['communication_score_10'].astype("string")
print(df['communication_score_10'].dtype)

string

In [117]:
df['communication_score_10'].unique()

<StringArray>
['10.4',  '7.0',  '4.5',  '7.4',  '4.0',  '8.1',  '4.1',  '7.3',  '7.6',
  '7.5',
 ...
 '12.9', '11.3', '12.3',  '0.3', '10.6',  '2.0',  '0.5', '11.2', '13.0',
 '12.0']
Length: 121, dtype: string

In [ ]:
#df['communication_score_10'] = df['communication_score_10'].fillna('4.5')
#df['communication_score_10'] = df['communication_score_10'].str.lstrip('-')

In [119]:
#df.to_csv("cleaned_uber_rapido_driver.csv", index=False)

print(df.isna().sum())

driver_id                     0
driver_name                   0
age                           0
city                          0
phone                         0
email                         0
platform                      0
vehicle_type                  0
vehicle_condition             0
experience_level              0
preferred_shift               0
reason_for_joining            0
languages_known               0
overall_driver_rating         0
total_trips_completed         0
trip_completion_rate_%        0
cancellation_rate_%           0
avg_daily_earnings_INR        0
total_complaints              0
total_compliments             0
peak_hour_availability        0
interview_date                0
communication_score_10        0
driving_test_score_10         0
route_knowledge_score_10      0
customer_handling_score_10    0
overall_interview_score_10    0
document_verification         0
background_check_status       0
interview_result              0
rejection_reason              0
onboarding_date               0
is_currently_active           0
dtype: int64

In [120]:
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
35145,DRV283033,Suresh Singh,29,Bangalore,91520896698,suresh.singh@@yahoo.com,Ola,Mini,Average,4+ yrs,...,4.1,1.0,4.1,5.2,Distinction,Clear,On hold,Invalid_id,2026-06-07 12:31:06,True
8744,DRV615054,P@nk@j Gupt@,52,Chennai,9173915045,pankaj.gupta@yahoo.com,Rapido,Sedan,Good,5+ yrs,...,7.5,1.8,4.1,11.6,Pass,Clear,Rejected,Invalid_id,2025-02-16 08:11:58,True
10081,DRV885140,Ramesh Singh,42,Lucknow,91548652370,ramesh.singh@rediffmail.com,Uber,Bike,Excellent,5+ yrs,...,5.2,4.3,8.5,5.2,Pending,Clear,Selected,Invalid_id,2026-05-05 18:39:44,True
24856,DRV632675,Sanjay Chaudhary,41,Delhi,91117896740,sanjay.chaudhary@@gmail.com,Bolt,Mini,Poor,Fresher,...,5.9,8.2,4.0,6.3,Distinction,Clear,Waitlist,Invalid_id,2026-07-17 19:18:41,True
45747,DRV843620,Pankaj Kumar,47,Hyderabad,91995279331,pankaj.kumar@gmail.com,Uber,Suv,Good,5+ yrs,...,7.7,1.9,8.5,7.3,Pending,Clear,Selected,Invalid_id,2026-04-03 08:43:05,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39310,DRV346878,Dinesh Nair,-46,Mumbai,91735565197,dinesh.nair@rediffmail.com,Uber,Suv,Super,Fresher,...,4.7,9.2,10.7,7.2,Pending,Clear,Selected,Invalid_id,2026-04-13 12:06:53,True
1340,DRV931839,Vikram Dubey,37,Mumbai,9024638836,vikram.dubey@hotmail.com,Uber,Mini,Great,Fresher,...,7.6,5.5,8.0,7.8,Pass,Clear,Rejected,Background check failed,2026-04-13 08:00:49,False
7168,DRV970641,Ganesh Rao,48,Lucknow,91645756176,ganesh.rao@hotmail.com,Rapido,Bike,Average,Fresher,...,7.0,7.5,4.0,5.8,Fail,Clear,On hold,Invalid_id,2026-03-05 17:50:18,True
48508,DRV660354,Suresh Jha,32,Hyderabad,9512414915,suresh.jha@@yahoo.com,Uber,Bike,Poor,4+ yrs,...,9.9,6.6,8.5,7.6,Distinction,Clear,Selected,Invalid_id,2025-02-01 13:33:22,False
32951,DRV432196,Umesh Tiwari,-20,Ahmedabad,9306372885,umesh.tiwari@hotmail.com,Rapido,Suv,Average,Fresher,...,7.5,6.5,1.4,6.8,Pass,Clear,On hold,Invalid_id,2026-08-09 04:49:46,False