In [1]:
import pandas as pd

#import matplotlib.pyplot as plt

df = pd.read_csv("uber_rapido_driver_dirty.csv")
df.head(5)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
0,DRV016649,Naresh Chauhan,NaN,Chennai,9255500096,naresh.chauhan@hotmail.com,uber,auto,good,0-1 yr,...,4.3,5.8,7.7,5.3,Fail,NaN,On Hold,NaN,-,false
1,DRV032785,Amit Gupta,45,Ahmedabad,9940345570,amit.gupta@rediffmail.com,Uber,Mini,Excellent,Fresher,...,9.3,NaN,9.0,8.1,NaN,Clear,On Hold,NaN,-,No
2,DRV011323,Yogesh Nair,53,Lucknow,9170487337,NaN,uber,SUV,avg,0-1 yr,...,6.3,9.0,5.5,6.9,NaN,clear,Selected,NaN,19 April 2021,false
3,DRV022168,Manoj Patel,46,Hyderabad,9246425981,manoj.patel@hotmail.com,RAPIDO,Mini,NaN,1-3 yrs,...,8.7,9.6,5.3,7.8,unknown,Clear,Selected,NaN,2021/05/27,0
4,DRV040782,Vikram Chaudhary,25,KOLKATA,9282240,vikram.chaudhary@gmail.com,Uber,suv,GOOD,Fresher,...,12.7,6.5,7.9,6.0,FAIL,clear,Rejected,Low rating history,-,NO

In [2]:
df.describe()

,total_trips_completed,trip_completion_rate_%,cancellation_rate_%,total_complaints,total_compliments,communication_score_10,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10
count,45930.000000,45565.00000,45484.000000,45965.000000,46024.000000,45416.000000,45559.000000,45448.000000,45500.000000,45545.000000
mean,6802.510799,77.89254,22.416584,8809.843120,8942.686272,6.508777,6.946878,6.508619,6.517708,6.613859
std,17638.171153,20.80393,23.708155,28303.698509,28456.710282,2.789817,2.630277,2.794014,2.804085,2.239486
min,-7996.000000,-2.00000,-2.000000,0.000000,0.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000
25%,1704.000000,69.40000,8.100000,14.000000,27.000000,4.600000,5.400000,4.600000,4.600000,5.900000
50%,3909.000000,80.50000,18.100000,27.000000,55.000000,6.600000,7.100000,6.600000,6.600000,6.700000
75%,6086.750000,91.60000,27.900000,41.000000,82.000000,8.500000,8.800000,8.600000,8.600000,7.400000
max,99999.000000,103.00000,103.000000,99999.000000,99999.000000,13.000000,13.000000,13.000000,13.000000,13.000000

In [3]:
df.shape

(50000, 33)

In [4]:
df['email'].unique()

array(['naresh.chauhan@hotmail.com', 'amit.gupta@rediffmail.com', nan,
       ..., 'deepak.srivastavahotmail.com', 'deepak.singhgmail.com',
       'deepak.dubeygmail.com'], dtype=object)

In [5]:
df['email'] = df['email'].astype("string")
print(df['email'].dtype)

string

In [6]:
##This code creates a gmail adrress for the drivers using their names, where they have no existing emails.

df['email'] = df['email'].fillna(
    df['driver_name'] + '@gmail.com'
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
14659,DRV006496,naresh reddy,40,Hyderabad,9852789442,naresh.reddy@rediffmail.com,NaN,Mini,GOOD,-,...,6.4,NaN,4.1,4.9,none,Flagged,Rejected,Poor communication,NaN,No
42263,DRV030074,anil nair,27,Delhi,9491866832,anil.nair@gmail.com,Uber & Rapido,BIKE,unknown,Fresher,...,6.3,4.2,4.3,4.6,NaN,Pending,Rejected,NaN,NaN,0
34080,DRV035990,Sanjay Chauhan,37,Mumbai,9849312027,sanjay.chauhan@yahoo.com,Uber & Rapido,BIKE,Poor,Fresher,...,NaN,NaN,NaN,11.8,NaN,FLAGGED,Selected,NaN,16-06-2022,No
11879,DRV048404,Naveen Mishra,33,Bangalore,9935872299,naveen.mishra@rediffmail.com,rapido,Sedan,good,1-3 yrs,...,5.7,4.9,7.7,6.7,Pending,pending,On Hold,NaN,-,True
9831,DRV012423,Amit Yadav,46,Jaipur,9843142522,amit.yadavgmail.com,Rapido,Mini,Poor,1-3 yrs,...,NaN,3.3,3.3,4.2,Pass,clear,Rejected,Failed driving test,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25229,DRV031716,N@veen Tiw@ri,-20,Kolkata,+91-9698404382,naveen.tiwarirediffmail.com,ola,auto,poor,0-1 yr,...,9.5,9.9,10.5,8.9,pending,pending,Rejected,NaN,NaN,No
45453,DRV016713,Ravi Tripathi,42,JAIPUR,9795846870,ravi.tripathi@hotmail.com,Uber & Rapido,BIKE,NaN,5+ yrs,...,8.0,6.9,7.1,6.6,Pass,clear,On Hold,NaN,NaN,Y
10156,DRV045686,Manoj Tripathi,34,Ahmedabad,9090078164,manoj.tripathi@yahoo.com,Uber & Rapido,NaN,GOOD,none,...,NaN,9.3,9.7,NaN,Fail,Pending,Rejected,NaN,2023-11-19T00:00:00Z,false
18194,DRV038593,Amit Chauhan,54,Chennai,9258409,amit.chauhan@yahoo.com,UBER,Auto,NaN,0-1 yr,...,7.0,5.1,5.8,NaN,NaN,Flagged,Rejected,Vehicle age too old,NaN,True
3819,DRV001573,Rakesh Singh,999,Delhi,9855193061,rakesh.singh@hotmail.com,Uber & Rapido,sedan,good,Fresher,...,9.3,8.1,5.6,7.2,Pending,NaN,On Hold,NaN,NaN,No

In [7]:
df.sample(10)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
45035,DRV016552,Rajesh Reddy,26,Chennai,+91-9255340054,rajesh.reddyhotmail.com,Uber & Rapido,NaN,avg,0-1 yr,...,5.7,-1.0,NaN,4.7,NaN,Clear,Rejected,NaN,-,0
42807,DRV000675,Pradeep Sharma,35,Bangalore,9615001757,Pradeep Sharma@gmail.com,none,Mini,Average,Fresher,...,7.8,4.5,8.8,7.6,Pass,FLAGGED,On Hold,na,2022/11/22,true
34552,DRV036212,Dinesh Rao,42,LUCKNOW,9938412238,dinesh.rao@@hotmail.com,uber,Mini,Excellent,5+ yrs,...,NaN,6.0,11.5,6.0,pending,clear,unknown,NaN,February 2023,false
17961,DRV020066,Naresh Dubey,unknown,Lucknow,9215051144,naresh.dubeyrediffmail.com,RAPIDO,Bike,Good,5+ yrs,...,4.5,9.0,10.2,7.8,Pending,Pending,On Hold,NaN,NaN,Y
31905,DRV008500,Lokesh Tripathi,NaN,Lucknow,9494019769,lokesh.tripathihotmail.com,rapido,BIKE,avg,Fresher,...,9.4,3.1,5.1,10.4,FAIL,Pending,NaN,Not applicable,NaN,False
15060,DRV003255,Manoj Rao,32,Ahmedabad,9117041463,manoj.rao@rediffmail.com,rapido,suv,Excellent,1-3 yrs,...,9.4,4.4,-1.6,6.7,pass,FLAGGED,Selected,Failed driving test,NaN,N
7670,DRV043223,Rakesh Yadav,50,Kolkata,9279512313,rakesh.yadav@hotmail.com,ola,Bike,Good,3-5 yrs,...,4.8,5.9,-1.2,6.0,Pass,NaN,On Hold,NaN,NaN,Y
862,DRV023482,Deepak Sharma,46,Delhi,9021001652,deepak.sharma@@hotmail.com,RAPIDO,Mini,Average,Fresher,...,4.0,3.3,3.8,4.1,FAIL,NaN,Rejected,Low rating history,-,no
35884,DRV020033,Rakesh Gupta,53,Jaipur,9756793060,rakesh.gupta@gmail.com,Rapido,BIKE,Poor,0-1 yr,...,5.6,7.3,5.3,11.3,Pending,NaN,Selected,NaN,2024-03-03T00:00:00Z,true
2707,DRV036198,Rajesh Dubey,35,Kolkata,9990620168,rajesh.dubey@yahoo.com,ola,Sedan,good,3-5 yrs,...,7.6,7.7,4.5,7.2,NaN,pending,Selected,NaN,2023-12-21T00:00:00Z,YES

In [8]:
df['phone'] = pd.to_numeric(df['phone'], errors='coerce') 
## This is to convert the phone collumn from object to numeric

In [9]:
df['phone'] = df['phone'].astype("string")
print(df['phone'].dtype)

string

In [10]:
df['driving_test_score_10'].unique()

array([ 4.3,  9.3,  6.3,  8.7, 12.7,  8.8,  8.1, -1.1, 11.6,  nan,  7.4,
       -0.6,  7.7,  6.2,  4.8,  7.1, 12.5, 11.2, -0.9,  5.5,  8.9,  6.4,
        5.1,  7. , 11. ,  7.6,  5.7, 12.2,  9.1,  7.5,  8.3,  4.6,  4. ,
        7.2,  8. ,  9.7, 10.9,  4.2,  9.5,  4.9,  5.8,  5. ,  6.9,  4.1,
        6.5,  4.5,  9.8,  5.4,  4.4, -1.3,  9.2,  4.7,  7.3, -1.5, 12.4,
        8.6,  8.4, -1.7,  5.3,  6.1,  6. ,  9.6,  7.9,  6.8,  5.2,  5.6,
       10.2, -0.7,  9.4,  9.9,  7.8,  8.2,  6.6,  6.7, 10.5,  9. , 10.8,
        5.9, 12. , 12.1, 11.5,  8.5, 10. , -1. , -0.8, 11.4, 10.3, -0.4,
       -0.5, 10.7, 11.7, 11.8, -0.3, 10.4, 12.8, -1.8, -1.2, -0.2, 11.9,
       -1.4, 10.1, 11.3, 12.3, -1.6, 12.6, -1.9, 10.6, 12.9, 11.1, 13. ,
       -0.1, -2. ])

In [11]:
## This code removes the decimals from the values and make them strings rather than floats. 
df['phone'] = df['phone'].str.replace(r'\.0$', '', regex=True)

In [12]:
## This creates random phone numbers for NaN values in the phone column

import numpy as np

mask = df['phone'].isna()

df.loc[mask, 'phone'] = [
    '+91' + ''.join(np.random.choice(list('0123456789'), 9))
    for _ in range(mask.sum())
]
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
21040,DRV024771,S@ntosh N@ir,31,Hyderabad,9829270926,santosh.nair@gmail.com,rapido,Mini,GOOD,5+ yrs,...,NaN,7.2,9.4,8.8,NaN,NaN,Waitlist,NaN,-,true
42207,DRV001875,Naveen Tiwari,31,Ahmedabad,+91267900455,naveen.tiwari@@hotmail.com,ola,Bike,GOOD,3-5 yrs,...,7.7,NaN,-0.2,6.2,NaN,Clear,Rejected,Incomplete documents,-,YES
22524,DRV033364,Bharat Gupta,35,Bangalore,9414436830,bharat.gupta@rediffmail.com,rapido,Auto,Average,0-1 yr,...,13.0,4.5,5.0,4.7,pass,clear,Rejected,Background check failed,NaN,Yes
26912,DRV014057,Vijay Gupta,20,MUMBAI,9486508,vijay.gupta@gmail.com,Rapido,sedan,Excellent,5+ yrs,...,11.2,8.7,6.1,6.1,Unknown,NaN,NaN,NaN,2021-03-05T00:00:00Z,True
5091,DRV000106,Lokesh Shukla,NaN,Jaipur,+91341701879,lokesh.shukla@yahoo.com,rapido,Mini,Good,5+ yrs,...,5.5,3.5,5.4,5.2,Pass,FLAGGED,On Hold,NaN,NaN,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12187,DRV015634,Pradeep Shukla,22,HYDERABAD,9639202963,Pradeep Shukla@gmail.com,Rapido,Bike,NaN,NaN,...,9.2,8.8,9.7,7.8,NaN,NaN,Selected,NaN,2021-01-09T00:00:00Z,No
10070,DRV036299,Ravi Mishra,31,Bangalore,9667135507,ravi.mishra@gmail.com,uber,Sedan,NaN,1-3 yrs,...,4.5,3.7,8.9,5.3,FAIL,NaN,selected,NaN,06/27/23,Yes
811,DRV049115,Dinesh Patel,52 yrs,Delhi,9251931494,dinesh.patel@gmail.com,Rapido,BIKE,poor,1-3 yrs,...,6.4,9.6,6.9,8.2,Pending,Flagged,Selected,NaN,10/17/21,true
44504,DRV014567,Manoj Yadav,NaN,Hyderabad,9816329189,manoj.yadav@hotmail.com,Uber & Rapido,Sedan,NaN,1-3 yrs,...,6.6,NaN,11.2,7.2,NaN,Clear,Selected,NaN,November 2021,yes
12101,DRV020470,Lokesh Gupta,unknown,Chennai,9775384696,lokesh.gupta@rediffmail.com,Rapido,Sedan,excellent,3-5 yrs,...,4.4,5.5,-1.6,11.5,Pass,Flagged,On Hold,NaN,NaN,No

In [13]:
df['age'] = df['age'].astype("string")
print(df['age'].dtype)

string

In [14]:
df['age'] = df['age'].fillna('70')

In [15]:
## This code fills the age column where NaN values exist with random values between 1 and 100

import numpy as np

mask = df['age'].isna()

df.loc[mask, 'age'] = np.random.randint(
    1, 101, size=mask.sum()
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
6672,DRV006475,Ravi Nair,44,Jaipur,9489006223,ravi.nair@yahoo.com,RAPIDO,auto,NaN,3-5 yrs,...,9.4,12.5,8.4,-0.3,-,NaN,Selected,-,2021-05-30T00:00:00Z,Yes
34327,DRV029613,R@vi P@tel,53,Kolkata,9128665,ravi.patel@yahoo.com,NaN,Bike,Average,Fresher,...,7.1,10.0,4.5,6.5,NaN,NaN,On Hold,NaN,NaN,true
7627,DRV004460,Sunil Verma,48,Mumbai,9230224331,sunil.verma@hotmail.com,ola,SUV,poor,0-1 yr,...,6.9,5.5,6.1,7.1,FAIL,Clear,none,NaN,April 2022,YES
34946,DRV022500,Pankaj Jha,43,Bangalore,9473447059,pankaj.jha@rediffmail,UBER,BIKE,good,0-1 yr,...,4.1,5.1,4.6,5.9,Pending,clear,Selected,NaN,NaN,NO
46356,DRV035789,Deep@k Gupt@,35,Kolkata,9176280681,deepak.gupta@rediffmail.com,Uber & Rapido,BIKE,-,1-3 yrs,...,-2.0,5.1,7.3,6.2,pending,Flagged,NaN,Vehicle age too old,NaN,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42529,DRV015313,SURESH MISHRA,22,Lucknow,9380659212,suresh.mishra@@hotmail.com,Rapido,SUV,Good,5+ yrs,...,7.1,-0.1,8.4,NaN,FAIL,Clear,Selected,NaN,02.03.2021,No
37383,DRV006000,Suresh Yadav,35,LUCKNOW,9071024777,suresh.yadav@gmail.com,UBER,auto,excellent,Fresher,...,-0.6,9.5,8.1,7.9,pending,Flagged,Rejected,Vehicle age too old,NaN,true
11482,DRV028155,Ganesh Shukla,49,Bangalore,9174364582,Ganesh Shukla@gmail.com,UBER,Auto,NaN,Fresher,...,4.8,4.0,7.2,4.8,pass,NaN,selected,NaN,NaN,true
47863,DRV014844,rakesh sharma,32,Hyderabad,9349539899,rakesh.sharma@rediffmail.com,UBER,BIKE,avg,Fresher,...,7.2,7.9,4.7,6.7,FAIL,NaN,NaN,NaN,NaN,no
5843,DRV044474,Dinesh Rao,unknown,Lucknow,+91152613654,dinesh.rao@gmail.com,Uber,Mini,excellent,3-5 yrs,...,NaN,7.7,3.3,6.3,Pending,Flagged,On Hold,NaN,NaN,False

In [16]:
## This is to remove the negative values and also the yrs in the age column.
df['driving_test_score_10'] = df['driving_test_score_10'].astype("string")
df['driving_test_score_10'] = df['driving_test_score_10'].str.lstrip('-')
#df['age'] = df['age'].str.rstrip('yrs')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
20854,DRV017943,Rajesh Nair,32,Bangalore,9843480557,rajesh.nair@hotmail.com,uber,Mini,good,NaN,...,1.8,8.8,8.8,8.8,pending,Pending,REJECTED,NaN,NaN,yes
21994,DRV047954,BHARAT GUPTA,999,Lucknow,9731451275,bharat.gupta@yahoo.com,uber,Mini,Average,5+ yrs,...,7.5,7.2,5.8,6.7,Fail,Flagged,Waitlist,NaN,2021/03/03,True
1651,DRV001611,Ganesh Kumar,unknown,Ahmedabad,9644962875,ganesh.kumar@yahoo.com,Rapido,BIKE,good,Fresher,...,5.5,3.3,-1.0,5.7,pass,Clear,NaN,none,NaN,no
46365,DRV043280,Dinesh Chaudhary,37,Hyderabad,9749954195,dinesh.chaudhary@gmail.com,Rapido,Auto,Poor,Fresher,...,8.4,3.0,4.0,11.9,NaN,NaN,Rejected,Incomplete documents,-,false
43159,DRV023247,Rakesh Tiwari,51,pune,+91785237582,rakesh.tiwari@rediffmail,UBER,auto,Excellent,unknown,...,7.5,7.2,6.2,7.4,Pending,NaN,On Hold,NaN,NaN,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45478,DRV028254,R@kesh R@o,54,Mumbai,9812560122,rakesh.rao@yahoo.com,uber,SUV,Average,5+ yrs,...,<NA>,7.1,6.2,7.4,FAIL,pending,NaN,none,NaN,False
27984,DRV011069,Ganesh Sharma,24,Lucknow,9571577083,ganesh.sharma@gmail.com,Rapido,Mini,NaN,NaN,...,5.4,9.8,7.5,7.9,FAIL,Pending,NaN,NaN,NaN,no
44550,DRV043195,Anil Pandey,28,Delhi,9762288,anil.pandey@@gmail.com,ola,Auto,NaN,0-1 yr,...,8.7,6.0,9.4,8.4,NaN,Flagged,On Hold,NaN,NaN,no
18142,DRV024557,Hitesh Rao,55,Hyderabad,9147593882,Hitesh Rao @gmail.com,Uber,NaN,excellent,Fresher,...,8.2,4.7,-0.4,7.7,NaN,clear,On Hold,NaN,07/27/22,1
14035,DRV004257,Suresh Nair,49,Ahmedabad,9665203828,Suresh Nair@gmail.com,ola,Sedan,Average,3-5 yrs,...,4.8,5.9,-1.4,5.8,pending,NaN,NaN,NaN,May 2021,NO

In [17]:
## This is to capitalise the platform column to give it a uniform format and also convert the data type from object to string.

df['platform'] = df['platform'].str.capitalize()
df['platform'] = df['platform'].astype("string")
print(df['platform'].dtype)

string

In [18]:
df['platform'] = df['platform'].fillna('Bolt')

In [19]:
df['customer_handling_score_10'] = df['customer_handling_score_10'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    #'Unknown': 'Experienced',
    #'None': 'Fairly_Experienced',
    #'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Motorcycle',
    #'Na': '1-20 yrs',
    #'-': '10-30 yrs',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    '<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
38652,DRV013442,Ajay Tiwari,70,Lucknow,9654452947,ajay.tiwarihotmail.com,Rapido,Auto,Excellent,0-1 yr,...,8.3,NaN,8.1,7.3,NaN,Clear,Rejected,unknown,21 July 2021,1
11676,NaN,Sanjay Rao,24,Chennai,9325212440,sanjay.rao@gmail.com,Uber,BIKE,poor,Fresher,...,5.8,NaN,4.4,4.9,NaN,pending,On Hold,Not applicable,NaN,Yes
2761,DRV033920,Yogesh Gupta,21,Jaipur,+91083419928,yogesh.gupta@gmail.com,Uber,sedan,Average,3-5 yrs,...,<NA>,-1.5,8.9,7.2,FAIL,clear,On Hold,NaN,NaN,no
29283,DRV043568,Ravi Verma,31,Lucknow,9046761057,ravi.verma@rediffmail.com,Uber,suv,Good,1-3 yrs,...,7.3,9.0,3.4,6.6,Fail,pending,On Hold,NaN,NaN,true
20711,DRV049286,Naveen Reddy,31,Kolkata,9513077113,naveen.reddy@rediffmail.com,Rapido,Bike,Average,Fresher,...,8.8,7.5,8.4,6.9,Pending,NaN,On Hold,NaN,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4332,DRV046925,Hitesh Srivastava,25,Bangalore,9684114596,hitesh.srivastava@gmail.com,Rapido,NaN,GOOD,0-1 yr,...,<NA>,6.4,NaN,6.9,Fail,Pending,Rejected,Failed driving test,NaN,False
25371,DRV041216,hitesh sharma,42,Bangalore,9549310633,hitesh.sharma@gmail.com,Rapido,NaN,good,Fresher,...,7.2,-1.6,5.0,NaN,Fail,clear,Rejected,NaN,NaN,N
45815,DRV015086,MANOJ JHA,40,Lucknow,+91311288126,manoj.jha@gmail.com,Uber,suv,excellent,0-1 yr,...,<NA>,9.7,NaN,7.3,Pending,Clear,On Hold,Poor communication,-,yes
10961,DRV001448,Vijay Verma,39,Pune,+91793066156,vijay.verma@yahoo.com,Uber & rapido,Auto,GOOD,Fresher,...,8.8,NaN,12.4,5.9,Fail,FLAGGED,Selected,NaN,09-04-2024,1
28782,DRV047913,Bharat Tripathi,31,Chennai,9918049070,bharat.tripathi@yahoo.com,Bolt,sedan,Excellent,Fresher,...,4.3,8.0,6.0,6.6,Fail,NaN,Selected,NaN,November 2022,no

In [20]:
## This capitalises the city column to give it a uniform format and also converts the data type from object to string.
df['city'] = df['city'].str.capitalize()
df['city'] = df['city'].astype("string")
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
47644,DRV025987,M@noj Shukl@,21,Bangalore,9360431800,manoj.shukla@@gmail.com,Uber,BIKE,GOOD,1-3 yrs,...,6.3,8.0,3.1,NaN,Unknown,pending,On Hold,NaN,NaN,NO
41195,DRV001217,Pankaj Pandey,999,Ahmedabad,9922845219,pankaj.pandey@rediffmail,Rapido,sedan,GOOD,0-1 yr,...,9.7,5.0,8.6,10.5,Fail,FLAGGED,Selected,NaN,08-06-2021,No
39835,DRV041266,Ramesh Nair,53,Bangalore,9272309469,Ramesh Nair@gmail.com,Ola,Auto,Poor,Fresher,...,9.0,8.6,7.9,-1.6,pass,Pending,Selected,NaN,02.02.2024,True
43216,DRV027797,VIKRAM DUBEY,26,Lucknow,+91350996554,vikram.dubey@hotmail.com,Uber,NaN,good,1-3 yrs,...,4.9,3.7,6.9,5.8,-,clear,NaN,Failed driving test,NaN,True
14092,DRV005151,Manoj Sharma,35,Lucknow,9210899035,manoj.sharma@@rediffmail.com,Uber,-,Excellent,1-3 yrs,...,7.1,9.9,6.2,NaN,Fail,-,Selected,NaN,2023/02/02,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36229,DRV017172,Vijay Tiwari,38,Ahmedabad,+91953408203,vijay.tiwari@hotmail.com,Ola,suv,GOOD,3-5 yrs,...,4.8,6.5,4.0,5.7,FAIL,Pending,Rejected,NaN,NaN,no
32771,DRV010182,Manoj Dubey,22,Hyderabad,9739032203,manoj.dubey@gmail.com,Uber,Mini,excellent,Fresher,...,9.7,5.3,5.6,6.6,pending,Clear,On Hold,NaN,NaN,No
42278,DRV036415,Pradeep Tiwari,39,Bangalore,9854242390,pradeep.tiwari@gmail.com,Bolt,BIKE,NaN,0-1 yr,...,5.4,5.2,3.7,4.5,NaN,NaN,Rejected,Failed driving test,NaN,False
19520,DRV048367,Pankaj Tiwari,20,Lucknow,+91029777150,pankaj.tiwari@hotmail.com,Na,suv,excellent,Fresher,...,7.2,4.5,7.4,10.7,FAIL,Flagged,Rejected,NaN,-,1
30966,DRV036584,Vijay Pandey,-53,Ahmedabad,9409347726,Vijay Pandey@gmail.com,None,Sedan,excellent,1-3 yrs,...,6.1,6.8,6.3,7.1,-,NaN,Selected,NaN,07/30/22,No

In [21]:
df['route_knowledge_score_10'].unique()

array([ 5.8,  nan,  9. ,  9.6,  6.5,  8.6,  8.7,  6.4,  7.9,  7.7,  3.6,
        5.2,  6.8,  8.5,  7.1,  4.6, -1.2,  5. ,  3.2,  3.5,  3.8,  5.6,
        4.9,  8.8, 12. ,  6.7,  6.3,  9.9,  3.4,  9.8, -0.3, 10.7,  9.4,
       12.4,  4.2,  6.2,  3.9, 10. ,  6. ,  9.5,  7.4,  3. , 10.3,  7. ,
       10.2,  6.1,  3.3,  8. ,  4. ,  4.7,  4.5,  7.6,  5.9, -1.3,  4.1,
        5.1,  4.3, 12.2, 11.2,  8.1, 11.9,  5.4, -0.9,  5.5,  6.6,  3.7,
        9.3, 12.8,  8.2, 10.8,  5.3,  9.2, 12.3,  3.1,  7.8,  7.2,  9.1,
        4.8,  7.5,  6.9,  9.7, 12.7,  8.9,  4.4,  7.3, 11. , -0.4, 13. ,
       11.7,  8.4, -1.5, 11.5, 12.9, 10.5,  5.7, -1.1, -1.4, 10.1,  8.3,
       -0.7, 10.4, -0.8, -1.9, 12.1, -2. , -0.2, 10.9, -1.8, 11.1, -1. ,
       11.8, 11.3, 11.4, -0.5, 12.5, -1.7, -1.6, -0.1, 10.6, 12.6, -0.6,
       11.6])

In [22]:
## This converts the data type from object to string.
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].astype("string")
print(df['route_knowledge_score_10'].dtype)

string

In [23]:
## This is to remove the negative values and also the yrs in the age column.
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].str.lstrip('-')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
10222,DRV032308,Ravi Singh,40,Delhi,9813335746,ravi.singh@yahoo.com,Uber,Mini,Average,5+ yrs,...,8.2,<NA>,6.9,6.8,pass,Flagged,Rejected,Poor communication,NaN,1
1750,DRV039024,Yogesh R@o,999,Bangalore,9002449522,Yogesh R@o@gmail.com,Rapido,sedan,poor,0-1 yr,...,<NA>,5.2,4.3,6.2,pending,NaN,On Hold,NaN,-,0
19424,DRV027312,Naveen Tiwari,20,Lucknow,9524611969,naveen.tiwari@hotmail.com,Ola,unknown,Excellent,1-3 yrs,...,9.8,6.9,8.9,8.6,none,FLAGGED,Rejected,NaN,NaN,No
9260,DRV004093,DEEPAK VERMA,48,Jaipur,+91060908524,deepak.verma@rediffmail.com,Uber & rapido,na,avg,0-1 yr,...,6.3,6.3,7.8,6.0,pending,Clear,Selected,NaN,18-10-2022,Y
5154,DRV027182,Anil Ch@udh@ry,23,Pune,9067307086,Anil Ch@udh@ry@gmail.com,Rapido,SUV,Average,Fresher,...,5.3,5.6,10.5,5.4,Pass,Clear,On Hold,na,NaN,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14841,DRV037679,Deepak Jha,999,Pune,9183147347,deepak.jha@rediffmail.com,Uber,BIKE,GOOD,Fresher,...,5.4,4.7,9.8,6.7,Pending,clear,Selected,NaN,2023-02-03T00:00:00Z,Y
30871,DRV024414,Sunil Jha,unknown,Jaipur,+91437114393,sunil.jha@hotmail.com,Uber,BIKE,Average,5+ yrs,...,8.5,7.3,9.3,7.0,pending,NaN,Selected,NaN,2021-11-25T00:00:00Z,NO
5247,DRV000591,Suresh Reddy,52 yrs,Mumbai,9522111700,suresh.reddy@hotmail.com,Uber,BIKE,NaN,3-5 yrs,...,0.6,3.1,NaN,6.5,Pending,pending,on hold,NaN,-,false
6139,DRV010567,Ajay Chaudhary,27 yrs,Ahmedabad,+91290041921,ajay.chaudharygmail.com,Rapido,Mini,Excellent,0-1 yr,...,4.8,10.3,4.2,5.6,Pending,NaN,Selected,NaN,2021-12-30T00:00:00Z,no
19150,DRV016670,Rakesh Singh,25,Lucknow,9320349908,rakesh.singh@gmail.com,Uber,sedan,avg,Fresher,...,9.0,9.9,3.3,11.5,Fail,NaN,on hold,NaN,December 2023,no

In [24]:
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].fillna('7.5')

In [25]:
## This code fills the age column where NaN values exist with random values between 0 and 10

import numpy as np

mask = df['customer_handling_score_10'] == 6

df.loc[mask, 'customer_handling_score_10'] = np.random.randint(
    0, 10, size=mask.sum()
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
27223,NaN,Mukesh Verma,52,Bangalore,9538502130,mukesh.verma@gmail.com,Rapido,Auto,avg,3-5 yrs,...,<NA>,10.0,9.2,7.3,NaN,Flagged,Rejected,Incomplete documents,NaN,Y
33024,DRV035241,Santosh Verma,51,Mumbai,9585450743,Santosh Verma@gmail.com,Rapido,BIKE,Excellent,Fresher,...,5.0,6.1,5.9,NaN,NaN,FLAGGED,Selected,NaN,May 2022,false
29488,NaN,Naresh Kumar,35,Hyderabad,9440495234,naresh.kumar@hotmail.com,Uber,sedan,Excellent,0-1 yr,...,7.0,3.1,9.9,11.0,Pending,Flagged,NaN,NaN,-,no
12091,DRV031809,ravi chaudhary,70,Ahmedabad,9604876088,ravi.chaudhary@rediffmail.com,Bolt,NaN,NaN,1-3 yrs,...,0.2,3.8,10.5,6.7,pending,clear,Rejected,Poor communication,NaN,true
49977,DRV006025,Mahesh Patel,-40,Chennai,9238523153,Mahesh Patel@gmail.com,Ola,Mini,Excellent,5+ yrs,...,12.6,8.9,11.0,7.3,pass,Pending,Selected,NaN,December 2022,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2568,DRV025101,AJAY MISHRA,40,Pune,+91480639431,ajay.mishra@rediffmail.com,Uber,auto,Excellent,3-5 yrs,...,9.0,7.3,NaN,6.0,NaN,NaN,on hold,NaN,NaN,no
8443,DRV014619,Lokesh Singh,70,Ahmedabad,9946761926,lokesh.singh@yahoo.com,Ola,Sedan,Good,5+ yrs,...,6.7,9.1,9.0,8.6,NaN,NaN,Selected,NaN,04-08-2023,false
35006,DRV049271,Vikram Shukla,24,Ahmedabad,9983239743,vikram.shukla@hotmail.com,Rapido,sedan,poor,3-5 yrs,...,12.9,6.0,9.0,7.1,Pending,Flagged,Rejected,Incomplete documents,NaN,false
5993,DRV029738,Pankaj Patel,34,Chennai,9490919192,pankaj.patel@gmail.com,Rapido,Auto,excellent,Fresher,...,6.2,4.4,4.1,NaN,NaN,Pending,Rejected,NaN,-,Y
17766,DRV019688,Girish Yadav,34,Pune,9044055325,girish.yadav@@rediffmail.com,Bolt,BIKE,Good,1-3 yrs,...,6.8,5.1,7.9,6.2,Fail,Clear,selected,NaN,2022-02-11T00:00:00Z,NO

In [26]:
df['vehicle_type'].unique()

array(['auto', 'Mini ', 'SUV', 'Mini', 'suv', 'BIKE', 'Bike', 'Auto',
       'Sedan', 'unknown', nan, 'sedan', 'none', 'na', '-', 'Unknown'],
      dtype=object)

In [27]:
## This converts the data type from object to string.
df['vehicle_type'] = df['vehicle_type'].astype("string")
print(df['vehicle_type'].dtype)

string

In [28]:
df['vehicle_type'] = df['vehicle_type'].str.capitalize()
df['vehicle_type'] = df['vehicle_type'].fillna('Motorbike')
df['vehicle_type'] = df['vehicle_type'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    #'Unknown': 'Experienced',
    'None': 'Bicycle',
    #'Avg': 'Average',
    #'poor': 'Super',
    'Unknown': 'Tricycle',
    'Na': 'Catapiller',
    '-': 'Truck',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
24711,DRV019613,Mukesh Jha,50,Pune,9136423,Mukesh Jha @gmail.com,Rapido,Mini,NaN,Fresher,...,1.8,6.4,6.5,5.2,Fail,NaN,Rejected,Low rating history,NaN,yes
31559,DRV036919,Sanjay Patel,53 yrs,Lucknow,9638033273,sanjay.patel@yahoo.com,Rapido,Auto,good,3-5 yrs,...,6.8,5.6,3.6,-0.6,NaN,Clear,Rejected,Poor communication,-,yes
40074,DRV047677,Vikram Kumar,50,Ahmedabad,9023092192,vikram.kumar@yahoo.com,Uber & rapido,Motorbike,GOOD,0-1 yr,...,4.9,9.3,8.4,6.6,pending,Pending,-,NaN,NaN,Y
15170,DRV018529,Lokesh Gupta,47,Mumbai,9889292366,lokesh.guptahotmail.com,Bolt,Sedan,Good,5+ yrs,...,9.0,8.3,9.9,9.0,Fail,FLAGGED,Selected,NaN,29.10.2023,No
24013,DRV002634,mukesh pandey,-34,Delhi,9226638750,mukesh.pandey@rediffmail.com,Ola,Bike,excellent,1-3 yrs,...,5.4,6.5,4.8,5.8,pending,Clear,NaN,Vehicle age too old,NaN,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24270,DRV049682,Dinesh Nair,30,Bangalore,9983341479,dinesh.nair@hotmail.com,Rapido,Sedan,avg,1-3 yrs,...,5.3,4.7,NaN,-0.9,NaN,Pending,na,NaN,NaN,N
21993,DRV047262,Santosh Sharma,23,Chennai,9301137801,santosh.sharma@yahoo.com,Uber,Suv,avg,1-3 yrs,...,7.6,9.1,7.6,8.1,Fail,pending,Rejected,Background check failed,NaN,yes
22553,DRV046723,RAMESH PANDEY,39,Delhi,9910610,ramesh.pandey@hotmail.com,Rapido,Auto,excellent,0-1 yr,...,7.8,5.6,4.6,5.3,FAIL,Clear,Selected,NaN,24.10.2021,False
13155,DRV047461,Umesh Yadav,34,Lucknow,9985681503,umesh.yadav@hotmail.com,Ola,Auto,avg,0-1 yr,...,8.5,12.3,7.0,7.8,Fail,unknown,Selected,NaN,June 2021,False
6423,DRV036713,Pankaj Rao,32,Ahmedabad,+91351177098,pankaj.rao@hotmail.com,Rapido,Bike,Excellent,0-1 yr,...,9.2,8.4,3.2,6.2,Pass,FLAGGED,Selected,NaN,NaN,no

In [29]:
df['vehicle_condition'].unique()

array(['good', 'Excellent', 'avg', nan, 'GOOD', 'excellent', 'Average',
       'Poor', 'poor', 'Good', 'unknown', '-', 'Unknown', 'na', 'none'],
      dtype=object)

In [30]:
## This converts the data type from object to string.
df['vehicle_condition'] = df['vehicle_condition'].astype("string")
print(df['vehicle_condition'].dtype)

string

In [31]:
df['vehicle_condition'] = df['vehicle_condition'].str.capitalize()
df['vehicle_condition'] = df['vehicle_condition'].fillna('Super')
df['vehicle_condition'] = df['vehicle_condition'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    'Unknown': 'Great',
    'None': 'Beautiful',
    'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Tricycle',
    'Na': 'Fair',
    '-': 'Wonderful',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
18185,DRV044331,Mahesh Chaudhary,34,Hyderabad,9397274553,mahesh.chaudhary@hotmail.com,Rapido,Sedan,Good,-,...,12.5,9.1,8.0,8.0,NaN,Clear,Selected,NaN,2023-08-01T00:00:00Z,0
34288,DRV028090,Sanjay Singh,37,Chennai,+91702783633,sanjay.singh@yahoo,Bolt,Suv,Poor,0-1 yr,...,7.2,4.8,6.1,NaN,pending,pending,Rejected,Background check failed,-,no
34218,DRV042447,Rajesh Rao,20,Lucknow,9750350324,rajesh.rao@gmail.com,Uber,Suv,Average,5+ yrs,...,9.2,0.9,5.0,NaN,Pending,pending,Rejected,Vehicle age too old,NaN,False
36746,DRV004542,mahesh chauhan,33,Jaipur,9067651807,mahesh.chauhan@rediffmail.com,Rapido,Sedan,Excellent,0-1 yr,...,4.8,10.9,-0.4,6.8,Fail,pending,NaN,NaN,NaN,0
6001,DRV039460,Mahesh Jha,999,Ahmedabad,9058709342,mahesh.jha@gmail.com,Uber,Sedan,Good,5+ yrs,...,6.1,5.7,4.9,6.4,Fail,Clear,On Hold,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26631,DRV030904,Vijay Reddy,35,Ahmedabad,9539146595,vijay.reddy@yahoo.com,Uber,Motorbike,Good,none,...,4.1,5.6,5.7,4.6,NaN,Pending,selected,Background check failed,NaN,1
8715,DRV044881,RAKESH PATEL,36,Bangalore,9917507981,rakesh.patel@hotmail.com,Ola,Mini,Average,5+ yrs,...,6.0,7.5,7.9,NaN,pending,clear,Selected,NaN,23-06-2021,No
23339,DRV036625,Santosh Singh,48,Ahmedabad,9160314277,santosh.singh@@yahoo.com,Ola,Motorbike,Good,5+ yrs,...,6.5,8.5,7.5,7.8,NaN,FLAGGED,NaN,NaN,NaN,N
43222,DRV017584,Mukesh Reddy,46,Chennai,9670720034,mukesh.reddy@@hotmail.com,Bolt,Mini,Poor,0-1 yr,...,4.3,9.2,10.3,6.8,Pending,clear,NaN,NaN,2022-06-18T00:00:00Z,yes
30898,NaN,Dinesh Reddy,41 yrs,Lucknow,+91598750748,dinesh.reddyrediffmail.com,Uber,Mini,Average,0-1 yr,...,9.6,7.3,9.1,NaN,pending,pending,On Hold,NaN,NaN,1

In [32]:
df['experience_level'].unique()

array(['0-1 yr', 'Fresher', '1-3 yrs', '5+ yrs', '3-5 yrs', nan,
       'unknown', 'na', 'Unknown', '-', 'none'], dtype=object)

In [33]:
## This converts the data type from object to string.
df['experience_level'] = df['experience_level'].astype("string")
print(df['experience_level'].dtype)

string

In [34]:
df['experience_level'] = df['experience_level'].str.capitalize()
df['experience_level'] = df['experience_level'].fillna('High')
df['experience_level'] = df['experience_level'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    '0-1 yr' : '4+ yrs',
    'Unknown': '7+ yrs',
    'None': '8+ yrs',
    #'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Tricycle',
    'Na': '6 yrs',
    '-': '8 yrs',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
28174,DRV027555,Sunil Reddy,47,Pune,9926391,sunil.reddy@hotmail.com,Ola,Sedan,Super,1-3 yrs,...,9.6,5.3,9.3,7.4,Fail,Clear,Selected,NaN,15-05-2023,0
1033,DRV025981,Amit Shukla,27,Mumbai,9747457393,amit.shukla@yahoo,Uber & rapido,Mini,Super,4+ yrs,...,8.3,9.1,8.5,8.0,NaN,FLAGGED,Selected,NaN,26.03.2024,1
42223,DRV032108,MANOJ JHA,34,Pune,9330908739,manoj.jha@hotmail.com,Uber,Auto,Excellent,5+ yrs,...,<NA>,7.2,3.1,4.4,NaN,Pending,Rejected,Low rating history,NaN,Y
47057,DRV019982,Vij@y Trip@thi,26,Ahmedabad,+91509181280,vijay.tripathi@gmail.com,Ola,Bike,Poor,4+ yrs,...,4.9,3.9,NaN,5.8,Fail,pending,On Hold,NaN,NaN,YES
43926,DRV024109,Hitesh Verma,49,Bangalore,9089163,hitesh.verma@rediffmail.com,Uber,Bike,Good,4+ yrs,...,5.9,9.8,3.0,7.2,NaN,clear,On Hold,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23568,DRV047037,rajesh reddy,43,Mumbai,9327118664,rajesh.reddyrediffmail.com,Rapido,Bike,Excellent,5+ yrs,...,5.6,3.3,6.3,4.7,Pass,Flagged,Rejected,Vehicle age too old,NaN,Y
26215,DRV025912,Harish Singh,999,Hyderabad,9333385614,harish.singh@rediffmail.com,Ola,Suv,Super,5+ yrs,...,10.7,9.3,-0.8,8.1,pending,Flagged,On Hold,NaN,NaN,0
43381,DRV014840,Lokesh Shukla,42 yrs,Mumbai,9003433309,lokesh.shukla@hotmail.com,Uber & rapido,Sedan,Excellent,4+ yrs,...,11.2,6.3,8.0,7.6,pending,clear,Selected,NaN,2022-07-18T00:00:00Z,YES
15987,DRV000385,Ganesh Jha,26,Lucknow,+91040159997,ganesh.jhagmail.com,Ola,Suv,Poor,3-5 yrs,...,4.4,3.3,3.1,5.0,FAIL,clear,Selected,NaN,26-04-2023,Yes
16684,DRV007809,Suresh Chauhan,43,Bangalore,9367116019,Suresh Chauhan@gmail.com,Uber,Mini,Super,3-5 yrs,...,5.5,4.9,4.0,5.9,Fail,FLAGGED,Selected,na,-,YES

In [35]:
df['driving_test_score_10'].unique()

<StringArray>
[ '4.3',  '9.3',  '6.3',  '8.7', '12.7',  '8.8',  '8.1',  '1.1', '11.6',
   <NA>,
 ...
 '12.3',  '1.6', '12.6',  '1.9', '10.6', '12.9', '11.1', '13.0',  '0.1',
  '2.0']
Length: 112, dtype: string

In [36]:
## This converts the data type from object to string.
df['driving_test_score_10'] = df['driving_test_score_10'].astype("string")
print(df['driving_test_score_10'].dtype)

string

In [37]:
df['driving_test_score_10'] = df['driving_test_score_10'].fillna('7.5')

In [38]:
df['route_knowledge_score_10'].unique()

<StringArray>
[ '5.8',  '7.5',  '9.0',  '9.6',  '6.5',  '8.6',  '8.7',  '6.4',  '7.9',
  '7.7',
 ...
 '11.4',  '0.5', '12.5',  '1.7',  '1.6',  '0.1', '10.6', '12.6',  '0.6',
 '11.6']
Length: 121, dtype: string

In [39]:
df['customer_handling_score_10'].unique()

array([ 7.7,  9. ,  5.5,  5.3,  7.9, 10.5,  9.7,  nan, 10.7,  5.9,  6.2,
        4.9,  6.7,  6.9,  6.8,  8.5, 12.3,  1. ,  3.5,  5. ,  4.1, 11.2,
        8.9,  7.6,  6.5,  3.6, 10.6,  4.3,  3.8,  3.2,  7.5,  4.6,  5.7,
        3.7, -0.9,  4.7,  4.2, -1.6,  8.8, -0.6,  6.4,  6.3,  9.8,  7. ,
        9.5,  8.3,  3.1,  9.4,  6.6,  9.1, 11.4,  7.3,  7.4, 11.5,  8.6,
        9.6,  7.2,  3. ,  3.3,  8.1,  3.4,  4.4,  4. ,  8.4,  8. ,  5.1,
        5.2, -1.9,  5.4,  4.5, 12. ,  6.1,  7.1, 11.1, 10. ,  5.6, -1.3,
       12.8, -1.2,  8.7,  3.9, 11.6,  9.2, -1.8,  7.8,  9.9,  9.3, 11.3,
       11. , 12.6, 12.1,  8.2, 12.5, -1.7,  2. ,  5.8, -0.2, 12.4, 11.7,
       -0.7, 12.9, 10.3, 12.2, 10.8,  4.8, 10.9, -1.5, 11.9, 11.8, -1.1,
       -0.8, -2. , 10.4, -0.3, -0.4, -0.5, -0.1, -1. , 10.2, 13. , 12.7,
       -1.4, 10.1,  0. ,  6. ])

In [40]:
## This converts the data type from object to string.
df['customer_handling_score_10'] = df['customer_handling_score_10'].astype("string")
print(df['customer_handling_score_10'].dtype)

string

In [41]:
df['customer_handling_score_10'] = df['customer_handling_score_10'].fillna('8.5')
df['customer_handling_score_10'] = df['customer_handling_score_10'].str.lstrip('-')

In [42]:
df['overall_interview_score_10'].unique()

array([ 5.3,  8.1,  6.9,  7.8,  6. , -1.4,  8.2,  8.3,  6.7,  5.8,  7.7,
        nan,  7.6,  6.5,  7.5,  4.1,  6.2, -1.6,  6.4,  7.2,  7.4,  3.6,
        6.3,  6.1,  5.2, -1.3,  5.6,  5.7,  5. ,  5.5,  6.8,  6.6, 10.7,
        7.3, 11.6,  4.2, 10.6, 10.5,  7.1, 12.6, -1. ,  7. ,  4.8, 11.1,
       11.9, 10.3,  4.9,  5.1,  4.5,  5.9,  8. , 12.4, 11.5, 12.9,  4.6,
        5.4,  7.9, -2. , 13. ,  9.7, 10.1, -1.8, -1.9, 11.7,  8.6, -1.5,
        8.4, 11.8, 11. ,  9.2,  8.5, 12.3, 12.5, 12.8, 12. , 11.4,  4.7,
        4.4, -1.7, -0.8, -0.7, -0.3,  8.7,  9.1,  4.3, 12.1,  8.8, -0.4,
       12.7, -0.2, 11.2, 10.8,  8.9, 12.2, 10.9, -1.2, 10.2, -0.6, 11.3,
        4. , -1.1, -0.5, 10.4,  9. ,  9.4,  3.9, -0.9,  3.8, -0.1,  9.3,
        9.6,  3.7,  9.5,  3.5,  9.8,  3.4])

In [43]:
## This converts the data type from object to string.
df['overall_interview_score_10'] = df['overall_interview_score_10'].astype("string")
print(df['overall_interview_score_10'].dtype)

string

In [44]:
df['overall_interview_score_10'] = df['overall_interview_score_10'].fillna('8.8')
df['overall_interview_score_10'] = df['overall_interview_score_10'].str.lstrip('-')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
22384,DRV022238,Amit Singh,32,Hyderabad,9904035579,Amit Singh@gmail.com,Rapido,Auto,Poor,4+ yrs,...,5.7,6.0,3.8,8.8,NaN,Clear,On Hold,NaN,-,true
39912,DRV026810,M@noj P@ndey,28,Ahmedabad,+91427908463,manoj.pandey@gmail.com,Uber,Suv,Good,4+ yrs,...,6.6,7.5,3.9,5.7,Fail,clear,Selected,NaN,14.03.2023,N
16644,DRV023313,Naveen Patel,54,Mumbai,9543897594,Naveen Patel@gmail.com,Uber,Bike,Good,8 yrs,...,6.4,5.8,10.2,6.6,pending,pending,Waitlist,NaN,-,No
38025,DRV028905,Lokesh Patel,39,Mumbai,+91884124073,lokesh.patel@hotmail.com,Rapido,Mini,Good,5+ yrs,...,5.9,4.0,8.5,5.3,pending,NaN,-,NaN,13 December 2021,YES
6297,DRV010561,Ajay Kumar,33,Ahmedabad,9353737839,ajay.kumar@hotmail.com,Ola,Auto,Excellent,Fresher,...,9.9,9.1,11.4,8.7,none,pending,On Hold,NaN,03/11/21,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1188,DRV037178,Deepak Kumar,52,Chennai,9834835342,deepak.kumar@rediffmail.com,Rapido,Auto,Super,1-3 yrs,...,9.7,4.6,10.2,7.9,Pass,FLAGGED,Rejected,Vehicle age too old,NaN,NO
5157,DRV008601,Lokesh Shukla,-48,Delhi,9960649228,lokesh.shukla@gmail.com,Uber,Mini,Super,3-5 yrs,...,4.1,6.1,3.8,5.6,pending,NaN,NaN,Background check failed,NaN,No
43047,DRV012092,ramesh chauhan,49,Delhi,9574630253,ramesh.chauhanhotmail.com,Uber,Mini,Excellent,5+ yrs,...,6.4,10.3,8.6,6.1,NaN,Pending,On Hold,NaN,NaN,Y
8277,DRV044143,Anil Chauhan,30,Lucknow,+91155814594,anil.chauhan@yahoo.com,Bolt,Suv,Average,Fresher,...,4.9,11.0,6.6,5.6,NaN,pending,On Hold,NaN,NaN,Y
28060,DRV032149,Lokesh Verma,24,Jaipur,9821698736,lokesh.verma@rediffmail.com,Rapido,Suv,Good,1-3 yrs,...,9.4,9.1,8.7,8.8,pending,pending,On Hold,NaN,NaN,false

In [45]:
df['document_verification'].unique()

array(['Fail', nan, 'unknown', 'FAIL', 'Pass', 'Pending', 'pass',
       'pending', 'none', 'Unknown', '-', 'na'], dtype=object)

In [46]:
## This converts the data type from object to string.
df['document_verification'] = df['document_verification'].astype("string")
print(df['document_verification'].dtype)

string

In [47]:
df['document_verification'] = df['document_verification'].str.capitalize()
df['document_verification'] = df['document_verification'].fillna('Distinction')
df['document_verification'] = df['document_verification'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999': '90',
    #'0-1 yr' : '4+ yrs',
    #'Unknown':'High',
    'None':'Credit',    
    #'Avg': 'Average',
    #'poor': 'Super',
    'Unknown':'Average',
    'Na': 'Fair',
    '-': 'Exceptional',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
30315,DRV046293,Lokesh Tripathi,43,Ahmedabad,9251771,lokesh.tripathi@rediffmail.com,Uber,Bike,Good,5+ yrs,...,6.7,5.1,7.6,7.1,Pending,NaN,NaN,NaN,09-04-2021,YES
33505,DRV027913,Ramesh Srivastava,35,Chennai,9711645,ramesh.srivastava@hotmail.com,Rapido,Bike,Excellent,3-5 yrs,...,7.2,9.4,10.2,8.2,Distinction,na,Rejected,NaN,NaN,False
26059,DRV031958,Anil Shukla,34,Mumbai,9892753075,anil.shukla@rediffmail.com,Uber,Mini,Super,5+ yrs,...,7.1,9.7,9.9,8.9,Pending,pending,Selected,NaN,2021-03-24T00:00:00Z,0
46937,DRV007033,PRADEEP SINGH,23 yrs,Mumbai,+91226398851,pradeep.singh@yahoo.com,Rapido,Bike,Beautiful,4+ yrs,...,4.3,9.2,5.0,6.4,Pass,Flagged,Rejected,Failed driving test,NaN,no
5144,DRV024340,Sanjay Pandey,48,Hyderabad,9320588605,sanjay.pandey@gmail.com,Rapido,Bike,Average,4+ yrs,...,4.4,4.7,3.1,10.2,Distinction,Clear,On Hold,NaN,-,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20525,DRV023174,Santosh Gupta,24 yrs,Mumbai,9278756507,santosh.gupta@gmail.com,Uber,Mini,Poor,4+ yrs,...,5.6,7.6,8.9,8.8,Exceptional,FLAGGED,On Hold,NaN,NaN,0
35222,DRV001258,Naveen Nair,-37,Chennai,9825732026,naveen.nair@gmail.com,Rapido,Bike,Excellent,5+ yrs,...,7.5,4.9,7.7,7.0,Fail,NaN,on hold,NaN,March 2022,N
39186,DRV004616,Umesh Nair,42,Lucknow,9332618382,umesh.nair@@gmail.com,Rapido,Suv,Super,1-3 yrs,...,5.6,7.9,12.7,7.0,Pending,clear,NaN,NaN,NaN,Y
37522,DRV009727,Mukesh Singh,32,Mumabi,+91044440726,mukesh.singh@rediffmail.com,Uber,Suv,Super,7+ yrs,...,5.5,7.1,7.5,0.7,Pass,Pending,REJECTED,NaN,2023-12-18T00:00:00Z,True
39025,DRV021359,Santosh Dubey,29,Pune,+91164814122,santosh.dubey@rediffmail.com,Ola,Suv,Good,High,...,9.1,3.6,1.3,6.3,Pass,FLAGGED,On Hold,NaN,-,yes

In [48]:
df['document_verification'].unique()

<StringArray>
[       'Fail', 'Distinction',     'Average',        'Pass',     'Pending',
      'Credit', 'Exceptional',        'Fair']
Length: 8, dtype: string

In [49]:
df['background_check_status'].unique()

array([nan, 'Clear', 'clear', 'pending', 'Flagged', 'FLAGGED', 'Pending',
       'na', 'unknown', 'none', '-', 'Unknown'], dtype=object)

In [50]:
## This converts the data type from object to string.
df['background_check_status'] = df['background_check_status'].astype("string")
print(df['background_check_status'].dtype)

string

In [51]:
df['background_check_status'] = df['background_check_status'].str.capitalize()
df['background_check_status'] = df['background_check_status'].fillna('Clear')
df['background_check_status'] = df['background_check_status'].replace({
'Na': 'Clear', 
'Unknown': 'Clear', 
'None': 'Pending', 
'-': 'Clear'
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
32003,DRV029514,Deepak Patel,30,Hyderabad,9198806516,deepak.patel@rediffmail.com,Uber & rapido,Sedan,Great,Fresher,...,8.3,11.2,3.8,8.8,Pass,Pending,Selected,NaN,01-12-2023,False
45950,DRV002221,Pankaj Jha,23,Jaipur,9721525701,pankaj.jha@yahoo.com,-,Auto,Poor,Fresher,...,4.8,7.5,6.7,6.0,Pass,Clear,Waitlist,NaN,NaN,True
15511,DRV019369,Rakesh Dubey,53,Mumbai,9824274490,rakesh.dubey@@rediffmail.com,Uber,Mini,Super,1-3 yrs,...,5.7,6.0,5.7,5.7,Distinction,Clear,Rejected,NaN,NaN,false
11417,DRV027890,Sanjay Kumar,39,Mumbai,+91077588854,sanjay.kumarrediffmail.com,Na,Suv,Super,3-5 yrs,...,8.9,3.9,7.9,6.7,Distinction,Flagged,on hold,NaN,June 2023,no
3440,DRV014461,Pankaj Reddy,22,Bangalore,9843129736,pankaj.reddy@hotmail.com,Uber & rapido,Auto,Excellent,3-5 yrs,...,7.8,7.2,11.1,6.0,Pending,Clear,On Hold,NaN,NaN,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29811,DRV026432,Vikr@m Kum@r,43,Hyderabad,9052732035,vikram.kumar@hotmail.com,Rapido,Suv,Super,3-5 yrs,...,7.0,3.1,0.7,8.8,Distinction,Clear,Rejected,NaN,-,false
23283,DRV043102,Rajesh Nair,52,Chennai,9022029087,rajesh.nair@hotmail.com,Uber,Auto,Poor,4+ yrs,...,7.3,3.5,8.1,11.6,Fail,Pending,Rejected,NaN,NaN,YES
22961,DRV033453,mukesh tiwari,44,Pune,+91817364601,mukesh.tiwarihotmail.com,Rapido,Bike,Poor,5+ yrs,...,5.1,7.7,7.1,5.7,Exceptional,Clear,Selected,NaN,NaN,YES
25752,DRV025443,Ramesh Jha,48,Mumbai,+91500449328,ramesh.jha@gmail.com,Uber,Suv,Average,4+ yrs,...,6.3,7.5,5.7,7.8,Pass,Flagged,Selected,NaN,13-12-2022,true
22949,DRV003849,GIRISH TIWARI,46,Jaipur,9928456862,girish.tiwari@rediffmail.com,Uber,Truck,Good,4+ yrs,...,4.9,8.0,9.1,8.8,Pending,Pending,Selected,NaN,2022/02/13,yes

In [52]:
df['background_check_status'].unique()

<StringArray>
['Clear', 'Pending', 'Flagged']
Length: 3, dtype: string

In [53]:
df['interview_result'].unique()

array(['On Hold', 'Selected', 'Rejected', 'Waitlist', nan, 'selected',
       'REJECTED', 'Unknown', 'on hold', 'none', '-', 'unknown', 'na'],
      dtype=object)

In [54]:
## This converts the data type from object to string.
df['interview_result'] = df['interview_result'].astype("string")
print(df['interview_result'].dtype)

string

In [55]:
df['interview_result'] = df['interview_result'].str.capitalize()
df['interview_result'] = df['interview_result'].fillna('Selected')
df['interview_result'] = df['interview_result'].replace({
'Na': 'Selected', 
'Unknown': 'Selected', 
'None': 'Pending', 
'-': 'Pending'
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
34970,DRV005289,Sanjay Mishra,54,Mumbai,9524684493,sanjay.mishra@@rediffmail.com,Uber,Mini,Super,3-5 yrs,...,10.4,9.9,9.3,7.0,Fail,Pending,Rejected,Background check failed,-,Yes
28522,DRV029072,Santosh Mishra,26,Kolkata,+91294957311,santosh.mishra@yahoo.com,Rapido,Auto,Good,8 yrs,...,5.4,4.2,9.8,6.8,Pass,Flagged,Selected,NaN,NaN,1
48898,DRV002296,SURESH SHUKLA,26,Jaipur,+91266720511,suresh.shukla@rediffmail,Bolt,Auto,Average,3-5 yrs,...,4.6,10.6,3.6,3.8,Fail,Clear,On hold,Background check failed,NaN,YES
11383,DRV031659,Sunil Shukla,unknown,Jaipur,9144174050,sunil.shukla@yahoo.com,Uber,Mini,Good,3-5 yrs,...,6.9,8.9,8.3,6.9,Distinction,Clear,Rejected,Background check failed,-,no
14946,DRV000391,Ravi Tripathi,49,Chennai,9878561432,ravi.tripathi@rediffmail.com,Bolt,Bike,Good,3-5 yrs,...,1.2,4.3,8.5,6.4,Distinction,Clear,Rejected,Low rating history,NaN,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8401,DRV012543,Lokesh Singh,70,Jaipur,+91257448276,lokesh.singh@@rediffmail.com,Uber,Bike,Good,5+ yrs,...,11.9,7.5,6.4,6.3,Average,Clear,Selected,NaN,04/10/24,false
1658,DRV039147,Ganesh Tiwari,29,Mumbai,9255603707,ganesh.tiwari@rediffmail.com,Ola,Mini,Super,3-5 yrs,...,5.5,4.1,7.4,5.8,Fail,Clear,Rejected,Failed driving test,NaN,No
40082,DRV011750,Ajay Tiwari,29,Hyderabad,9580796859,Ajay Tiwari@gmail.com,Ola,Auto,Poor,1-3 yrs,...,8.0,7.5,3.9,5.4,Fail,Clear,Selected,NaN,03/17/22,Y
27632,DRV041748,Lokesh Reddy,48,Delhi,9687703,lokesh.reddy@gmail.com,Uber & rapido,Auto,Great,5+ yrs,...,9.7,5.0,8.3,7.4,Pass,Clear,Selected,NaN,April 2021,NO
21912,NaN,Ramesh Shukla,23,Hyderabad,9186489767,ramesh.shukla@rediffmail.com,Uber,Suv,Super,4+ yrs,...,7.2,5.8,6.5,6.5,Distinction,Clear,On hold,NaN,NaN,N

In [56]:
df['interview_result'].unique()

<StringArray>
['On hold', 'Selected', 'Rejected', 'Waitlist', 'Pending']
Length: 5, dtype: string

In [57]:
df['rejection_reason'].unique()

array([nan, 'Low rating history', 'Not applicable', 'na', 'none',
       'Incomplete documents', 'Vehicle age too old',
       'Poor communication', '-', 'Background check failed',
       'Failed driving test', 'unknown', 'Unknown'], dtype=object)

In [58]:
## This converts the data type from object to string.
df['rejection_reason'] = df['rejection_reason'].astype("string")
print(df['rejection_reason'].dtype)

string

In [59]:
df['rejection_reason'] = df['rejection_reason'].str.capitalize()
df['rejection_reason'] = df['rejection_reason'].fillna('Invalid_id')
df['rejection_reason'] = df['rejection_reason'].replace({
'Na': 'Invalid_id', 
'Unknown': 'Selected', 
'None': 'Poor communication', 
'-': 'Background check failed'
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
33185,DRV011057,Vijay Gupta,45,Delhi,9760154711,vijay.gupta@hotmail.com,Uber & rapido,Auto,Excellent,1-3 yrs,...,7.5,7.5,9.2,8.3,Fail,Pending,On hold,Invalid_id,NaN,Yes
24806,DRV018557,Naveen Patel,36,Chennai,9470840452,Naveen Patel@gmail.com,Uber,Auto,Good,3-5 yrs,...,0.5,5.8,9.5,7.1,Pass,Clear,On hold,Invalid_id,NaN,N
21331,DRV007867,Harish Reddy,31,Lucknow,9504314318,harish.reddy@hotmail.com,Uber,Mini,Poor,1-3 yrs,...,7.0,3.8,4.9,6.1,Pending,Flagged,Rejected,Failed driving test,NaN,Y
9422,DRV038072,Manoj Pandey,unknown,Kolkata,+91926896129,manoj.pandey@hotmail.com,Rapido,Sedan,Super,1-3 yrs,...,4.3,6.0,8.0,6.2,Distinction,Pending,Selected,Invalid_id,03/25/22,yes
1851,DRV002991,manoj jha,49,Bangalore,9287264822,manoj.jha@yahoo.com,Uber,Tricycle,Poor,4+ yrs,...,8.9,6.3,5.6,8.8,Pending,Clear,On hold,Poor communication,NaN,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13187,DRV043669,ramesh chauhan,999,Ahmedabad,9500419578,ramesh.chauhan@gmail.com,Rapido,Auto,Super,Fresher,...,7.9,8.0,7.0,7.4,Distinction,Clear,Selected,Invalid_id,-,False
1815,DRV016225,Manoj Nair,27,Kolkata,9797542727,manoj.nairyahoo.com,Uber & rapido,Suv,Good,1-3 yrs,...,1.3,10.2,9.2,8.8,Distinction,Clear,Rejected,Low rating history,-,N
1627,DRV018182,VIKRAM SRIVASTAVA,20,Lucknow,+91551718738,vikram.srivastava@hotmail.com,Uber,Mini,Average,3-5 yrs,...,7.5,8.7,3.9,6.4,Pending,Clear,On hold,Invalid_id,NaN,Yes
12952,DRV030519,Harish Gupta,49,Hyderabad,9736149606,harish.gupta@hotmail.com,Rapido,Suv,Average,Fresher,...,7.5,8.0,6.9,6.4,Fail,Flagged,On hold,Invalid_id,NaN,true
31064,DRV009265,Ravi Reddy,44,Mumbai,9125858857,ravi.reddy@rediffmail.com,Uber,Mini,Super,3-5 yrs,...,0.3,6.3,8.5,7.0,Pass,Clear,On hold,Invalid_id,NaN,N

In [60]:
df['rejection_reason'].unique()

<StringArray>
[             'Invalid_id',      'Low rating history',
          'Not applicable',      'Poor communication',
    'Incomplete documents',     'Vehicle age too old',
 'Background check failed',     'Failed driving test',
                'Selected']
Length: 9, dtype: string

In [61]:
df['onboarding_date'].unique()

array(['-', '19 April 2021', '2021/05/27', ..., '2023/04/22',
       '07-06-2022', '2021-03-31T00:00:00Z'], dtype=object)

In [69]:
## This code generates random date values for the onboarding column. 

import pandas as pd
import numpy as np

df['onboarding_date'] = pd.to_datetime(df['onboarding_date'], errors='coerce')

start = pd.Timestamp("2025-01-01")
end = pd.Timestamp("2026-08-11")

mask = df["onboarding_date"].isna()

df.loc[mask, "onboarding_date"] = pd.to_datetime(
    np.random.randint(
        start.value // 10**9,
        end.value // 10**9,
        size=mask.sum()
    ),
    unit="s"
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
4424,DRV037476,AMIT CHAUHAN,70,Chennai,9256254523,amit.chauhangmail.com,Uber,Suv,Poor,3-5 yrs,...,4.9,4.2,9.4,7.0,Distinction,Clear,Selected,Invalid_id,2025-05-16 02:09:14,True
41735,DRV006620,Pradeep Sharma,28,Bangalore,9870975698,pradeep.sharma@gmail.com,Uber,Suv,Good,1-3 yrs,...,8.5,7.0,13.0,7.7,Distinction,Clear,On hold,Invalid_id,2025-07-29 05:51:47,False
36530,DRV036786,Santosh Srivastava,27,Lucknow,9538378271,santosh.srivastava@rediffmail.com,Ola,Suv,Poor,Fresher,...,8.2,3.4,1.9,6.5,Pending,Clear,Rejected,Background check failed,2025-07-21 00:08:56,True
32423,DRV038834,deepak chaudhary,30,Delhi,9888682287,deepak.chaudhary@hotmail.com,Uber,Auto,Average,5+ yrs,...,9.0,7.5,5.6,6.1,Distinction,Clear,Rejected,Low rating history,2025-01-01 12:59:11,True
20890,DRV042603,Dinesh Dubey,50,Delhi,+91568367789,dinesh.dubey@gmail.com,Rapido,Motorbike,Good,Fresher,...,8.0,5.7,8.1,8.8,Pass,Flagged,Selected,Invalid_id,2025-07-09 16:05:36,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35634,DRV018169,Lokesh Shukla,70,Jaipur,9869365973,lokesh.shukla@rediffmail.com,Uber,Motorbike,Average,1-3 yrs,...,11.9,9.4,7.7,8.2,Distinction,Pending,Rejected,Low rating history,2026-05-07 19:04:38,True
21125,DRV041447,manoj tripathi,30,Delhi,9511038894,manoj.tripathi@yahoo.com,Uber,Sedan,Poor,Fresher,...,4.2,7.8,3.8,5.7,Distinction,Pending,On hold,Invalid_id,2026-03-11 00:07:45,False
15766,DRV037778,umesh rao,34,Mumbai,9841274070,umesh.rao@hotmail.com,Uber,Sedan,Super,3-5 yrs,...,6.0,5.1,8.7,6.7,Pass,Flagged,On hold,Invalid_id,2025-09-28 00:14:10,False
13900,DRV021108,Sunil Singh,70,Delhi,9301351386,sunil.singh@hotmail.com,Uber,Sedan,Excellent,4+ yrs,...,4.3,7.1,3.1,5.1,Distinction,Clear,On hold,Invalid_id,2025-02-17 22:50:53,True
16811,DRV026815,Lokesh Yadav,49,Chennai,+91598981696,lokesh.yadav@yahoo.com,Uber & rapido,Truck,Excellent,5+ yrs,...,4.3,6.1,8.1,5.5,Distinction,Flagged,Selected,Invalid_id,2026-03-09 06:37:25,True

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   driver_id                   49005 non-null  object
 1   driver_name                 50000 non-null  object
 2   age                         50000 non-null  string
 3   city                        50000 non-null  string
 4   phone                       50000 non-null  string
 5   email                       50000 non-null  string
 6   platform                    50000 non-null  string
 7   vehicle_type                50000 non-null  string
 8   vehicle_condition           50000 non-null  string
 9   experience_level            50000 non-null  string
 10  preferred_shift             38773 non-null  object
 11  reason_for_joining          38637 non-null  object
 12  languages_known             47847 non-null  object
 13  overall_driver_rating       46033 non-null  object
 14  total_trips_completed       45930 non-null  float64
 15  trip_completion_rate_%      45565 non-null  float64
 16  cancellation_rate_%         45484 non-null  float64
 17  avg_daily_earnings_INR      47489 non-null  object
 18  total_complaints            45965 non-null  float64
 19  total_compliments           46024 non-null  float64
 20  peak_hour_availability      50000 non-null  object
 21  interview_date              45067 non-null  object
 22  communication_score_10      45416 non-null  float64
 23  driving_test_score_10       50000 non-null  string
 24  route_knowledge_score_10    50000 non-null  string
 25  customer_handling_score_10  50000 non-null  string
 26  overall_interview_score_10  50000 non-null  string
 27  document_verification       50000 non-null  string
 28  background_check_status     50000 non-null  string
 29  interview_result            50000 non-null  string
 30  rejection_reason            50000 non-null  string
 31  onboarding_date             50000 non-null  object
 32  is_currently_active         50000 non-null  object
dtypes: float64(6), object(11), string(16)
memory usage: 12.6+ MB

In [64]:
df['onboarding_date'].unique()

array([Timestamp('2025-02-10 22:07:31'), Timestamp('2026-01-12 11:59:18'),
       datetime.datetime(2021, 4, 19, 0, 0), ...,
       Timestamp('2025-05-23 21:39:02'), Timestamp('2026-03-19 19:31:23'),
       Timestamp('2025-10-10 00:15:38')], dtype=object)

In [65]:
df['is_currently_active'].unique()

array(['false', 'No', '0', 'NO', 'N', 'true', '1', 'yes', 'YES', 'Y',
       'True', 'no', 'False', 'Yes'], dtype=object)

In [66]:
## This converts the data type from object to string.
df['is_currently_active'] = df['is_currently_active'].astype("string")
print(df['is_currently_active'].dtype)

string

In [95]:
df['is_currently_active'] = df['is_currently_active'].str.capitalize()
df['is_currently_active'] = df['is_currently_active'].fillna('True')
df['is_currently_active'] = df['is_currently_active'].replace({
'No':'False', 
'0': 'False', 
'1': 'True', 
'N': 'False',
'Y': 'True',
'Yes': 'True',
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
49466,NaN,Pradeep Jha,21,Lucknow,+91741220175,pradeep.jha@hotmail.com,Rapido,Suv,Super,4+ yrs,...,7.9,8.7,9.6,7.6,Fail,Flagged,Selected,Invalid_id,2025-10-10 13:10:59,True
10719,NaN,Bharat Rao,29,Bangalore,+91410652429,bharat.rao@yahoo.com,Bolt,Bike,Average,8+ yrs,...,9.0,3.2,8.5,7.8,Pass,Clear,On hold,Invalid_id,2025-02-14 21:19:32,True
12682,NaN,R@kesh Sh@rm@,31,Mumbai,9597097256,R@kesh Sh@rm@@gmail.com,Uber,Truck,Excellent,1-3 yrs,...,9.6,6.9,6.9,6.9,Pending,Clear,On hold,Invalid_id,2026-06-07 09:37:21,True
2458,NaN,Hitesh Yadav,52 yrs,Hyderabad,9936082373,hitesh.yadavyahoo.com,Uber,Mini,Excellent,5+ yrs,...,5.2,5.9,9.0,5.9,Fail,Clear,On hold,Invalid_id,2026-01-06 16:45:09,True
13040,NaN,Ganesh Chauhan,43,Bangalore,+91402739875,ganesh.chauhan@gmail.com,Rapido,Auto,Excellent,1-3 yrs,...,8.2,3.9,7.2,12.7,Pending,Flagged,Rejected,Not applicable,2026-05-01 02:27:23,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9373,NaN,Yogesh Shukla,41,Delhi,9651476851,yogesh.shukla@yahoo.com,Rapido,Suv,Good,High,...,9.7,4.3,4.6,6.8,Distinction,Clear,On hold,Invalid_id,2026-04-03 19:24:37,False
24858,NaN,Vikram Srivastava,54,Lucknow,9673497579,vikram.srivastava@hotmail.com,Rapido,Sedan,Average,3-5 yrs,...,9.7,3.0,4.0,5.2,Distinction,Flagged,Rejected,Low rating history,2026-05-08 12:27:28,False
45298,NaN,Umesh Pandey,70,Kolkata,9024078449,umesh.pandey@hotmail.com,Uber & rapido,Suv,Poor,Fresher,...,4.3,8.8,11.9,8.8,Pass,Clear,Selected,Invalid_id,2026-05-30 22:01:34,False
8244,NaN,Vikram Jha,34,Ahmedabad,9956362740,vikram.jha@yahoo.com,Uber,Bike,Good,5+ yrs,...,8.0,9.9,3.1,6.4,Distinction,Pending,Selected,Invalid_id,2026-07-01 19:44:33,True
44167,NaN,Pankaj Pandey,27,Ahmedabad,+91048503895,pankaj.pandey@yahoo.com,Rapido,Bike,Excellent,1-3 yrs,...,9.1,9.2,4.0,7.0,Pass,Pending,On hold,Invalid_id,2025-05-01 22:11:34,False

In [165]:
#df.to_csv("cleaned_uber_rapido_driver.csv", index=False)

print(df.isna().sum())

driver_id                        0
driver_name                      0
age                              0
city                             0
phone                            0
email                            0
platform                         0
vehicle_type                     0
vehicle_condition                0
experience_level                 0
preferred_shift                  0
reason_for_joining               0
languages_known                  0
overall_driver_rating            0
total_trips_completed            0
trip_completion_rate_%           0
cancellation_rate_%           4516
avg_daily_earnings_INR        2511
total_complaints              4035
total_compliments             3976
peak_hour_availability           0
interview_date                4933
communication_score_10        4584
driving_test_score_10            0
route_knowledge_score_10         0
customer_handling_score_10       0
overall_interview_score_10       0
document_verification            0
background_check_status          0
interview_result                 0
rejection_reason                 0
onboarding_date                  0
is_currently_active              0
dtype: int64

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   driver_id                   49005 non-null  object
 1   driver_name                 50000 non-null  object
 2   age                         50000 non-null  string
 3   city                        50000 non-null  string
 4   phone                       50000 non-null  string
 5   email                       50000 non-null  string
 6   platform                    50000 non-null  string
 7   vehicle_type                50000 non-null  string
 8   vehicle_condition           50000 non-null  string
 9   experience_level            50000 non-null  string
 10  preferred_shift             50000 non-null  string
 11  reason_for_joining          38637 non-null  object
 12  languages_known             47847 non-null  object
 13  overall_driver_rating       46033 non-null  object
 14  total_trips_completed       45930 non-null  float64
 15  trip_completion_rate_%      45565 non-null  float64
 16  cancellation_rate_%         45484 non-null  float64
 17  avg_daily_earnings_INR      47489 non-null  object
 18  total_complaints            45965 non-null  float64
 19  total_compliments           46024 non-null  float64
 20  peak_hour_availability      50000 non-null  object
 21  interview_date              45067 non-null  object
 22  communication_score_10      45416 non-null  float64
 23  driving_test_score_10       50000 non-null  string
 24  route_knowledge_score_10    50000 non-null  string
 25  customer_handling_score_10  50000 non-null  string
 26  overall_interview_score_10  50000 non-null  string
 27  document_verification       50000 non-null  string
 28  background_check_status     50000 non-null  string
 29  interview_result            50000 non-null  string
 30  rejection_reason            50000 non-null  string
 31  onboarding_date             50000 non-null  datetime64[ns]
 32  is_currently_active         50000 non-null  string
dtypes: datetime64[ns](1), float64(6), object(8), string(18)
memory usage: 12.6+ MB

In [82]:
## This converts the data type from object to string.
df['preferred_shift'] = df['preferred_shift'].astype("string")
print(df['preferred_shift'].dtype)

string

In [80]:
df['preferred_shift'] = df['preferred_shift'].str.capitalize()
df['preferred_shift'] = df['preferred_shift'].fillna('Afternoon')
df['preferred_shift'] = df['preferred_shift'].replace({
'Na': 'Evening', 
'Unknown': 'Midweek', 
'None': 'Twice_Weekly', 
'-': 'Weekend',
'Night ': 'Morning',
})

In [89]:
df['preferred_shift'].unique()

<StringArray>
[       'Night',      'Weekend',    'Afternoon',          'Day',
         'Both',      'Morning',      'Midweek', 'Twice_weekly',
      'Evening']
Length: 9, dtype: string

In [92]:
df['driver_id'].unique()

<StringArray>
[       'Night',      'Weekend',    'Afternoon',          'Day',
         'Both',      'Morning',      'Midweek', 'Twice_weekly',
      'Evening']
Length: 9, dtype: string

In [99]:
## This converts the data type from object to string.
df['driver_id'] = df['driver_id'].astype("string")
print(df['driver_id'].dtype)

string

In [94]:
import numpy as np

conversion = df['driver_id']= np.nan
print(conversion)

nan

In [97]:
##This code creates a driver_id for the drivers using their names, where they have no existing emails.

#DRV037476 

import numpy as np

df["driver_id"] = [
    f"DRV{np.random.randint(0, 1000000):06d}"
    for _ in range(len(df))
]
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
25548,DRV367000,Rakesh Kumar,31,Hyderabad,9204446122,rakesh.kumar@hotmail.com,Ola,Sedan,Excellent,4+ yrs,...,9.9,7.8,9.2,8.8,Distinction,Clear,Rejected,Invalid_id,2026-05-30 11:37:53,True
23311,DRV346580,Umesh Mishra,23,Delhi,9221023780,umesh.mishra@hotmail.com,Ola,Bike,Excellent,4+ yrs,...,8.5,7.3,5.3,1.1,Pending,Flagged,Rejected,Invalid_id,2026-01-04 23:58:08,True
37445,DRV308324,Mahesh Jha,43,Chennai,9049122529,mahesh.jha@hotmail.com,Uber & rapido,Sedan,Poor,3-5 yrs,...,4.6,3.4,9.8,6.9,Pass,Flagged,Rejected,Invalid_id,2025-07-15 07:26:04,False
49918,DRV752752,Sunil Sharma,54,Pune,9177046128,sunil.sharma@@yahoo.com,Rapido,Auto,Super,Fresher,...,4.9,4.9,9.4,8.8,Pending,Pending,Selected,Invalid_id,2025-01-10 06:01:53,False
13968,DRV886786,Hitesh Jha,49,Hyderabad,+91531891936,Hitesh Jha@gmail.com,Rapido,Auto,Good,1-3 yrs,...,6.3,7.6,4.1,6.3,Fail,Clear,On hold,Invalid_id,2025-12-13 16:25:18,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26104,DRV974311,RAJESH DUBEY,53 yrs,Pune,9417995483,rajesh.dubey@yahoo.com,Uber,Mini,Super,Fresher,...,8.4,4.2,8.9,6.6,Distinction,Clear,On hold,Invalid_id,2025-04-05 01:37:52,True
35069,DRV926565,SURESH TIWARI,29,Lucknow,+91210750975,suresh.tiwari@yahoo.com,Uber,Bike,Average,Fresher,...,6.0,4.5,1.2,6.1,Fail,Clear,Selected,Invalid_id,2025-05-12 14:01:57,True
30390,DRV704644,Harish Verma,54,Pune,+91024124589,harish.verma@gmail.com,Ola,Auto,Super,5+ yrs,...,7.8,10.0,9.1,8.8,Fail,Flagged,Selected,Invalid_id,2026-07-23 17:19:07,True
3335,DRV089509,SANJAY JHA,46,Ahmedabad,9996734,sanjay.jha@rediffmail.com,Rapido,Bike,Excellent,5+ yrs,...,5.4,12.7,3.3,5.8,Pending,Pending,Selected,Invalid_id,2025-02-09 21:51:35,True
22171,DRV171366,Harish Reddy,36,Delhi,9114883218,harish.reddy@@hotmail.com,Rapido,Sedan,Average,1-3 yrs,...,9.7,8.7,5.6,10.4,Distinction,Pending,On hold,Invalid_id,2025-05-20 01:32:10,False

In [98]:
df['driver_id'].unique()

array(['DRV757058', 'DRV543581', 'DRV719897', ..., 'DRV098833',
       'DRV492381', 'DRV836200'], dtype=object)

In [102]:
## This converts the data type from object to string.
df['reason_for_joining'] = df['reason_for_joining'].astype("string")
print(df['reason_for_joining'].dtype)

string

In [105]:
df['reason_for_joining'] = df['reason_for_joining'].str.capitalize()
df['reason_for_joining'] = df['reason_for_joining'].fillna('Part_Time')
df['reason_for_joining'] = df['reason_for_joining'].replace({
'Na': 'Internship', 
'Unknown': 'Trainer', 
'None': 'Passion', 
'-': 'Passive_Income',
})

In [107]:
df['reason_for_joining'].unique()

<StringArray>
[      'Side hustle',         'Part_time',     'Not disclosed',
      'Extra income', 'Lost previous job',   'Family pressure',
           'Passion',     'Full time job',    'Flexible hours',
           'Trainer',        'Internship',    'Passive_Income']
Length: 12, dtype: string

In [118]:
## This converts the data type from object to string.
df['languages_known'] = df['languages_known'].astype("string")
print(df['languages_known'].dtype)

string

In [122]:
df['languages_known'] = df['languages_known'].str.capitalize()
df['languages_known'] = df['languages_known'].fillna('English, Igbo, Yoruba')

In [125]:
df['languages_known'].unique()

<StringArray>
[      'Hindi, tamil, telugu',    'Kannada, tamil, marathi',
      'Tamil, marathi, hindi', 'Gujarati, kannada, marathi',
              'Hindi, telugu',             'English, tamil',
    'English, tamil, marathi',                      'Hindi',
   'Tamil, gujarati, bengali',                    'Marathi',
 ...
      'English, hindi, tamil',    'Marathi, hindi, bengali',
   'Marathi, gujarati, tamil',   'English, gujarati, tamil',
    'Kannada, hindi, english',   'Gujarati, tamil, marathi',
   'Marathi, gujarati, hindi',  'Kannada, english, bengali',
  'Gujarati, bengali, telugu',   'Gujarati, kannada, hindi']
Length: 405, dtype: string

In [127]:
## This converts the data type from object to string.
df['overall_driver_rating'] = df['overall_driver_rating'].astype("string")
print(df['overall_driver_rating'].dtype)

string

In [128]:
df['overall_driver_rating'] = df['overall_driver_rating'].fillna('7.7')
df['overall_driver_rating'] = df['overall_driver_rating'].str.lstrip('-')
df['overall_driver_rating'] = df['overall_driver_rating'].replace({
#'Na': 'Internship', 
#'Unknown': 'Trainer', 
#'None': 'Passion', 
#'-': 'Passive_Income',
'unrated': '6.9',
})

In [131]:
df['overall_driver_rating'].unique()

<StringArray>
['7.7', '5.8', '4.8', '4.4', '3.1', '4.3', '3.9', '3.3', '4.9', '3.6', '4.6',
 '2.6', '3.2', '6.9', '3.4', '5.6', '3.8', '6.4', '2.9', '5.2', '4.1', '3.5',
 '5.5', '1.7', '4.5', '4.2', '4.0', '3.0', '1.0', '5.7', '4.7', '2.5', '3.7',
 '2.7', '2.8', '6.0', '1.2', '1.6', '1.3', '0.6', '5.3', '6.1', '6.2', '5.0',
 '0.8', '5.9', '0.2', '0.4', '6.5', '5.4', '1.9', '5.1', '1.1', '1.4', '1.5',
 '0.9', '6.3', '0.5', '0.7', '1.8', '0.3', '2.0', '0.1']
Length: 63, dtype: string

In [148]:
## This converts the data type from object to string.
df['total_trips_completed'] = df['total_trips_completed'].astype("string")
print(df['total_trips_completed'].dtype)

string

In [151]:
#df['total_trips_completed'] = df['total_trips_completed'].fillna('7450')
#df['total_trips_completed'] = df['total_trips_completed'].str.lstrip('-')

import numpy as np

df['total_trips_completed'] = np.random.randint(2000, 7001, size=len(df))

In [152]:
df['total_trips_completed'].unique()

array([2527, 4600, 5608, ..., 5744, 3407, 4756])

In [156]:
## This converts the data type from object to string.
df['trip_completion_rate_%'] = df['trip_completion_rate_%'].astype("string")
print(df['trip_completion_rate_%'].dtype)

string

In [164]:
df['trip_completion_rate_%'].unique()

<StringArray>
[ '68.4',  '99.8',  '75.8',  '64.4',  '97.6',  '72.8',  '84.6',  '94.8',
  '74.5',  '63.1',
 ...
  '96.0', '100.7',   '1.2',  '90.0', '102.0',  '80.3',  '75.3',  '97.0',
 '103.0',  '89.3']
Length: 451, dtype: string

In [163]:
df['trip_completion_rate_%'] = df['trip_completion_rate_%'].fillna('74.5')
df['trip_completion_rate_%'] = df['trip_completion_rate_%'].str.lstrip('-')