In [1]:
import pandas as pd

#import matplotlib.pyplot as plt

df = pd.read_csv("uber_rapido_driver_dirty.csv")
df.head(5)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
0,DRV016649,Naresh Chauhan,NaN,Chennai,9255500096,naresh.chauhan@hotmail.com,uber,auto,good,0-1 yr,...,4.3,5.8,7.7,5.3,Fail,NaN,On Hold,NaN,-,false
1,DRV032785,Amit Gupta,45,Ahmedabad,9940345570,amit.gupta@rediffmail.com,Uber,Mini,Excellent,Fresher,...,9.3,NaN,9.0,8.1,NaN,Clear,On Hold,NaN,-,No
2,DRV011323,Yogesh Nair,53,Lucknow,9170487337,NaN,uber,SUV,avg,0-1 yr,...,6.3,9.0,5.5,6.9,NaN,clear,Selected,NaN,19 April 2021,false
3,DRV022168,Manoj Patel,46,Hyderabad,9246425981,manoj.patel@hotmail.com,RAPIDO,Mini,NaN,1-3 yrs,...,8.7,9.6,5.3,7.8,unknown,Clear,Selected,NaN,2021/05/27,0
4,DRV040782,Vikram Chaudhary,25,KOLKATA,9282240,vikram.chaudhary@gmail.com,Uber,suv,GOOD,Fresher,...,12.7,6.5,7.9,6.0,FAIL,clear,Rejected,Low rating history,-,NO

In [2]:
df.describe()

,total_trips_completed,trip_completion_rate_%,cancellation_rate_%,total_complaints,total_compliments,communication_score_10,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10
count,45930.000000,45565.00000,45484.000000,45965.000000,46024.000000,45416.000000,45559.000000,45448.000000,45500.000000,45545.000000
mean,6802.510799,77.89254,22.416584,8809.843120,8942.686272,6.508777,6.946878,6.508619,6.517708,6.613859
std,17638.171153,20.80393,23.708155,28303.698509,28456.710282,2.789817,2.630277,2.794014,2.804085,2.239486
min,-7996.000000,-2.00000,-2.000000,0.000000,0.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000
25%,1704.000000,69.40000,8.100000,14.000000,27.000000,4.600000,5.400000,4.600000,4.600000,5.900000
50%,3909.000000,80.50000,18.100000,27.000000,55.000000,6.600000,7.100000,6.600000,6.600000,6.700000
75%,6086.750000,91.60000,27.900000,41.000000,82.000000,8.500000,8.800000,8.600000,8.600000,7.400000
max,99999.000000,103.00000,103.000000,99999.000000,99999.000000,13.000000,13.000000,13.000000,13.000000,13.000000

In [3]:
df.shape

(50000, 33)

In [4]:
df['email'].unique()

array(['naresh.chauhan@hotmail.com', 'amit.gupta@rediffmail.com', nan,
       ..., 'deepak.srivastavahotmail.com', 'deepak.singhgmail.com',
       'deepak.dubeygmail.com'], dtype=object)

In [5]:
df['email'] = df['email'].astype("string")
print(df['email'].dtype)

string

In [6]:
##This code creates a gmail adrress for the drivers using their names, where they have no existing emails.

df['email'] = df['email'].fillna(
    df['driver_name'] + '@gmail.com'
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
13585,DRV013992,Lokesh Shukla,36,Mumbai,9765392250,lokesh.shukla@gmail.com,Rapido,BIKE,poor,1-3 yrs,...,4.5,7.9,NaN,6.7,FAIL,pending,On Hold,NaN,-,True
43292,DRV046755,Suresh Jha,29,Mumbai,9035831461,suresh.jha@gmail.com,NaN,Mini,Excellent,0-1 yr,...,6.3,8.8,6.1,7.6,NaN,pending,Selected,NaN,26.05.2023,False
30705,DRV021730,Vikram Rao,29 yrs,Ahmedabad,9209680751,vikram.rao@rediffmail,RAPIDO,sedan,good,Fresher,...,5.1,7.5,8.1,6.3,pass,Flagged,Selected,NaN,2021/10/15,no
12778,DRV007478,Vijay Nair,32,Mumbai,9436920756,vijay.nair@gmail.com,Rapido,Bike,Poor,1-3 yrs,...,NaN,NaN,7.9,6.8,pending,Pending,NaN,NaN,NaN,yes
46711,DRV030236,H@rish P@ndey,27,Chennai,+91-9362210357,harish.pandey@hotmail.com,Uber,Mini,GOOD,0-1 yr,...,4.9,3.1,6.5,12.0,FAIL,Pending,Rejected,NaN,NaN,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36280,DRV020208,Naveen Jha,45,Bangalore,9434698101,naveen.jha@yahoo.com,rapido,SUV,NaN,1-3 yrs,...,5.3,9.0,7.8,7.6,NaN,NaN,Selected,NaN,2021/03/04,False
36127,DRV001399,Santosh Srivastava,46,Ahmedabad,9413320602,santosh.srivastava@rediffmail.com,uber,Sedan,Excellent,3-5 yrs,...,7.1,9.3,8.4,8.4,Fail,clear,On Hold,NaN,NaN,False
30567,DRV039083,Sanjay Shukla,52,Bangalore,9687004585,sanjay.shukla@hotmail.com,uber,suv,excellent,0-1 yr,...,6.6,6.7,7.1,5.9,Pending,clear,Selected,NaN,03.07.2021,YES
6548,DRV003402,Ravi Jha,unknown,Pune,95374-33330,ravi.jha@gmail.com,Rapido,Mini,Excellent,Fresher,...,6.2,6.8,7.3,7.5,FAIL,NaN,Selected,NaN,2023-05-07T00:00:00Z,N
27199,DRV001389,Girish Sharma,22,Kolkata,9141208547,girish.sharma@yahoo.com,RAPIDO,sedan,NaN,Fresher,...,9.1,5.1,7.4,7.0,Fail,FLAGGED,NaN,NaN,2021/06/26,1

In [7]:
df.sample(10)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
41911,DRV027909,Ajay Verma,50,Delhi,9415083658,ajay.vermarediffmail.com,Uber,suv,none,0-1 yr,...,NaN,8.6,7.6,7.2,FAIL,Clear,NaN,Poor communication,NaN,0
18267,DRV017583,DEEPAK VERMA,24,Kolkata,9768811508,deepak.verma@@yahoo.com,uber,SUV,Average,0-1 yr,...,9.8,4.3,9.0,8.0,NaN,Pending,NaN,NaN,05/03/21,false
7288,DRV035521,Naresh Nair,39,LUCKNOW,+91-9453426281,naresh.nair@rediffmail.com,UBER,Auto,excellent,0-1 yr,...,NaN,6.0,4.0,5.5,Pass,Flagged,selected,NaN,NaN,Yes
42921,DRV033883,Anil Mishra,51,Delhi,9160973983,anil.mishra@yahoo.com,Uber & Rapido,BIKE,good,3-5 yrs,...,9.4,7.0,6.1,7.8,NaN,NaN,Selected,NaN,31.07.2021,NO
9218,DRV000124,ajay shukla,999,Ahmedabad,NaN,ajay shukla@gmail.com,Uber,BIKE,poor,5+ yrs,...,8.0,9.1,5.8,7.5,pending,pending,Selected,NaN,27.01.2024,False
992,DRV043212,Ajay Nair,30,Jaipur,9135908702,ajay.nair@gmail.com,Uber & Rapido,Auto,Poor,0-1 yr,...,5.7,9.9,7.6,NaN,NaN,clear,Rejected,Incomplete documents,-,NO
27173,DRV045642,Sunil Reddy,30,HYDERABAD,9849077368,sunil.reddy@yahoo.com,Uber & Rapido,BIKE,avg,1-3 yrs,...,NaN,6.4,7.0,6.2,FAIL,Pending,Selected,NaN,March 2021,Y
34727,DRV009053,Deepak Chaudhary,26,Ahmedabad,+91-9577945004,deepak.chaudhary@hotmail.com,RAPIDO,auto,good,1-3 yrs,...,6.6,7.9,3.6,5.6,NaN,NaN,Selected,NaN,NaN,false
16295,DRV042570,Mukesh Singh,54,Jaipur,XXXXXXXXXX,mukesh.singh@rediffmail.com,Uber,Bike,GOOD,0-1 yr,...,NaN,6.9,NaN,-1.6,Pending,Flagged,On Hold,NaN,NaN,NO
6035,DRV014733,Vikr@m Shukl@,52,HYDERABAD,9399206746,vikram.shukla@rediffmail.com,Uber,sedan,na,Fresher,...,NaN,9.6,12.9,NaN,pass,Flagged,Rejected,Not applicable,NaN,true

In [8]:
df['phone'] = pd.to_numeric(df['phone'], errors='coerce') 
## This is to convert the phone collumn from object to numeric

In [9]:
df['phone'] = df['phone'].astype("string")
print(df['phone'].dtype)

string

In [10]:
df['driving_test_score_10'].unique()

array([ 4.3,  9.3,  6.3,  8.7, 12.7,  8.8,  8.1, -1.1, 11.6,  nan,  7.4,
       -0.6,  7.7,  6.2,  4.8,  7.1, 12.5, 11.2, -0.9,  5.5,  8.9,  6.4,
        5.1,  7. , 11. ,  7.6,  5.7, 12.2,  9.1,  7.5,  8.3,  4.6,  4. ,
        7.2,  8. ,  9.7, 10.9,  4.2,  9.5,  4.9,  5.8,  5. ,  6.9,  4.1,
        6.5,  4.5,  9.8,  5.4,  4.4, -1.3,  9.2,  4.7,  7.3, -1.5, 12.4,
        8.6,  8.4, -1.7,  5.3,  6.1,  6. ,  9.6,  7.9,  6.8,  5.2,  5.6,
       10.2, -0.7,  9.4,  9.9,  7.8,  8.2,  6.6,  6.7, 10.5,  9. , 10.8,
        5.9, 12. , 12.1, 11.5,  8.5, 10. , -1. , -0.8, 11.4, 10.3, -0.4,
       -0.5, 10.7, 11.7, 11.8, -0.3, 10.4, 12.8, -1.8, -1.2, -0.2, 11.9,
       -1.4, 10.1, 11.3, 12.3, -1.6, 12.6, -1.9, 10.6, 12.9, 11.1, 13. ,
       -0.1, -2. ])

In [11]:
## This code removes the decimals from the values and make them strings rather than floats. 
df['phone'] = df['phone'].str.replace(r'\.0$', '', regex=True)

In [12]:
## This creates random phone numbers for NaN values in the phone column

import numpy as np

mask = df['phone'].isna()

df.loc[mask, 'phone'] = [
    '+91' + ''.join(np.random.choice(list('0123456789'), 9))
    for _ in range(mask.sum())
]
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
19998,DRV016623,vikram chaudhary,20,Chennai,+91224773898,vikram chaudhary@gmail.com,rapido,SUV,Good,5+ yrs,...,6.7,3.5,5.8,NaN,Pass,pending,On Hold,NaN,-,false
40078,DRV030256,Mukesh Gupta,42 yrs,Lucknow,9481858148,mukesh.gupta@gmail.com,NaN,BIKE,excellent,Fresher,...,9.5,7.9,9.3,8.2,Fail,pending,Selected,NaN,2023-08-20T00:00:00Z,1
46025,DRV013538,Sunil Mishra,28,Lucknow,9586577922,sunil.mishra@rediffmail,rapido,Mini,Good,Fresher,...,5.7,7.0,NaN,6.3,Pass,NaN,Rejected,NaN,NaN,Yes
35094,DRV024751,Ramesh Chaudhary,35,Bangalore,9605602851,ramesh.chaudhary@rediffmail.com,Rapido,NaN,NaN,Fresher,...,7.0,7.3,7.3,6.5,Pending,NaN,NaN,NaN,NaN,No
33183,DRV005693,Yogesh Sharma,47,Chennai,9282784033,yogesh.sharma@@gmail.com,UBER,SUV,excellent,1-3 yrs,...,9.9,8.2,3.1,7.5,NaN,Pending,Rejected,Background check failed,NaN,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41360,DRV014342,Deepak Kumar,55,Ahmedabad,9741982,deepak.kumar@rediffmail.com,UBER,sedan,excellent,3-5 yrs,...,8.4,3.2,4.5,6.1,NaN,Clear,On Hold,NaN,-,NO
37048,DRV003692,Ganesh Verma,24,Lucknow,9371682470,ganesh.verma@yahoo.com,Rapido,suv,good,Fresher,...,5.3,3.6,6.6,4.8,Unknown,Clear,Rejected,Incomplete documents,NaN,no
9637,DRV048916,Pradeep Dubey,33,Chennai,9891088081,pradeep.dubey@@gmail.com,Uber,sedan,NaN,0-1 yr,...,4.5,8.4,7.8,6.7,pass,Pending,On Hold,NaN,NaN,N
39481,DRV024715,Mukesh Chaudhary,54,Ahmedabad,9213022821,mukesh.chaudhary@hotmail.com,NaN,auto,Good,0-1 yr,...,4.2,5.1,5.0,4.7,NaN,NaN,selected,NaN,-,Y
28780,DRV030686,Deepak Singh,22,CHENNAI,9508456643,deepak.singh@rediffmail.com,Rapido,suv,NaN,5+ yrs,...,9.1,7.9,NaN,7.7,NaN,NaN,Selected,NaN,04/05/23,True

In [13]:
df['age'] = df['age'].astype("string")
print(df['age'].dtype)

string

In [14]:
df['age'] = df['age'].fillna('70')

In [15]:
## This code fills the age column where NaN values exist with random values between 1 and 100

import numpy as np

mask = df['age'].isna()

df.loc[mask, 'age'] = np.random.randint(
    1, 101, size=mask.sum()
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
30285,DRV010507,umesh kumar,31,Pune,+91436033846,umesh.kumar@yahoo.com,UBER,Unknown,Good,0-1 yr,...,5.4,NaN,4.1,6.7,pending,unknown,On Hold,NaN,-,false
36313,DRV000197,Pankaj Chauhan,32,Ahmedabad,9054744436,Pankaj Chauhan@gmail.com,Uber,SUV,GOOD,5+ yrs,...,-2.0,NaN,10.2,5.8,Pending,clear,On Hold,NaN,NaN,false
9754,DRV032541,Sanjay Shukla,55,Mumbai,+91121337812,sanjay.shukla@rediffmail.com,Rapido,-,Average,3-5 yrs,...,-0.9,NaN,7.8,7.2,NaN,Clear,Selected,NaN,28.04.2024,No
21383,DRV021604,Anil Dubey,25,Ahmedabad,9033706547,anil.dubey@rediffmail.com,rapido,suv,good,NaN,...,-1.2,9.3,8.4,8.6,pass,NaN,Selected,NaN,July 2022,No
10857,DRV018661,LOKESH NAIR,54,Delhi,+91801330427,lokesh.nair@hotmail.com,Uber & Rapido,Mini,NaN,-,...,7.7,3.7,-1.9,5.9,na,clear,On Hold,NaN,NaN,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7116,DRV014527,Amit Shukla,21,Delhi,9282907432,amit.shukla@rediffmail.com,Rapido,Mini,Good,Fresher,...,7.5,8.2,9.0,NaN,Pass,NaN,NaN,NaN,2023-03-24T00:00:00Z,0
28398,DRV032010,Mahesh Pandey,51,Hyderabad,9631932,mahesh.pandey@hotmail.com,NaN,Unknown,NaN,0-1 yr,...,4.1,-1.1,7.3,4.4,NaN,pending,Rejected,Vehicle age too old,NaN,N
9463,DRV006860,MAHESH SHARMA,47,Bangalore,9809683909,mahesh.sharma@rediffmail.com,UBER,BIKE,poor,0-1 yr,...,7.0,3.1,7.6,6.8,NaN,FLAGGED,Rejected,none,NaN,YES
36409,DRV039940,vikram tripathi,54,Mumbai,+91183171166,vikram tripathi@gmail.com,Uber & Rapido,Auto,NaN,3-5 yrs,...,12.8,9.8,NaN,6.0,Fail,Pending,NaN,Poor communication,NaN,false
4107,DRV004594,Ravi Srivastava,30,Pune,9101103181,ravi.srivastava@yahoo.com,Uber,sedan,GOOD,3-5 yrs,...,9.9,7.4,6.4,7.0,Fail,Clear,Rejected,NaN,01/11/22,true

In [16]:
## This is to remove the negative values and also the yrs in the age column.
df['driving_test_score_10'] = df['driving_test_score_10'].astype("string")
df['driving_test_score_10'] = df['driving_test_score_10'].str.lstrip('-')
#df['age'] = df['age'].str.rstrip('yrs')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
5187,DRV037272,Harish Shukla,31,Pune,+91216791933,harish.shukla@hotmail.com,RAPIDO,auto,avg,3-5 yrs,...,6.2,5.5,10.0,-1.8,Pass,pending,Selected,NaN,20-03-2023,Yes
22185,DRV035480,Umesh Chauhan,54,LUCKNOW,9477730975,umesh.chauhan@gmail.com,NaN,Auto,Average,0-1 yr,...,8.7,4.8,5.1,6.3,pending,NaN,Selected,NaN,17-09-2023,YES
22159,DRV043412,Rajesh Kumar,54 yrs,Mumbai,9692848494,rajesh.kumar@hotmail.com,Uber,SUV,GOOD,1-3 yrs,...,1.8,11.2,3.6,5.0,FAIL,NaN,Selected,NaN,03/09/21,no
12397,DRV048079,Umesh Tiwari,27,Delhi,9281852565,umesh.tiwari@yahoo.com,uber,suv,excellent,3-5 yrs,...,8.3,9.1,9.7,8.2,NaN,NaN,Selected,NaN,07 December 2023,NO
48414,DRV031583,Amit Y@d@v,48,Chennai,9476740788,amit.yadav@hotmail.com,ola,Auto,Average,unknown,...,8.8,7.4,3.3,6.0,Unknown,NaN,Rejected,NaN,2022/03/31,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35326,DRV027284,suresh kumar,-26,Chennai,9653706931,suresh kumar@gmail.com,RAPIDO,Sedan,good,1-3 yrs,...,10.2,5.0,7.6,10.9,NaN,NaN,REJECTED,Incomplete documents,NaN,true
20571,DRV016539,Dinesh Mishra,42,Jaipur,9001001378,dinesh.mishra@rediffmail.com,uber,Auto,Excellent,Fresher,...,7.3,6.5,5.0,6.5,NaN,Clear,Selected,NaN,10-05-2023,N
22542,DRV018487,Vijay Dubey,44,Bangalore,+91916404554,vijay.dubey@hotmail.com,Uber,SUV,NaN,5+ yrs,...,4.7,11.6,-0.6,7.3,NaN,Clear,Selected,NaN,February 2023,YES
21059,DRV048892,HITESH VERMA,24,Jaipur,9735751900,hitesh.verma@yahoo.com,uber,Mini,GOOD,3-5 yrs,...,10.0,9.6,7.2,NaN,Fail,Unknown,On Hold,NaN,NaN,false
49703,DRV031496,Deepak Chaudhary,34,Hyderabad,9635036127,deepak.chaudhary@hotmail.com,Rapido,Auto,Good,1-3 yrs,...,9.4,12.2,5.0,5.8,NaN,FLAGGED,Rejected,Failed driving test,NaN,True

In [17]:
## This is to capitalise the platform column to give it a uniform format and also convert the data type from object to string.

df['platform'] = df['platform'].str.capitalize()
df['platform'] = df['platform'].astype("string")
print(df['platform'].dtype)

string

In [18]:
df['platform'] = df['platform'].fillna('Bolt')

In [19]:
df['customer_handling_score_10'] = df['customer_handling_score_10'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    #'Unknown': 'Experienced',
    #'None': 'Fairly_Experienced',
    #'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Motorcycle',
    #'Na': '1-20 yrs',
    #'-': '10-30 yrs',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    '<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
23919,DRV028571,Santosh Dubey,36,Ahmedabad,9356986226,santosh.dubey@hotmail.com,Rapido,suv,Good,0-1 yr,...,8.8,6.4,11.5,7.1,Pending,pending,Selected,NaN,06/03/21,N
32958,DRV030515,Naresh Patel,43,Delhi,9365977055,naresh.patel@hotmail.com,Rapido,SUV,Excellent,1-3 yrs,...,10.0,3.6,10.3,6.9,pending,Flagged,Rejected,Poor communication,NaN,No
40933,DRV006294,Lokesh Reddy,46,Mumbai,9858804987,lokesh.reddy@rediffmail.com,Uber & rapido,Auto,excellent,1-3 yrs,...,9.9,4.3,7.2,7.1,FAIL,FLAGGED,Selected,NaN,June 2022,true
15680,DRV030589,Lokesh Mishra,999,Pune,9678651739,lokesh.mishra@hotmail,Uber,SUV,excellent,5+ yrs,...,8.1,4.3,3.5,5.0,Pass,pending,NaN,NaN,NaN,N
24696,DRV017962,Harish Dubey,52,Jaipur,9938747915,harish.dubey@gmail.com,Bolt,Bike,NaN,0-1 yr,...,12.4,5.0,9.8,6.9,Pending,Flagged,NaN,Background check failed,NaN,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17551,DRV015528,Pradeep Shukla,47,Ahmedabad,9840192580,pradeep.shukla@gmail.com,Rapido,BIKE,NaN,0-1 yr,...,7.1,4.9,NaN,6.8,pending,FLAGGED,On Hold,NaN,-,No
4357,DRV036084,Bharat Pandey,unknown,Lucknow,9447568653,bharat.pandey@gmail.com,Uber,Auto,Average,5+ yrs,...,1.2,3.5,4.2,4.2,NaN,FLAGGED,Rejected,Poor communication,NaN,True
4696,DRV042727,Naveen Chauhan,32,Jaipur,+91929235784,naveen.chauhan@gmail.com,Uber & rapido,Mini,Average,5+ yrs,...,11.2,9.6,NaN,7.7,FAIL,pending,Selected,NaN,07/04/21,yes
1818,DRV030113,Amit Nair,37,Pune,+91437909196,amit.nair@hotmail.com,Rapido,SUV,-,3-5 yrs,...,<NA>,8.0,9.3,-0.6,pass,Pending,On Hold,NaN,NaN,0
16165,DRV036370,Mahesh Pandey,33,Ahmedabad,9252694209,Mahesh Pandey@gmail.com,Rapido,auto,poor,1-3 yrs,...,8.2,5.5,12.7,NaN,FAIL,NaN,none,Not applicable,NaN,True

In [20]:
## This capitalises the city column to give it a uniform format and also converts the data type from object to string.
df['city'] = df['city'].str.capitalize()
df['city'] = df['city'].astype("string")
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
4375,DRV036681,Deepak Sharma,27,Mumbai,+91644537841,deepak.sharma@hotmail.com,Rapido,Mini,NaN,3-5 yrs,...,8.5,5.5,7.4,6.4,Fail,NaN,Rejected,Not applicable,NaN,Yes
39517,DRV027420,Amit Chaudhary,48,Delhi,9050828622,amit.chaudhary@rediffmail.com,Uber,Sedan,avg,NaN,...,4.4,9.9,-0.9,5.9,pass,NaN,On Hold,NaN,NaN,False
17449,DRV029672,Deepak Singh,26,Lucknow,9741425131,deepak.singh@yahoo.com,Rapido,Sedan,Good,Fresher,...,6.2,NaN,-1.0,6.9,Pass,NaN,On Hold,NaN,-,NO
24069,DRV027602,HARISH YADAV,22,Kolkata,9132537102,harish.yadav@rediffmail.com,Rapido,Sedan,NaN,1-3 yrs,...,5.7,5.5,3.9,4.8,Fail,FLAGGED,Rejected,Incomplete documents,-,1
16801,DRV041114,Naveen Srivastava,35,Jaipur,9062407790,naveen.srivastava@yahoo.com,Bolt,suv,Excellent,3-5 yrs,...,5.8,5.3,11.1,6.6,NaN,pending,Selected,NaN,05-08-2023,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15537,NaN,Pradeep Singh,43,Kolkata,9295045824,pradeep.singh@rediffmail.com,Rapido,Bike,Average,0-1 yr,...,9.9,9.0,7.9,8.3,Pending,clear,Rejected,Incomplete documents,NaN,NO
2157,DRV046580,yogesh tiwari,49,Jaipur,9878514613,yogesh.tiwari@gmail.com,Rapido,BIKE,NaN,3-5 yrs,...,7.3,6.1,3.4,5.2,Pass,FLAGGED,Rejected,Not applicable,NaN,yes
23261,DRV049082,Anil Dubey,44,Kolkata,9383765999,anil.dubey@rediffmail.com,Uber & rapido,Auto,avg,Fresher,...,5.6,3.9,6.3,6.5,pass,FLAGGED,On Hold,NaN,NaN,True
37038,DRV003830,Rajesh Nair,53,Kolkata,+91419924053,rajesh.nair@rediffmail.com,Uber,NaN,poor,Fresher,...,6.3,7.6,9.2,6.7,Fail,FLAGGED,unknown,NaN,NaN,N
36525,NaN,Harish Nair,23,Pune,+91089135005,harish.nair@rediffmail.com,Rapido,Sedan,Poor,5+ yrs,...,9.5,7.9,5.4,7.7,NaN,Pending,Rejected,Poor communication,-,False

In [21]:
df['route_knowledge_score_10'].unique()

array([ 5.8,  nan,  9. ,  9.6,  6.5,  8.6,  8.7,  6.4,  7.9,  7.7,  3.6,
        5.2,  6.8,  8.5,  7.1,  4.6, -1.2,  5. ,  3.2,  3.5,  3.8,  5.6,
        4.9,  8.8, 12. ,  6.7,  6.3,  9.9,  3.4,  9.8, -0.3, 10.7,  9.4,
       12.4,  4.2,  6.2,  3.9, 10. ,  6. ,  9.5,  7.4,  3. , 10.3,  7. ,
       10.2,  6.1,  3.3,  8. ,  4. ,  4.7,  4.5,  7.6,  5.9, -1.3,  4.1,
        5.1,  4.3, 12.2, 11.2,  8.1, 11.9,  5.4, -0.9,  5.5,  6.6,  3.7,
        9.3, 12.8,  8.2, 10.8,  5.3,  9.2, 12.3,  3.1,  7.8,  7.2,  9.1,
        4.8,  7.5,  6.9,  9.7, 12.7,  8.9,  4.4,  7.3, 11. , -0.4, 13. ,
       11.7,  8.4, -1.5, 11.5, 12.9, 10.5,  5.7, -1.1, -1.4, 10.1,  8.3,
       -0.7, 10.4, -0.8, -1.9, 12.1, -2. , -0.2, 10.9, -1.8, 11.1, -1. ,
       11.8, 11.3, 11.4, -0.5, 12.5, -1.7, -1.6, -0.1, 10.6, 12.6, -0.6,
       11.6])

In [22]:
## This converts the data type from object to string.
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].astype("string")
print(df['route_knowledge_score_10'].dtype)

string

In [23]:
## This is to remove the negative values and also the yrs in the age column.
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].str.lstrip('-')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
29957,DRV011290,Sunil Reddy,50,Chennai,9227953352,sunil.reddy@yahoo.com,Uber,Mini,excellent,Fresher,...,11.8,9.2,9.0,7.8,Pending,pending,Selected,NaN,09 March 2022,No
27225,DRV047001,Ravi Dubey,34,Ahmedabad,+91207459855,ravi.dubey@rediffmail.com,Rapido,auto,NaN,Fresher,...,9.5,6.4,12.2,7.9,pending,NaN,Selected,NaN,2022/08/26,true
18620,DRV034810,Rakesh Verma,42,Pune,9136817402,rakesh.verma@rediffmail.com,Uber,Auto,good,Fresher,...,8.3,7.8,10.5,7.6,Fail,NaN,On Hold,NaN,NaN,YES
7496,DRV014280,Mukesh Nair,38,Mumbai,9405659,mukesh.nairrediffmail.com,Uber,Auto,-,NaN,...,1.8,9.4,4.6,NaN,NaN,NaN,On Hold,NaN,08.04.2021,false
45611,DRV004045,Ramesh Chauhan,22,Lucknow,9963303262,ramesh.chauhan@gmail.com,Uber,sedan,Average,3-5 yrs,...,6.5,6.1,6.6,6.6,NaN,NaN,Selected,NaN,2022/10/01,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22824,DRV019015,Pr@deep Ch@uh@n,41,Delhi,+91550899797,pradeep.chauhan@yahoo.com,Uber,auto,Poor,3-5 yrs,...,8.5,5.9,9.8,6.9,FAIL,clear,Selected,NaN,2022-03-04T00:00:00Z,False
38759,DRV029680,bharat shukla,24 yrs,Jaipur,9772424234,bharat.shukla@gmail,Uber,Mini,NaN,-,...,12.0,6.8,6.7,5.8,Fail,NaN,On Hold,NaN,NaN,True
16307,DRV006431,Manoj Dubey,51,Ahmedabad,+91153454448,manoj.dubey@rediffmail.com,Rapido,suv,Average,Fresher,...,9.0,10.0,9.7,8.2,-,NaN,Rejected,Background check failed,NaN,Yes
1993,DRV027251,ramesh pandey,999,Delhi,+91387557310,ramesh.pandey@hotmail.com,Uber,NaN,poor,3-5 yrs,...,7.5,6.6,5.7,7.4,Fail,clear,on hold,NaN,26 July 2021,false
27192,DRV014981,S@nj@y Y@d@v,44,Mumabi,9077801105,sanjay.yadav@hotmail.com,Bolt,Mini,avg,3-5 yrs,...,8.6,12.5,9.8,8.8,Fail,FLAGGED,Selected,NaN,09.12.2022,NO

In [24]:
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].fillna('7.5')

In [25]:
## This code fills the age column where NaN values exist with random values between 0 and 10

import numpy as np

mask = df['customer_handling_score_10'] == 6

df.loc[mask, 'customer_handling_score_10'] = np.random.randint(
    0, 10, size=mask.sum()
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
5068,DRV001976,Suresh Tiwari,32,Pune,+91863076353,suresh.tiwari@@gmail.com,Rapido,unknown,NaN,Fresher,...,4.1,6.4,7.3,6.3,Fail,Clear,Unknown,NaN,NaN,N
31644,DRV017186,R@jesh Singh,70,Pune,9064834743,rajesh.singh@rediffmail.com,Uber,Bike,poor,0-1 yr,...,7.1,4.4,6.1,5.8,none,none,Rejected,Not applicable,NaN,0
8955,DRV028235,Vikram Rao,32,Delhi,9289169153,vikram.rao@gmail.com,Rapido,BIKE,NaN,Fresher,...,4.0,7.5,6.5,6.9,pass,FLAGGED,Selected,NaN,2023-01-18T00:00:00Z,1
1997,DRV047437,mukesh singh,46,Pune,9413896636,mukesh.singh@rediffmail.com,Uber,Mini,NaN,Fresher,...,5.1,0.2,NaN,6.5,Pending,FLAGGED,Rejected,NaN,NaN,yes
38362,DRV007979,vijay yadav,39,Mumbai,9082211,vijay.yadav@yahoo.com,Uber,sedan,Poor,3-5 yrs,...,0.4,9.7,9.1,7.2,FAIL,Clear,Rejected,Not applicable,NaN,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16812,DRV004844,Umesh Chaudhary,38,Ahmedabad,9410118746,umesh.chaudhary@yahoo.com,Uber & rapido,auto,NaN,3-5 yrs,...,9.9,10.0,9.8,9.0,Fail,Clear,On Hold,NaN,NaN,no
29770,DRV006885,Anil Singh,43,Hyderabad,9302491333,anil.singh@gmail.com,Rapido,Auto,good,Fresher,...,11.8,8.4,3.8,7.1,Fail,clear,Selected,NaN,18 March 2023,yes
3264,DRV036533,Sunil Reddy,52,Lucknow,9763337241,sunil.reddy@gmail.com,Uber,Mini,GOOD,1-3 yrs,...,1.0,7.5,7.0,6.0,unknown,Flagged,On Hold,NaN,NaN,yes
11198,DRV022075,Naveen Yadav,28,Bangalore,9057801460,naveen.yadav@rediffmail.com,Rapido,suv,excellent,3-5 yrs,...,5.8,5.7,8.4,7.4,Fail,pending,Selected,NaN,2022/01/31,True
11418,DRV049221,Yogesh Srivastava,42,Bangalroe,9911256748,yogesh.srivastava@gmail.com,Uber,auto,excellent,Fresher,...,5.2,11.3,3.5,5.8,NaN,pending,on hold,Failed driving test,NaN,false

In [26]:
df['vehicle_type'].unique()

array(['auto', 'Mini ', 'SUV', 'Mini', 'suv', 'BIKE', 'Bike', 'Auto',
       'Sedan', 'unknown', nan, 'sedan', 'none', 'na', '-', 'Unknown'],
      dtype=object)

In [27]:
## This converts the data type from object to string.
df['vehicle_type'] = df['vehicle_type'].astype("string")
print(df['vehicle_type'].dtype)

string

In [28]:
df['vehicle_type'] = df['vehicle_type'].str.capitalize()
df['vehicle_type'] = df['vehicle_type'].fillna('Motorbike')
df['vehicle_type'] = df['vehicle_type'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    #'Unknown': 'Experienced',
    'None': 'Bicycle',
    #'Avg': 'Average',
    #'poor': 'Super',
    'Unknown': 'Tricycle',
    'Na': 'Catapiller',
    '-': 'Truck',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
302,DRV017002,Ravi Srivastava,30,Hyderabad,9339817025,Ravi Srivastava@gmail.com,Rapido,Bike,NaN,1-3 yrs,...,<NA>,6.7,4.7,7.0,FAIL,none,REJECTED,NaN,November 2022,true
40325,DRV034830,Sunil Tiwari,48,Hyderabad,9680363128,sunil.tiwari@yahoo.com,Uber,Sedan,Poor,0-1 yr,...,7.4,7.5,3.4,5.1,Fail,Flagged,Rejected,Vehicle age too old,-,No
45926,DRV002792,Umesh Dubey,43,Chennai,9866673606,umesh.dubey@gmail,Uber,Mini,Average,0-1 yr,...,0.2,5.4,12.2,-1.5,NaN,Pending,Rejected,NaN,NaN,True
4047,DRV007853,Ravi Chauhan,53,Pune,+91482391455,ravi.chauhan@gmail.com,Uber,Mini,Unknown,none,...,6.9,5.1,4.4,4.9,Pass,FLAGGED,Rejected,Failed driving test,NaN,false
26672,DRV007112,Hitesh Reddy,41,Pune,9859494533,hitesh.reddy@yahoo.com,Rapido,Tricycle,Average,0-1 yr,...,8.7,9.6,9.7,9.2,NaN,Pending,Selected,NaN,January 2024,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31564,DRV032702,Vijay Tripathi,23,Chennai,9043116808,vijay.tripathi@yahoo.com,Uber,Mini,poor,0-1 yr,...,5.6,7.6,-0.2,6.8,pass,pending,On Hold,NaN,NaN,Y
7062,DRV016772,Pankaj Tiwari,29,Chennai,9982978964,pankaj.tiwari@hotmail.com,Uber,Auto,NaN,Fresher,...,4.4,5.4,9.9,6.8,NaN,pending,on hold,Incomplete documents,NaN,YES
38534,DRV000649,Girish Pandey,54,Mumbai,9165568980,girish.pandey@@yahoo.com,Rapido,Mini,poor,1-3 yrs,...,<NA>,7.7,6.3,6.9,FAIL,FLAGGED,NaN,NaN,NaN,Y
41368,DRV047953,rajesh shukla,70,Bangalore,9704979055,rajesh.shukla@yahoo.com,Uber,Mini,Excellent,1-3 yrs,...,6.2,8.6,NaN,-0.3,Pending,NaN,Rejected,NaN,21 May 2021,0
5390,DRV025988,Ramesh Verma,47,Delhi,+91842727084,Ramesh Verma@gmail.com,Uber,Tricycle,Excellent,Fresher,...,5.6,3.5,4.7,5.3,Pass,Clear,on hold,NaN,NaN,no

In [29]:
df['vehicle_condition'].unique()

array(['good', 'Excellent', 'avg', nan, 'GOOD', 'excellent', 'Average',
       'Poor', 'poor', 'Good', 'unknown', '-', 'Unknown', 'na', 'none'],
      dtype=object)

In [30]:
## This converts the data type from object to string.
df['vehicle_condition'] = df['vehicle_condition'].astype("string")
print(df['vehicle_condition'].dtype)

string

In [31]:
df['vehicle_condition'] = df['vehicle_condition'].str.capitalize()
df['vehicle_condition'] = df['vehicle_condition'].fillna('Super')
df['vehicle_condition'] = df['vehicle_condition'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    'Unknown': 'Great',
    'None': 'Beautiful',
    'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Tricycle',
    'Na': 'Fair',
    '-': 'Wonderful',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
34200,DRV027769,Santosh Rao,51,Delhi,9570149010,santosh.rao@yahoo.com,Rapido,Motorbike,Excellent,3-5 yrs,...,7.5,7.0,9.9,8.5,Pass,Pending,Selected,NaN,06/17/21,False
26364,DRV017061,SURESH CHAUDHARY,35,Delhi,9318510683,suresh.chaudhary@rediffmail.com,Uber & rapido,Bike,Average,1-3 yrs,...,8.9,3.6,9.9,7.7,NaN,FLAGGED,NaN,NaN,07/12/22,Yes
3387,DRV005220,Girish Reddy,25,Mumbai,9352467,girish.reddy@rediffmail.com,Rapido,Auto,Super,0-1 yr,...,4.4,7.5,4.2,3.8,NaN,pending,Rejected,Failed driving test,NaN,YES
21003,DRV005528,Yogesh Shukla,41,Pune,+91295948939,yogesh.shukla@rediffmail.com,Rapido,Suv,Super,-,...,7.3,1.9,7.6,6.8,pass,clear,Rejected,NaN,NaN,false
17566,DRV000592,deepak sharma,23,Lucknow,9394136880,deepak.sharma@rediffmail.com,Rapido,Suv,Super,Fresher,...,6.4,7.5,-0.2,7.4,Pass,clear,Selected,NaN,23-05-2023,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14724,DRV046771,GANESH GUPTA,70,Bangalroe,9136473335,ganesh.gupta@rediffmail.com,Unknown,Auto,Average,3-5 yrs,...,8.1,4.9,NaN,8.1,Pass,NaN,on hold,NaN,06 September 2022,No
39485,DRV014483,Pradeep Rao,40,Pune,9123253910,pradeep.rao@gmail.com,Uber,Sedan,Super,unknown,...,7.6,7.7,3.6,7.1,Pass,clear,selected,none,NaN,Yes
49170,DRV035716,Ajay Tripathi,20,Mumbai,+91374199905,ajay.tripathi@yahoo.com,Uber,Mini,Good,1-3 yrs,...,10.1,8.2,5.9,8.2,FAIL,NaN,Selected,NaN,2021/12/07,False
14394,DRV041814,Yogesh Kumar,21,Mumbai,9969605293,yogesh.kumar@yahoo.com,Uber,Suv,Good,Fresher,...,6.5,11.6,5.2,6.6,pending,pending,selected,NaN,09/09/21,N
37304,DRV040817,Umesh Patel,50,Chennai,+91097290919,umesh.patel@gmail.com,Rapido,Bike,Super,3-5 yrs,...,8.4,10.4,7.0,5.9,Pass,NaN,On Hold,NaN,NaN,Y

In [32]:
df['experience_level'].unique()

array(['0-1 yr', 'Fresher', '1-3 yrs', '5+ yrs', '3-5 yrs', nan,
       'unknown', 'na', 'Unknown', '-', 'none'], dtype=object)

In [33]:
## This converts the data type from object to string.
df['experience_level'] = df['experience_level'].astype("string")
print(df['experience_level'].dtype)

string

In [34]:
df['experience_level'] = df['experience_level'].str.capitalize()
df['experience_level'] = df['experience_level'].fillna('High')
df['experience_level'] = df['experience_level'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    '0-1 yr' : '4+ yrs',
    'Unknown': '7+ yrs',
    'None': '8+ yrs',
    #'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Tricycle',
    'Na': '6 yrs',
    '-': '8 yrs',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
26012,DRV046433,Vijay Mishra,21,Ahmedabad,9508759,vijay.mishra@yahoo.com,Ola,Mini,Super,1-3 yrs,...,11.7,5.9,8.0,7.9,pass,clear,Selected,NaN,15-09-2023,Yes
12147,DRV019191,Rajesh Tiwari,51,Kolkata,+91921353459,Rajesh Tiwari@gmail.com,Uber,Suv,Poor,4+ yrs,...,9.1,3.4,7.8,6.1,NaN,Pending,Selected,NaN,2023/04/24,Y
28984,DRV001192,ganesh nair,37,Delhi,9720157995,ganesh.nair@yahoo.com,Rapido,Mini,Average,3-5 yrs,...,8.5,6.3,NaN,6.6,Pending,Flagged,On Hold,NaN,-,True
2303,DRV043716,Naresh Chaudhary,70,Kolkata,9194797642,naresh.chaudhary@hotmail.com,Uber,Bike,Excellent,3-5 yrs,...,6.2,4.1,6.1,6.5,NaN,FLAGGED,Selected,NaN,22-03-2023,1
27171,DRV022265,Harish Srivastava,43,Jaipur,9788675584,harish.srivastava@hotmail.com,Uber & rapido,Mini,Good,Fresher,...,6.6,0.8,8.3,NaN,Pending,Clear,Selected,NaN,NaN,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25896,DRV014371,LOKESH NAIR,42,Ahmedabad,9035964331,lokesh.nair@yahoo,Uber,Auto,Excellent,1-3 yrs,...,6.4,7.8,9.8,7.2,Fail,NaN,Rejected,NaN,13.08.2021,1
22637,DRV014195,Ramesh Yadav,51,Mumbai,9152499570,ramesh.yadav@gmail.com,Ola,Tricycle,Excellent,5+ yrs,...,5.1,8.9,8.6,8.2,Pass,Pending,Selected,NaN,October 2021,Yes
25083,DRV006205,Sanjay Shukla,70,Hyderabad,9598296863,sanjay.shukla@@yahoo.com,Ola,Bike,Super,4+ yrs,...,5.5,8.6,12.5,10.4,Fail,clear,on hold,NaN,NaN,true
31869,DRV000560,Naresh Kumar,999,Pune,+91616645899,naresh.kumar@rediffmail.com,Uber,Bike,Excellent,3-5 yrs,...,1.9,8.9,6.1,6.6,Unknown,NaN,On Hold,NaN,NaN,0
8096,DRV024587,Naresh Shukla,34,Ahmedabad,9663170,naresh.shukla@hotmail.com,Rapido,Auto,Average,5+ yrs,...,4.1,9.1,3.1,NaN,pending,clear,NaN,NaN,2021/07/19,N

In [35]:
df['driving_test_score_10'].unique()

<StringArray>
[ '4.3',  '9.3',  '6.3',  '8.7', '12.7',  '8.8',  '8.1',  '1.1', '11.6',
   <NA>,
 ...
 '12.3',  '1.6', '12.6',  '1.9', '10.6', '12.9', '11.1', '13.0',  '0.1',
  '2.0']
Length: 112, dtype: string

In [36]:
## This converts the data type from object to string.
df['driving_test_score_10'] = df['driving_test_score_10'].astype("string")
print(df['driving_test_score_10'].dtype)

string

In [37]:
df['driving_test_score_10'] = df['driving_test_score_10'].fillna('7.5')

In [38]:
df['route_knowledge_score_10'].unique()

<StringArray>
[ '5.8',  '7.5',  '9.0',  '9.6',  '6.5',  '8.6',  '8.7',  '6.4',  '7.9',
  '7.7',
 ...
 '11.4',  '0.5', '12.5',  '1.7',  '1.6',  '0.1', '10.6', '12.6',  '0.6',
 '11.6']
Length: 121, dtype: string

In [39]:
df['customer_handling_score_10'].unique()

array([ 7.7,  9. ,  5.5,  5.3,  7.9, 10.5,  9.7,  nan, 10.7,  5.9,  6.2,
        4.9,  6.7,  6.9,  6.8,  8.5, 12.3,  3.5,  5. ,  4.1,  3. , 11.2,
        8.9,  7.6,  6.5,  3.6, 10.6,  4.3,  3.8,  3.2,  7.5,  4.6,  5.7,
        3.7, -0.9,  4.7,  4.2, -1.6,  8.8, -0.6,  6.4,  6.3,  9.8,  7. ,
        9.5,  8.3,  3.1,  9.4,  6.6,  9.1, 11.4,  7.3,  7.4, 11.5,  8.6,
        9.6,  7.2,  3.3,  8.1,  3.4,  4.4,  4. ,  8.4,  8. ,  5.1,  5.2,
       -1.9,  5.4,  4.5, 12. ,  6.1,  7.1, 11.1, 10. ,  5.6, -1.3, 12.8,
       -1.2,  8.7,  3.9, 11.6,  9.2, -1.8,  7.8,  9.9,  9.3, 11.3, 11. ,
       12.6, 12.1,  8.2, 12.5, -1.7,  5.8,  2. , -0.2, 12.4, 11.7, -0.7,
       12.9, 10.3, 12.2, 10.8,  4.8, 10.9, -1.5, 11.9, 11.8, -1.1, -0.8,
       -2. , 10.4, -0.3, -0.4, -0.5,  1. , -0.1, -1. , 10.2, 13. , 12.7,
       -1.4, 10.1,  0. ,  6. ])

In [40]:
## This converts the data type from object to string.
df['customer_handling_score_10'] = df['customer_handling_score_10'].astype("string")
print(df['customer_handling_score_10'].dtype)

string

In [41]:
df['customer_handling_score_10'] = df['customer_handling_score_10'].fillna('8.5')
df['customer_handling_score_10'] = df['customer_handling_score_10'].str.lstrip('-')

In [42]:
df['overall_interview_score_10'].unique()

array([ 5.3,  8.1,  6.9,  7.8,  6. , -1.4,  8.2,  8.3,  6.7,  5.8,  7.7,
        nan,  7.6,  6.5,  7.5,  4.1,  6.2, -1.6,  6.4,  7.2,  7.4,  3.6,
        6.3,  6.1,  5.2, -1.3,  5.6,  5.7,  5. ,  5.5,  6.8,  6.6, 10.7,
        7.3, 11.6,  4.2, 10.6, 10.5,  7.1, 12.6, -1. ,  7. ,  4.8, 11.1,
       11.9, 10.3,  4.9,  5.1,  4.5,  5.9,  8. , 12.4, 11.5, 12.9,  4.6,
        5.4,  7.9, -2. , 13. ,  9.7, 10.1, -1.8, -1.9, 11.7,  8.6, -1.5,
        8.4, 11.8, 11. ,  9.2,  8.5, 12.3, 12.5, 12.8, 12. , 11.4,  4.7,
        4.4, -1.7, -0.8, -0.7, -0.3,  8.7,  9.1,  4.3, 12.1,  8.8, -0.4,
       12.7, -0.2, 11.2, 10.8,  8.9, 12.2, 10.9, -1.2, 10.2, -0.6, 11.3,
        4. , -1.1, -0.5, 10.4,  9. ,  9.4,  3.9, -0.9,  3.8, -0.1,  9.3,
        9.6,  3.7,  9.5,  3.5,  9.8,  3.4])

In [43]:
## This converts the data type from object to string.
df['overall_interview_score_10'] = df['overall_interview_score_10'].astype("string")
print(df['overall_interview_score_10'].dtype)

string

In [44]:
df['overall_interview_score_10'] = df['overall_interview_score_10'].fillna('8.8')
df['overall_interview_score_10'] = df['overall_interview_score_10'].str.lstrip('-')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
32304,DRV035491,Anil Srivastava,23,Hyderabad,9728508667,anil.srivastava@hotmail.com,Ola,Sedan,Average,5+ yrs,...,5.4,11.1,6.7,7.0,Fail,pending,Selected,NaN,19.07.2023,N
27739,DRV016722,Pradeep Tiwari,38,Kolkata,9512020986,pradeep.tiwari@gmail.com,Rapido,Bike,Poor,Fresher,...,4.6,6.2,8.8,6.6,FAIL,Pending,NaN,Unknown,November 2023,1
5528,DRV005461,Girish Rao,46,Chennai,+91871729720,Girish Rao@gmail.com,Uber,Bike,Good,5+ yrs,...,1.7,6.1,4.8,5.7,Pending,Pending,On Hold,NaN,NaN,Y
17496,DRV001817,Manoj Jha,70,Kolkata,9394539469,manoj.jha@gmail.com,None,Auto,Excellent,5+ yrs,...,4.7,7.5,9.3,6.6,NaN,FLAGGED,Rejected,Not applicable,NaN,true
10094,DRV030314,Ajay Yadav,40,Hyderabad,9710095463,ajay.yadav@yahoo.com,Rapido,Suv,Excellent,4+ yrs,...,7.5,7.5,8.5,8.8,FAIL,NaN,Rejected,Poor communication,NaN,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1599,DRV016925,mukesh rao,54,Mumbai,9085219735,mukesh rao@gmail.com,Rapido,Auto,Super,1-3 yrs,...,12.3,7.4,11.1,7.4,FAIL,NaN,Selected,NaN,2024/02/24,yes
48766,DRV030869,Naresh Shukla,28,Mumbai,+91165591361,naresh.shukla@gmail.com,Uber & rapido,Auto,Poor,5+ yrs,...,7.2,8.5,9.0,7.5,pass,Flagged,Selected,NaN,NaN,NO
9659,DRV034804,Ramesh Pandey,41,Ahmedabad,9428517989,ramesh.pandey@gmail.com,Rapido,Suv,Excellent,3-5 yrs,...,7.5,4.6,8.6,8.8,Fail,FLAGGED,Rejected,Poor communication,-,Y
40531,DRV030405,SANTOSH KUMAR,22,Pune,9326694021,santosh.kumar@rediffmail.com,Uber,Mini,Excellent,4+ yrs,...,1.6,7.6,4.9,8.8,FAIL,Flagged,Rejected,Incomplete documents,-,false
21163,DRV017402,Deepak Verma,29,Delhi,+91445650309,deepak.verma@rediffmail.com,Na,Suv,Super,3-5 yrs,...,5.5,6.2,8.5,7.3,NaN,Clear,Rejected,NaN,-,True

In [45]:
df['document_verification'].unique()

array(['Fail', nan, 'unknown', 'FAIL', 'Pass', 'Pending', 'pass',
       'pending', 'none', 'Unknown', '-', 'na'], dtype=object)

In [46]:
## This converts the data type from object to string.
df['document_verification'] = df['document_verification'].astype("string")
print(df['document_verification'].dtype)

string

In [47]:
df['document_verification'] = df['document_verification'].str.capitalize()
df['document_verification'] = df['document_verification'].fillna('Distinction')
df['document_verification'] = df['document_verification'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999': '90',
    #'0-1 yr' : '4+ yrs',
    #'Unknown':'High',
    'None':'Credit',    
    #'Avg': 'Average',
    #'poor': 'Super',
    'Unknown':'Average',
    'Na': 'Fair',
    '-': 'Exceptional',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
5263,DRV009294,Bharat Sharma,-39,Lucknow,9336579983,bharat.sharma@yahoo.com,None,Auto,Good,4+ yrs,...,7.5,7.5,7.3,6.1,Fail,NaN,On Hold,NaN,NaN,No
24535,DRV041937,Santosh Mishra,48,Jaipur,+91878504822,santosh.mishra@rediffmail.com,Uber,Bike,Poor,4+ yrs,...,8.1,6.5,6.2,6.1,Fail,pending,Waitlist,NaN,-,NO
10897,DRV022942,Sunil Kumar,34,Chennai,9565487943,sunil.kumar@gmail.com,Unknown,Mini,Good,3-5 yrs,...,7.2,5.1,7.8,6.3,Distinction,Clear,On Hold,NaN,NaN,1
11500,DRV003422,Ajay Mishra,20,Delhi,+91537516830,ajay.mishra@rediffmail.com,Uber,Auto,Poor,4+ yrs,...,8.6,4.8,4.4,5.8,Pass,NaN,Rejected,Background check failed,NaN,no
29360,DRV008300,Vijay Chaudhary,20,Delhi,9140119351,vijay.chaudhary@gmail.com,Uber,Mini,Good,1-3 yrs,...,6.4,3.7,3.1,8.8,Pass,Clear,Rejected,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19319,DRV003509,Mahesh Dubey,40,Hyderabad,9354394478,mahesh.dubeyhotmail.com,Bolt,Sedan,Excellent,4+ yrs,...,6.9,3.4,8.2,7.0,Pass,Pending,On Hold,NaN,NaN,no
24222,DRV018967,Mukesh Pandey,70,Kolkata,9368055,mukesh.pandey@yahoo.com,Rapido,Auto,Super,1-3 yrs,...,9.8,9.8,10.5,7.3,Pass,FLAGGED,On Hold,NaN,NaN,no
2233,DRV042687,Girish Kumar,28 yrs,Pune,9557975293,girish.kumar@@gmail.com,Rapido,Suv,Poor,Fresher,...,8.5,9.2,9.4,8.8,Distinction,NaN,Rejected,Low rating history,NaN,yes
27634,DRV012069,Naresh Shukla,38,Jaipur,9622323197,Naresh Shukla@gmail.com,Rapido,Mini,Average,1-3 yrs,...,7.5,8.4,9.8,8.4,Distinction,Flagged,on hold,NaN,-,False
25951,DRV003316,Harish Tripathi,38,Kolkata,+91023059961,Harish Tripathi@gmail.com,Rapido,Mini,Good,4+ yrs,...,12.2,7.5,12.3,7.2,Pass,NaN,Selected,NaN,May 2024,YES

In [48]:
df['document_verification'].unique()

<StringArray>
[       'Fail', 'Distinction',     'Average',        'Pass',     'Pending',
      'Credit', 'Exceptional',        'Fair']
Length: 8, dtype: string

In [49]:
df['background_check_status'].unique()

array([nan, 'Clear', 'clear', 'pending', 'Flagged', 'FLAGGED', 'Pending',
       'na', 'unknown', 'none', '-', 'Unknown'], dtype=object)

In [50]:
## This converts the data type from object to string.
df['background_check_status'] = df['background_check_status'].astype("string")
print(df['background_check_status'].dtype)

string

In [51]:
df['background_check_status'] = df['background_check_status'].str.capitalize()
df['background_check_status'] = df['background_check_status'].fillna('Clear')
df['background_check_status'] = df['background_check_status'].replace({
'Na': 'Clear', 
'Unknown': 'Clear', 
'None': 'Pending', 
'-': 'Clear'
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
29615,DRV018627,Amit Srivastava,45,Hyderabad,9182995803,amit.srivastava@rediffmail.com,Uber,Sedan,Good,5+ yrs,...,0.2,7.3,9.1,7.3,Fail,Pending,Rejected,Low rating history,NaN,NO
21765,DRV012708,Hitesh Gupta,40,Lucknow,+91676839242,hitesh.gupta@yahoo.com,Uber & rapido,Mini,Poor,Fresher,...,6.0,11.6,8.5,7.1,Distinction,Flagged,Rejected,Background check failed,-,NO
46731,DRV026803,Vijay Sharma,52,Kolkata,9813761,Vijay Sharma@gmail.com,Rapido,Sedan,Poor,Fresher,...,7.5,8.5,9.9,1.3,Pass,Clear,Rejected,Poor communication,NaN,Y
4141,DRV026911,R@mesh Shukl@,49,Delhi,9228433447,ramesh.shukla@yahoo.com,Uber,Mini,Average,3-5 yrs,...,4.8,5.8,8.5,4.8,Fail,Pending,Rejected,Low rating history,-,1
18305,DRV033884,Girish Dubey,-36,Delhi,9220749186,girish.dubey@yahoo.com,Uber,Auto,Super,5+ yrs,...,8.4,8.9,6.6,7.6,Fail,Flagged,Selected,NaN,2023/01/02,true
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16968,DRV022827,Anil Verma,51,Kolkata,9058542281,anil.verma@rediffmail.com,Uber,Tricycle,Super,3-5 yrs,...,7.5,8.3,7.3,10.2,Distinction,Flagged,Rejected,NaN,NaN,false
23083,DRV037274,vijay chauhan,26,Jaipur,+91681279708,vijay.chauhan@rediffmail.com,Rapido,Suv,Super,5+ yrs,...,9.5,7.8,7.8,7.8,Fail,Flagged,On Hold,NaN,NaN,0
43835,DRV036828,Pankaj Gupta,70,Jaipur,+91888295098,pankaj.gupta@gmail.com,Rapido,Bike,Average,4+ yrs,...,6.6,9.6,8.4,8.8,Pass,Clear,NaN,-,NaN,true
35677,DRV037673,Pankaj Shukla,43,Mumbai,9755515444,pankaj.shukla@gmail,Uber & rapido,Auto,Good,4+ yrs,...,8.6,8.0,4.3,11.6,Pass,Clear,Rejected,NaN,NaN,NO
8683,DRV028752,Sanjay Verma,42,Ahmedabad,9865105994,sanjay.vermahotmail.com,Rapido,Suv,Good,4+ yrs,...,4.1,6.6,6.2,8.8,Distinction,Clear,Rejected,Not applicable,-,No

In [52]:
df['background_check_status'].unique()

<StringArray>
['Clear', 'Pending', 'Flagged']
Length: 3, dtype: string

In [53]:
df['interview_result'].unique()

array(['On Hold', 'Selected', 'Rejected', 'Waitlist', nan, 'selected',
       'REJECTED', 'Unknown', 'on hold', 'none', '-', 'unknown', 'na'],
      dtype=object)

In [54]:
## This converts the data type from object to string.
df['interview_result'] = df['interview_result'].astype("string")
print(df['interview_result'].dtype)

string

In [55]:
df['interview_result'] = df['interview_result'].str.capitalize()
df['interview_result'] = df['interview_result'].fillna('Selected')
df['interview_result'] = df['interview_result'].replace({
'Na': 'Selected', 
'Unknown': 'Selected', 
'None': 'Pending', 
'-': 'Pending'
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
22773,DRV041193,Aj@y R@o,49,Chennai,9891078471,ajay.rao@gmail.com,Uber,Suv,Beautiful,High,...,9.6,5.5,3.1,6.6,Distinction,Clear,Pending,NaN,2022/07/19,Y
47687,DRV044093,dinesh pandey,44,Ahmedabad,+91131716994,dinesh.pandeyhotmail.com,Rapido,Auto,Poor,4+ yrs,...,0.9,8.2,3.6,5.0,Pass,Clear,On hold,NaN,NaN,1
4027,DRV007301,vijay rao,34 yrs,Pune,9658075398,vijay rao@gmail.com,Rapido,Suv,Poor,Fresher,...,4.5,4.1,8.5,5.0,Pass,Clear,Rejected,NaN,NaN,True
12560,DRV012550,Mahesh Chaudhary,27,Ahmedabad,+91317498714,mahesh.chaudharyyahoo.com,Ola,Mini,Good,3-5 yrs,...,5.4,5.4,5.7,5.0,Pending,Pending,Rejected,Background check failed,NaN,Y
16682,DRV006154,Lokesh Kumar,45,Delhi,9535319777,lokesh.kumar@rediffmail.com,Uber & rapido,Motorbike,Good,1-3 yrs,...,6.4,7.3,8.5,5.8,Fail,Flagged,Selected,Incomplete documents,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33566,DRV010236,Manoj Mishra,70,Delhi,9761149518,manoj.mishra@hotmail.com,Rapido,Mini,Super,4+ yrs,...,6.6,7.5,10.3,5.8,Fail,Clear,Waitlist,NaN,NaN,0
5469,DRV041576,pradeep jha,34,Jaipur,+91636743171,pradeep.jha@gmail.com,Rapido,Tricycle,Poor,Fresher,...,8.7,7.5,9.3,8.1,Pending,Clear,Selected,NaN,2021/09/20,Y
2322,DRV028085,Ajay Patel,38,Bangalore,9123688510,Ajay Patel@gmail.com,Uber,Auto,Poor,5+ yrs,...,1.9,12.2,5.1,5.3,Distinction,Clear,On hold,-,NaN,false
17220,DRV009516,Ajay Pandey,53,Ahmedabad,+91827906785,ajay.pandey@@yahoo.com,Rapido,Mini,Poor,3-5 yrs,...,7.4,3.7,4.0,4.9,Pending,Clear,Rejected,NaN,-,true
6883,DRV025446,manoj jha,70,Kolkata,9162586671,manoj jha@gmail.com,Uber,Sedan,Super,5+ yrs,...,6.2,8.7,7.4,7.2,Pass,Flagged,Selected,NaN,-,NO

In [56]:
df['interview_result'].unique()

<StringArray>
['On hold', 'Selected', 'Rejected', 'Waitlist', 'Pending']
Length: 5, dtype: string

In [57]:
df['rejection_reason'].unique()

array([nan, 'Low rating history', 'Not applicable', 'na', 'none',
       'Incomplete documents', 'Vehicle age too old',
       'Poor communication', '-', 'Background check failed',
       'Failed driving test', 'unknown', 'Unknown'], dtype=object)

In [58]:
## This converts the data type from object to string.
df['rejection_reason'] = df['rejection_reason'].astype("string")
print(df['rejection_reason'].dtype)

string

In [59]:
df['rejection_reason'] = df['rejection_reason'].str.capitalize()
df['rejection_reason'] = df['rejection_reason'].fillna('Invalid_id')
df['rejection_reason'] = df['rejection_reason'].replace({
'Na': 'Invalid_id', 
'Unknown': 'Selected', 
'None': 'Poor communication', 
'-': 'Background check failed'
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
19475,DRV023927,UMESH PATEL,20 yrs,Lucknow,9140985237,umesh.patel@yahoo.com,Rapido,Motorbike,Average,Fresher,...,5.6,6.7,3.2,4.9,Fail,Clear,On hold,Vehicle age too old,NaN,Yes
48609,DRV039591,Ganesh Tiwari,-30,Hyderabad,9319840448,ganesh.tiwari@rediffmail.com,Rapido,Mini,Super,5+ yrs,...,9.9,7.5,5.3,8.2,Distinction,Clear,On hold,Invalid_id,NaN,No
44345,DRV010279,Sanjay Rao,-50,Chennai,9340651674,sanjay.rao@gmail.com,Uber,Sedan,Poor,1-3 yrs,...,6.3,11.0,5.3,6.5,Pass,Clear,Waitlist,Invalid_id,19.05.2024,true
20132,DRV025379,Pr@deep N@ir,31,Jaipur,9231918443,pradeep.nair@@gmail.com,Rapido,Mini,Poor,Fresher,...,4.9,3.3,10.5,1.1,Pending,Flagged,Rejected,Invalid_id,-,no
19163,DRV035569,Ganesh Shukla,52,Jaipur,+91868324725,ganesh.shukla@@rediffmail.com,Rapido,Motorbike,Super,4+ yrs,...,7.5,3.3,7.6,6.2,Distinction,Clear,Selected,Invalid_id,2022/07/15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,DRV040302,Naresh Pandey,38,Mumbai,9322264531,naresh.pandey@hotmail.com,Uber,Bike,Good,8 yrs,...,4.4,10.3,6.7,6.4,Pass,Clear,Selected,Vehicle age too old,NaN,N
6854,DRV043530,Umesh Gupta,29 yrs,Kolkata,+91661296259,umesh.gupta@rediffmail.com,Rapido,Sedan,Fair,8 yrs,...,5.0,9.2,4.5,7.0,Distinction,Pending,Selected,Invalid_id,December 2022,1
9411,DRV009270,Anil Chauhan,52 yrs,Jaipur,9983757512,Anil Chauhan@gmail.com,Uber,Sedan,Good,5+ yrs,...,9.7,8.6,8.5,6.7,Average,Clear,Selected,Invalid_id,December 2021,NO
12373,DRV004350,Naresh Rao,29,Delhi,+91063256290,naresh.rao@rediffmail.com,Na,Auto,Good,3-5 yrs,...,5.2,8.0,8.5,6.0,Pending,Pending,Selected,Invalid_id,04.02.2024,YES
37204,DRV034772,Yogesh Kumar,20,Lucknow,9269507130,yogesh.kumar@rediffmail.com,Na,Sedan,Good,High,...,8.5,3.4,8.9,6.0,Distinction,Clear,Selected,Invalid_id,NaN,False

In [60]:
df['rejection_reason'].unique()

<StringArray>
[             'Invalid_id',      'Low rating history',
          'Not applicable',      'Poor communication',
    'Incomplete documents',     'Vehicle age too old',
 'Background check failed',     'Failed driving test',
                'Selected']
Length: 9, dtype: string

In [61]:
df['onboarding_date'].unique()

array(['-', '19 April 2021', '2021/05/27', ..., '2023/04/22',
       '07-06-2022', '2021-03-31T00:00:00Z'], dtype=object)

In [66]:
## This code generates random date values for the onboarding column. 

import pandas as pd
import numpy as np

df['onboarding_date'] = pd.to_datetime(df['onboarding_date'], errors='coerce')

start = pd.Timestamp("2025-01-01")
end = pd.Timestamp("2026-08-11")

mask = df["onboarding_date"].isna()

df.loc[mask, "onboarding_date"] = pd.to_datetime(
    np.random.randint(
        start.value // 10**9,
        end.value // 10**9,
        size=mask.sum()
    ),
    unit="s"
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
49479,DRV041438,RAKESH SHARMA,45,Delhi,9040838347,rakesh.sharma@yahoo.com,Rapido,Auto,Average,3-5 yrs,...,7.2,4.3,8.5,6.2,Pending,Clear,Waitlist,Invalid_id,2025-08-01 18:16:22,Y
20746,DRV043981,Ramesh Sharma,36,Lucknow,9798675673,ramesh.sharma@yahoo.com,Uber,Bike,Excellent,5+ yrs,...,11.1,7.5,1.1,1.8,Pending,Clear,Rejected,Selected,2026-07-01 16:18:29,N
22711,DRV009782,Mahesh Sharma,42,Jaipur,+91207330381,mahesh.sharma@gmail.com,Ola,Mini,Poor,Fresher,...,4.9,9.5,12.0,6.5,Fail,Pending,Selected,Invalid_id,2025-05-23 09:17:32,False
17119,DRV039105,Pankaj Kumar,unknown,Ahmedabad,9849620,pankaj.kumar@hotmail.com,Uber,Bike,Poor,Fresher,...,5.2,7.5,8.6,7.9,Pending,Clear,Selected,Invalid_id,2026-07-09 12:05:35,No
30698,DRV044507,Vijay Kumar,38,Pune,9157221403,vijay.kumar@yahoo.com,Rapido,Auto,Excellent,3-5 yrs,...,4.4,1.8,5.5,5.2,Pending,Clear,On hold,Selected,2026-02-03 19:39:50,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28563,DRV035919,RAKESH CHAUDHARY,47,Jaipur,9106860713,rakesh.chaudhary@yahoo.com,Rapido,Sedan,Poor,4+ yrs,...,5.8,8.6,6.8,6.4,Distinction,Pending,On hold,Poor communication,2025-04-19 07:08:29,N
528,DRV003061,Naveen Verma,53,Chenna,9185040847,naveen.verma@gmail.com,Uber,Suv,Average,4+ yrs,...,6.3,6.7,8.5,8.8,Fail,Clear,On hold,Invalid_id,2025-03-21 07:20:24,False
1815,DRV016225,Manoj Nair,27,Kolkata,9797542727,manoj.nairyahoo.com,Uber & rapido,Suv,Good,1-3 yrs,...,1.3,10.2,9.2,8.8,Distinction,Clear,Rejected,Low rating history,2025-10-10 11:15:24,N
22297,DRV044373,Ajay Shukla,48,Chennai,9323663750,ajay.shukla@yahoo.com,Uber & rapido,Bicycle,Excellent,5+ yrs,...,7.5,9.6,5.2,6.3,Fail,Flagged,Rejected,Invalid_id,2025-05-24 02:21:01,true
23995,DRV028730,Hitesh Verma,51,Bangalore,9439802,hitesh.verma@gmail.com,Uber & rapido,Suv,Average,4+ yrs,...,11.7,9.7,3.1,6.5,Distinction,Clear,Selected,Failed driving test,2026-03-04 00:05:10,0

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   driver_id                   49005 non-null  object
 1   driver_name                 50000 non-null  object
 2   age                         50000 non-null  string
 3   city                        50000 non-null  string
 4   phone                       50000 non-null  string
 5   email                       50000 non-null  string
 6   platform                    50000 non-null  string
 7   vehicle_type                50000 non-null  string
 8   vehicle_condition           50000 non-null  string
 9   experience_level            50000 non-null  string
 10  preferred_shift             38773 non-null  object
 11  reason_for_joining          38637 non-null  object
 12  languages_known             47847 non-null  object
 13  overall_driver_rating       46033 non-null  object
 14  total_trips_completed       45930 non-null  float64
 15  trip_completion_rate_%      45565 non-null  float64
 16  cancellation_rate_%         45484 non-null  float64
 17  avg_daily_earnings_INR      47489 non-null  object
 18  total_complaints            45965 non-null  float64
 19  total_compliments           46024 non-null  float64
 20  peak_hour_availability      50000 non-null  object
 21  interview_date              45067 non-null  object
 22  communication_score_10      45416 non-null  float64
 23  driving_test_score_10       50000 non-null  string
 24  route_knowledge_score_10    50000 non-null  string
 25  customer_handling_score_10  50000 non-null  string
 26  overall_interview_score_10  50000 non-null  string
 27  document_verification       50000 non-null  string
 28  background_check_status     50000 non-null  string
 29  interview_result            50000 non-null  string
 30  rejection_reason            50000 non-null  string
 31  onboarding_date             50000 non-null  datetime64[ns]
 32  is_currently_active         50000 non-null  object
dtypes: datetime64[ns](1), float64(6), object(10), string(16)
memory usage: 12.6+ MB

In [68]:
df['onboarding_date'].unique()

<DatetimeArray>
['2025-02-05 04:13:11', '2026-03-17 14:46:38', '2021-04-19 00:00:00',
 '2021-05-27 00:00:00', '2025-10-10 23:58:09', '2023-04-01 00:00:00',
 '2023-08-08 00:00:00', '2022-02-06 00:00:00', '2026-07-25 22:01:50',
 '2026-03-08 03:19:08',
 ...
 '2025-01-02 07:58:44', '2026-04-29 19:10:29', '2026-05-19 00:41:30',
 '2025-04-26 02:38:14', '2026-05-16 00:44:24', '2025-12-22 10:09:09',
 '2025-04-29 01:31:47', '2026-07-14 04:08:51', '2025-11-23 06:40:10',
 '2025-10-30 18:28:28']
Length: 49968, dtype: datetime64[ns]

In [78]:
df['is_currently_active'].unique()

<StringArray>
['False', 'True']
Length: 2, dtype: string

In [71]:
## This converts the data type from object to string.
df['is_currently_active'] = df['is_currently_active'].astype("string")
print(df['is_currently_active'].dtype)

string

In [77]:
df['is_currently_active'] = df['is_currently_active'].str.capitalize()
df['is_currently_active'] = df['is_currently_active'].fillna('True')
df['is_currently_active'] = df['is_currently_active'].replace({
'No':'False', 
'0': 'False', 
'1': 'True', 
'N': 'False',
'Y': 'True',
'Yes': 'True',
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
41597,DRV022189,Girish Shukla,36,Ahmedabad,+91880931919,girish.shukla@hotmail.com,Uber,Mini,Super,3-5 yrs,...,9.2,9.4,8.5,7.1,Distinction,Pending,Selected,Invalid_id,2025-05-09 17:58:49,True
48137,DRV039153,Amit Srivastava,-36,Jaipur,9663501848,amit.srivastava@gmail.com,Bolt,Auto,Good,4+ yrs,...,13.0,4.5,5.4,5.4,Pending,Clear,On hold,Invalid_id,2025-02-27 15:01:15,False
32054,DRV041234,Umesh Chaudhary,27,Kolkata,9248587865,umesh.chaudhary@yahoo,Uber & rapido,Mini,Average,High,...,4.5,4.4,7.3,2.0,Distinction,Clear,Rejected,Low rating history,2025-10-11 15:18:03,False
33400,DRV002084,DINESH SINGH,23,Pune,9142334062,dinesh.singh@gmail.com,Uber,Mini,Good,5+ yrs,...,7.3,7.5,5.7,6.2,Pending,Clear,Rejected,Background check failed,2025-10-29 19:25:42,True
31882,NaN,vijay singh,70,Chennai,9786397812,vijay.singh@rediffmail.com,Rapido,Suv,Wonderful,1-3 yrs,...,5.8,6.3,9.7,6.8,Average,Clear,Rejected,Failed driving test,2025-08-08 10:32:52,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17201,DRV044992,Yogesh Pandey,45,Mumbai,+91917590479,yogesh.pandey@yahoo,Rapido,Sedan,Good,3-5 yrs,...,5.3,5.6,9.4,6.1,Distinction,Pending,On hold,Invalid_id,2025-01-10 17:20:31,True
21779,DRV009204,sunil jha,42,Hyderabad,9197854359,sunil.jha@gmail.com,Uber,Mini,Excellent,5+ yrs,...,6.8,3.5,5.9,5.5,Pass,Pending,Selected,Invalid_id,2026-05-29 17:09:19,False
34458,DRV007380,Deep@k N@ir,48,Bangalore,9497902776,Deep@k N@ir@gmail.com,Uber,Sedan,Super,5+ yrs,...,6.2,9.2,5.9,6.1,Pass,Clear,On hold,Invalid_id,2026-06-05 02:40:17,True
2012,DRV005597,Pankaj Reddy,40,Mumbai,9437236383,pankaj.reddy@rediffmail.com,Uber & rapido,Suv,Average,3-5 yrs,...,9.4,5.0,6.6,8.8,Pass,Flagged,Selected,Invalid_id,2025-06-28 21:59:53,False
39290,DRV018272,BHARAT VERMA,47,Bangalore,9709882786,bharat.verma@rediffmail.com,Uber,Suv,Average,Fresher,...,9.2,7.9,11.6,6.5,Fail,Flagged,Selected,Invalid_id,2025-05-08 08:02:41,False