In [1]:
import pandas as pd

#import matplotlib.pyplot as plt

df = pd.read_csv("uber_rapido_driver_dirty.csv")
df.head(5)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
0,DRV016649,Naresh Chauhan,70,Chennai,9255500096,naresh.chauhan@hotmail.com,Uber,Auto,Good,4+ yrs,...,4.3,5.8,7.7,5.3,Fail,Clear,On hold,Invalid_id,2025-02-10 22:07:31,False
1,DRV032785,Amit Gupta,45,Ahmedabad,9940345570,amit.gupta@rediffmail.com,Uber,Mini,Excellent,Fresher,...,9.3,7.5,9.0,8.1,Distinction,Clear,On hold,Invalid_id,2026-01-12 11:59:18,False
2,DRV011323,Yogesh Nair,53,Lucknow,9170487337,Yogesh Nair @gmail.com,Uber,Suv,Average,4+ yrs,...,6.3,9.0,5.5,6.9,Distinction,Clear,Selected,Invalid_id,2021-04-19 00:00:00,False
3,DRV022168,Manoj Patel,46,Hyderabad,9246425981,manoj.patel@hotmail.com,Rapido,Mini,Super,1-3 yrs,...,8.7,9.6,5.3,7.8,Average,Clear,Selected,Invalid_id,2021-05-27 00:00:00,False
4,DRV040782,Vikram Chaudhary,25,Kolkata,9282240,vikram.chaudhary@gmail.com,Uber,Suv,Good,Fresher,...,12.7,6.5,7.9,6.0,Fail,Clear,Rejected,Low rating history,2026-02-08 13:31:18,False

In [2]:
df.describe()

,phone,total_trips_completed,trip_completion_rate_%,cancellation_rate_%,total_complaints,total_compliments,communication_score_10,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10
count,5.000000e+04,45930.000000,45565.00000,45484.000000,45965.000000,46024.000000,45416.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,2.582512e+10,6802.510799,77.89254,22.416584,8809.843120,8942.686272,6.508777,7.078886,6.679730,6.762170,6.892432
std,3.364797e+10,17638.171153,20.80393,23.708155,28303.698509,28456.710282,2.789817,2.272019,2.470516,2.551966,1.951489
min,9.000153e+06,-7996.000000,-2.00000,-2.000000,0.000000,0.000000,-2.000000,0.100000,0.100000,0.000000,0.100000
25%,9.246444e+09,1704.000000,69.40000,8.100000,14.000000,27.000000,4.600000,5.500000,4.800000,4.800000,6.000000
50%,9.595512e+09,3909.000000,80.50000,18.100000,27.000000,55.000000,6.600000,7.400000,7.000000,7.000000,6.800000
75%,9.938337e+09,6086.750000,91.60000,27.900000,41.000000,82.000000,8.500000,8.600000,8.400000,8.500000,7.800000
max,9.199984e+10,99999.000000,103.00000,103.000000,99999.000000,99999.000000,13.000000,13.000000,13.000000,13.000000,13.000000

In [3]:
df.shape

(50000, 33)

In [4]:
df['email'].unique()

array(['naresh.chauhan@hotmail.com', 'amit.gupta@rediffmail.com',
       '  Yogesh Nair  @gmail.com', ..., 'deepak.srivastavahotmail.com',
       'deepak.singhgmail.com', 'deepak.dubeygmail.com'], dtype=object)

In [5]:
df['email'] = df['email'].astype("string")
print(df['email'].dtype)

string

In [6]:
##This code creates a gmail adrress for the drivers using their names, where they have no existing emails.

df['email'] = df['email'].fillna(
    df['driver_name'] + '@gmail.com'
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
20947,DRV029948,Lokesh Gupta,32,Bangalore,9326820076,lokesh.gupta@hotmail.com,Uber,Mini,Good,5+ yrs,...,6.8,5.0,7.0,5.7,Pass,Clear,Selected,Failed driving test,2025-08-06 20:15:24,True
48549,DRV022612,Hitesh Rao,39,Pune,9296570360,hitesh.rao@hotmail.com,Uber,Auto,Good,1-3 yrs,...,6.5,4.0,8.5,11.3,Pending,Pending,On hold,Invalid_id,2025-05-09 07:40:15,True
12490,DRV029464,Ramesh Srivastava,49,Delhi,9391411444,ramesh.srivastava@yahoo.com,Uber,Mini,Average,1-3 yrs,...,1.6,4.5,5.7,5.0,Distinction,Clear,Rejected,Not applicable,2025-07-14 09:39:40,False
47208,DRV004891,Vijay Pandey,51,Bangalore,9842308,vijay.pandey@yahoo.com,Uber,Mini,Good,High,...,8.6,6.0,9.1,10.3,Fail,Pending,Selected,Invalid_id,2026-03-17 06:06:39,True
22470,DRV010371,G@nesh Jh@,34,Kolkata,9467422024,ganesh.jha@gmail.com,Uber & rapido,Sedan,Poor,4+ yrs,...,4.6,9.4,6.7,6.0,Pass,Flagged,Selected,Invalid_id,2026-04-04 13:42:59,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19501,DRV007553,Ganesh Tripathi,23,Pune,9606525730,ganesh.tripathi@yahoo.com,Uber,Bike,Good,3-5 yrs,...,6.4,5.8,4.6,5.9,Fail,Pending,Rejected,Invalid_id,2025-04-25 08:36:39,False
18213,DRV015098,Naresh Dubey,50,Pune,9013686,naresh.dubeygmail.com,Rapido,Suv,Poor,5+ yrs,...,1.2,5.8,8.1,7.6,Pending,Clear,Selected,Invalid_id,2025-09-17 19:21:05,False
42777,DRV033419,Mahesh Mishra,38,Dlhi,91963192957,mahesh.mishra@rediffmail.com,Uber,Bike,Beautiful,5+ yrs,...,6.0,7.9,8.5,7.6,Distinction,Flagged,On hold,Invalid_id,2025-07-24 19:19:37,True
18363,DRV048477,Pradeep Mishra,39,Ahmedabad,9647071124,pradeep.mishra@yahoo.com,Uber & rapido,Mini,Average,4+ yrs,...,5.5,12.2,5.0,6.2,Distinction,Clear,Rejected,Vehicle age too old,2025-03-09 17:03:14,False
287,DRV031635,Yogesh Reddy,21,Kolkata,9182730901,yogesh.reddy@@yahoo.com,Uber,Sedan,Super,5+ yrs,...,6.4,1.1,7.7,8.0,Pass,Flagged,Selected,Invalid_id,2025-12-01 11:05:55,True

In [7]:
df.sample(10)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
49447,DRV044841,Manoj Srivastava,22,Mumbai,9642924996,manoj.srivastava@rediffmail.com,Uber,Bike,Poor,Fresher,...,9.7,7.5,5.5,7.4,Pass,Clear,Selected,Invalid_id,2025-12-15 05:59:32,False
12877,DRV028508,Pr@deep R@o,37 yrs,Jaipur,9402519955,pradeep.rao@gmail.com,Uber,Auto,Poor,4+ yrs,...,4.7,5.0,9.6,12.4,Pass,Pending,Rejected,Vehicle age too old,2025-10-15 09:09:21,True
2275,DRV039596,Mahesh Verma,29,Chennai,9256571,Mahesh Verma@gmail.com,Unknown,Mini,Poor,1-3 yrs,...,7.7,9.9,3.2,6.8,Pending,Clear,Pending,Poor communication,2026-04-03 02:54:02,True
30708,DRV036130,Bharat Shukla,22,Ahmedabad,9751295548,bharat.shukla@hotmail.com,Uber,Mini,Good,1-3 yrs,...,7.3,7.5,3.6,6.6,Fail,Clear,On hold,Invalid_id,2026-07-09 08:14:31,True
5344,NaN,Girish Shukla,29,Chennai,9752890308,girish.shukla@hotmail.com,Uber & rapido,Bike,Excellent,4+ yrs,...,0.7,4.9,7.5,5.9,Distinction,Clear,Selected,Background check failed,2025-08-09 10:16:33,True
42065,DRV013314,Vikram Tripathi,36,Bangalore,9741769298,vikram.tripathi@rediffmail.com,Ola,Truck,Good,4+ yrs,...,7.8,4.2,3.4,6.1,Fail,Clear,On hold,Invalid_id,2025-05-25 08:15:06,True
18036,DRV017760,BHARAT TIWARI,999,Ahmedabad,9704866796,bharat.tiwari@@rediffmail.com,Uber & rapido,Suv,Average,8 yrs,...,8.6,6.0,7.1,6.5,Pass,Clear,On hold,Invalid_id,2026-07-10 05:56:27,False
34021,DRV013594,LOKESH DUBEY,44,Kolkata,91230946899,lokesh.dubey@yahoo.com,Uber,Bike,Super,Fresher,...,12.9,5.6,7.8,7.0,Distinction,Pending,Waitlist,Invalid_id,2025-01-21 21:17:44,False
37239,DRV001833,Vijay Reddy,53,Jaipur,9974288420,vijay.reddy@hotmail.com,Uber,Auto,Average,4+ yrs,...,7.4,7.5,9.3,7.3,Average,Clear,On hold,Invalid_id,2025-10-17 02:29:00,True
10612,DRV004744,Vikram Tiwari,33,Lucknow,9017939761,vikram.tiwari@yahoo.com,Uber,Suv,Average,Fresher,...,7.3,3.6,8.7,6.8,Pending,Pending,On hold,Invalid_id,2026-06-04 21:38:03,False

In [8]:
df['phone'] = pd.to_numeric(df['phone'], errors='coerce') 
## This is to convert the phone collumn from object to numeric

In [9]:
df['phone'] = df['phone'].astype("string")
print(df['phone'].dtype)

string

In [10]:
df['driving_test_score_10'].unique()

array([ 4.3,  9.3,  6.3,  8.7, 12.7,  8.8,  8.1,  1.1, 11.6,  7.5,  7.4,
        0.6,  7.7,  6.2,  4.8,  7.1, 12.5, 11.2,  0.9,  5.5,  8.9,  6.4,
        5.1,  7. , 11. ,  7.6,  5.7, 12.2,  9.1,  8.3,  4.6,  4. ,  7.2,
        8. ,  9.7, 10.9,  4.2,  9.5,  4.9,  5.8,  5. ,  6.9,  4.1,  6.5,
        4.5,  9.8,  5.4,  4.4,  1.3,  9.2,  4.7,  7.3,  1.5, 12.4,  8.6,
        8.4,  1.7,  5.3,  6.1,  6. ,  9.6,  7.9,  6.8,  5.2,  5.6, 10.2,
        0.7,  9.4,  9.9,  7.8,  8.2,  6.6,  6.7, 10.5,  9. , 10.8,  5.9,
       12. , 12.1, 11.5,  8.5, 10. ,  1. ,  0.8, 11.4, 10.3,  0.4,  0.5,
       10.7, 11.7, 11.8,  0.3, 10.4, 12.8,  1.8,  1.2,  0.2, 11.9,  1.4,
       10.1, 11.3, 12.3,  1.6, 12.6,  1.9, 10.6, 12.9, 11.1, 13. ,  0.1,
        2. ])

In [11]:
## This code removes the decimals from the values and make them strings rather than floats. 
df['phone'] = df['phone'].str.replace(r'\.0$', '', regex=True)

In [12]:
## This creates random phone numbers for NaN values in the phone column

import numpy as np

mask = df['phone'].isna()

df.loc[mask, 'phone'] = [
    '+91' + ''.join(np.random.choice(list('0123456789'), 9))
    for _ in range(mask.sum())
]
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
19896,DRV030580,Rajesh Pandey,31,Lucknow,9915138768,rajesh.pandey@yahoo.com,Uber,Bike,Good,4+ yrs,...,8.9,9.0,8.5,7.3,Pending,Pending,On hold,Invalid_id,2026-06-27 06:02:30,True
45807,DRV022957,M@noj Ch@uh@n,52,Lucknow,9581491788,manoj.chauhan@hotmail.com,Rapido,Mini,Poor,5+ yrs,...,8.4,8.3,12.7,1.6,Distinction,Clear,Rejected,Incomplete documents,2026-01-30 17:45:00,False
23018,DRV024709,Harish Patel,unknown,Ahmedabad,91233531985,harish.patel@gmail.com,Ola,Sedan,Super,1-3 yrs,...,4.2,11.2,8.2,7.1,Fail,Flagged,On hold,Invalid_id,2025-05-28 12:01:22,True
46474,DRV026731,Umesh Srivastava,40,Kolkata,9238663269,umesh.srivastava@yahoo.com,Rapido,Auto,Great,8 yrs,...,6.5,9.0,9.5,7.5,Distinction,Clear,Selected,Invalid_id,2025-07-27 02:32:52,True
18513,DRV004294,Hitesh Sh@rm@,38,Ahmedabad,9225652821,Hitesh Sh@rm@@gmail.com,Uber,Sedan,Excellent,Fresher,...,9.6,7.5,9.1,1.8,Distinction,Clear,Selected,Poor communication,2025-07-21 07:37:24,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14310,DRV043896,Mukesh Shukla,51,Kolkata,9088220291,mukesh.shukla@@rediffmail.com,Uber,Suv,Super,3-5 yrs,...,9.5,7.3,8.5,8.2,Fail,Pending,Selected,Invalid_id,2025-02-14 13:19:47,True
42265,DRV005450,harish dubey,36,Kolkata,9064638981,harish.dubey@hotmail.com,Uber & rapido,Sedan,Excellent,Fresher,...,7.5,7.4,8.7,8.1,Distinction,Clear,Selected,Invalid_id,2026-05-18 06:58:44,False
34131,DRV011056,Harish Sharma,36,Hyderabad,9106958501,harish.sharma@rediffmail.com,Uber,Bike,Average,5+ yrs,...,5.3,8.3,8.3,8.8,Pending,Flagged,Selected,Invalid_id,2026-07-17 07:36:01,False
10797,DRV034260,GIRISH TRIPATHI,28,Jaipur,9177833091,girish.tripathi@hotmail.com,Uber & rapido,Suv,Good,Fresher,...,10.1,5.7,5.5,6.1,Fail,Flagged,Rejected,Vehicle age too old,2025-05-03 13:10:03,True
5977,DRV000371,girish sharma,54,Mumbai,9875955424,girish.sharma@gmail.com,Rapido,Auto,Super,4+ yrs,...,10.6,8.5,6.7,8.8,Fail,Pending,On hold,Invalid_id,2025-10-05 04:59:30,True

In [13]:
df['age'] = df['age'].astype("string")
print(df['age'].dtype)

string

In [14]:
df['age'] = df['age'].fillna('70')

In [15]:
## This code fills the age column where NaN values exist with random values between 1 and 100

import numpy as np

mask = df['age'].isna()

df.loc[mask, 'age'] = np.random.randint(
    1, 101, size=mask.sum()
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
22681,DRV017233,Naveen Dubey,50,Pune,9518441547,naveen.dubey@hotmail.com,Uber,Suv,Super,1-3 yrs,...,7.5,3.3,1.6,4.5,Distinction,Clear,Rejected,Poor communication,2025-03-29 12:16:37,False
43526,DRV010085,Ajay Kumar,36 yrs,Jaipur,9389765754,ajay.kumaryahoo.com,Ola,Bike,Super,1-3 yrs,...,9.5,7.7,7.2,8.4,Fail,Clear,Selected,Invalid_id,2025-08-12 05:19:35,True
41757,DRV006663,Vikram Gupta,51,Jaipur,91479069665,vikram.gupta@yahoo.com,Uber,Suv,Super,Fresher,...,6.1,4.6,5.0,4.7,Pending,Clear,Rejected,Incomplete documents,2025-12-04 06:23:04,True
20571,DRV016539,Dinesh Mishra,42,Jaipur,9001001378,dinesh.mishra@rediffmail.com,Uber,Auto,Excellent,Fresher,...,7.3,6.5,5.0,6.5,Distinction,Clear,Selected,Invalid_id,2026-02-09 16:18:48,False
34891,DRV045564,PANKAJ TRIPATHI,70,Chennai,9413771922,pankaj.tripathi@yahoo,Uber,Suv,Average,Fresher,...,1.5,6.2,6.6,11.2,Pending,Pending,Rejected,Poor communication,2026-05-18 13:36:18,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17048,DRV045091,Sunil Singh,24,Lucknow,9329640808,sunil.singh@yahoo.com,Bolt,Sedan,Good,Fresher,...,6.9,4.4,7.3,12.5,Pending,Pending,Selected,Invalid_id,2025-01-16 06:42:31,False
17405,DRV023950,Sanjay Gupta,70,Chennai,9760709930,sanjay.gupta@yahoo.com,Rapido,Sedan,Average,7+ yrs,...,8.3,6.0,3.7,5.5,Fail,Clear,On hold,Invalid_id,2025-09-03 05:18:28,False
36139,DRV032656,Umesh Rao,35,Lucknow,9685355283,umesh.rao@gmail.com,Ola,Suv,Poor,Fresher,...,10.8,7.1,8.8,8.0,Pending,Clear,Rejected,Invalid_id,2025-08-26 04:49:52,True
38397,DRV013323,pankaj shukla,41,Kolkata,9386553092,pankaj.shukla@gmail.com,NaN,Sedan,Super,7+ yrs,...,8.8,3.8,9.5,6.9,Distinction,Clear,Selected,Invalid_id,2025-12-12 15:15:38,True
40788,DRV046846,Yogesh Sharma,24,Kolkata,9252849914,yogesh.sharma@gmail.com,Uber,Bike,Average,1-3 yrs,...,6.7,8.7,0.0,6.5,Distinction,Pending,On hold,Invalid_id,2025-01-14 12:29:19,True

In [16]:
## This is to remove the negative values and also the yrs in the age column.
df['driving_test_score_10'] = df['driving_test_score_10'].astype("string")
df['driving_test_score_10'] = df['driving_test_score_10'].str.lstrip('-')
#df['age'] = df['age'].str.rstrip('yrs')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
25758,DRV045699,Mukesh Nair,40,Mumbai,9636231886,mukesh.nair@yahoo.com,Ola,Mini,Excellent,Fresher,...,7.5,9.6,3.7,7.8,Fail,Clear,Selected,Invalid_id,2025-04-15 05:57:41,False
25835,DRV001441,yogesh yadav,45,Chenna,9861589344,yogesh.yadav@hotmail.com,Ola,Catapiller,Average,1-3 yrs,...,4.8,8.4,7.8,7.0,Pass,Pending,On hold,Invalid_id,2025-03-21 23:38:36,True
34435,DRV019059,Suresh Rao,999,Ahmedabad,9092413756,suresh.rao@yahoo,Bolt,Bike,Excellent,5+ yrs,...,4.0,4.0,8.5,4.2,Credit,Clear,On hold,Poor communication,2025-12-17 08:50:25,False
19000,DRV018787,Mukesh Rao,41,Kolkata,91548410509,mukesh.rao@rediffmail.com,Rapido,Sedan,Poor,3-5 yrs,...,8.5,9.9,3.7,7.1,Pending,Clear,Selected,Invalid_id,2026-02-10 11:18:44,True
7953,DRV044867,Ganesh Reddy,70,Ahmedabad,9480617594,ganesh.reddy@yahoo.com,Ola,Mini,Good,4+ yrs,...,10.7,7.3,8.2,8.7,Pass,Clear,On hold,Invalid_id,2025-03-29 16:51:49,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30992,DRV013256,Rajesh Verma,55,Lucknow,9463919057,rajesh.verma@rediffmail.com,Rapido,Suv,Super,4+ yrs,...,5.9,9.5,1.3,6.0,Distinction,Clear,Selected,Invalid_id,2025-04-29 09:13:58,False
23015,DRV040461,Naresh Mishra,50,Delhi,9563994248,naresh.mishra@rediffmail.com,Uber,Bike,Poor,Fresher,...,8.5,5.9,3.0,7.5,Pass,Clear,Selected,Invalid_id,2025-09-15 11:55:31,False
27026,DRV026207,Bharat Yadav,47,Kolkata,9346031266,bharat.yadav@hotmail,Rapido,Suv,Good,High,...,4.9,5.3,6.7,5.7,Pending,Pending,Selected,Invalid_id,2026-04-12 04:13:49,True
34658,DRV037169,Sanjay Jha,52,Delhi,91718450426,sanjay.jha@rediffmail.com,Rapido,Motorbike,Good,5+ yrs,...,4.2,4.5,8.6,8.8,Pending,Pending,Rejected,Invalid_id,2025-08-13 10:33:20,False
23483,DRV049194,Vikram Pandey,53,Chennai,9148939203,vikram.pandey@hotmail.com,Rapido,Motorbike,Average,3-5 yrs,...,5.7,6.0,8.1,6.9,Fail,Flagged,Selected,Not applicable,2026-02-07 00:05:28,True

In [17]:
## This is to capitalise the platform column to give it a uniform format and also convert the data type from object to string.

df['platform'] = df['platform'].str.capitalize()
df['platform'] = df['platform'].astype("string")
print(df['platform'].dtype)

string

In [18]:
df['platform'] = df['platform'].fillna('Bolt')

In [19]:
df['customer_handling_score_10'] = df['customer_handling_score_10'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    #'Unknown': 'Experienced',
    #'None': 'Fairly_Experienced',
    #'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Motorcycle',
    #'Na': '1-20 yrs',
    #'-': '10-30 yrs',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    '<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
19141,DRV019702,Santosh Srivastava,25,Pune,9525980415,santosh.srivastava@hotmail.com,Uber,Auto,Poor,1-3 yrs,...,9.4,5.3,5.7,6.5,Pending,Pending,Rejected,Poor communication,2026-06-23 08:05:32,True
32479,DRV038649,Ajay Tripathi,29,Delhi,9829116251,ajay.tripathi@rediffmail.com,Rapido,Auto,Good,5+ yrs,...,12.4,11.5,7.0,8.0,Pass,Clear,On hold,Invalid_id,2026-06-25 09:08:07,True
38655,DRV017077,Rajesh Nair,70,Ahmedabad,9521736055,rajesh.nair@gmail.com,Uber,Mini,Average,Fresher,...,9.3,3.9,6.1,6.4,Pending,Clear,Rejected,Invalid_id,2026-04-16 06:24:51,False
9109,DRV031417,Pradeep Gupta,999,Bangalroe,9806071260,pradeep.gupta@rediffmail.com,Rapido,Mini,Poor,3-5 yrs,...,4.7,7.1,8.2,7.0,Distinction,Clear,Selected,Invalid_id,2025-04-01 19:26:01,True
43234,DRV001665,Mukesh Chaudhary,-34,Jaipur,9869694320,mukesh.chaudhary@gmail.com,Rapido,Auto,Average,1-3 yrs,...,6.1,9.1,7.6,7.4,Pass,Clear,Rejected,Incomplete documents,2025-05-15 10:09:52,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39001,DRV001243,Amit Mishra,28,Chennai,9080350,amit.mishra@hotmail.com,Rapido,Auto,Poor,4+ yrs,...,6.4,5.3,7.8,6.5,Fail,Pending,On hold,Invalid_id,2026-03-30 18:05:38,False
6099,DRV009395,Mahesh Chaudhary,54,Ahmedabad,9356666970,mahesh.chaudhary@@rediffmail.com,Uber,Bike,Super,Fresher,...,4.5,6.5,6.4,6.7,Pass,Clear,Rejected,Failed driving test,2025-04-08 10:26:14,False
42255,DRV019069,Naresh Dubey,33,Hyderabad,9415851197,Naresh Dubey@gmail.com,Rapido,Suv,Great,1-3 yrs,...,5.9,6.9,7.8,7.2,Distinction,Clear,Rejected,Invalid_id,2025-08-04 09:05:06,False
5209,DRV024564,Sunil Reddy,38,Jaipur,9056911022,sunil.reddy@yahoo.com,Uber,Bike,Good,5+ yrs,...,7.5,12.2,6.4,7.2,Fail,Clear,Rejected,Invalid_id,2025-07-03 17:39:58,False
14371,DRV038789,Dinesh Srivastava,40,Ahmedabad,9564579,dinesh.srivastava@@hotmail.com,Uber,Sedan,Super,5+ yrs,...,4.9,4.1,8.7,6.2,Pending,Clear,Rejected,Poor communication,2025-04-08 04:34:14,True

In [20]:
## This capitalises the city column to give it a uniform format and also converts the data type from object to string.
df['city'] = df['city'].str.capitalize()
df['city'] = df['city'].astype("string")
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
27786,DRV037042,Sanjay Sharma,70,Kolkata,91941649401,sanjay.sharma@gmail.com,Rapido,Bike,Good,1-3 yrs,...,6.1,3.5,8.5,5.5,Fail,Pending,Selected,Invalid_id,2025-02-13 21:07:06,True
16460,DRV027633,Anil Mishra,-39,Jaipur,91010596264,anil.mishra@rediffmail.com,Uber,Bike,Super,1-3 yrs,...,11.8,9.1,7.4,6.2,Pass,Flagged,Rejected,Invalid_id,2026-06-20 21:39:18,False
47622,DRV032117,Ramesh Chaudhary,41,Lucknow,9090913490,ramesh.chaudhary@hotmail,Rapido,Auto,Excellent,High,...,1.9,8.9,9.8,12.7,Distinction,Clear,On hold,Invalid_id,2025-04-22 18:33:28,False
37551,DRV017886,Pankaj Mishra,41,Kolkata,9286869148,pankaj.mishra@yahoo.com,Bolt,Sedan,Average,1-3 yrs,...,7.2,0.2,3.3,6.0,Pending,Pending,On hold,Invalid_id,2026-02-01 01:46:23,True
41376,DRV008253,Mukesh Chaudhary,37,Kolkata,9529203535,mukesh.chaudhary@rediffmail.com,Rapido,Auto,Average,1-3 yrs,...,9.5,9.9,1.2,11.2,Distinction,Clear,Selected,Invalid_id,2025-05-24 18:33:22,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42240,DRV021144,BHARAT SINGH,35,Mumbai,9398431280,bharat.singh@yahoo.com,Uber,Mini,Good,5+ yrs,...,5.7,10.3,6.6,6.3,Distinction,Clear,On hold,Invalid_id,2026-05-05 10:16:19,False
40065,DRV009289,Umesh Singh,45,Pune,9025725550,umesh.singh@yahoo.com,Ola,Auto,Average,4+ yrs,...,8.6,7.5,9.9,8.0,Distinction,Clear,Selected,Invalid_id,2026-01-26 06:59:52,False
47822,DRV012980,AMIT PATEL,999,Bangalore,9921384841,amit.patel@hotmail.com,Uber,Bike,Poor,4+ yrs,...,7.7,4.2,3.7,5.8,Distinction,Clear,Waitlist,Invalid_id,2026-04-06 00:19:24,True
35421,DRV033972,Sanjay Verma,37,Hyderabad,9834032230,sanjay.verma@rediffmail.com,Uber,Sedan,Good,Fresher,...,7.5,9.1,3.9,7.0,Pending,Clear,Selected,Invalid_id,2026-07-13 13:06:11,False
24572,DRV041071,Vijay Jha,41 yrs,Ahmedabad,9406792184,Vijay Jha@gmail.com,Uber,Bike,Super,5+ yrs,...,10.7,7.3,5.8,8.8,Pass,Clear,Rejected,Invalid_id,2025-07-10 16:05:02,False

In [21]:
df['route_knowledge_score_10'].unique()

array([ 5.8,  7.5,  9. ,  9.6,  6.5,  8.6,  8.7,  6.4,  7.9,  7.7,  3.6,
        5.2,  6.8,  8.5,  7.1,  4.6,  1.2,  5. ,  3.2,  3.5,  3.8,  5.6,
        4.9,  8.8, 12. ,  6.7,  6.3,  9.9,  3.4,  9.8,  0.3, 10.7,  9.4,
       12.4,  4.2,  6.2,  3.9, 10. ,  6. ,  9.5,  7.4,  3. , 10.3,  7. ,
       10.2,  6.1,  3.3,  8. ,  4. ,  4.7,  4.5,  7.6,  5.9,  1.3,  4.1,
        5.1,  4.3, 12.2, 11.2,  8.1, 11.9,  5.4,  0.9,  5.5,  6.6,  3.7,
        9.3, 12.8,  8.2, 10.8,  5.3,  9.2, 12.3,  3.1,  7.8,  7.2,  9.1,
        4.8,  6.9,  9.7, 12.7,  8.9,  4.4,  7.3, 11. ,  0.4, 13. , 11.7,
        8.4,  1.5, 11.5, 12.9, 10.5,  5.7,  1.1,  1.4, 10.1,  8.3,  0.7,
       10.4,  0.8,  1.9, 12.1,  2. ,  0.2, 10.9,  1.8, 11.1,  1. , 11.8,
       11.3, 11.4,  0.5, 12.5,  1.7,  1.6,  0.1, 10.6, 12.6,  0.6, 11.6])

In [22]:
## This converts the data type from object to string.
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].astype("string")
print(df['route_knowledge_score_10'].dtype)

string

In [23]:
## This is to remove the negative values and also the yrs in the age column.
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].str.lstrip('-')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
4416,DRV030717,Ramesh Yadav,30,Mumbai,91393193209,ramesh.yadav@gmail.com,Uber,Sedan,Super,6 yrs,...,5.8,7.5,9.5,7.8,Pass,Pending,Waitlist,Invalid_id,2026-07-01 06:08:24,True
20542,DRV048332,MUKESH RAO,31,Mumbai,9281481088,mukesh.rao@hotmail.com,Uber & rapido,Bicycle,Poor,5+ yrs,...,8.6,9.9,10.0,9.3,Distinction,Flagged,On hold,Invalid_id,2026-01-20 19:46:42,False
26466,DRV042989,Ramesh Gupta,54 yrs,Jaipur,9631353446,ramesh.gupta@hotmail.com,Uber,Suv,Good,5+ yrs,...,4.1,7.5,3.9,11.8,Pending,Clear,Rejected,Vehicle age too old,2025-09-11 15:50:16,True
41887,DRV005938,SANJAY MISHRA,27,Bangalore,91215183645,sanjay.mishra@hotmail.com,Uber & rapido,Bicycle,Average,Fresher,...,8.6,8.5,7.0,8.8,Pass,Clear,Selected,Invalid_id,2026-04-13 21:14:09,True
33533,DRV005010,Dinesh Gupta,34,Pune,9964918377,dinesh.gupta@gmail.com,Rapido,Auto,Poor,3-5 yrs,...,11.6,9.1,8.5,8.4,Pass,Clear,On hold,Invalid_id,2025-02-25 00:31:51,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9538,DRV028133,Hitesh Shukla,45,Delhi,9775792658,hitesh.shukla@yahoo.com,Uber,Auto,Super,4+ yrs,...,7.5,8.8,4.1,7.1,Distinction,Clear,Rejected,Invalid_id,2026-03-09 17:43:10,True
4552,DRV034112,Mukesh Tripathi,26,Mumbai,9062594396,Mukesh Tripathi@gmail.com,Rapido,Catapiller,Good,Fresher,...,7.4,6.7,1.5,7.4,Pass,Clear,Selected,Failed driving test,2025-03-18 14:47:24,True
12603,DRV039403,Harish Chauhan,39,Chennai,9405736833,harish.chauhan@rediffmail.com,Rapido,Suv,Excellent,5+ yrs,...,6.1,9.8,11.0,8.2,Credit,Pending,Selected,Invalid_id,2025-05-18 09:55:52,False
33670,DRV030175,naresh nair,45,Bangalore,91269618645,naresh.nair@rediffmail.com,Rapido,Bike,Fair,3-5 yrs,...,9.2,5.1,9.5,10.4,Fail,Clear,Selected,Invalid_id,2026-05-27 12:03:37,False
6638,DRV018676,ANIL SHARMA,999,Hyderabad,9260381213,anil.sharma@yahoo.com,Uber,Suv,Excellent,4+ yrs,...,9.6,6.4,8.5,10.6,Fail,Clear,Selected,Invalid_id,2026-05-26 16:43:48,True

In [24]:
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].fillna('7.5')

In [25]:
## This code fills the age column where NaN values exist with random values between 0 and 10

import numpy as np

mask = df['customer_handling_score_10'] == 6

df.loc[mask, 'customer_handling_score_10'] = np.random.randint(
    0, 10, size=mask.sum()
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
5524,DRV040575,Manoj Jha,30,Kolkata,9437869368,Manoj Jha@gmail.com,Rapido,Sedan,Average,Fresher,...,7.5,6.4,1.7,5.5,Distinction,Flagged,Rejected,Invalid_id,2026-03-01 01:05:50,True
10696,DRV036552,Yogesh Kumar,39,Kolkata,91167565787,yogesh.kumarhotmail.com,Uber,Motorbike,Great,4+ yrs,...,2.0,9.7,3.1,5.9,Distinction,Clear,Selected,Invalid_id,2026-05-30 12:44:52,False
32681,DRV012000,Rakesh Yadav,35,Chennai,91157552560,rakesh.yadav@hotmail.com,Rapido,Sedan,Good,7+ yrs,...,5.6,3.1,8.5,8.8,Pass,Flagged,Rejected,Invalid_id,2025-12-23 10:14:33,True
34664,DRV002406,RAVI YADAV,26,Mumbai,9357592596,ravi.yadav@rediffmail.com,Uber,Auto,Poor,4+ yrs,...,6.0,1.3,11.9,5.8,Fail,Pending,Rejected,Background check failed,2025-08-04 17:01:45,True
39860,DRV024494,Suresh Singh,999,Ahmedabad,9118043584,Suresh Singh@gmail.com,Uber,Mini,Poor,5+ yrs,...,7.2,9.0,5.9,8.8,Fail,Clear,On hold,Invalid_id,2025-05-11 12:50:58,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24927,DRV028162,Mukesh Shukla,25,Mumbai,9824857814,mukesh.shukla@rediffmail.com,Uber,Suv,Good,High,...,7.5,7.5,5.3,6.6,Distinction,Clear,On hold,Invalid_id,2025-05-20 12:07:29,True
37466,DRV032065,Vijay Mishra,47,Ahmedabad,9004220420,vijay.mishra@gmail.com,Uber,Auto,Good,1-3 yrs,...,7.5,7.6,9.9,7.8,Fail,Clear,Selected,Invalid_id,2025-10-13 21:46:53,True
33312,DRV042286,Ajay Patel,26,Mumbai,9284317276,ajay.patel@hotmail.com,-,Suv,Super,4+ yrs,...,7.5,4.5,8.2,1.9,Fail,Flagged,Selected,Invalid_id,2025-07-21 16:45:02,False
8601,DRV042692,Mahesh Chaudhary,37,Lucknow,9156134978,mahesh.chaudhary@hotmail.com,Rapido,Auto,Average,3-5 yrs,...,6.8,3.1,5.9,4.8,Pass,Clear,Rejected,Invalid_id,2025-06-24 19:02:18,True
38242,DRV032405,Deepak Reddy,30,Kolkata,9643022168,deepak.reddy@gmail.com,Uber & rapido,Suv,Good,4+ yrs,...,4.1,9.2,4.4,6.1,Distinction,Pending,Rejected,Vehicle age too old,2025-03-13 07:07:27,True

In [26]:
df['vehicle_type'].unique()

array(['Auto', 'Mini ', 'Suv', 'Mini', 'Bike', 'Sedan', 'Tricycle',
       'Motorbike', 'Bicycle', 'Catapiller', 'Truck'], dtype=object)

In [27]:
## This converts the data type from object to string.
df['vehicle_type'] = df['vehicle_type'].astype("string")
print(df['vehicle_type'].dtype)

string

In [28]:
df['vehicle_type'] = df['vehicle_type'].str.capitalize()
df['vehicle_type'] = df['vehicle_type'].fillna('Motorbike')
df['vehicle_type'] = df['vehicle_type'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    #'Unknown': 'Experienced',
    'None': 'Bicycle',
    #'Avg': 'Average',
    #'poor': 'Super',
    'Unknown': 'Tricycle',
    'Na': 'Catapiller',
    '-': 'Truck',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
40073,DRV025142,Hitesh Pandey,42,Hyderabad,9925308040,hitesh.pandey@hotmail.com,Uber,Sedan,Average,3-5 yrs,...,4.4,7.5,1.5,7.4,Pass,Clear,Selected,Invalid_id,2025-08-27 02:06:35,True
18753,DRV016492,Rakesh Mishra,31,Ahmedabad,9166001181,rakesh.mishra@yahoo.com,Ola,Bicycle,Good,1-3 yrs,...,4.8,6.7,6.8,5.7,Pass,Pending,Selected,Invalid_id,2026-05-22 17:35:30,False
32198,DRV021922,Sunil Nair,31,Bangalore,91325562399,sunil.nair@yahoo.com,Rapido,Suv,Average,3-5 yrs,...,6.2,8.5,5.6,8.8,Fail,Flagged,Rejected,Low rating history,2025-11-15 08:39:22,True
31551,DRV039796,Hitesh Reddy,70,Bangalore,9997202479,hitesh.reddy@hotmail.com,Uber & rapido,Auto,Good,1-3 yrs,...,9.8,5.4,3.9,5.7,Pending,Clear,Selected,Invalid_id,2025-12-18 13:40:54,True
15796,DRV041289,Vikram Pandey,70,Chennai,91384874612,vikram.pandey@@rediffmail.com,Uber,Sedan,Average,1-3 yrs,...,12.5,4.0,8.0,6.1,Pending,Pending,Rejected,Incomplete documents,2026-07-15 03:21:56,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32193,DRV017192,Bharat Rao,27,Jaipur,9507163187,bharat.rao@yahoo.com,Rapido,Mini,Good,5+ yrs,...,6.9,5.9,10.5,5.5,Distinction,Pending,Selected,Invalid_id,2025-08-29 12:07:08,True
49386,DRV029904,Naresh Patel,29,Hyderabad,91824323896,naresh.patel@rediffmail.com,Uber,Sedan,Average,3-5 yrs,...,4.7,10.0,5.9,7.2,Pending,Flagged,Selected,Not applicable,2026-06-09 15:48:18,False
48967,DRV026093,Ravi Kumar,unknown,Lucknow,91419577416,ravi.kumar@gmail.com,Uber,Suv,Excellent,High,...,1.8,4.9,3.3,8.8,Pending,Flagged,Selected,Invalid_id,2026-06-21 13:56:51,True
26146,DRV037201,Ravi Jha,52,Bangalore,91086166133,ravi.jha@gmail.com,Rapido,Motorbike,Excellent,High,...,6.4,5.9,7.8,6.4,Pending,Clear,On hold,Invalid_id,2026-01-14 06:46:13,False
15078,DRV028049,Ganesh Sharma,50,Hyderabad,9891938,ganesh.sharma@rediffmail,Uber & rapido,Auto,Excellent,7+ yrs,...,7.5,7.5,9.8,8.8,Distinction,Clear,Selected,Invalid_id,2025-05-12 21:48:02,True

In [29]:
df['vehicle_condition'].unique()

array(['Good', 'Excellent', 'Average', 'Super', 'Poor', 'Great',
       'Wonderful', 'Fair', 'Beautiful'], dtype=object)

In [30]:
## This converts the data type from object to string.
df['vehicle_condition'] = df['vehicle_condition'].astype("string")
print(df['vehicle_condition'].dtype)

string

In [31]:
df['vehicle_condition'] = df['vehicle_condition'].str.capitalize()
df['vehicle_condition'] = df['vehicle_condition'].fillna('Super')
df['vehicle_condition'] = df['vehicle_condition'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    'Unknown': 'Great',
    'None': 'Beautiful',
    'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Tricycle',
    'Na': 'Fair',
    '-': 'Wonderful',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
20418,DRV040579,Ajay Kumar,53,Jaipur,9553257653,ajay.kumar@hotmail.com,Uber,Bike,Excellent,Fresher,...,7.4,9.4,4.5,6.9,Distinction,Pending,On hold,Invalid_id,2025-07-22 11:41:55,False
20792,DRV034895,ramesh pandey,48,Hyderabad,9797806463,ramesh.pandey@yahoo.com,Rapido,Auto,Excellent,3-5 yrs,...,7.0,4.0,7.1,6.0,Distinction,Clear,Selected,Invalid_id,2025-05-25 03:03:43,False
40694,DRV026686,Santosh Chauhan,30,Chennai,9910107016,santosh.chauhan@yahoo.com,Uber & rapido,Auto,Super,4+ yrs,...,8.1,7.5,7.2,6.8,Pending,Clear,On hold,Invalid_id,2025-05-01 00:56:15,True
3727,DRV038997,Ajay Kumar,39,Lucknow,9149840061,Ajay Kumar@gmail.com,Uber,Mini,Excellent,Fresher,...,4.6,9.8,7.9,12.0,Pass,Clear,On hold,Invalid_id,2026-06-04 01:37:17,False
17393,DRV042591,Anil Verma,43,Chennai,91635614872,anil.verma@@rediffmail.com,Rapido,Bike,Super,5+ yrs,...,10.8,8.5,5.9,7.1,Distinction,Clear,Waitlist,Invalid_id,2025-05-24 10:21:44,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29755,DRV048137,Hitesh Sriv@st@v@,51 yrs,Hyderabad,9589443752,hitesh.srivastava@rediffmail.com,Uber,Sedan,Poor,High,...,7.5,10.7,4.4,7.4,Pass,Flagged,Selected,Invalid_id,2026-07-17 18:48:01,False
20023,DRV034038,Vijay Yadav,999,Mumbai,9480826117,vijay.yadav@gmail.com,Uber,Suv,Poor,3-5 yrs,...,5.7,7.0,7.3,6.0,Fail,Flagged,Waitlist,Selected,2026-06-21 04:14:06,True
22818,DRV015523,Lokesh Dubey,21,Ahmedabad,9348585503,lokesh.dubey@yahoo,Uber,Mini,Average,5+ yrs,...,7.0,3.3,1.5,5.6,Distinction,Clear,Rejected,Background check failed,2026-02-21 17:22:35,True
23625,DRV027134,Harish Yadav,39,Ahmedabad,9533542571,harish.yadav@yahoo.com,Rapido,Mini,Poor,4+ yrs,...,8.7,8.8,7.8,7.3,Pass,Pending,Selected,Invalid_id,2025-12-22 12:10:08,True
32295,DRV022751,ajay kumar,32,Ahmedabad,91125417162,ajay.kumar@yahoo,Bolt,Sedan,Poor,Fresher,...,7.8,4.9,9.4,8.8,Fail,Clear,Selected,Invalid_id,2025-12-04 13:19:34,False

In [32]:
df['experience_level'].unique()

array(['4+ yrs', 'Fresher', '1-3 yrs', '5+ yrs', '3-5 yrs', 'High',
       '7+ yrs', '6 yrs', '8 yrs', '8+ yrs'], dtype=object)

In [33]:
## This converts the data type from object to string.
df['experience_level'] = df['experience_level'].astype("string")
print(df['experience_level'].dtype)

string

In [34]:
df['experience_level'] = df['experience_level'].str.capitalize()
df['experience_level'] = df['experience_level'].fillna('High')
df['experience_level'] = df['experience_level'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    '0-1 yr' : '4+ yrs',
    'Unknown': '7+ yrs',
    'None': '8+ yrs',
    #'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Tricycle',
    'Na': '6 yrs',
    '-': '8 yrs',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
39273,DRV024476,Yogesh Singh,24 yrs,Delhi,9280378146,yogesh.singhyahoo.com,Rapido,Bike,Excellent,Fresher,...,8.6,8.2,10.0,8.6,Distinction,Clear,Waitlist,Invalid_id,2026-05-15 12:31:12,True
21715,DRV005250,Aj@y Singh,30,Delhi,9999021206,ajay.singh@rediffmail.com,-,Auto,Excellent,5+ yrs,...,7.2,8.3,8.3,0.6,Fail,Flagged,Selected,Invalid_id,2025-04-09 20:27:15,True
14070,DRV042121,Rakesh Chauhan,22,Jaipur,9244658798,rakesh.chauhanrediffmail.com,Uber,Suv,Excellent,1-3 yrs,...,6.4,9.8,8.5,8.4,Fail,Flagged,On hold,Invalid_id,2026-01-28 19:33:04,True
21591,NaN,Sanjay Reddy,-28,Bangalroe,9803913500,sanjay.reddy@yahoo.com,Uber & rapido,Suv,Super,5+ yrs,...,9.6,7.5,5.6,7.0,Pass,Clear,Selected,Invalid_id,2026-05-07 21:34:12,False
49207,DRV013756,Mukesh Pandey,-47,Pune,91461603152,mukesh.pandey@gmail.com,Uber,Auto,Super,3-5 yrs,...,4.3,4.8,9.5,6.3,Pending,Clear,Rejected,Incomplete documents,2025-06-21 15:33:07,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5619,DRV010190,Manoj Sharma,28,Mumbai,91808945204,manoj.sharma@hotmail.com,Rapido,Sedan,Poor,5+ yrs,...,11.4,4.8,8.5,6.7,Pending,Clear,Selected,Invalid_id,2025-06-29 12:23:24,False
18240,DRV035093,pankaj shukla,70,Delhi,91954319287,pankaj.shukla@gmail.com,Ola,Bike,Good,3-5 yrs,...,9.4,7.5,13.0,5.9,Pending,Pending,On hold,Invalid_id,2025-01-17 02:36:54,False
6447,DRV007968,suresh rao,37,Delhi,9091817285,suresh.rao@yahoo.com,Rapido,Mini,Super,High,...,9.5,5.9,4.2,5.8,Pass,Flagged,On hold,Invalid_id,2026-01-14 20:47:24,False
9950,DRV038024,Mukesh Jha,35,Chennai,91770632498,mukesh.jha@hotmail.com,Ola,Auto,Good,5+ yrs,...,5.6,5.2,3.8,5.6,Pending,Clear,Rejected,Invalid_id,2025-07-16 16:02:15,True
44568,DRV008429,Ravi Chaudhary,35,Pune,9090992978,Ravi Chaudhary@gmail.com,Uber,Auto,Average,Fresher,...,9.4,9.5,12.6,8.0,Pending,Clear,Selected,Invalid_id,2026-08-08 03:50:14,True

In [35]:
df['driving_test_score_10'].unique()

<StringArray>
[ '4.3',  '9.3',  '6.3',  '8.7', '12.7',  '8.8',  '8.1',  '1.1', '11.6',
  '7.5',
 ...
 '12.3',  '1.6', '12.6',  '1.9', '10.6', '12.9', '11.1', '13.0',  '0.1',
  '2.0']
Length: 111, dtype: string

In [36]:
## This converts the data type from object to string.
df['driving_test_score_10'] = df['driving_test_score_10'].astype("string")
print(df['driving_test_score_10'].dtype)

string

In [37]:
df['driving_test_score_10'] = df['driving_test_score_10'].fillna('7.5')

In [38]:
df['route_knowledge_score_10'].unique()

<StringArray>
[ '5.8',  '7.5',  '9.0',  '9.6',  '6.5',  '8.6',  '8.7',  '6.4',  '7.9',
  '7.7',
 ...
 '11.4',  '0.5', '12.5',  '1.7',  '1.6',  '0.1', '10.6', '12.6',  '0.6',
 '11.6']
Length: 121, dtype: string

In [39]:
df['customer_handling_score_10'].unique()

array([ 7.7,  9. ,  5.5,  5.3,  7.9, 10.5,  9.7,  8.5, 10.7,  5.9,  6.2,
        4.9,  6.7,  6.9,  6.8, 12.3,  1. ,  3.5,  5. ,  4.1, 11.2,  8.9,
        7.6,  6.5,  3.6, 10.6,  4.3,  3.8,  3.2,  7.5,  4.6,  5.7,  3.7,
        0.9,  4.7,  4.2,  1.6,  8.8,  0.6,  6.4,  6.3,  9.8,  7. ,  9.5,
        8.3,  3.1,  9.4,  6.6,  9.1, 11.4,  7.3,  7.4, 11.5,  8.6,  9.6,
        7.2,  3. ,  3.3,  8.1,  3.4,  4.4,  4. ,  8.4,  8. ,  5.1,  5.2,
        1.9,  5.4,  4.5, 12. ,  6.1,  7.1, 11.1, 10. ,  5.6,  1.3, 12.8,
        1.2,  8.7,  3.9, 11.6,  9.2,  1.8,  7.8,  9.9,  9.3, 11.3, 11. ,
       12.6, 12.1,  8.2, 12.5,  1.7,  2. ,  5.8,  0.2, 12.4, 11.7,  0.7,
       12.9, 10.3, 12.2, 10.8,  4.8, 10.9,  1.5, 11.9, 11.8,  1.1,  0.8,
       10.4,  0.3,  0.4,  0.5,  0.1, 10.2, 13. , 12.7,  1.4, 10.1,  0. ,
        6. ])

In [40]:
## This converts the data type from object to string.
df['customer_handling_score_10'] = df['customer_handling_score_10'].astype("string")
print(df['customer_handling_score_10'].dtype)

string

In [41]:
df['customer_handling_score_10'] = df['customer_handling_score_10'].fillna('8.5')
df['customer_handling_score_10'] = df['customer_handling_score_10'].str.lstrip('-')

In [42]:
df['overall_interview_score_10'].unique()

array([ 5.3,  8.1,  6.9,  7.8,  6. ,  1.4,  8.2,  8.3,  6.7,  5.8,  7.7,
        8.8,  7.6,  6.5,  7.5,  4.1,  6.2,  1.6,  6.4,  7.2,  7.4,  3.6,
        6.3,  6.1,  5.2,  1.3,  5.6,  5.7,  5. ,  5.5,  6.8,  6.6, 10.7,
        7.3, 11.6,  4.2, 10.6, 10.5,  7.1, 12.6,  1. ,  7. ,  4.8, 11.1,
       11.9, 10.3,  4.9,  5.1,  4.5,  5.9,  8. , 12.4, 11.5, 12.9,  4.6,
        5.4,  7.9,  2. , 13. ,  9.7, 10.1,  1.8,  1.9, 11.7,  8.6,  1.5,
        8.4, 11.8, 11. ,  9.2,  8.5, 12.3, 12.5, 12.8, 12. , 11.4,  4.7,
        4.4,  1.7,  0.8,  0.7,  0.3,  8.7,  9.1,  4.3, 12.1,  0.4, 12.7,
        0.2, 11.2, 10.8,  8.9, 12.2, 10.9,  1.2, 10.2,  0.6, 11.3,  4. ,
        1.1,  0.5, 10.4,  9. ,  9.4,  3.9,  0.9,  3.8,  0.1,  9.3,  9.6,
        3.7,  9.5,  3.5,  9.8,  3.4])

In [43]:
## This converts the data type from object to string.
df['overall_interview_score_10'] = df['overall_interview_score_10'].astype("string")
print(df['overall_interview_score_10'].dtype)

string

In [44]:
df['overall_interview_score_10'] = df['overall_interview_score_10'].fillna('8.8')
df['overall_interview_score_10'] = df['overall_interview_score_10'].str.lstrip('-')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
19783,DRV019006,Naveen Gupta,42,Hyderabad,91479299289,Naveen Gupta@gmail.com,Rapido,Tricycle,Super,High,...,5.2,7.0,4.9,6.8,Pass,Pending,Pending,Invalid_id,2025-07-14 11:23:43,False
149,DRV046760,Harish Tiwari,54,Ahmedabad,9708521522,harish.tiwari@rediffmail.com,Rapido,Auto,Good,3-5 yrs,...,6.5,9.8,6.1,8.0,Distinction,Pending,Rejected,Invalid_id,2026-01-21 07:20:23,False
39684,DRV018490,Pradeep Gupta,34,Jaipur,9420186805,pradeep.gupta@gmail.com,Rapido,Bike,Good,5+ yrs,...,8.7,4.3,9.5,6.6,Fail,Clear,Rejected,Invalid_id,2025-10-10 03:41:53,True
12825,DRV025719,Ganesh Nair,53,Hydrabad,9059729421,ganesh.nair@yahoo.com,Rapido,Auto,Good,Fresher,...,8.1,9.0,7.4,7.3,Fail,Flagged,On hold,Invalid_id,2026-04-14 07:26:40,False
45617,DRV037526,Pankaj Kumar,36,Mumbai,9849341194,pankaj.kumar@rediffmail.com,Rapido,Bike,Average,High,...,9.2,8.9,9.7,8.2,Pass,Clear,Selected,Invalid_id,2026-04-30 12:28:11,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13383,DRV009188,Dinesh Dubey,70,Pune,9622691102,dinesh.dubey@yahoo.com,Rapido,Bike,Good,8+ yrs,...,7.5,5.1,7.7,5.8,Pending,Clear,Selected,Invalid_id,2025-06-23 19:44:19,False
20623,DRV045901,Sanjay Tiwari,29,Jaipur,9840083434,sanjay.tiwari@hotmail.com,Uber & rapido,Suv,Excellent,4+ yrs,...,7.7,8.1,6.6,7.7,Pass,Flagged,Rejected,Invalid_id,2025-10-09 18:14:06,True
21535,DRV011788,GIRISH PATEL,26,Jaipur,91517009364,GIRISH PATEL@gmail.com,Ola,Suv,Excellent,1-3 yrs,...,9.2,7.1,8.0,8.6,Fail,Pending,Selected,Invalid_id,2025-05-09 06:04:04,False
49292,DRV012903,Ravi Jha,53,Lucknow,91348223602,ravi.jha@yahoo.com,Rapido,Mini,Poor,4+ yrs,...,6.3,7.7,1.2,6.8,Fail,Pending,On hold,Poor communication,2026-05-17 13:50:31,True
21160,DRV028236,Ravi Singh,22,Jaipur,9652094763,ravi.singh@yahoo.com,Rapido,Auto,Good,1-3 yrs,...,4.4,8.8,7.8,7.0,Fail,Pending,Selected,Invalid_id,2025-08-17 19:25:03,False

In [45]:
df['document_verification'].unique()

array(['Fail', 'Distinction', 'Average', 'Pass', 'Pending', 'Credit',
       'Exceptional', 'Fair'], dtype=object)

In [46]:
## This converts the data type from object to string.
df['document_verification'] = df['document_verification'].astype("string")
print(df['document_verification'].dtype)

string

In [47]:
df['document_verification'] = df['document_verification'].str.capitalize()
df['document_verification'] = df['document_verification'].fillna('Distinction')
df['document_verification'] = df['document_verification'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999': '90',
    #'0-1 yr' : '4+ yrs',
    #'Unknown':'High',
    'None':'Credit',    
    #'Avg': 'Average',
    #'poor': 'Super',
    'Unknown':'Average',
    'Na': 'Fair',
    '-': 'Exceptional',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
49305,DRV017303,Hitesh Chaudhary,48,Kolkata,9431130666,hitesh.chaudhary@rediffmail.com,Uber,Bike,Poor,Fresher,...,9.0,10.8,7.7,7.2,Credit,Flagged,Selected,Invalid_id,2025-02-16 12:41:03,False
38590,NaN,Dinesh Dubey,20,Pune,9050073460,Dinesh Dubey@gmail.com,Uber,Bike,Average,4+ yrs,...,9.2,4.3,7.8,8.8,Pending,Flagged,On hold,Invalid_id,2025-12-30 22:24:07,True
49496,DRV042843,Amit Gupta,70,Hyderabad,9842839802,amit.gupta@gmail,Ola,Mini,Super,Fresher,...,4.8,9.3,10.0,8.8,Pass,Clear,Selected,Invalid_id,2025-09-22 05:54:46,True
40788,DRV046846,Yogesh Sharma,24,Kolkata,9252849914,yogesh.sharma@gmail.com,Uber,Bike,Average,1-3 yrs,...,6.7,8.7,0.0,6.5,Distinction,Pending,On hold,Invalid_id,2025-01-14 12:29:19,True
12319,DRV023732,Ravi Reddy,27,Delhi,9332769309,ravi.reddy@gmail.com,Uber & rapido,Bike,Poor,4+ yrs,...,9.5,8.0,8.5,1.6,Distinction,Clear,Selected,Invalid_id,2026-07-12 22:40:44,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14836,DRV023382,Ravi Rao,35,Mumbai,9047630077,ravi.rao@gmail.com,Uber,Suv,Good,Fresher,...,7.0,9.7,9.3,8.8,Pass,Clear,Selected,Background check failed,2025-08-06 18:06:26,True
22091,DRV023523,Bharat Shukla,35,Hyderabad,9109836761,bharat.shukla@hotmail.com,Rapido,Auto,Average,3-5 yrs,...,8.0,7.5,3.2,6.6,Pass,Clear,Selected,Invalid_id,2025-10-22 00:50:58,False
18319,DRV024137,Umesh Kumar,-41,Bangalore,9096383495,umesh.kumar@rediffmail.com,Uber & rapido,Auto,Super,4+ yrs,...,7.5,7.0,9.3,7.7,Pass,Pending,Rejected,Invalid_id,2025-05-16 12:57:17,False
12661,DRV028896,Dinesh Jha,20,Jaipur,9048048842,dinesh.jha@hotmail,Rapido,Auto,Good,4+ yrs,...,4.2,7.8,3.9,11.5,Distinction,Flagged,On hold,Invalid_id,2026-08-02 15:29:28,True
40209,DRV025159,Sunil Tripathi,51,Delhi,9331171045,sunil.tripathi@yahoo.com,Rapido,Sedan,Excellent,5+ yrs,...,11.8,3.4,3.9,5.2,Pending,Pending,Selected,Invalid_id,2025-04-23 14:02:55,True

In [48]:
df['document_verification'].unique()

<StringArray>
[       'Fail', 'Distinction',     'Average',        'Pass',     'Pending',
      'Credit', 'Exceptional',        'Fair']
Length: 8, dtype: string

In [49]:
df['background_check_status'].unique()

array(['Clear', 'Pending', 'Flagged'], dtype=object)

In [50]:
## This converts the data type from object to string.
df['background_check_status'] = df['background_check_status'].astype("string")
print(df['background_check_status'].dtype)

string

In [51]:
df['background_check_status'] = df['background_check_status'].str.capitalize()
df['background_check_status'] = df['background_check_status'].fillna('Clear')
df['background_check_status'] = df['background_check_status'].replace({
'Na': 'Clear', 
'Unknown': 'Clear', 
'None': 'Pending', 
'-': 'Clear'
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
47888,DRV018318,Ravi Reddy,25,Delhi,9950293263,ravi.reddy@yahoo.com,Rapido,Auto,Poor,5+ yrs,...,9.3,6.2,3.2,8.8,Distinction,Flagged,Selected,Invalid_id,2025-06-05 17:44:37,False
2292,DRV046972,Harish Sharma,35,Chennai,9764845321,harish.sharma@gmail.com,Uber,Mini,Super,3-5 yrs,...,6.7,7.3,7.3,6.8,Fail,Clear,Rejected,Invalid_id,2026-02-06 14:44:48,False
35473,DRV016645,Pradeep Sharma,45,Delhi,91018174466,pradeep.sharma@rediffmail.com,Uber,Auto,Super,4+ yrs,...,8.7,7.5,3.4,6.9,Pending,Flagged,Selected,Invalid_id,2025-06-22 22:43:57,False
38000,DRV040669,Amit Reddy,34,Lucknow,91210623709,amit.reddy@rediffmail.com,Rapido,Bike,Average,1-3 yrs,...,7.3,8.3,5.8,11.1,Pass,Pending,On hold,Invalid_id,2025-03-14 15:31:46,True
40060,DRV030379,Mukesh Shukla,28,Mumabi,9401273279,mukesh.shukla@yahoo.com,Rapido,Mini,Poor,5+ yrs,...,5.7,4.2,5.5,4.7,Pending,Clear,Rejected,Invalid_id,2026-05-28 20:53:17,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39628,DRV047513,Naveen Nair,39,Mumbai,9252024022,naveen.nair@yahoo.com,Ola,Auto,Super,3-5 yrs,...,4.0,10.5,5.5,8.8,Fail,Clear,Rejected,Poor communication,2025-08-30 19:25:29,False
22082,DRV042553,Yogesh Patel,unknown,Bangalore,91896784929,yogesh.patel@yahoo.com,Uber,Mini,Super,Fresher,...,4.9,7.8,9.2,7.9,Distinction,Pending,Rejected,Background check failed,2026-06-04 01:38:10,False
20328,DRV043325,Mahesh Chaudhary,43,Delhi,9214182637,mahesh.chaudhary@@gmail.com,Rapido,Bike,Poor,Fresher,...,4.8,6.2,4.9,6.1,Pass,Pending,Selected,Invalid_id,2025-03-23 02:05:04,False
7685,DRV020381,Bharat Srivastava,27,Ahmedabad,9426235252,bharat.srivastava@hotmail.com,Rapido,Auto,Super,Fresher,...,4.0,12.1,4.9,1.2,Pending,Pending,Selected,Invalid_id,2025-03-09 06:58:44,False
34514,DRV008085,Mahesh Reddy,35,Mumabi,9694439383,mahesh.reddy@@hotmail.com,Rapido,Tricycle,Super,4+ yrs,...,10.2,5.3,6.7,5.6,Fail,Pending,On hold,Invalid_id,2025-01-16 12:45:52,True

In [52]:
df['background_check_status'].unique()

<StringArray>
['Clear', 'Pending', 'Flagged']
Length: 3, dtype: string

In [53]:
df['interview_result'].unique()

array(['On hold', 'Selected', 'Rejected', 'Waitlist', 'Pending'],
      dtype=object)

In [54]:
## This converts the data type from object to string.
df['interview_result'] = df['interview_result'].astype("string")
print(df['interview_result'].dtype)

string

In [55]:
df['interview_result'] = df['interview_result'].str.capitalize()
df['interview_result'] = df['interview_result'].fillna('Selected')
df['interview_result'] = df['interview_result'].replace({
'Na': 'Selected', 
'Unknown': 'Selected', 
'None': 'Pending', 
'-': 'Pending'
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
46457,DRV049310,Mukesh Nair,21,Bangalore,9630034749,mukesh.nair@hotmail.com,Uber,Auto,Average,5+ yrs,...,6.9,7.5,5.2,5.1,Pass,Flagged,Selected,Invalid_id,2026-06-23 16:43:31,True
20787,DRV025179,UMESH MISHRA,41,Hyderabad,9620924,umesh.mishra@rediffmail.com,Uber,Suv,Good,4+ yrs,...,6.8,6.4,4.9,7.0,Exceptional,Pending,Selected,Invalid_id,2025-12-09 00:23:25,False
38072,DRV015193,Rajesh Verma,70,Hyderabad,9948947141,rajesh.verma@@hotmail.com,Rapido,Bike,Good,5+ yrs,...,5.0,4.6,9.2,6.8,Pending,Clear,Rejected,Incomplete documents,2026-05-12 17:06:10,False
32777,DRV018494,Naveen Verma,38,Bangalore,9508225778,naveen.verma@@yahoo.com,Uber,Sedan,Good,5+ yrs,...,8.6,6.2,8.3,7.0,Fail,Clear,On hold,Invalid_id,2025-04-15 15:22:10,True
3973,DRV042089,Mukesh Tiwari,45,Kolkata,9462176,mukesh.tiwari@@gmail.com,Rapido,Mini,Super,5+ yrs,...,7.0,7.5,5.2,5.8,Distinction,Pending,Rejected,Invalid_id,2025-01-10 11:14:19,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43024,DRV015300,Yogesh Chaudhary,47,Pune,9936075670,yogesh.chaudhary@gmail.com,Rapido,Suv,Good,3-5 yrs,...,8.7,12.6,8.5,7.1,Fair,Clear,Selected,Invalid_id,2026-02-11 07:17:33,False
19102,DRV006357,MUKESH SHARMA,999,Jaipur,9878881,mukesh.sharmarediffmail.com,Rapido,Sedan,Fair,1-3 yrs,...,7.4,7.3,4.5,7.0,Distinction,Clear,Selected,Invalid_id,2026-03-12 16:51:56,False
28099,DRV015215,Ganesh Singh,48,Jaipur,91083224384,ganesh.singh@rediffmail.com,Uber,Bike,Super,1-3 yrs,...,4.5,9.5,5.6,7.3,Distinction,Flagged,On hold,Invalid_id,2025-12-09 01:22:07,True
7106,DRV032406,UMESH TRIPATHI,49,Jaipur,9673522550,umesh.tripathi@@gmail.com,Uber,Suv,Good,4+ yrs,...,8.2,3.7,9.4,7.4,Distinction,Clear,Selected,Invalid_id,2026-06-20 18:44:35,False
48983,DRV007314,Yogesh Dubey,39,Jaipur,9888394926,yogesh.dubey@hotmail.com,Uber & rapido,Bike,Good,5+ yrs,...,9.5,9.1,9.2,13.0,Pass,Clear,Selected,Failed driving test,2025-05-03 19:42:09,True

In [56]:
df['interview_result'].unique()

<StringArray>
['On hold', 'Selected', 'Rejected', 'Waitlist', 'Pending']
Length: 5, dtype: string

In [57]:
df['rejection_reason'].unique()

array(['Invalid_id', 'Low rating history', 'Not applicable',
       'Poor communication', 'Incomplete documents',
       'Vehicle age too old', 'Background check failed',
       'Failed driving test', 'Selected'], dtype=object)

In [58]:
## This converts the data type from object to string.
df['rejection_reason'] = df['rejection_reason'].astype("string")
print(df['rejection_reason'].dtype)

string

In [59]:
df['rejection_reason'] = df['rejection_reason'].str.capitalize()
df['rejection_reason'] = df['rejection_reason'].fillna('Invalid_id')
df['rejection_reason'] = df['rejection_reason'].replace({
'Na': 'Invalid_id', 
'Unknown': 'Selected', 
'None': 'Poor communication', 
'-': 'Background check failed'
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
2335,DRV025470,R@kesh Ch@uh@n,-33,Lucknow,91904777665,rakesh.chauhan@yahoo.com,Rapido,Sedan,Excellent,7+ yrs,...,9.5,4.0,8.8,7.2,Fail,Pending,Selected,Invalid_id,2025-09-01 21:55:51,True
37554,DRV026895,Rakesh Yadav,32 yrs,Chennai,9718857519,rakesh.yadav@@yahoo.com,Ola,Suv,Excellent,5+ yrs,...,9.0,7.5,10.3,7.4,Distinction,Pending,Selected,Invalid_id,2025-01-01 00:17:09,True
13420,DRV030849,Dinesh Trip@thi,44,Kolkata,9129342229,dinesh.tripathi@yahoo.com,Uber,Auto,Average,8+ yrs,...,9.1,4.0,4.1,5.7,Pass,Clear,On hold,Invalid_id,2025-01-26 05:15:40,True
24384,DRV013355,Amit Rao,54,Ahmedabad,9850207169,amit.rao@yahoo,Uber & rapido,Bike,Excellent,1-3 yrs,...,9.3,8.9,9.2,9.2,Distinction,Flagged,Selected,Invalid_id,2026-03-24 20:26:29,False
32778,DRV046497,Ravi Pandey,48,Hyderabad,91657594928,ravi.pandey@gmail.com,Ola,Mini,Poor,5+ yrs,...,1.5,3.4,9.1,7.5,Distinction,Clear,Selected,Invalid_id,2025-03-11 18:14:13,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2151,DRV033845,Deepak Jha,22,Delhi,9873755794,deepak.jha@yahoo.com,Uber,Suv,Super,1-3 yrs,...,5.2,3.9,3.5,4.2,Fail,Flagged,Rejected,Poor communication,2025-07-19 21:57:56,True
38425,DRV038472,Vikr@m Trip@thi,42,Chennai,9770330584,vikram.tripathi@yahoo.com,Uber,Bike,Good,Fresher,...,7.9,3.4,8.5,6.5,Pass,Clear,Selected,Invalid_id,2026-05-08 11:50:22,True
13092,DRV011274,MAHESH PANDEY,24,Mumbai,9850049666,mahesh.pandey@hotmail.com,Uber,Suv,Good,5+ yrs,...,7.5,3.7,7.4,5.8,Distinction,Clear,On hold,Invalid_id,2026-05-17 03:45:20,True
12735,DRV033587,Anil Shukla,43,Hyderabad,9980200458,anil.shukla@hotmail.com,Rapido,Suv,Excellent,5+ yrs,...,4.1,4.6,9.5,6.3,Pass,Clear,Rejected,Invalid_id,2026-03-26 12:07:24,True
46811,DRV034274,harish yadav,48,Hyderabad,9341182848,harish.yadav@hotmail.com,Rapido,Bike,Poor,4+ yrs,...,5.2,3.2,4.7,12.7,Distinction,Flagged,Rejected,Invalid_id,2026-05-19 09:20:32,True

In [60]:
df['rejection_reason'].unique()

<StringArray>
[             'Invalid_id',      'Low rating history',
          'Not applicable',      'Poor communication',
    'Incomplete documents',     'Vehicle age too old',
 'Background check failed',     'Failed driving test',
                'Selected']
Length: 9, dtype: string

In [61]:
df['onboarding_date'].unique()

array(['2025-02-10 22:07:31', '2026-01-12 11:59:18',
       '2021-04-19 00:00:00', ..., '2025-09-26 06:05:30',
       '2026-04-12 21:14:46', '2025-05-06 04:10:59'], dtype=object)

In [62]:
## This code generates random date values for the onboarding column. 

import pandas as pd
import numpy as np

df['onboarding_date'] = pd.to_datetime(df['onboarding_date'], errors='coerce')

start = pd.Timestamp("2025-01-01")
end = pd.Timestamp("2026-08-11")

mask = df["onboarding_date"].isna()

df.loc[mask, "onboarding_date"] = pd.to_datetime(
    np.random.randint(
        start.value // 10**9,
        end.value // 10**9,
        size=mask.sum()
    ),
    unit="s"
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
16979,DRV045009,Ravi Dubey,47,Kolkata,9036809413,ravi.dubey@yahoo.com,Rapido,Bike,Poor,1-3 yrs,...,7.8,3.6,3.5,5.5,Pending,Flagged,On hold,Selected,2026-06-26 03:03:58,True
37496,DRV001944,Ravi Chaudhary,23,Ahmedabad,91343589431,ravi.chaudhary@gmail.com,Rapido,Motorbike,Excellent,3-5 yrs,...,7.6,3.3,8.2,7.2,Pending,Clear,Selected,Invalid_id,2026-07-25 08:10:49,False
10047,DRV048484,Umesh Dubey,26,Jaipur,9266548166,umesh.dubey@yahoo.com,Uber,Bike,Average,Fresher,...,7.9,7.5,6.9,6.9,Pending,Flagged,Selected,Invalid_id,2025-06-10 00:57:33,False
6248,DRV044123,Vikram Verma,51,Kolkata,9145153425,vikram.verma@yahoo.com,Uber,Suv,Average,Fresher,...,6.5,3.4,5.9,5.3,Distinction,Flagged,Selected,Invalid_id,2025-05-07 13:35:07,True
4173,DRV020191,mahesh sharma,52,Dlhi,9282386964,mahesh.sharma@gmail.com,Bolt,Bike,Super,4+ yrs,...,7.5,12.4,7.1,1.5,Distinction,Clear,Selected,Invalid_id,2026-07-31 03:24:23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18829,DRV037112,Umesh Shukla,50,Ahmedabad,91769787076,umesh.shukla@hotmail,Uber,Bike,Beautiful,4+ yrs,...,7.8,7.5,12.3,8.8,Pass,Pending,Selected,Invalid_id,2026-02-17 16:18:56,False
48597,DRV028489,Vikram Mishra,70,Pune,9727750332,vikram.mishra@gmail.com,Rapido,Sedan,Excellent,1-3 yrs,...,5.0,4.4,0.5,11.1,Pass,Clear,Selected,Invalid_id,2026-04-03 15:06:38,True
35352,DRV010603,Ramesh Gupta,34,Ahmedabad,9060904540,ramesh.gupta@gmail,Bolt,Suv,Good,Fresher,...,7.9,9.5,3.5,7.0,Pending,Clear,Selected,Invalid_id,2025-04-09 02:58:32,True
11974,DRV015264,Girish Gupta,38,Lucknow,9633396945,girish.gupta@hotmail.com,Rapido,Suv,Good,High,...,6.1,4.2,8.7,6.6,Distinction,Clear,Selected,Invalid_id,2026-05-22 06:34:03,True
17639,DRV042527,Rakesh Reddy,999,Delhi,91544432487,rakesh.reddy@yahoo.com,Uber,Suv,Good,Fresher,...,6.5,7.9,8.1,8.8,Pending,Flagged,Selected,Invalid_id,2025-08-03 01:44:26,True

In [63]:
df['onboarding_date'].unique()

<DatetimeArray>
['2025-02-10 22:07:31', '2026-01-12 11:59:18', '2021-04-19 00:00:00',
 '2021-05-27 00:00:00', '2026-02-08 13:31:18', '2023-04-01 00:00:00',
 '2023-08-08 00:00:00', '2022-02-06 00:00:00', '2025-12-30 07:03:08',
 '2025-07-04 10:48:53',
 ...
 '2025-11-25 01:15:51', '2026-01-07 07:46:46', '2026-04-23 02:16:25',
 '2026-05-06 22:04:05', '2025-06-23 16:04:25', '2025-10-09 23:03:17',
 '2025-06-21 04:21:16', '2025-09-26 06:05:30', '2026-04-12 21:14:46',
 '2025-05-06 04:10:59']
Length: 49969, dtype: datetime64[ns]

In [64]:
df['is_currently_active'].unique()

array([False,  True])

In [65]:
## This converts the data type from object to string.
df['is_currently_active'] = df['is_currently_active'].astype("string")
print(df['is_currently_active'].dtype)

string

In [66]:
df['is_currently_active'] = df['is_currently_active'].str.capitalize()
df['is_currently_active'] = df['is_currently_active'].fillna('True')
df['is_currently_active'] = df['is_currently_active'].replace({
'No':'False', 
'0': 'False', 
'1': 'True', 
'N': 'False',
'Y': 'True',
'Yes': 'True',
})
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
24559,DRV015427,Deepak Pandey,36 yrs,Dlhi,9832333754,deepak.pandey@hotmail.com,Ola,Bike,Super,3-5 yrs,...,8.8,4.7,6.6,7.2,Distinction,Clear,Selected,Invalid_id,2025-05-23 13:23:47,True
3267,DRV030086,Sunil Jha,-25,Kolkata,9879580901,sunil.jha@rediffmail.com,Ola,Sedan,Super,3-5 yrs,...,9.0,8.7,5.9,6.9,Distinction,Pending,Pending,Invalid_id,2026-07-26 21:45:13,False
39431,DRV002013,Sanjay Srivastava,39,Jaipur,9080942629,sanjay.srivastava@hotmail.com,Uber,Suv,Average,5+ yrs,...,10.9,8.6,12.9,7.2,Fair,Flagged,On hold,Invalid_id,2025-11-26 12:40:08,False
2760,DRV002791,Mahesh Nair,22,Hyderabad,9458156147,mahesh.nair@hotmail.com,Rapido,Sedan,Excellent,Fresher,...,5.2,5.1,1.0,6.4,Pass,Clear,Rejected,Poor communication,2025-10-22 22:46:26,False
48114,DRV025190,Pankaj Verma,28,Hyderabad,9729491,pankaj.verma@gmail.com,Uber,Catapiller,Super,4+ yrs,...,7.5,7.5,6.3,6.5,Fail,Clear,On hold,Invalid_id,2025-05-02 22:18:00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31571,DRV030774,Pradeep Kumar,24,Mumbai,9582335603,pradeep.kumar@yahoo.com,Uber,Auto,Good,5+ yrs,...,9.4,8.2,5.4,8.8,Pass,Pending,Selected,Invalid_id,2025-08-15 12:19:50,False
42290,DRV037147,Anil Chauhan,43,Delhi,9357628053,anil.chauhan@hotmail.com,Uber,Sedan,Super,Fresher,...,7.2,7.1,9.4,11.9,Fail,Flagged,Selected,Invalid_id,2025-02-17 22:19:37,True
39423,DRV002712,Pr@deep R@o,21,Chennai,9589581955,Pr@deep R@o@gmail.com,Rapido,Auto,Super,Fresher,...,8.0,7.1,7.9,0.9,Distinction,Clear,Selected,Invalid_id,2025-01-08 18:28:24,False
45255,DRV044754,Dinesh Shukla,33,Lucknow,9013619,Dinesh Shukla @gmail.com,Rapido,Auto,Average,Fresher,...,7.4,8.6,5.2,8.8,Pass,Pending,Selected,Invalid_id,2025-03-28 13:22:25,True
20686,DRV044528,PANKAJ SHARMA,22,Ahmedabad,91469154044,pankaj.sharma@rediffmail.com,Uber,Suv,Excellent,1-3 yrs,...,6.3,4.2,8.5,7.2,Distinction,Flagged,Selected,Invalid_id,2025-01-28 12:11:02,True

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   driver_id                   49005 non-null  object
 1   driver_name                 50000 non-null  object
 2   age                         50000 non-null  string
 3   city                        50000 non-null  string
 4   phone                       50000 non-null  string
 5   email                       50000 non-null  string
 6   platform                    50000 non-null  string
 7   vehicle_type                50000 non-null  string
 8   vehicle_condition           50000 non-null  string
 9   experience_level            50000 non-null  string
 10  preferred_shift             38773 non-null  object
 11  reason_for_joining          38637 non-null  object
 12  languages_known             47847 non-null  object
 13  overall_driver_rating       46033 non-null  object
 14  total_trips_completed       45930 non-null  float64
 15  trip_completion_rate_%      45565 non-null  float64
 16  cancellation_rate_%         45484 non-null  float64
 17  avg_daily_earnings_INR      47489 non-null  object
 18  total_complaints            45965 non-null  float64
 19  total_compliments           46024 non-null  float64
 20  peak_hour_availability      50000 non-null  object
 21  interview_date              45067 non-null  object
 22  communication_score_10      45416 non-null  float64
 23  driving_test_score_10       50000 non-null  string
 24  route_knowledge_score_10    50000 non-null  string
 25  customer_handling_score_10  50000 non-null  string
 26  overall_interview_score_10  50000 non-null  string
 27  document_verification       50000 non-null  string
 28  background_check_status     50000 non-null  string
 29  interview_result            50000 non-null  string
 30  rejection_reason            50000 non-null  string
 31  onboarding_date             50000 non-null  datetime64[ns]
 32  is_currently_active         50000 non-null  string
dtypes: datetime64[ns](1), float64(6), object(9), string(17)
memory usage: 12.6+ MB

In [68]:
## This converts the data type from object to string.
df['preferred_shift'] = df['preferred_shift'].astype("string")
print(df['preferred_shift'].dtype)

string

In [69]:
df['preferred_shift'] = df['preferred_shift'].str.capitalize()
df['preferred_shift'] = df['preferred_shift'].fillna('Afternoon')
df['preferred_shift'] = df['preferred_shift'].replace({
'Na': 'Evening', 
'Unknown': 'Midweek', 
'None': 'Twice_Weekly', 
'-': 'Weekend',
'Night ': 'Morning',
})

In [70]:
df['preferred_shift'].unique()

<StringArray>
[       'Night',      'Weekend',    'Afternoon',          'Day',
         'Both',      'Morning',      'Midweek', 'Twice_Weekly',
      'Evening']
Length: 9, dtype: string

In [71]:
df['driver_id'].unique()

array(['DRV016649', 'DRV032785', 'DRV011323', ..., 'DRV026085',
       'DRV025771', 'DRV025843'], dtype=object)

In [72]:
## This converts the data type from object to string.
df['driver_id'] = df['driver_id'].astype("string")
print(df['driver_id'].dtype)

string

In [73]:
import numpy as np

conversion = df['driver_id']= np.nan
print(conversion)

nan

In [74]:
##This code creates a driver_id for the drivers using their names, where they have no existing emails.

#DRV037476 

import numpy as np

df["driver_id"] = [
    f"DRV{np.random.randint(0, 1000000):06d}"
    for _ in range(len(df))
]
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
42062,DRV276645,Pradeep Rao,35,Jaipur,9423202124,pradeep.rao@@hotmail.com,Na,Suv,Poor,5+ yrs,...,4.2,0.9,8.5,4.5,Fail,Clear,Rejected,Selected,2026-06-18 20:01:32,False
16253,DRV711456,hitesh verma,27,Ahmedabad,9772497478,hitesh.verma@hotmail.com,Uber,Bike,Excellent,5+ yrs,...,6.7,9.6,5.9,7.8,Pass,Clear,Selected,Invalid_id,2025-09-29 01:40:25,True
5030,DRV958314,Lokesh Dubey,28,Kolkata,9623465163,lokesh.dubey@yahoo.com,Uber & rapido,Suv,Super,Fresher,...,8.5,3.7,7.9,6.2,Distinction,Clear,Selected,Invalid_id,2026-07-03 00:04:46,False
34412,DRV061874,Rajesh Kumar,24,Pune,9462217382,rajesh.kumar@rediffmail.com,Rapido,Mini,Super,Fresher,...,8.5,5.6,0.2,8.2,Distinction,Clear,Selected,Invalid_id,2025-07-21 03:05:14,True
35498,DRV329675,Umesh Dubey,55,Pune,9956812140,umesh.dubey@gmail.com,Uber,Bike,Poor,High,...,11.2,8.0,7.6,0.2,Distinction,Pending,Selected,Invalid_id,2026-08-10 18:41:43,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13863,DRV488462,Ravi Kumar,25,Kolkata,9532554186,ravi.kumar@yahoo.com,Uber & rapido,Auto,Poor,3-5 yrs,...,7.5,8.6,5.0,6.6,Distinction,Clear,Rejected,Not applicable,2025-05-29 10:10:49,True
24780,DRV927207,Ramesh Chauhan,41,Pune,91246796066,ramesh.chauhan@rediffmail.com,Uber,Suv,Excellent,High,...,9.0,3.4,6.8,6.6,Pending,Clear,Selected,Selected,2025-02-06 08:47:48,True
12478,DRV566160,YOGESH PANDEY,999,Pune,9324584618,yogesh.pandey@gmail.com,Uber,Mini,Average,4+ yrs,...,8.1,3.2,4.8,6.3,Pending,Flagged,Rejected,Low rating history,2025-06-02 11:24:23,True
7091,DRV916938,Vijay Patel,41,Pune,9281267229,vijay.patel@hotmail.com,Rapido,Suv,Poor,Fresher,...,9.8,8.4,7.6,8.7,Pass,Clear,Selected,Invalid_id,2026-05-10 08:43:48,False
21320,DRV473122,Hitesh Shukla,23,Lucknow,9259538465,hitesh.shukla@rediffmail.com,Ola,Mini,Average,Fresher,...,8.1,10.7,4.4,6.7,Pass,Pending,Selected,Invalid_id,2025-01-25 06:11:48,False

In [75]:
df['driver_id'].unique()

array(['DRV178116', 'DRV800760', 'DRV689158', ..., 'DRV829669',
       'DRV941518', 'DRV085131'], dtype=object)

In [76]:
## This converts the data type from object to string.
df['reason_for_joining'] = df['reason_for_joining'].astype("string")
print(df['reason_for_joining'].dtype)

string

In [77]:
df['reason_for_joining'] = df['reason_for_joining'].str.capitalize()
df['reason_for_joining'] = df['reason_for_joining'].fillna('Part_Time')
df['reason_for_joining'] = df['reason_for_joining'].replace({
'Na': 'Internship', 
'Unknown': 'Trainer', 
'None': 'Passion', 
'-': 'Passive_Income',
})

In [78]:
df['reason_for_joining'].unique()

<StringArray>
[      'Side hustle',         'Part_Time',     'Not disclosed',
      'Extra income', 'Lost previous job',   'Family pressure',
           'Passion',     'Full time job',    'Flexible hours',
           'Trainer',        'Internship',    'Passive_Income']
Length: 12, dtype: string

In [79]:
## This converts the data type from object to string.
df['languages_known'] = df['languages_known'].astype("string")
print(df['languages_known'].dtype)

string

In [80]:
df['languages_known'] = df['languages_known'].str.capitalize()
df['languages_known'] = df['languages_known'].fillna('English, Igbo, Yoruba')

In [81]:
df['languages_known'].unique()

<StringArray>
[      'Hindi, tamil, telugu',    'Kannada, tamil, marathi',
      'Tamil, marathi, hindi', 'Gujarati, kannada, marathi',
              'Hindi, telugu',             'English, tamil',
    'English, tamil, marathi',                      'Hindi',
   'Tamil, gujarati, bengali',                    'Marathi',
 ...
      'English, hindi, tamil',    'Marathi, hindi, bengali',
   'Marathi, gujarati, tamil',   'English, gujarati, tamil',
    'Kannada, hindi, english',   'Gujarati, tamil, marathi',
   'Marathi, gujarati, hindi',  'Kannada, english, bengali',
  'Gujarati, bengali, telugu',   'Gujarati, kannada, hindi']
Length: 405, dtype: string

In [82]:
## This converts the data type from object to string.
df['overall_driver_rating'] = df['overall_driver_rating'].astype("string")
print(df['overall_driver_rating'].dtype)

string

In [83]:
df['overall_driver_rating'] = df['overall_driver_rating'].fillna('7.7')
df['overall_driver_rating'] = df['overall_driver_rating'].str.lstrip('-')
df['overall_driver_rating'] = df['overall_driver_rating'].replace({
#'Na': 'Internship', 
#'Unknown': 'Trainer', 
#'None': 'Passion', 
#'-': 'Passive_Income',
'unrated': '6.9',
})

In [84]:
df['overall_driver_rating'].unique()

<StringArray>
['7.7', '5.8', '4.8', '4.4', '3.1', '4.3', '3.9', '3.3', '4.9', '3.6', '4.6',
 '2.6', '3.2', '6.9', '3.4', '5.6', '3.8', '6.4', '2.9', '5.2', '4.1', '3.5',
 '5.5', '1.7', '4.5', '4.2', '4.0', '3.0', '1.0', '5.7', '4.7', '2.5', '3.7',
 '2.7', '2.8', '6.0', '1.2', '1.6', '1.3', '0.6', '5.3', '6.1', '6.2', '5.0',
 '0.8', '5.9', '0.2', '0.4', '6.5', '5.4', '1.9', '5.1', '1.1', '1.4', '1.5',
 '0.9', '6.3', '0.5', '0.7', '1.8', '0.3', '2.0', '0.1']
Length: 63, dtype: string

In [85]:
## This converts the data type from object to string.
df['total_trips_completed'] = df['total_trips_completed'].astype("string")
print(df['total_trips_completed'].dtype)

string

In [86]:
#df['total_trips_completed'] = df['total_trips_completed'].fillna('7450')
#df['total_trips_completed'] = df['total_trips_completed'].str.lstrip('-')

import numpy as np

df['total_trips_completed'] = np.random.randint(2000, 7001, size=len(df))

In [87]:
df['total_trips_completed'].unique()

array([6485, 6198, 2906, ..., 2164, 2045, 6705])

In [88]:
## This converts the data type from object to string.
df['trip_completion_rate_%'] = df['trip_completion_rate_%'].astype("string")
print(df['trip_completion_rate_%'].dtype)

string

In [89]:
df['trip_completion_rate_%'].unique()

<StringArray>
[ '68.4',  '99.8',  '75.8',  '64.4',  '97.6',  '72.8',  '84.6',  '94.8',
    <NA>,  '63.1',
 ...
  '96.0', '100.7',  '-1.2',  '90.0', '102.0',  '80.3',  '75.3',  '97.0',
 '103.0',  '89.3']
Length: 452, dtype: string

In [90]:
df['trip_completion_rate_%'] = df['trip_completion_rate_%'].fillna('74.5')
df['trip_completion_rate_%'] = df['trip_completion_rate_%'].str.lstrip('-')

In [91]:
#df.to_csv("cleaned_uber_rapido_driver.csv", index=False)

print(df.isna().sum())

driver_id                        0
driver_name                      0
age                              0
city                             0
phone                            0
email                            0
platform                         0
vehicle_type                     0
vehicle_condition                0
experience_level                 0
preferred_shift                  0
reason_for_joining               0
languages_known                  0
overall_driver_rating            0
total_trips_completed            0
trip_completion_rate_%           0
cancellation_rate_%           4516
avg_daily_earnings_INR        2511
total_complaints              4035
total_compliments             3976
peak_hour_availability           0
interview_date                4933
communication_score_10        4584
driving_test_score_10            0
route_knowledge_score_10         0
customer_handling_score_10       0
overall_interview_score_10       0
document_verification            0
background_check_status          0
interview_result                 0
rejection_reason                 0
onboarding_date                  0
is_currently_active              0
dtype: int64

In [92]:
## This converts the data type from object to string.
df['cancellation_rate_%'] = df['cancellation_rate_%'].astype("string")
print(df['cancellation_rate_%'].dtype)

string

In [93]:
df['cancellation_rate_%'] = df['cancellation_rate_%'].fillna('44.5')

In [94]:
df['cancellation_rate_%'].unique()

<StringArray>
[ '17.5',  '28.5',  '29.3',  '21.7',  '33.2',   '0.1',  '33.4',  '11.4',
   '2.3',   '3.4',
 ...
 '101.3',   '9.1',  '30.9',  '15.3',   '0.2', '100.2',  '27.8',  '16.2',
  '28.3', '103.0']
Length: 402, dtype: string

In [95]:
df['avg_daily_earnings_INR'].unique()

array(['2275', '1164', '2394', ..., '₹488', '642.00', '₹1690'],
      dtype=object)

In [96]:
## This converts the data type from object to string.
df['avg_daily_earnings_INR'] = df['avg_daily_earnings_INR'].astype("string")
print(df['avg_daily_earnings_INR'].dtype)

string

In [97]:
df['avg_daily_earnings_INR'] = df['avg_daily_earnings_INR'].fillna('4445')

In [98]:
df['total_complaints'].unique()

array([3.6000e+01, 1.8000e+01, 1.7000e+01, 2.4000e+01, 1.6000e+01,
       1.4000e+01, 4.4000e+01, 2.1000e+01, 9.9999e+04, 2.3000e+01,
       9.0000e+00, 3.5000e+01, 3.0000e+01, 4.8000e+01, 3.1000e+01,
              nan, 2.9000e+01, 1.5000e+01, 1.9000e+01, 4.5000e+01,
       2.6000e+01, 4.1000e+01, 4.9000e+01, 1.0000e+01, 2.2000e+01,
       2.8000e+01, 3.0000e+00, 4.0000e+01, 3.8000e+01, 1.3000e+01,
       2.7000e+01, 2.5000e+01, 1.2000e+01, 2.0000e+00, 6.0000e+00,
       8.0000e+00, 4.3000e+01, 3.4000e+01, 3.3000e+01, 5.0000e+00,
       1.0000e+00, 3.9000e+01, 7.0000e+00, 3.2000e+01, 5.0000e+01,
       3.7000e+01, 4.7000e+01, 4.6000e+01, 1.1000e+01, 4.2000e+01,
       0.0000e+00, 2.0000e+01, 4.0000e+00])

In [99]:
## This converts the data type from object to string.
df['total_complaints'] = df['total_complaints'].astype("string")
print(df['total_complaints'].dtype)

string

In [100]:
df['total_complaints'] = df['total_complaints'].fillna('50.5')

In [101]:
df['total_compliments'].unique()

array([7.7000e+01, 2.2000e+01, 5.9000e+01, 3.0000e+00,        nan,
       1.9000e+01, 6.8000e+01, 7.5000e+01, 2.3000e+01, 1.0000e+00,
       1.7000e+01, 9.0000e+01, 2.5000e+01, 6.1000e+01, 3.5000e+01,
       7.0000e+00, 9.9999e+04, 9.1000e+01, 5.4000e+01, 5.5000e+01,
       4.0000e+01, 8.9000e+01, 4.4000e+01, 9.8000e+01, 3.9000e+01,
       1.3000e+01, 9.0000e+00, 9.3000e+01, 6.0000e+01, 9.9000e+01,
       6.9000e+01, 4.2000e+01, 1.0000e+02, 7.9000e+01, 8.0000e+01,
       2.9000e+01, 4.9000e+01, 8.4000e+01, 4.8000e+01, 7.0000e+01,
       1.5000e+01, 6.2000e+01, 1.4000e+01, 9.6000e+01, 2.6000e+01,
       2.4000e+01, 5.2000e+01, 4.1000e+01, 8.3000e+01, 8.8000e+01,
       4.7000e+01, 3.1000e+01, 1.0000e+01, 3.0000e+01, 2.1000e+01,
       6.4000e+01, 5.0000e+01, 5.8000e+01, 3.6000e+01, 6.0000e+00,
       7.8000e+01, 1.1000e+01, 9.2000e+01, 7.4000e+01, 8.1000e+01,
       5.7000e+01, 7.6000e+01, 8.6000e+01, 3.2000e+01, 4.5000e+01,
       7.1000e+01, 2.0000e+00, 8.2000e+01, 5.3000e+01, 4.3000e+01,
       3.3000e+01, 2.8000e+01, 1.8000e+01, 6.5000e+01, 1.6000e+01,
       9.7000e+01, 6.6000e+01, 2.7000e+01, 4.0000e+00, 5.6000e+01,
       8.7000e+01, 8.0000e+00, 6.7000e+01, 5.0000e+00, 5.1000e+01,
       3.7000e+01, 7.3000e+01, 3.4000e+01, 8.5000e+01, 9.5000e+01,
       2.0000e+01, 6.3000e+01, 4.6000e+01, 0.0000e+00, 7.2000e+01,
       1.2000e+01, 3.8000e+01, 9.4000e+01])

In [102]:
## This converts the data type from object to string.
df['total_compliments'] = df['total_compliments'].astype("string")
print(df['total_compliments'].dtype)

string

In [103]:
df['total_compliments'] = df['total_compliments'].fillna('20.5')

In [104]:
df['interview_date'].unique()

array(['10 July 2023', 'June 2021', 'February 2021', ..., '2022/04/24',
       '11 April 2023', '03/27/22'], dtype=object)

In [105]:
## This converts the data type from object to string.
df['interview_date'] = df['interview_date'].astype("string")
print(df['interview_date'].dtype)

string

In [106]:
df['interview_date'] = df['interview_date'].fillna('20 May 25')

In [107]:
## This code generates random date values for the onboarding column. 

import pandas as pd
import numpy as np

df['interview_date'] = pd.to_datetime(df['interview_date'], errors='coerce')

start = pd.Timestamp("2021-01-01")
end = pd.Timestamp("2024-08-11")

mask = df["interview_date"].isna()

df.loc[mask, "interview_date"] = pd.to_datetime(
    np.random.randint(
        start.value // 10**9,
        end.value // 10**9,
        size=mask.sum()
    ),
    unit="s"
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
29365,DRV962754,girish mishra,23,Chennai,9337759643,girish.mishra@hotmail.com,Rapido,Mini,Good,1-3 yrs,...,7.5,8.2,4.6,7.0,Fail,Clear,Selected,Invalid_id,2026-08-04 09:27:32,True
15030,DRV353951,Umesh Ch@udh@ry,33,Hyderabad,91336530411,umesh.chaudhary@rediffmail.com,Uber,Bike,Excellent,1-3 yrs,...,9.4,7.5,5.4,6.8,Pass,Clear,Selected,Poor communication,2026-03-03 12:41:20,True
36014,DRV450248,Vikram Chauhan,41,Ahmedabad,91062217881,Vikram Chauhan @gmail.com,Bolt,Auto,Average,3-5 yrs,...,6.6,6.0,4.9,11.4,Fair,Clear,Rejected,Vehicle age too old,2026-02-17 00:32:26,False
23087,DRV248026,BHARAT KUMAR,42,Delhi,91091802884,bharat.kumargmail.com,Uber,Bike,Good,4+ yrs,...,5.5,7.2,7.3,12.3,Pending,Pending,Waitlist,Invalid_id,2025-12-21 07:19:17,False
36072,DRV658811,Girish Gupta,48,Lucknow,9198840375,Girish Gupta@gmail.com,Uber,Mini,Excellent,1-3 yrs,...,6.0,3.5,5.8,5.0,Pending,Pending,On hold,Invalid_id,2025-11-25 10:18:50,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15888,DRV332158,Manoj Gupta,23,Pune,9954554908,manoj.gupta@@hotmail.com,Rapido,Bike,Super,8 yrs,...,4.2,6.6,8.5,6.3,Pending,Flagged,Selected,Low rating history,2025-11-21 10:04:35,False
8743,DRV272285,Umesh Tiwari,39,Mumbai,91918482331,umesh.tiwari@gmail,Uber & rapido,Auto,Excellent,4+ yrs,...,4.5,3.4,8.5,5.2,Pending,Flagged,On hold,Invalid_id,2025-09-20 18:42:41,False
44379,DRV429550,Yogesh Yadav,43,Chennai,9041810625,yogesh.yadav@yahoo.com,Uber,Suv,Super,4+ yrs,...,7.7,3.3,9.8,6.1,Pass,Flagged,On hold,Invalid_id,2025-01-26 06:31:07,False
31409,DRV724660,HARISH DUBEY,26 yrs,Kolkata,9959516116,harish.dubey@gmail.com,Uber,Motorbike,Super,5+ yrs,...,9.1,11.3,5.1,6.9,Distinction,Clear,On hold,Invalid_id,2026-08-05 17:53:39,True
30212,DRV542467,Ramesh Dubey,-37,Hydrabad,9043671305,ramesh.dubey@yahoo.com,Rapido,Motorbike,Good,3-5 yrs,...,6.2,5.5,7.4,6.0,Credit,Clear,Rejected,Not applicable,2025-09-17 19:44:47,True

In [108]:
df['interview_date'].unique()

<DatetimeArray>
['2023-07-10 00:00:00', '2021-11-17 13:17:04', '2021-10-02 04:17:25',
 '2022-08-09 06:34:01', '2023-02-18 16:13:29', '2021-09-21 02:44:35',
 '2021-07-24 23:29:37', '2022-01-24 00:00:00', '2022-08-19 15:45:18',
 '2021-03-31 00:00:00',
 ...
 '2021-05-19 10:24:51', '2024-01-19 06:16:42', '2024-05-09 23:47:57',
 '2021-12-13 20:45:58', '2021-01-22 22:48:52', '2022-07-06 13:41:38',
 '2021-07-11 01:55:51', '2021-10-29 21:46:09', '2022-09-19 10:09:14',
 '2024-05-14 20:06:12']
Length: 44822, dtype: datetime64[ns]

In [109]:
# This converts the data type from object to string.
df['communication_score_10'] = df['communication_score_10'].astype("string")
print(df['communication_score_10'].dtype)

string

In [110]:
df['communication_score_10'] = df['communication_score_10'].fillna('4.5')
df['communication_score_10'] = df['communication_score_10'].str.lstrip('-')

In [111]:
df['communication_score_10'].unique()

<StringArray>
['10.4',  '7.0',  '4.5',  '7.4',  '4.0',  '8.1',  '4.1',  '7.3',  '7.6',
  '7.5',
 ...
 '12.9', '11.3', '12.3',  '0.3', '10.6',  '2.0',  '0.5', '11.2', '13.0',
 '12.0']
Length: 121, dtype: string

In [112]:
print(df.isna().sum())

driver_id                     0
driver_name                   0
age                           0
city                          0
phone                         0
email                         0
platform                      0
vehicle_type                  0
vehicle_condition             0
experience_level              0
preferred_shift               0
reason_for_joining            0
languages_known               0
overall_driver_rating         0
total_trips_completed         0
trip_completion_rate_%        0
cancellation_rate_%           0
avg_daily_earnings_INR        0
total_complaints              0
total_compliments             0
peak_hour_availability        0
interview_date                0
communication_score_10        0
driving_test_score_10         0
route_knowledge_score_10      0
customer_handling_score_10    0
overall_interview_score_10    0
document_verification         0
background_check_status       0
interview_result              0
rejection_reason              0
onboarding_date               0
is_currently_active           0
dtype: int64

In [113]:
df.to_csv("uber_rapido_driver_cleaned.csv",index=False)