In [1]:
import pandas as pd

#import matplotlib.pyplot as plt

df = pd.read_csv("uber_rapido_driver_dirty.csv")
df.head(5)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
0,DRV016649,Naresh Chauhan,NaN,Chennai,9255500096,naresh.chauhan@hotmail.com,uber,auto,good,0-1 yr,...,4.3,5.8,7.7,5.3,Fail,NaN,On Hold,NaN,-,false
1,DRV032785,Amit Gupta,45,Ahmedabad,9940345570,amit.gupta@rediffmail.com,Uber,Mini,Excellent,Fresher,...,9.3,NaN,9.0,8.1,NaN,Clear,On Hold,NaN,-,No
2,DRV011323,Yogesh Nair,53,Lucknow,9170487337,NaN,uber,SUV,avg,0-1 yr,...,6.3,9.0,5.5,6.9,NaN,clear,Selected,NaN,19 April 2021,false
3,DRV022168,Manoj Patel,46,Hyderabad,9246425981,manoj.patel@hotmail.com,RAPIDO,Mini,NaN,1-3 yrs,...,8.7,9.6,5.3,7.8,unknown,Clear,Selected,NaN,2021/05/27,0
4,DRV040782,Vikram Chaudhary,25,KOLKATA,9282240,vikram.chaudhary@gmail.com,Uber,suv,GOOD,Fresher,...,12.7,6.5,7.9,6.0,FAIL,clear,Rejected,Low rating history,-,NO

In [2]:
df.describe()

,total_trips_completed,trip_completion_rate_%,cancellation_rate_%,total_complaints,total_compliments,communication_score_10,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10
count,45930.000000,45565.00000,45484.000000,45965.000000,46024.000000,45416.000000,45559.000000,45448.000000,45500.000000,45545.000000
mean,6802.510799,77.89254,22.416584,8809.843120,8942.686272,6.508777,6.946878,6.508619,6.517708,6.613859
std,17638.171153,20.80393,23.708155,28303.698509,28456.710282,2.789817,2.630277,2.794014,2.804085,2.239486
min,-7996.000000,-2.00000,-2.000000,0.000000,0.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000
25%,1704.000000,69.40000,8.100000,14.000000,27.000000,4.600000,5.400000,4.600000,4.600000,5.900000
50%,3909.000000,80.50000,18.100000,27.000000,55.000000,6.600000,7.100000,6.600000,6.600000,6.700000
75%,6086.750000,91.60000,27.900000,41.000000,82.000000,8.500000,8.800000,8.600000,8.600000,7.400000
max,99999.000000,103.00000,103.000000,99999.000000,99999.000000,13.000000,13.000000,13.000000,13.000000,13.000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   driver_id                   49005 non-null  object
 1   driver_name                 50000 non-null  object
 2   age                         47543 non-null  object
 3   city                        50000 non-null  object
 4   phone                       46089 non-null  object
 5   email                       45395 non-null  object
 6   platform                    47761 non-null  object
 7   vehicle_type                47775 non-null  object
 8   vehicle_condition           39468 non-null  object
 9   experience_level            47776 non-null  object
 10  preferred_shift             38773 non-null  object
 11  reason_for_joining          38637 non-null  object
 12  languages_known             47847 non-null  object
 13  overall_driver_rating       46033 non-null  object
 14  total_trips_completed       45930 non-null  float64
 15  trip_completion_rate_%      45565 non-null  float64
 16  cancellation_rate_%         45484 non-null  float64
 17  avg_daily_earnings_INR      47489 non-null  object
 18  total_complaints            45965 non-null  float64
 19  total_compliments           46024 non-null  float64
 20  peak_hour_availability      50000 non-null  object
 21  interview_date              45067 non-null  object
 22  communication_score_10      45416 non-null  float64
 23  driving_test_score_10       45559 non-null  float64
 24  route_knowledge_score_10    45448 non-null  float64
 25  customer_handling_score_10  45500 non-null  float64
 26  overall_interview_score_10  45545 non-null  float64
 27  document_verification       36233 non-null  object
 28  background_check_status     36549 non-null  object
 29  interview_result            45243 non-null  object
 30  rejection_reason            12174 non-null  object
 31  onboarding_date             26172 non-null  object
 32  is_currently_active         50000 non-null  object
dtypes: float64(10), object(23)
memory usage: 12.6+ MB

In [4]:
df.shape

(50000, 33)

In [36]:
df['email'].unique()

<StringArray>
[  'naresh.chauhan@hotmail.com',    'amit.gupta@rediffmail.com',
    '  Yogesh Nair  @gmail.com',      'manoj.patel@hotmail.com',
   'vikram.chaudhary@gmail.com',   'sanjay.chaudhary@yahoo.com',
   'rakesh.chaudhary@gmail.com',    'naveen.mishra@hotmail.com',
       'Hitesh Singh@gmail.com',     'harish.chauhan@gmail.com',
 ...
      'naveen.singh@@gmail.com',         'manoj.jha@@gmail.com',
         'naresh.gupta@hotmail',      'RAMESH TIWARI@gmail.com',
           'mahesh.kumar@gmail',           'harish.kumar@yahoo',
    'ANIL SRIVASTAVA@gmail.com', 'deepak.srivastavahotmail.com',
        'deepak.singhgmail.com',        'deepak.dubeygmail.com']
Length: 8553, dtype: string

In [6]:
df['email'] = df['email'].astype("string")
print(df['email'].dtype)

string

In [7]:
##This code creates a gmail adrress for the drivers using their names, where they have no existing emails.

df['email'] = df['email'].fillna(
    df['driver_name'] + '@gmail.com'
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
45650,DRV044996,Anil Yadav,36,BANGALORE,NaN,anil.yadav@rediffmail.com,Uber,sedan,Poor,Fresher,...,9.1,6.0,6.3,6.9,NaN,FLAGGED,NaN,NaN,2021-11-08T00:00:00Z,1
19683,DRV030353,Mukesh Tripathi,25,Chenna,9300498539,mukesh.tripathi@yahoo.com,Uber & Rapido,Sedan,good,3-5 yrs,...,9.6,4.4,3.5,5.3,Pending,FLAGGED,On Hold,NaN,NaN,false
21021,DRV013455,Dinesh Kumar,52,Jaipur,9271651407,Dinesh Kumar@gmail.com,Rapido,auto,Poor,Fresher,...,NaN,12.6,8.6,6.7,NaN,FLAGGED,On Hold,NaN,NaN,YES
19198,DRV049301,Pradeep Srivastava,54,Delhi,9263574619,pradeep.srivastava@rediffmail.com,Uber & Rapido,auto,unknown,1-3 yrs,...,8.0,8.8,6.9,7.9,Pass,pending,On Hold,NaN,-,False
5712,DRV001268,Pankaj Kumar,37,Jaipur,9896107802,pankaj.kumar@gmail.com,Uber,sedan,Average,1-3 yrs,...,5.3,-0.7,-1.4,11.5,Pending,pending,Rejected,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14599,NaN,Umesh Tripathi,-25,Jaipur,9327414765,umesh.tripathi@yahoo.com,Uber,Mini,avg,3-5 yrs,...,8.3,3.2,4.9,6.5,Fail,pending,Selected,NaN,August 2023,False
2693,DRV005770,R@vi Jh@,31,Mumbai,9819399790,ravi.jha@gmail.com,na,Mini,NaN,0-1 yr,...,8.5,9.1,9.8,8.3,NaN,NaN,Rejected,Low rating history,-,NO
45482,DRV015081,Dinesh Srivastava,45,Ahmedabad,9657357,dinesh.srivastava@gmail.com,Rapido,Auto,Good,Fresher,...,-1.9,5.7,4.6,5.7,NaN,pending,On Hold,NaN,-,false
20777,DRV035403,Ramesh Shukla,-40,Ahmedabad,NaN,ramesh.shukla@hotmail.com,Rapido,Sedan,GOOD,0-1 yr,...,6.6,10.2,-1.0,6.6,pass,Flagged,Rejected,Incomplete documents,NaN,N
25883,DRV023747,dinesh tiwari,39,Chennai,9417432144,dinesh.tiwari@hotmail.com,Uber & Rapido,sedan,Average,3-5 yrs,...,9.7,3.1,6.4,7.2,FAIL,Clear,Selected,NaN,March 2023,YES

In [8]:
df.sample(10)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
11784,DRV012779,Naresh Rao,55,Delhi,9031005608,naresh.rao@yahoo.com,rapido,Mini,NaN,5+ yrs,...,8.5,9.6,4.5,7.0,Pending,NaN,On Hold,NaN,NaN,1
3955,DRV047199,Vijay Patel,31,Bangalore,9687783655,vijay.patel@rediffmail.com,RAPIDO,Auto,Excellent,5+ yrs,...,8.4,5.4,6.6,5.8,FAIL,NaN,Waitlist,Poor communication,NaN,1
21665,DRV016471,Vijay Nair,26 yrs,Lucknow,XXXXXXXXXX,Vijay Nair@gmail.com,Uber,suv,avg,1-3 yrs,...,NaN,6.9,8.8,-1.7,Pending,Clear,On Hold,NaN,15 March 2022,NO
13248,DRV000468,sunil dubey,54,Pune,9066943321,sunil.dubey@yahoo.com,Uber & Rapido,suv,avg,Fresher,...,NaN,7.3,-1.4,5.1,FAIL,NaN,Selected,NaN,02/07/24,true
36470,DRV002660,Bharat Kumar,27,chennai,9047805,bharat.kumar@yahoo.com,uber,SUV,excellent,0-1 yr,...,8.0,5.4,4.5,6.6,Fail,FLAGGED,On Hold,NaN,NaN,1
5754,DRV032255,Santosh Singh,33,Hyderabad,9154722900,santosh.singh@rediffmail.com,uber,Auto,good,3-5 yrs,...,7.6,4.9,NaN,6.1,pending,clear,Selected,NaN,11-08-2022,false
210,DRV036001,H@rish Ch@udh@ry,20,bangalore,+91-9954686687,harish.chaudhary@rediffmail.com,UBER,Mini,Poor,3-5 yrs,...,5.9,11.0,5.5,5.9,Pass,Pending,NaN,na,-,Yes
12185,DRV046637,Mukesh Patel,36,Hyderabad,9663172010,mukesh.patelgmail.com,Rapido,Mini,Average,5+ yrs,...,6.7,8.2,4.6,6.1,NaN,pending,Selected,NaN,NaN,false
34024,DRV004865,Ravi Verma,999,Jaipur,NaN,ravi.verma@yahoo,UBER,BIKE,Good,NaN,...,7.4,4.2,6.9,6.3,none,clear,Waitlist,Not applicable,NaN,No
23640,DRV044411,Pradeep Verma,30,Pune,9297127377,pradeep.verma@yahoo.com,Uber,auto,excellent,0-1 yr,...,8.4,3.9,3.3,4.8,Fail,NaN,Rejected,none,NaN,YES

In [9]:
df['phone'] = pd.to_numeric(df['phone'], errors='coerce') 
## This is to convert the phone collumn from object to numeric

In [10]:
df['phone'] = df['phone'].astype("string")
print(df['phone'].dtype)

string

In [37]:
df['driving_test_score_10'].unique()

<StringArray>
[ '4.3',  '9.3',  '6.3',  '8.7', '12.7',  '8.8',  '8.1',  '1.1', '11.6',
   <NA>,
 ...
 '12.3',  '1.6', '12.6',  '1.9', '10.6', '12.9', '11.1', '13.0',  '0.1',
  '2.0']
Length: 112, dtype: string

In [12]:
## This code removes the decimals from the values and make them strings rather than floats. 
df['phone'] = df['phone'].str.replace(r'\.0$', '', regex=True)

In [13]:
## This creates random phone numbers for NaN values in the phone column

import numpy as np

mask = df['phone'].isna()

df.loc[mask, 'phone'] = [
    '+91' + ''.join(np.random.choice(list('0123456789'), 9))
    for _ in range(mask.sum())
]
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
14725,DRV014548,Sunil Patel,999,Kolkata,9714338218,sunil.patelhotmail.com,none,Mini,Good,3-5 yrs,...,NaN,3.7,9.5,6.7,NaN,NaN,On Hold,NaN,NaN,false
19828,DRV001352,Naveen Gupta,42,Mumbai,9610711382,naveen.gupta@gmail.com,UBER,Mini,excellent,1-3 yrs,...,7.0,8.3,4.4,5.9,Fail,pending,Rejected,NaN,NaN,false
45429,DRV009964,Ravi Gupta,NaN,Pune,+91442976823,ravi.gupta@gmail.com,Rapido,Mini,avg,Fresher,...,6.4,NaN,4.6,6.0,Pass,clear,Selected,NaN,February 2022,True
44856,DRV009020,Ganesh Dubey,-26,Mumbai,9857372281,ganesh.dubey@rediffmail.com,RAPIDO,Bike,poor,1-3 yrs,...,5.9,-1.9,7.9,6.5,FAIL,NaN,On Hold,NaN,NaN,no
13671,DRV015759,Yogesh Rao,36,LUCKNOW,9128700620,yogesh.rao@@gmail.com,uber,SUV,none,1-3 yrs,...,NaN,5.0,10.0,6.5,Pass,pending,On Hold,NaN,NaN,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1631,DRV049954,Bharat Chaudhary,20,Jaipur,9969331038,bharat.chaudhary@@yahoo.com,rapido,BIKE,excellent,Fresher,...,7.4,4.8,5.7,6.8,Pending,NaN,-,NaN,2023/08/17,yes
48579,DRV049411,Santosh Reddy,39,LUCKNOW,9545125271,santosh.reddy@gmail.com,Uber,SUV,Average,1-3 yrs,...,5.3,4.0,5.0,5.3,Pass,Pending,Rejected,Vehicle age too old,NaN,1
16819,DRV048414,Anil Chaudhary,45,Pune,9623372008,anil.chaudhary@hotmail.com,rapido,NaN,Good,1-3 yrs,...,5.2,4.1,5.4,-1.1,FAIL,NaN,On Hold,NaN,NaN,No
34915,DRV004091,Rakesh Mishra,42,Hyderabad,9952664948,rakesh.mishra@yahoo.com,rapido,suv,Excellent,0-1 yr,...,4.5,NaN,4.0,12.3,pending,FLAGGED,Rejected,NaN,NaN,no
39248,DRV005748,Sanjay Tripathi,32,Pune,9883930795,sanjay.tripathi@gmail.com,rapido,sedan,Average,1-3 yrs,...,5.5,3.9,12.6,7.0,NaN,Clear,Rejected,Poor communication,NaN,N

In [14]:
df['age'] = df['age'].astype("string")
print(df['age'].dtype)

string

In [15]:
df['age'] = df['age'].fillna('70')

In [16]:
## This code fills the age column where NaN values exist with random values between 1 and 100

import numpy as np

mask = df['age'].isna()

df.loc[mask, 'age'] = np.random.randint(
    1, 101, size=mask.sum()
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
22326,DRV011762,PANKAJ PATEL,29,jaipur,9960349,pankaj.patel@gmail.com,uber,sedan,NaN,5+ yrs,...,5.4,3.9,6.2,5.5,pass,NaN,REJECTED,NaN,12/30/21,N
34354,DRV013841,Girish Tripathi,33 yrs,Dlhi,9849609740,girish.tripathi@yahoo.com,rapido,auto,Excellent,unknown,...,9.1,4.5,5.5,-0.3,Fail,clear,Rejected,Low rating history,NaN,NO
368,DRV047234,Hitesh Patel,30,Lucknow,9393479428,hitesh.patel@gmail,Uber,Bike,poor,Fresher,...,11.8,7.9,9.0,8.5,pending,FLAGGED,On Hold,NaN,NaN,No
1446,DRV001154,Ravi Singh,45,Jaipur,+91657895337,ravi.singh@gmail.com,Uber,Auto,Poor,0-1 yr,...,5.9,3.7,4.0,5.1,Pending,NaN,NaN,NaN,17.01.2022,False
9206,DRV044322,Naresh Pandey,32,Ahmedabad,9278605600,naresh.pandey@yahoo.com,uber,Mini,GOOD,5+ yrs,...,7.4,7.8,3.5,6.0,pass,Pending,REJECTED,NaN,2022-03-20T00:00:00Z,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8570,DRV014412,Deepak Shukla,35,Pune,9996347145,deepak.shukla@hotmail.com,RAPIDO,Bike,Excellent,1-3 yrs,...,7.2,5.5,4.6,6.5,Pending,Clear,NaN,Failed driving test,NaN,false
10972,DRV036833,Girish Dubey,44,Mumbai,9894212105,girish.dubey@gmail.com,Uber & Rapido,SUV,excellent,3-5 yrs,...,11.9,5.7,5.3,6.2,pending,pending,on hold,none,NaN,yes
46911,DRV004487,P@nk@j P@tel,51,Ahmedabad,+91344143416,pankaj.patel@@gmail.com,ola,auto,Poor,5+ yrs,...,NaN,6.2,3.5,5.5,NaN,pending,Selected,NaN,December 2023,YES
42146,DRV008361,Mukesh Shukla,70,Lucknow,9443938657,mukesh.shukla@rediffmail.com,Rapido,Sedan,Good,Fresher,...,8.4,-0.7,7.7,6.7,pass,pending,On Hold,NaN,-,NO
11510,DRV002663,SUNIL SINGH,41,Ahmedabad,9717714013,sunil.singh@@rediffmail.com,Rapido,Auto,avg,3-5 yrs,...,5.1,5.3,9.5,NaN,NaN,Pending,Rejected,NaN,NaN,Y

In [17]:
## This is to remove the negative values and also the yrs in the age column.
df['driving_test_score_10'] = df['driving_test_score_10'].astype("string")
df['driving_test_score_10'] = df['driving_test_score_10'].str.lstrip('-')
#df['age'] = df['age'].str.rstrip('yrs')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
33504,DRV027033,R@kesh Reddy,47,kolkata,9505885238,rakesh.reddy@rediffmail.com,NaN,Auto,avg,Unknown,...,4.4,10.0,-1.8,7.6,pass,FLAGGED,Selected,NaN,25-02-2024,Yes
4321,DRV018781,Sanjay Dubey,39 yrs,Chennai,+91334705836,sanjay.dubey@rediffmail,RAPIDO,Auto,excellent,Fresher,...,5.3,5.8,6.1,6.8,NaN,NaN,On Hold,NaN,-,N
22210,DRV036785,Harish Srivastava,31,Delhi,+91598744936,harish.srivastavarediffmail.com,unknown,sedan,good,1-3 yrs,...,5.2,7.0,NaN,5.8,NaN,NaN,Waitlist,NaN,2021/06/21,no
29331,DRV029313,Naresh Pandey,49,Ahmedabad,9297128905,naresh.pandey@hotmail.com,UBER,Auto,GOOD,none,...,<NA>,7.9,5.3,7.5,Pass,Pending,On Hold,NaN,NaN,YES
48994,DRV047442,Rakesh Gupta,36,Chennai,+91705997793,rakesh.gupta@yahoo.com,-,sedan,Unknown,1-3 yrs,...,8.8,8.4,8.6,8.8,NaN,clear,Selected,NaN,09/27/21,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30081,DRV040856,Rajesh Verma,44,Pune,9793740211,rajesh.verma@gmail.com,Rapido,Auto,Poor,0-1 yr,...,10.2,4.2,6.6,7.4,Pending,Flagged,Selected,NaN,2021-09-14T00:00:00Z,NO
3987,DRV007837,PANKAJ VERMA,51,Mumbai,9416954781,pankaj.verma@gmail.com,NaN,Sedan,NaN,1-3 yrs,...,<NA>,6.7,8.0,-1.1,NaN,Pending,Rejected,Low rating history,NaN,False
19200,DRV048629,Pradeep Srivastava,41,Chennai,9904554387,pradeep.srivastava@yahoo.com,ola,Mini,excellent,5+ yrs,...,7.3,4.0,9.0,10.9,pending,Clear,Selected,NaN,07/24/22,False
49819,DRV033889,Rajesh Tiwari,25,Kolkata,9655108339,rajesh.tiwari@hotmail.com,Unknown,Mini,Excellent,1-3 yrs,...,9.1,7.0,7.4,8.2,FAIL,Flagged,Selected,NaN,26-10-2021,NO
20910,DRV044278,Sunil Pandey,20,Lucknow,+91830699211,sunil.pandey@rediffmail.com,NaN,auto,excellent,0-1 yr,...,6.7,NaN,5.0,NaN,NaN,FLAGGED,Unknown,NaN,NaN,yes

In [18]:
## This is to capitalise the platform column to give it a uniform format and also convert the data type from object to string.

df['platform'] = df['platform'].str.capitalize()
df['platform'] = df['platform'].astype("string")
print(df['platform'].dtype)

string

In [19]:
df['platform'] = df['platform'].fillna('Bolt')

In [20]:
df['customer_handling_score_10'] = df['customer_handling_score_10'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    #'Unknown': 'Experienced',
    #'None': 'Fairly_Experienced',
    #'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Motorcycle',
    #'Na': '1-20 yrs',
    #'-': '10-30 yrs',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    '<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
39448,DRV009634,Vikram Rao,54,Lucknow,+91135454480,vikram.rao@hotmail,Uber,BIKE,unknown,3-5 yrs,...,9.7,3.4,10.6,6.9,NaN,clear,NaN,NaN,2021-05-02T00:00:00Z,NO
21552,DRV004531,Yogesh Verma,24,Pune,9372040330,Yogesh Verma@gmail.com,Uber & rapido,Mini,Poor,0-1 yr,...,9.4,-0.6,5.3,5.4,NaN,Clear,Rejected,none,NaN,N
11903,DRV018370,Harish Singh,22,jaipur,9558946341,harish.singh@yahoo.com,Uber & rapido,Sedan,excellent,3-5 yrs,...,9.7,3.4,6.8,-0.9,Pass,FLAGGED,NaN,NaN,-,True
18844,DRV011054,Vijay Kumar,70,KOLKATA,9543004938,vijay.kumar@rediffmail,Ola,SUV,GOOD,Fresher,...,4.5,4.9,4.9,5.1,pending,Pending,On Hold,NaN,-,false
42588,DRV013318,Lokesh Gupta,26,Delhi,9627494250,lokesh.gupta@rediffmail.com,Rapido,Sedan,excellent,0-1 yr,...,5.0,3.8,NaN,4.7,NaN,NaN,Unknown,Vehicle age too old,-,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3088,DRV005632,Ramesh Sharma,-28,Ahmedabad,+91128341171,Ramesh Sharma@gmail.com,Ola,Bike,excellent,3-5 yrs,...,5.9,8.4,5.8,6.4,FAIL,NaN,Rejected,NaN,NaN,False
20823,DRV035628,Amit Gupta,39,DELHI,9182461,amit.gupta@yahoo.com,Rapido,Mini,excellent,5+ yrs,...,4.1,9.3,8.4,-1.9,Pending,pending,-,NaN,18 November 2023,NO
13177,DRV042543,SANJAY REDDY,36,jaipur,+91138216386,sanjay.reddy@gmail.com,Rapido,auto,-,0-1 yr,...,7.7,8.3,5.7,7.2,NaN,clear,Selected,NaN,2023-12-23T00:00:00Z,False
42268,DRV048632,Mahesh Gupta,50,Hyderabad,9171281542,mahesh.gupta@rediffmail.com,Uber,Mini,Poor,5+ yrs,...,6.8,8.0,3.3,5.4,Fail,Pending,On Hold,NaN,NaN,0
34565,DRV013205,ganesh shukla,32,Jaipur,9611177757,ganesh.shukla@hotmail.com,Uber,BIKE,NaN,1-3 yrs,...,7.6,8.4,10.0,8.2,NaN,NaN,Selected,NaN,NaN,no

In [21]:
## This capitalises the city column to give it a uniform format and also converts the data type from object to string.
df['city'] = df['city'].str.capitalize()
df['city'] = df['city'].astype("string")
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
30320,DRV025043,Girish Verma,27,Kolkata,+91789581046,girish.verma@rediffmail.com,Rapido,suv,Good,5+ yrs,...,6.8,6.6,8.2,6.2,Pass,Flagged,NaN,NaN,06/07/22,true
1286,DRV024905,Amit Srivastava,48,Hyderabad,9762516741,amit.srivastava@gmail.com,Uber,sedan,Poor,na,...,4.2,10.6,5.5,5.6,pass,Clear,Rejected,Not applicable,-,no
14922,DRV017565,Amit Tripathi,55,Kolkata,9163483907,amit.tripathi@gmail.com,Uber,Bike,NaN,Fresher,...,9.1,4.4,9.7,6.8,Pass,Pending,Selected,NaN,23-03-2022,False
4132,DRV003674,Mahesh Singh,31,Ahmedabad,9457710576,mahesh.singh@rediffmail.com,Uber,Auto,excellent,Fresher,...,4.1,9.5,9.2,NaN,Fail,NaN,Rejected,none,-,Y
15089,DRV018147,rakesh rao,21,Pune,9215588743,rakesh.rao@hotmail.com,Rapido,Bike,NaN,0-1 yr,...,7.8,6.7,7.3,7.8,NaN,NaN,NaN,Incomplete documents,NaN,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
786,DRV016140,Ganesh Chaudhary,39 yrs,Chenna,9706237308,ganesh.chaudhary@hotmail.com,Unknown,BIKE,NaN,1-3 yrs,...,<NA>,8.0,NaN,11.2,Pass,FLAGGED,On Hold,NaN,NaN,N
23059,DRV034006,Deepak Kumar,28,Delhi,9186742695,deepak.kumar@hotmail.com,Uber,Bike,na,1-3 yrs,...,9.9,8.1,7.3,8.5,Pass,Flagged,NaN,NaN,11 December 2022,Y
46657,DRV018590,Mahesh Mishra,32,Mumbai,9696313823,mahesh.mishra@rediffmail.com,Uber,unknown,Good,1-3 yrs,...,7.8,4.7,NaN,NaN,pending,Flagged,Rejected,Failed driving test,NaN,no
8350,DRV013275,Ganesh Kumar,28,Hyderabad,9888986703,ganesh.kumar@rediffmail.com,Uber,BIKE,good,na,...,4.8,5.2,4.4,5.1,FAIL,Flagged,NaN,NaN,02/24/23,N
28504,DRV023629,Yogesh Chaudhary,31,Pune,9866367332,yogesh.chaudhary@@gmail.com,Rapido,Auto,Good,0-1 yr,...,6.2,-1.1,3.1,10.4,pass,clear,On Hold,NaN,-,true

In [38]:
df['route_knowledge_score_10'].unique()

<StringArray>
[ '5.8',  '7.5',  '9.0',  '9.6',  '6.5',  '8.6',  '8.7',  '6.4',  '7.9',
  '7.7',
 ...
 '11.4',  '0.5', '12.5',  '1.7',  '1.6',  '0.1', '10.6', '12.6',  '0.6',
 '11.6']
Length: 121, dtype: string

In [23]:
## This converts the data type from object to string.
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].astype("string")
print(df['route_knowledge_score_10'].dtype)

string

In [24]:
## This is to remove the negative values and also the yrs in the age column.
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].str.lstrip('-')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
45245,DRV012605,Vikram Rao,36,Chennai,9506757843,vikram.rao@rediffmail.com,Uber,auto,Poor,0-1 yr,...,7.4,<NA>,7.1,6.9,pending,-,-,NaN,2022-09-22T00:00:00Z,YES
13555,DRV042091,PRADEEP NAIR,26,Kolkata,9974022016,pradeep.nair@hotmail.com,Rapido,Mini,Good,5+ yrs,...,5.0,9.1,3.2,12.3,NaN,NaN,Selected,-,January 2023,False
12368,DRV009317,Manoj Sharma,70,Ahmedabad,9599459050,manoj.sharma@hotmail.com,Uber & rapido,Mini,Poor,5+ yrs,...,8.4,7.3,NaN,6.8,NaN,Pending,na,Poor communication,NaN,1
42661,DRV040459,Umesh Kumar,37,Ahmedabad,9315551146,umesh.kumar@rediffmail.com,Uber,SUV,Average,5+ yrs,...,<NA>,<NA>,4.7,6.2,pass,Flagged,Selected,NaN,August 2021,N
49238,DRV008259,S@nj@y P@ndey,37,Lucknow,9952014557,sanjay.pandey@hotmail,Rapido,Bike,GOOD,0-1 yr,...,1.3,6.1,4.4,5.9,Pending,Clear,Rejected,Background check failed,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3897,DRV000146,Hitesh Verma,-26,Hyderabad,9028420353,hitesh.verma@hotmail.com,Uber,Mini,NaN,1-3 yrs,...,4.7,7.5,5.5,NaN,pending,pending,On Hold,NaN,NaN,1
15802,DRV005640,Vikram Tiwari,29,Lucknow,+91197304238,vikram.tiwari@gmail.com,Rapido,Auto,poor,0-1 yr,...,9.4,5.5,7.1,7.6,na,Flagged,Selected,NaN,22 November 2023,false
42294,DRV021610,Deepak Sharma,45,Hyderabad,9426863098,deepak.sharma@hotmail.com,Bolt,BIKE,excellent,0-1 yr,...,8.9,4.0,5.8,6.8,Fail,NaN,Rejected,Vehicle age too old,-,Yes
10215,DRV036028,Pradeep Kumar,36,Pune,9832350429,pradeep.kumargmail.com,Ola,NaN,GOOD,unknown,...,4.6,4.8,4.8,4.6,Unknown,NaN,Rejected,Background check failed,NaN,no
13783,DRV017080,NARESH YADAV,55,Chennai,+91749185096,naresh.yadav@rediffmail.com,Uber,auto,Excellent,Fresher,...,7.4,<NA>,7.4,5.8,pending,Flagged,Selected,NaN,21-02-2021,YES

In [25]:
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].fillna('7.5')

In [26]:
## This code fills the age column where NaN values exist with random values between 0 and 10

import numpy as np

mask = df['customer_handling_score_10'] == 6

df.loc[mask, 'customer_handling_score_10'] = np.random.randint(
    0, 10, size=mask.sum()
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
46914,DRV001146,rajesh reddy,24,Kolkata,9589304016,rajesh.reddy@gmail.com,Uber,suv,avg,5+ yrs,...,9.8,4.1,NaN,7.4,NaN,NaN,REJECTED,NaN,19.11.2021,1
14355,DRV037707,Bharat Dubey,39,Pune,9250731386,bharat.dubey@@rediffmail.com,Uber,auto,GOOD,0-1 yr,...,7.8,3.8,3.5,4.9,FAIL,pending,Rejected,Low rating history,NaN,1
6282,DRV009517,Girish Mishr@,35,Mumbai,9070854040,girish.mishra@hotmail.com,Uber,SUV,Average,5+ yrs,...,4.1,7.6,11.3,12.6,NaN,NaN,Rejected,NaN,-,0
31287,DRV005661,Hitesh Mishra,38,Pune,9496678565,hitesh.mishra@hotmail.com,Uber,suv,poor,3-5 yrs,...,0.5,7.3,8.1,6.7,none,Clear,Rejected,NaN,NaN,Yes
12512,DRV043298,Mahesh Verma,43,Kolkata,9358625267,mahesh.verma@yahoo.com,Bolt,Auto,NaN,3-5 yrs,...,<NA>,6.7,9.3,7.1,FAIL,pending,Selected,NaN,NaN,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4518,DRV029962,Santosh Rao,35,Kolkata,+91365604809,santosh.rao@hotmail.com,Rapido,sedan,avg,5+ yrs,...,4.1,10.0,3.5,6.5,Pending,pending,On Hold,NaN,2023-07-11T00:00:00Z,Y
17542,DRV021920,naresh sharma,26,Chennai,9750486,naresh sharma@gmail.com,Uber & rapido,BIKE,good,0-1 yr,...,6.4,6.1,5.6,5.3,Pass,FLAGGED,Rejected,Failed driving test,NaN,No
49352,DRV031007,S@nj@y N@ir,-29,Hyderabad,9425457776,sanjay.nair@yahoo.com,Rapido,Sedan,excellent,5+ yrs,...,7.8,3.0,9.3,11.4,pending,NaN,On Hold,NaN,NaN,False
26687,DRV040077,girish patel,47,Kolkata,+91956456259,girish.patel@gmail.com,Uber,SUV,good,1-3 yrs,...,7.0,9.1,3.7,6.9,Fail,FLAGGED,Selected,NaN,31.08.2023,Yes
245,DRV014544,vikram mishra,21,Lucknow,9457004997,vikram.mishra@yahoo.com,Rapido,Auto,good,3-5 yrs,...,9.5,11.7,8.8,8.6,NaN,clear,On Hold,NaN,-,Y

In [39]:
df['vehicle_type'].unique()

<StringArray>
[      'Auto',      'Mini ',        'Suv',       'Mini',       'Bike',
      'Sedan',   'Tricycle',  'Motorbike',    'Bicycle', 'Catapiller',
      'Truck']
Length: 11, dtype: string

In [28]:
## This converts the data type from object to string.
df['vehicle_type'] = df['vehicle_type'].astype("string")
print(df['vehicle_type'].dtype)

string

In [29]:
df['vehicle_type'] = df['vehicle_type'].str.capitalize()
df['vehicle_type'] = df['vehicle_type'].fillna('Motorbike')
df['vehicle_type'] = df['vehicle_type'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    #'Unknown': 'Experienced',
    'None': 'Bicycle',
    #'Avg': 'Average',
    #'poor': 'Super',
    'Unknown': 'Tricycle',
    'Na': 'Catapiller',
    '-': 'Truck',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
15709,DRV024545,N@resh Trip@thi,28,Hyderabad,9833614369,N@resh Trip@thi@gmail.com,Rapido,Suv,Good,5+ yrs,...,9.9,7.1,8.7,8.9,pass,Flagged,Waitlist,NaN,May 2023,Y
36424,DRV000100,Deepak Mishra,33,Hyderabad,9075183612,deepak.mishra@hotmail.com,Ola,Bike,GOOD,1-3 yrs,...,5.1,5.9,-0.2,6.1,pending,Unknown,Waitlist,NaN,February 2024,false
7931,DRV008571,VIKRAM VERMA,42,Kolkata,+91496995590,vikram.verma@hotmail.com,Ola,Mini,NaN,1-3 yrs,...,6.7,3.1,7.0,12.4,pass,Pending,On Hold,NaN,-,Yes
42227,DRV019126,Pankaj Reddy,23,Delhi,+91846149162,pankaj.reddy@yahoo.com,Na,Mini,GOOD,0-1 yr,...,8.3,7.7,11.5,5.6,NaN,Pending,On Hold,NaN,-,True
45952,DRV037556,Harish Dubey,49,Jaipur,9497670,harish.dubey@rediffmail.com,Uber,Suv,excellent,0-1 yr,...,10.8,5.9,6.1,7.5,NaN,Pending,Selected,NaN,16 July 2023,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39301,DRV002154,ramesh chauhan,37,Delhi,9487794357,ramesh.chauhan@@gmail.com,Uber,Bike,good,3-5 yrs,...,7.9,6.6,12.1,6.7,FAIL,Flagged,Rejected,Poor communication,-,N
3317,DRV043874,Vikram Chauhan,35,Mumbai,9902050398,vikram.chauhan@hotmail.com,Uber & rapido,Auto,avg,3-5 yrs,...,5.1,5.0,5.1,5.8,Fail,Clear,Selected,NaN,NaN,yes
48205,DRV000479,Vikram Shukla,30,Delhi,+91989231903,vikram.shukla@yahoo.com,Rapido,Auto,Unknown,Fresher,...,6.8,7.2,6.5,NaN,FAIL,Pending,On Hold,NaN,NaN,no
12122,DRV013724,Santosh Sharma,45,Ahmedabad,+91408423573,santosh.sharma@rediffmail.com,Uber,Suv,NaN,1-3 yrs,...,6.5,4.2,7.5,NaN,pending,clear,NaN,NaN,-,True
33003,DRV028511,Rajesh Nair,28,Chennai,9588571531,Rajesh Nair@gmail.com,Rapido,Bicycle,NaN,Fresher,...,6.9,9.5,3.0,7.2,NaN,NaN,Rejected,Low rating history,NaN,True

In [40]:
df['vehicle_condition'].unique()

<StringArray>
[     'Good', 'Excellent',   'Average',     'Super',      'Poor',     'Great',
 'Wonderful',      'Fair', 'Beautiful']
Length: 9, dtype: string

In [34]:
## This converts the data type from object to string.
df['vehicle_condition'] = df['vehicle_condition'].astype("string")
print(df['vehicle_condition'].dtype)

string

In [35]:
df['vehicle_condition'] = df['vehicle_condition'].str.capitalize()
df['vehicle_condition'] = df['vehicle_condition'].fillna('Super')
df['vehicle_condition'] = df['vehicle_condition'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    'Unknown': 'Great',
    'None': 'Beautiful',
    'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Tricycle',
    'Na': 'Fair',
    '-': 'Wonderful',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    #'<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
19679,DRV017672,Naveen Chaudhary,-37,Ahmedabad,9141380835,naveen.chaudhary@hotmail.com,Uber,Auto,Poor,3-5 yrs,...,9.5,5.6,7.7,6.6,Fail,Clear,On Hold,NaN,NaN,1
41342,DRV047342,anil sharma,46,Chennai,9102565640,anil.sharma@rediffmail,Uber,Motorbike,Poor,NaN,...,9.8,7.5,5.5,7.1,Pending,NaN,none,NaN,-,1
279,DRV031630,Umesh Tiwari,31,Lucknow,9742330931,umesh.tiwari@hotmail.com,Uber & rapido,Mini,Good,1-3 yrs,...,7.6,5.4,6.6,10.7,NaN,clear,on hold,NaN,NaN,true
13759,DRV042943,Bharat Tiwari,32,Kolkata,+91488774776,bharat.tiwari@yahoo,Uber,Mini,Poor,1-3 yrs,...,8.1,6.9,3.6,6.7,NaN,NaN,Rejected,Background check failed,NaN,NO
49118,DRV043837,HITESH TRIPATHI,42,Lucknow,+91440912384,hitesh.tripathi@hotmail.com,Rapido,Suv,Average,Fresher,...,5.7,4.8,5.9,6.2,FAIL,Pending,Rejected,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17631,DRV038428,PRADEEP SHUKLA,26,Mumbai,9210742155,pradeep.shukla@rediffmail.com,-,Mini,Poor,3-5 yrs,...,4.2,4.9,6.9,6.2,FAIL,NaN,Selected,NaN,April 2024,0
2841,DRV036444,RAKESH RAO,25,Chennai,9676268406,rakesh.rao@hotmail.com,Rapido,Suv,Poor,Fresher,...,0.7,4.7,4.7,5.9,FAIL,pending,NaN,NaN,07 May 2022,N
48659,DRV028265,Rakesh Yadav,999,Kolkata,+91053536148,rakesh.yadav@yahoo.com,Rapido,Auto,Poor,Unknown,...,<NA>,5.6,3.5,NaN,NaN,NaN,Rejected,Background check failed,NaN,YES
32334,DRV030680,Vikram Gupta,45,Pune,9494634606,vikram.gupta@hotmail.com,Rapido,Sedan,Super,Fresher,...,4.9,9.3,NaN,NaN,Fail,Flagged,NaN,NaN,NaN,1
34877,DRV008313,Hitesh Mishra,22,Pune,9562357717,hitesh.mishra@rediffmail.com,Uber,Mini,Super,Fresher,...,6.7,10.0,12.6,7.8,pass,Flagged,NaN,Vehicle age too old,NaN,Y