In [1]:
import pandas as pd

#import matplotlib.pyplot as plt

df = pd.read_csv("uber_rapido_driver_dirty.csv")
df.head(5)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
0,DRV016649,Naresh Chauhan,NaN,Chennai,9255500096,naresh.chauhan@hotmail.com,uber,auto,good,0-1 yr,...,4.3,5.8,7.7,5.3,Fail,NaN,On Hold,NaN,-,false
1,DRV032785,Amit Gupta,45,Ahmedabad,9940345570,amit.gupta@rediffmail.com,Uber,Mini,Excellent,Fresher,...,9.3,NaN,9.0,8.1,NaN,Clear,On Hold,NaN,-,No
2,DRV011323,Yogesh Nair,53,Lucknow,9170487337,NaN,uber,SUV,avg,0-1 yr,...,6.3,9.0,5.5,6.9,NaN,clear,Selected,NaN,19 April 2021,false
3,DRV022168,Manoj Patel,46,Hyderabad,9246425981,manoj.patel@hotmail.com,RAPIDO,Mini,NaN,1-3 yrs,...,8.7,9.6,5.3,7.8,unknown,Clear,Selected,NaN,2021/05/27,0
4,DRV040782,Vikram Chaudhary,25,KOLKATA,9282240,vikram.chaudhary@gmail.com,Uber,suv,GOOD,Fresher,...,12.7,6.5,7.9,6.0,FAIL,clear,Rejected,Low rating history,-,NO

In [2]:
df.describe()

,total_trips_completed,trip_completion_rate_%,cancellation_rate_%,total_complaints,total_compliments,communication_score_10,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10
count,45930.000000,45565.00000,45484.000000,45965.000000,46024.000000,45416.000000,45559.000000,45448.000000,45500.000000,45545.000000
mean,6802.510799,77.89254,22.416584,8809.843120,8942.686272,6.508777,6.946878,6.508619,6.517708,6.613859
std,17638.171153,20.80393,23.708155,28303.698509,28456.710282,2.789817,2.630277,2.794014,2.804085,2.239486
min,-7996.000000,-2.00000,-2.000000,0.000000,0.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000
25%,1704.000000,69.40000,8.100000,14.000000,27.000000,4.600000,5.400000,4.600000,4.600000,5.900000
50%,3909.000000,80.50000,18.100000,27.000000,55.000000,6.600000,7.100000,6.600000,6.600000,6.700000
75%,6086.750000,91.60000,27.900000,41.000000,82.000000,8.500000,8.800000,8.600000,8.600000,7.400000
max,99999.000000,103.00000,103.000000,99999.000000,99999.000000,13.000000,13.000000,13.000000,13.000000,13.000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   driver_id                   49005 non-null  object
 1   driver_name                 50000 non-null  object
 2   age                         47543 non-null  object
 3   city                        50000 non-null  object
 4   phone                       46089 non-null  object
 5   email                       45395 non-null  object
 6   platform                    47761 non-null  object
 7   vehicle_type                47775 non-null  object
 8   vehicle_condition           39468 non-null  object
 9   experience_level            47776 non-null  object
 10  preferred_shift             38773 non-null  object
 11  reason_for_joining          38637 non-null  object
 12  languages_known             47847 non-null  object
 13  overall_driver_rating       46033 non-null  object
 14  total_trips_completed       45930 non-null  float64
 15  trip_completion_rate_%      45565 non-null  float64
 16  cancellation_rate_%         45484 non-null  float64
 17  avg_daily_earnings_INR      47489 non-null  object
 18  total_complaints            45965 non-null  float64
 19  total_compliments           46024 non-null  float64
 20  peak_hour_availability      50000 non-null  object
 21  interview_date              45067 non-null  object
 22  communication_score_10      45416 non-null  float64
 23  driving_test_score_10       45559 non-null  float64
 24  route_knowledge_score_10    45448 non-null  float64
 25  customer_handling_score_10  45500 non-null  float64
 26  overall_interview_score_10  45545 non-null  float64
 27  document_verification       36233 non-null  object
 28  background_check_status     36549 non-null  object
 29  interview_result            45243 non-null  object
 30  rejection_reason            12174 non-null  object
 31  onboarding_date             26172 non-null  object
 32  is_currently_active         50000 non-null  object
dtypes: float64(10), object(23)
memory usage: 12.6+ MB

In [4]:
df.shape

(50000, 33)

In [5]:
df['email'].unique()

array(['naresh.chauhan@hotmail.com', 'amit.gupta@rediffmail.com', nan,
       ..., 'deepak.srivastavahotmail.com', 'deepak.singhgmail.com',
       'deepak.dubeygmail.com'], dtype=object)

In [6]:
df['email'] = df['email'].astype("string")
print(df['email'].dtype)

string

In [7]:
##This code creates a gmail adrress for the drivers using their names, where they have no existing emails.

df['email'] = df['email'].fillna(
    df['driver_name'] + '@gmail.com'
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
43357,DRV037230,Deepak Patel,20,Mumabi,NaN,deepak.patel@rediffmail.com,Rapido,auto,avg,-,...,10.8,6.1,7.6,11.3,pass,NaN,NaN,NaN,10-08-2023,yes
22733,DRV048979,Deepak Gupta,33,Chennai,9081495857,deepak.gupta@gmail.com,Uber & Rapido,SUV,Good,1-3 yrs,...,5.1,3.6,NaN,-0.4,pending,pending,On Hold,NaN,NaN,False
34866,DRV001291,Naveen Mishra,32,Jaipur,9407756487,naveen.mishra@rediffmail.com,Uber & Rapido,suv,good,NaN,...,4.8,10.0,NaN,7.2,none,FLAGGED,NaN,NaN,NaN,Y
11664,DRV019109,Suresh Mishra,43,Lucknow,9012925584,suresh.mishra@yahoo.com,ola,Auto,good,3-5 yrs,...,9.1,7.3,6.9,8.0,pass,FLAGGED,Rejected,NaN,01/13/23,yes
12004,DRV000201,Rakesh Patel,999,Lucknow,9581508812,rakesh.patel@hotmail.com,Unknown,auto,NaN,1-3 yrs,...,8.3,5.9,5.5,6.7,Fail,Pending,Rejected,Not applicable,NaN,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2292,DRV046972,Harish Sharma,35,Chennai,9764845321,harish.sharma@gmail.com,Uber,Mini,NaN,3-5 yrs,...,6.7,7.3,7.3,6.8,Fail,NaN,Rejected,NaN,NaN,0
28837,DRV043043,R@vi Jh@,999,Bangalore,XXXXXXXXXX,ravi.jha@rediffmail.com,uber,sedan,Good,3-5 yrs,...,5.7,3.7,8.8,6.8,pass,Flagged,Selected,NaN,2023-07-06T00:00:00Z,0
34218,DRV042447,Rajesh Rao,20,Lucknow,9750350324,rajesh.rao@gmail.com,Uber,SUV,avg,5+ yrs,...,9.2,-0.9,5.0,NaN,Pending,pending,Rejected,Vehicle age too old,NaN,False
7287,DRV040939,sunil kumar,30,Lucknow,9065029812,sunil.kumar@yahoo.com,Unknown,Bike,GOOD,NaN,...,8.4,5.8,8.7,6.5,unknown,NaN,Rejected,Poor communication,NaN,1
24575,DRV044745,HITESH PATEL,42,Bangalore,9018110509,hitesh.patel@yahoo.com,RAPIDO,auto,avg,5+ yrs,...,4.1,12.8,6.6,-1.4,NaN,NaN,Selected,NaN,2021-08-18T00:00:00Z,Yes

In [8]:
df.sample(10)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
17056,DRV046857,Hitesh Gupta,24,Jaipur,9622348178,hitesh.gupta@yahoo,RAPIDO,SUV,Average,1-3 yrs,...,5.5,NaN,12.3,5.3,Fail,Flagged,On Hold,NaN,-,YES
32831,DRV011226,Lokesh Rao,44,Lucknow,93226-08805,lokesh.rao@gmail.com,NaN,suv,Excellent,1-3 yrs,...,6.1,3.8,9.6,6.6,Fail,Pending,on hold,NaN,2022/07/08,Yes
2394,DRV030047,Bharat Nair,45 yrs,Hyderabad,9913653878,bharat.nair@gmail.com,Rapido,Mini,excellent,1-3 yrs,...,-1.8,5.3,NaN,4.7,NaN,NaN,NaN,NaN,NaN,Yes
18318,DRV030619,Sunil Pandey,47,Ahmedabad,+91-9041711106,Sunil Pandey@gmail.com,NaN,SUV,Good,5+ yrs,...,8.4,9.7,8.8,8.1,FAIL,FLAGGED,NaN,NaN,2022/11/26,True
36438,DRV019162,Suresh Sharma,30,Pune,9487600488,suresh.sharma@@hotmail.com,Uber & Rapido,sedan,avg,5+ yrs,...,5.9,12.8,3.6,5.1,Pass,Pending,On Hold,NaN,NaN,False
339,DRV031968,Anil Dubey,47,Bangalore,9532229998,anil.dubey@yahoo.com,Rapido,Bike,Good,5+ yrs,...,9.4,4.9,-0.2,6.9,Pending,pending,NaN,NaN,NaN,Yes
37263,DRV016137,Ajay Patel,28,Pune,9297948080,ajay.patel@yahoo.com,Rapido,BIKE,avg,1-3 yrs,...,6.7,8.0,6.1,NaN,NaN,Clear,selected,NaN,2022-04-22T00:00:00Z,N
24580,DRV029771,Rajesh Yadav,55,Kolkata,9607876343,rajesh.yadav@yahoo,ola,sedan,poor,1-3 yrs,...,6.4,8.5,6.9,7.1,FAIL,FLAGGED,Selected,NaN,NaN,False
2906,DRV042710,Yogesh Mishra,33,Bangalore,9205425524,yogesh.mishra@yahoo.com,Uber & Rapido,Mini,NaN,5+ yrs,...,4.1,5.9,4.1,5.1,Fail,Pending,On Hold,NaN,NaN,1
2646,DRV013883,Suresh Singh,NaN,Delhi,+91-9786068893,Suresh Singh@gmail.com,RAPIDO,Auto,Poor,Fresher,...,5.9,-1.2,9.9,6.4,Pending,NaN,On Hold,NaN,-,true

In [9]:
df['phone'] = pd.to_numeric(df['phone'], errors='coerce') 
## This is to convert the phone collumn from object to numeric

In [10]:
df['phone'] = df['phone'].astype("string")
print(df['phone'].dtype)

string

In [11]:
df['driving_test_score_10'].unique()

array([ 4.3,  9.3,  6.3,  8.7, 12.7,  8.8,  8.1, -1.1, 11.6,  nan,  7.4,
       -0.6,  7.7,  6.2,  4.8,  7.1, 12.5, 11.2, -0.9,  5.5,  8.9,  6.4,
        5.1,  7. , 11. ,  7.6,  5.7, 12.2,  9.1,  7.5,  8.3,  4.6,  4. ,
        7.2,  8. ,  9.7, 10.9,  4.2,  9.5,  4.9,  5.8,  5. ,  6.9,  4.1,
        6.5,  4.5,  9.8,  5.4,  4.4, -1.3,  9.2,  4.7,  7.3, -1.5, 12.4,
        8.6,  8.4, -1.7,  5.3,  6.1,  6. ,  9.6,  7.9,  6.8,  5.2,  5.6,
       10.2, -0.7,  9.4,  9.9,  7.8,  8.2,  6.6,  6.7, 10.5,  9. , 10.8,
        5.9, 12. , 12.1, 11.5,  8.5, 10. , -1. , -0.8, 11.4, 10.3, -0.4,
       -0.5, 10.7, 11.7, 11.8, -0.3, 10.4, 12.8, -1.8, -1.2, -0.2, 11.9,
       -1.4, 10.1, 11.3, 12.3, -1.6, 12.6, -1.9, 10.6, 12.9, 11.1, 13. ,
       -0.1, -2. ])

In [12]:
## This code removes the decimals from the values and make them strings rather than floats. 
df['phone'] = df['phone'].str.replace(r'\.0$', '', regex=True)

In [13]:
## This creates random phone numbers for NaN values in the phone column

import numpy as np

mask = df['phone'].isna()

df.loc[mask, 'phone'] = [
    '+91' + ''.join(np.random.choice(list('0123456789'), 9))
    for _ in range(mask.sum())
]
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
47520,DRV039516,Suresh Tripathi,33,Ahmedabad,9396902872,suresh.tripathi@gmail.com,UBER,Auto,na,5+ yrs,...,9.1,6.5,3.4,6.3,NaN,NaN,On Hold,NaN,NaN,1
4594,DRV046102,Ravi Tripathi,55,Mumbai,+91616676442,ravi.tripathi@yahoo.com,Uber,Bike,Good,3-5 yrs,...,8.9,4.9,9.7,NaN,NaN,NaN,Rejected,Background check failed,NaN,No
21476,DRV048859,Pankaj Yadav,38,Chennai,9946242580,pankaj.yadav@@rediffmail.com,uber,Mini,none,3-5 yrs,...,4.7,6.8,8.6,6.8,Fail,NaN,Rejected,Not applicable,NaN,yes
31158,DRV034068,Umesh Jha,25,Pune,+91393042227,umesh.jha@gmail.com,RAPIDO,BIKE,Poor,Fresher,...,5.8,12.1,4.8,6.4,FAIL,pending,selected,NaN,September 2021,False
4761,DRV031421,Rakesh Dubey,40,Mumbai,9325794960,rakesh.dubey@rediffmail.com,Rapido,BIKE,avg,3-5 yrs,...,6.0,-0.8,9.7,-1.6,FAIL,Flagged,Selected,NaN,2022-11-30T00:00:00Z,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31858,DRV034475,anil tripathi,49,Mumbai,9674120446,anil.tripathi@yahoo.com,rapido,Sedan,unknown,1-3 yrs,...,8.1,8.4,7.1,6.8,NaN,Clear,On Hold,NaN,NaN,True
29414,DRV027652,Hitesh Sharma,37,Delhi,9773233979,hitesh.sharma@rediffmail.com,ola,Sedan,Poor,3-5 yrs,...,-0.8,7.6,10.0,7.5,FAIL,Clear,on hold,NaN,26-02-2024,NO
25068,DRV042568,M@noj P@ndey,23,Mumbai,9824573267,M@noj P@ndey@gmail.com,Uber,Mini,NaN,NaN,...,5.0,6.3,3.7,5.1,NaN,clear,Rejected,Failed driving test,NaN,Yes
37763,NaN,Naveen Patel,25,Lucknow,9139289778,naveen.patel@rediffmail.com,Uber & Rapido,auto,avg,Fresher,...,7.2,9.3,8.6,8.3,Pass,Clear,Rejected,NaN,NaN,Y
49485,DRV017860,Lokesh Gupta,51,Pune,9194978702,lokesh.gupta@yahoo.com,UBER,Auto,Good,1-3 yrs,...,NaN,4.5,8.4,6.6,Pending,FLAGGED,On Hold,NaN,NaN,Yes

In [14]:
df['age'] = df['age'].astype("string")
print(df['age'].dtype)

string

In [15]:
df['age'] = df['age'].fillna('70')

In [16]:
## This code fills the age column where NaN values exist with random values between 1 and 100

import numpy as np

mask = df['age'].isna()

df.loc[mask, 'age'] = np.random.randint(
    1, 101, size=mask.sum()
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
550,DRV012110,Mahesh Verma,27 yrs,Kolkata,9423662660,mahesh.verma@gmail.com,Unknown,auto,poor,1-3 yrs,...,9.9,5.5,6.5,7.7,Pass,NaN,Selected,NaN,10-08-2022,YES
7646,DRV011709,Yogesh Tiwari,999,Bangalore,+91966693168,yogesh.tiwari@yahoo,Uber,Auto,Average,1-3 yrs,...,8.5,-0.4,9.4,8.1,Pass,FLAGGED,On Hold,NaN,NaN,Yes
27284,DRV019670,Ajay Nair,43,ahmedabad,9709313448,ajay.nair@gmail.com,Uber & Rapido,SUV,NaN,3-5 yrs,...,6.6,9.1,4.0,6.7,Pass,Flagged,On Hold,NaN,NaN,true
43829,DRV003994,Anil Jha,-28,Chennai,9922857789,anil.jhayahoo.com,rapido,Mini,Average,3-5 yrs,...,6.7,9.4,8.6,7.5,pass,clear,Rejected,NaN,NaN,no
42598,DRV011325,Naresh Kumar,50,Jaipur,+91137886538,naresh.kumar@rediffmail.com,Uber & Rapido,BIKE,na,Fresher,...,12.9,7.8,9.9,NaN,FAIL,Clear,Waitlist,NaN,June 2021,true
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16294,DRV019014,Pankaj Sharma,48,Hyderabad,9182344,pankaj.sharma@hotmail,Uber,Auto,good,3-5 yrs,...,7.3,5.2,6.3,NaN,Fail,FLAGGED,none,NaN,-,Yes
41781,DRV018809,Santosh Chauhan,21,Jaipur,9551557636,santosh.chauhan@hotmail,Uber & Rapido,auto,Poor,5+ yrs,...,9.9,NaN,8.2,10.9,Pending,Clear,Selected,NaN,2023-05-03T00:00:00Z,True
14774,DRV007688,amit tiwari,36,Mumbai,+91527437747,amit.tiwari@hotmail.com,uber,unknown,Average,1-3 yrs,...,9.9,7.9,7.3,7.4,NaN,pending,Selected,NaN,2021-10-24T00:00:00Z,True
5442,DRV023839,Yogesh Pandey,51 yrs,Bangalroe,9033815454,yogesh.pandeyhotmail.com,RAPIDO,auto,Excellent,-,...,4.8,10.8,8.1,7.5,NaN,clear,Rejected,NaN,NaN,0
40730,DRV017490,Girish Pandey,20,MUMBAI,9289770505,girish.pandey@rediffmail.com,RAPIDO,Auto,Excellent,3-5 yrs,...,7.7,7.5,8.6,10.5,NaN,Clear,On Hold,NaN,-,Yes

In [17]:
## This is to remove the negative values and also the yrs in the age column.
df['driving_test_score_10'] = df['driving_test_score_10'].astype("string")
df['driving_test_score_10'] = df['driving_test_score_10'].str.lstrip('-')
#df['age'] = df['age'].str.rstrip('yrs')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
24419,DRV017652,Yogesh Rao,24,Pune,9743952256,yogesh.rao@rediffmail.com,Rapido,suv,avg,5+ yrs,...,9.0,3.5,8.3,6.2,NaN,FLAGGED,On Hold,NaN,NaN,0
23571,DRV012040,Sanjay Chaudhary,37,Delhi,9284128612,sanjay.chaudhary@hotmail.com,Uber,auto,NaN,1-3 yrs,...,9.1,4.5,4.3,6.2,NaN,NaN,Selected,NaN,03.02.2022,False
46490,DRV028985,Deepak Patel,46,Hydrabad,9059786108,deepak.patel@rediffmail.com,Uber & Rapido,Sedan,Good,0-1 yr,...,6.1,5.9,12.8,NaN,pending,Pending,REJECTED,Background check failed,NaN,no
22602,DRV046020,MUKESH JHA,20,Lucknow,9454877395,mukesh.jha@hotmail.com,Rapido,Mini,GOOD,Fresher,...,5.3,5.0,4.2,4.7,Pass,NaN,on hold,Vehicle age too old,NaN,no
43173,DRV001035,Suresh Singh,999,Pune,9778281286,suresh.singh@hotmail.com,Rapido,Bike,good,3-5 yrs,...,5.3,7.5,3.3,5.9,Fail,FLAGGED,On Hold,NaN,NaN,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25149,DRV047616,Naresh Chaudhary,30,Ahmedabad,+91766560293,naresh.chaudhary@hotmail.com,ola,BIKE,na,0-1 yr,...,5.4,3.6,-0.8,NaN,NaN,NaN,Rejected,none,NaN,NO
39116,DRV041340,Yogesh Ch@udh@ry,46,Pune,+91953019480,yogesh.chaudharygmail.com,ola,na,good,3-5 yrs,...,4.8,8.3,4.5,6.8,pass,Pending,Waitlist,NaN,-,Y
30609,DRV004829,Anil Reddy,55,Hyderabad,9094836925,anil.reddy@gmail.com,NaN,auto,good,3-5 yrs,...,9.4,6.3,12.4,7.2,FAIL,pending,On Hold,NaN,NaN,False
23246,DRV008933,Lokesh Rao,23,Mumbai,9436183433,Lokesh Rao @gmail.com,Uber,na,good,Fresher,...,<NA>,10.7,3.7,6.3,Pending,FLAGGED,Selected,NaN,2021-06-06T00:00:00Z,true
4275,DRV012332,Rajesh Nair,23,Jaipur,9420961377,rajesh.nair@@hotmail.com,RAPIDO,sedan,avg,Fresher,...,1.2,8.7,5.2,7.0,Pass,clear,Selected,NaN,09-09-2022,0

In [18]:
## This is to capitalise the platform column to give it a uniform format and also convert the data type from object to string.

df['platform'] = df['platform'].str.capitalize()
df['platform'] = df['platform'].astype("string")
print(df['platform'].dtype)

string

In [19]:
df['platform'] = df['platform'].fillna('Bolt')

In [20]:
df['customer_handling_score_10'] = df['customer_handling_score_10'].replace({
   #'NaN': '70',
   # 'Mini ': 'Trailer',
    #'unknown': '80',
    #'999' : '90',
    #'Unknown': 'Experienced',
    #'None': 'Fairly_Experienced',
    #'Avg': 'Average',
    #'poor': 'Super',
    #'Unknown': 'Motorcycle',
    #'Na': '1-20 yrs',
    #'-': '10-30 yrs',
    #"<NA>": 'Bus',
    #'Auto': '',
    #'suv' : 'SUV'
    #'uber': '',
    '<NA>': '6'
})
df.sample(10000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
15241,DRV010710,Rakesh Nair,53,Delhi,+91269287407,rakesh.nair@@yahoo.com,Uber,sedan,excellent,Fresher,...,7.1,4.1,8.6,7.5,NaN,NaN,Selected,NaN,03-09-2022,True
41725,DRV032286,Vijay Dubey,28,Ahmedabad,9869241,vijay.dubeyyahoo.com,Rapido,auto,GOOD,Fresher,...,9.3,5.1,12.2,7.5,NaN,NaN,Selected,NaN,13.01.2024,1
5321,DRV025731,Vikram Kumar,46,Lucknow,9588208170,vikram.kumar@rediffmail.com,Rapido,Sedan,Average,0-1 yr,...,5.4,NaN,9.8,7.7,pass,NaN,On Hold,NaN,-,no
20660,DRV009193,Umesh Chauhan,20,Chennai,9261171105,umesh.chauhan@rediffmail.com,Bolt,auto,GOOD,none,...,6.2,5.3,3.3,4.5,NaN,Flagged,Rejected,Background check failed,NaN,YES
38522,DRV041597,Rakesh Shukla,54,Delhi,9070547242,rakesh.shukla@yahoo.com,Uber,BIKE,avg,5+ yrs,...,6.9,3.2,8.1,NaN,FAIL,NaN,NaN,NaN,September 2023,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34942,DRV009524,Deepak Patel,29,Bangalore,9506426,Deepak Patel@gmail.com,Rapido,Bike,Good,3-5 yrs,...,8.7,6.8,12.4,6.7,Pass,FLAGGED,selected,NaN,NaN,N
25348,NaN,dinesh sharma,30,Kolkata,9599165200,dinesh sharma@gmail.com,Uber,Bike,Good,3-5 yrs,...,4.4,5.0,6.6,5.9,Pass,pending,On Hold,-,-,Y
38437,DRV034425,Naresh Tripathi,70,Ahmedabad,9618657907,naresh.tripathi@hotmail.com,Rapido,sedan,Average,1-3 yrs,...,4.7,6.8,6.0,13.0,pass,clear,On Hold,NaN,-,No
49354,DRV032419,P@nk@j Gupt@,999,Kolkata,9865006774,pankaj.gupta@yahoo.com,Uber,Mini,Good,0-1 yr,...,9.1,6.2,6.2,6.2,Pending,NaN,On Hold,NaN,NaN,yes
46086,DRV037211,Bharat Verma,-22,Chennai,9609133368,bharat.verma@hotmail.com,Rapido,NaN,avg,NaN,...,6.9,4.2,8.3,6.4,pass,Flagged,Selected,NaN,NaN,True

In [21]:
## This capitalises the city column to give it a uniform format and also converts the data type from object to string.
df['city'] = df['city'].str.capitalize()
df['city'] = df['city'].astype("string")
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
40610,DRV020060,SUNIL CHAUDHARY,70,Bangalore,9346697671,sunil.chaudhary@gmail.com,Rapido,NaN,NaN,Fresher,...,10.1,9.0,6.7,6.8,pass,clear,NaN,Background check failed,NaN,yes
30277,DRV040790,Harish Patel,33 yrs,Bangalore,9281841357,harish.patel@rediffmail,Uber,auto,avg,1-3 yrs,...,<NA>,7.7,4.4,5.8,Pass,clear,Rejected,Failed driving test,NaN,NO
177,DRV007628,Sunil Sharma,29,Hyderabad,9109822,sunil.sharma@rediffmail.com,Uber,Bike,avg,Unknown,...,9.3,8.8,7.3,7.3,Pass,NaN,NaN,NaN,June 2021,true
32607,DRV032677,Manoj Yadav,38,Bangalore,9638123568,manoj.yadav@hotmail.com,Uber & rapido,suv,excellent,Fresher,...,5.2,NaN,4.5,5.9,FAIL,clear,Selected,NaN,19 August 2022,N
10558,DRV017001,Sanjay Chaudhary,52,Pune,9711050803,Sanjay Chaudhary @gmail.com,Uber,BIKE,NaN,1-3 yrs,...,7.2,3.6,3.6,5.4,pass,NaN,Selected,NaN,03/12/23,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28121,DRV027262,Vikram Tripathi,45,Mumbai,9126888803,vikram.tripathi@rediffmail.com,Rapido,SUV,NaN,3-5 yrs,...,8.6,4.9,8.1,7.3,pass,NaN,On Hold,NaN,NaN,true
10250,DRV047022,Umesh Tiwari,32,Hyderabad,9398221284,umesh.tiwari@yahoo.com,Rapido,-,NaN,5+ yrs,...,7.0,3.2,6.7,6.0,pass,NaN,Selected,NaN,24.01.2024,no
3496,DRV025502,Ravi Dubey,37,Mumbai,9711391030,ravi.dubey@rediffmail.com,Rapido,SUV,NaN,0-1 yr,...,6.8,8.1,3.2,6.0,Pending,Pending,On Hold,NaN,NaN,1
5475,DRV041319,Girish Verma,28,Mumbai,9208895342,girish.vermarediffmail.com,Uber,Mini,-,3-5 yrs,...,4.7,6.0,5.8,5.5,NaN,none,Rejected,NaN,NaN,no
16017,DRV014638,UMESH JHA,44,Lucknow,+91353906589,umesh.jha@gmail.com,Uber,sedan,poor,5+ yrs,...,7.3,NaN,NaN,5.8,Pending,Pending,Rejected,Not applicable,NaN,False

In [22]:
df['route_knowledge_score_10'].unique()

array([ 5.8,  nan,  9. ,  9.6,  6.5,  8.6,  8.7,  6.4,  7.9,  7.7,  3.6,
        5.2,  6.8,  8.5,  7.1,  4.6, -1.2,  5. ,  3.2,  3.5,  3.8,  5.6,
        4.9,  8.8, 12. ,  6.7,  6.3,  9.9,  3.4,  9.8, -0.3, 10.7,  9.4,
       12.4,  4.2,  6.2,  3.9, 10. ,  6. ,  9.5,  7.4,  3. , 10.3,  7. ,
       10.2,  6.1,  3.3,  8. ,  4. ,  4.7,  4.5,  7.6,  5.9, -1.3,  4.1,
        5.1,  4.3, 12.2, 11.2,  8.1, 11.9,  5.4, -0.9,  5.5,  6.6,  3.7,
        9.3, 12.8,  8.2, 10.8,  5.3,  9.2, 12.3,  3.1,  7.8,  7.2,  9.1,
        4.8,  7.5,  6.9,  9.7, 12.7,  8.9,  4.4,  7.3, 11. , -0.4, 13. ,
       11.7,  8.4, -1.5, 11.5, 12.9, 10.5,  5.7, -1.1, -1.4, 10.1,  8.3,
       -0.7, 10.4, -0.8, -1.9, 12.1, -2. , -0.2, 10.9, -1.8, 11.1, -1. ,
       11.8, 11.3, 11.4, -0.5, 12.5, -1.7, -1.6, -0.1, 10.6, 12.6, -0.6,
       11.6])

In [23]:
## This converts the data type from object to string.
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].astype("string")
print(df['route_knowledge_score_10'].dtype)

string

In [24]:
## This is to remove the negative values and also the yrs in the age column.
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].str.lstrip('-')
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
3712,DRV043715,Pradeep Patel,49,Delhi,9825715721,pradeep.patel@rediffmail,Ola,SUV,excellent,5+ yrs,...,9.2,7.8,6.2,8.1,NaN,FLAGGED,Selected,NaN,28-03-2022,False
38101,DRV014456,Girish Gupta,51,Chennai,9033225510,girish.gupta@gmail.com,Uber,NaN,Excellent,Fresher,...,7.4,7.1,8.4,7.8,Pass,pending,on hold,NaN,August 2021,0
49939,DRV023538,rajesh tripathi,53,Mumbai,+91210398924,rajesh.tripathi@yahoo,Uber & rapido,Auto,avg,NaN,...,6.0,4.4,5.8,5.7,pass,Clear,On Hold,NaN,NaN,no
6352,DRV038718,Harish Gupta,50,Delhi,9195019932,harish.gupta@rediffmail.com,Uber,NaN,Average,5+ yrs,...,8.9,6.7,4.7,12.0,Fail,Flagged,NaN,Poor communication,NaN,Y
37529,DRV026828,ANIL MISHRA,51,Mumbai,9588662816,anil.mishra@rediffmail.com,Rapido,sedan,unknown,1-3 yrs,...,4.7,9.8,12.7,6.7,NaN,Pending,Selected,Not applicable,NaN,true
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7465,DRV028952,Santosh Tiwari,35,Pune,9826501791,santosh.tiwari@gmail.com,Uber,Mini,poor,0-1 yr,...,7.0,9.9,4.4,6.8,Pass,clear,Rejected,NaN,-,yes
32518,DRV034373,Vikram Nair,25,Delhi,9492220007,Vikram Nair@gmail.com,Uber,sedan,Average,3-5 yrs,...,4.9,5.8,NaN,6.6,Fail,NaN,Selected,NaN,December 2022,yes
4549,DRV040311,Suresh Nair,37,Bangalore,+91248270924,suresh.nair@rediffmail.com,Rapido,Auto,GOOD,0-1 yr,...,6.5,9.3,NaN,6.8,Pending,NaN,Selected,NaN,09 December 2021,yes
37729,DRV019906,Pankaj Jha,70,Mumbai,+91519095518,pankaj.jha@yahoo.com,Uber,SUV,NaN,Fresher,...,5.8,9.6,NaN,7.1,FAIL,Pending,Selected,NaN,27-04-2022,Yes
47883,DRV000873,Ravi Rao,31,Delhi,9188868,ravi.rao@rediffmail.com,Uber & rapido,Mini,good,Fresher,...,4.1,9.4,7.7,6.6,NaN,NaN,Rejected,Vehicle age too old,NaN,0

In [25]:
df['route_knowledge_score_10'] = df['route_knowledge_score_10'].fillna('7.5')

In [26]:
## This code fills the age column where NaN values exist with random values between 0 and 10

import numpy as np

mask = df['customer_handling_score_10'] == 6

df.loc[mask, 'customer_handling_score_10'] = np.random.randint(
    0, 10, size=mask.sum()
)
df.sample(1000)

,driver_id,driver_name,age,city,phone,email,platform,vehicle_type,vehicle_condition,experience_level,...,driving_test_score_10,route_knowledge_score_10,customer_handling_score_10,overall_interview_score_10,document_verification,background_check_status,interview_result,rejection_reason,onboarding_date,is_currently_active
33963,DRV005792,Mukesh Verma,30,Lucknow,9363085128,mukesh.verma@gmail.com,Bolt,sedan,avg,1-3 yrs,...,9.4,4.4,8.2,7.8,NaN,unknown,Selected,NaN,2023-02-19T00:00:00Z,No
17291,DRV029222,Rajesh Rao,54,Chennai,9118641550,rajesh.rao@yahoo,Rapido,BIKE,NaN,3-5 yrs,...,4.4,7.5,NaN,11.3,NaN,NaN,Rejected,Poor communication,NaN,False
40378,DRV003580,Santosh Nair,48,Pune,9950189274,santosh.nair@gmail.com,Uber,Auto,Excellent,1-3 yrs,...,5.2,9.4,5.8,11.9,Pending,Pending,On Hold,NaN,NaN,0
44490,DRV024145,Bharat Kumar,70,Chennai,+91776782336,bharat.kumar@yahoo.com,Unknown,Sedan,Poor,3-5 yrs,...,9.1,9.2,4.6,7.2,FAIL,Clear,Selected,NaN,NaN,True
26328,DRV005190,Naresh Jha,31,Lucknow,9393958808,naresh.jha@gmail.com,Uber,NaN,Excellent,Fresher,...,8.2,8.9,6.1,-1.1,FAIL,Flagged,Selected,NaN,08/25/21,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23756,DRV010219,Sanjay Patel,34,Lucknow,9597433639,sanjay.patel@@gmail.com,Unknown,suv,NaN,Fresher,...,8.3,9.1,7.0,6.9,pending,FLAGGED,Selected,NaN,12-12-2022,Yes
37433,DRV026937,Deepak Singh,34,Lucknow,9315635557,deepak.singh@yahoo.com,Ola,SUV,NaN,1-3 yrs,...,4.7,8.0,7.3,NaN,NaN,Clear,Selected,NaN,07-08-2021,Y
26642,DRV037940,Harish Kumar,46 yrs,Chennai,9259175482,harish.kumar@rediffmail.com,Ola,Bike,poor,Fresher,...,9.1,5.9,10.0,8.1,Pending,NaN,On Hold,NaN,NaN,yes
7622,DRV029579,Naresh Rao,35,Ahmedabad,9268992486,naresh.raohotmail.com,Uber,Auto,Good,1-3 yrs,...,11.4,9.6,3.6,6.2,Fail,FLAGGED,Selected,NaN,03.10.2022,false
14637,DRV049552,Ravi Dubey,25,Bangalore,9415888,ravi.dubey@yahoo.com,Ola,suv,Poor,0-1 yr,...,11.5,4.1,9.9,6.7,pending,pending,On Hold,NaN,-,false